### ISSUE TITLE
`IS NOT NULL` in materialized view is not respected

### ISSUE THREAD

**Issue by enedil** [scylladb/scylladb#10365]
Scylla version: latest from docker, but should work the same in master.

Issue description:

Even though, the view filter for the mv contains `value2 IS NOT NULL`, the view ends up containing rows for which `value2` was NULL. This is related to the fact, that as it seems, `IS NOT NULL` restriction is never really checked (the `matches_view_filter` invokes `cql3::expr::is_satisfied_by`, which ignores IS NOT NULL. Instead, this restriction is checked by hand, in `view_updates::generate_update`, but it is not checked on columns that don't get into the view primary key).

Specific example:
```
cqlsh:ks> CREATE TABLE test(id int, value1 int, value2 int, PRIMARY KEY(id));
cqlsh:ks> CREATE MATERIALIZED VIEW mv AS SELECT id, value1 FROM test WHERE value1 IS NOT NULL AND value2 IS NOT NULL PRIMARY KEY(id, value1);
cqlsh:ks> INSERT INTO test(id, value1) VALUES (2000, 1);
cqlsh:ks> SELECT * FROM mv;

 id   | value1
------+--------
 2000 |      1
```

Expected output:
```
cqlsh:ks> SELECT * FROM mv;

 id   | value1
------+--------
```

**Comment by nyh** [comment]
he "IS NOT NULL" was added with materialized views to be put on the **key** columns, to eliminate the possibility of rows with null keys (which aren't allowed). We have a test for this - `test_materialized_views.py`::`test_mv_is_not_null`.

In your use case, you used `IS NOT NULL` on a non-key columns value2, basically as a filter. While filters are indeed supported in views general, as you discovered it appears that IS NOT NULL is not honored and in general is not supported in restrictions (see #8517).

We should either add full support for IS NOT NULL - not just for keys - or alternatively as a (temporary?) workaround print an error message in this case. You're right that we shouldn't just silently ignore the "IS NOT NULL" specification.

**Comment by nyh** [comment]
I checked, and the same bug exists in Cassandra: It also allows "xyz IS NOT NULL" (for non-key columns) in a materialized view's definition, and then ignores it and doesn't use it for filtering.

This makes it a bit of a problem to fix because of backward-compatibility concerns: It is possible that some existing Cassandra or Scylla applications, because their developers didn't know what this "IS NOT NULL" thing in a materialized view means, put too many columns with IS NOT NULL, which is currently ignored (in both Scylla and Cassandra) but if this issue is fixed, it won't be ignored. If we want to go for optimal backward compatibility we can use a "safe mode" (`restrict_*`) option, but I think this might be an overkill (plus, would be wrong if one day we do #8517).
