### ISSUE TITLE
sstableloader cannot load table named "view"

### ISSUE THREAD

**Issue by nivekuil** [scylladb/scylladb#10619]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.0.rc3
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): docker 
`sstableloader -d '0.0.0.0' /tmp/mykeyspace/view-e02db1e0857d11ecae9033c76234e6f3/md-83-big-Index.db`
```
===== Using optimized driver!!! =====
org.apache.cassandra.exceptions.SyntaxException: line 1:22 no viable alternative at input 'view' (CREATE TABLE mykeyspace.[view]...)
	at org.apache.cassandra.cql3.ErrorCollector.throwFirstSyntaxError(ErrorCollector.java:101)
	at org.apache.cassandra.cql3.CQLFragmentParser.parseAnyUnhandled(CQLFragmentParser.java:80)
	at org.apache.cassandra.cql3.QueryProcessor.parseStatement(QueryProcessor.java:587)
	at com.scylladb.tools.BulkLoader$CQLClient.getCFMetaData(BulkLoader.java:697)
	at com.scylladb.tools.BulkLoader.process(BulkLoader.java:1569)
	at com.scylladb.tools.BulkLoader.lambda$main$1(BulkLoader.java:1367)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
  0% done.        0 statements sent (in        0 batches,        0 failed).
       0 statements generated.
       0 cql rows processed in        0 partitions.
       0 cql rows and        0 partitions deleted.
       0 local and        0 remote counter shards where skipped.
```

**Comment by nyh** [comment]
The problem is that the name "view" is a reserved keyword in CQL, so one cannot simply do `CREATE TABLE mykeyspace.view` as it confuses the parser. But CQL does allow you to to **quote** the table name, as follows `CREATE TABLE mykeyspace."view"` and that should work.

So sstableloader should quote table names it uses if they are keywords.
Quoting is also necessary for table names which have mixed lower case and upper case.

sstableloader could make an effort to quote only table names where such quoting is necessary, but this requires knowing the list of reserved keywords. Inside Scylla we decided to do that (see discussion in https://github.com/scylladb/scylla/pull/9920). But in an external tool like sstableloader it seems easier to just quote all the identifiers - table names, column names, and so on - unconditionally.

By the way, don't Cassandra have the same bug?

**Comment by Bouncheck** [comment]
Seems to work now.
I've launched new scylla docker container, created "view" table the following way:
```
CREATE KEYSPACE mykeyspace WITH replication = {'class':'SimpleStrategy', 'replication_factor': 1};
CREATE TABLE mykeyspace."view" (pk int PRIMARY KEY);
INSERT INTO mykeyspace."view" (pk) VALUES (1);
INSERT INTO mykeyspace."view" (pk) VALUES (2);
INSERT INTO mykeyspace."view" (pk) VALUES (3);
```
Made a snapshot using nodetool and copied its directory to the host.
After that I have launched another clean dockerized scylla, run CREATEs and sstableloader'd data.
All 3 rows were present.
