### ISSUE TITLE
raft: `modify_config` called by leader to remove itself from the configuration gets stuck

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#10833]
The `modify_config` call does the job - the leader is removed from the config - but the call on the leader gets stuck.
This causes `decommission` to get stuck near the end, if called on a node which currently contains group 0 leader.
There are other steps after `leave_group0` call inside `decommission` - these steps can't be reached in that case.

Similar to #10010, except there it's a follower that removes the leader, here the leader removes itself (maybe it's really the same root cause?) (also we need to verify if #10010 is still occurring, perhaps it got fixed).

**Comment by kostja** [comment]
Should be fixed by changing the node in raft to non-voter before running removenode/decommission. Potentially rather high impact - a stuck topology operation. Needs a test case.

**Comment by kbr-scylla** [comment]
I think this is fixed now, but need to check.

**Comment by kbr-scylla** [comment]
Well, decommissioning a leader works, looks like there's nothing to fix.

I suspected that this is because at some point we added intermediate become_nonvoter step, where the decommissioning node becomes a nonvoter causing it to lose leadership, so when it leaves group 0, it's no longer a leader and so won't get stuck.

But  I did an experiment where I removed this intermediate step and decommissioned a leader, and it worked. The node correctly left group 0 and lost leadership after that.

So we had to fix it at some point, I just don't know when.

Closing.
