### ISSUE TITLE
Move auth keyspace to group0

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#11157]
Currently users which use authentication have to manually change auth keyspace authentication  factor which defaults to 1 if they run non-trivial clusters. Not changing it leads to a potential authentication data/access loss , when a node which contains a fragment of the auth data (i.e. credentials of a specific user) dies. 

Worse yet, it may lead to availability issues if the node which owns the authentication information is not available, and lots of clients are trying to connect.

Moving this information to group0 would allow to automatically change auth keyspace replication factor as the cluster grows. Besides, to properly support ANSI SQL DEFINER rights it's necessary to auto-grant/auto-revoke access on schema changes, which means that access control must be part of the same linearizable schema state as the schema definitions themselves.

```[tasklist]
### Tasks
- [ ] https://github.com/scylladb/scylladb/issues/17619
```

**Comment by eliransin** [comment]
An alternate solution to moving to group0 (at least for solving the first problem) us discussed here:
#1796
Maybe we should do both.

**Comment by kostja** [comment]
@avikivity could you please decide which one should we do? I'd like to assign this out.

**Comment by avikivity** [comment]
I think we should start with EverywhereReplicationStrategy. It's simple and it fixes problems even for those not yet opting in to Raft.

Later, rather than moving it to group 0, I think we should move it to broadcast tables (after it matures), so that full CQL support is retained. With group 0 tables it is illegal to update the table via CQL.

**Comment by mykaul** [comment]
> I think we should start with EverywhereReplicationStrategy. It's simple and it fixes problems even for those not yet opting in to Raft.

@eliransin - you are working on this for 5.3, I reckon?

**Comment by mykaul** [comment]
@ptrsmrn - why is this on backlog milestone?

**Comment by ptrsmrn** [comment]
> @ptrsmrn - why is this on backlog milestone?

@mykaul I wasn't aware we have yet another auth-raft related issue, so I pinned this one under the umbrella https://github.com/scylladb/scylladb/issues/16970 issue as well.
I set the milestone to 6.0 for this issue, and all other umbrella issues, but I have one concern - the github's 6.0 milestone says that the due date for 6.0 is 5th Feb, which is in a week, is that correct? Because I had some issues set to 6.1 because of that date.

**Comment by mykaul** [comment]
> > @ptrsmrn - why is this on backlog milestone?
> 
> @mykaul I wasn't aware we have yet another auth-raft related issue, so I pinned this one under the umbrella #16970 issue as well. I set the milestone to 6.0 for this issue, and all other umbrella issues, but I have one concern - the github's 6.0 milestone says that the due date for 6.0 is 5th Feb, which is in a week, is that correct? Because I had some issues set to 6.1 because of that date.

We might drift. The aim is Feb, sooner the better.
