### ISSUE TITLE
docs: need a page with scylla limits

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#11188]
A question that often comes up in the scylla user slack channel is what are the limits of scylla. e.g. number of rows in a partition, size of rows/partitions/cells, etc.
I usually point people to the our relevant default configuration, i.e.: https://github.com/scylladb/scylladb/blob/934af9be52df9bae661a0d5c65c4e5411da992c9/conf/scylla.yaml#L401-L411 and explain that these are good as a rule-of-thumb but are not hard limits.
We need a documentation page on this subject that is discoverable when googling: `scylla limits` or similar keywords. Currently this is the only related page that comes up on such a search: https://docs.scylladb.com/stable/kb/system-limits.html.
Maybe we already have such a page, but I couldn't find it, neither with googling, nor by browsing the docs.

@tzach @annastuchlik

**Comment by tzach** [comment]
The problem is we do not have hard limits for many of the variables, like 
- rows in a partition
- elements in a collection
- size of a cell 
- etc

We do plan to introduce guardrails for each (AKA "Safe mode") which can be then documented

**Comment by denesb** [comment]
> The problem is we do not have hard limits for many of the variables, like

Exactly. But people coming from C* seems to assume we must have and there has to be a page explaining to them that we don't and at the same time mentioning and explaining the warning limits. Otherwise we'll keep answering the same question on slack every week.

**Comment by fee-mendes** [comment]
I think this issue title is a bit too optimistic for what's its intended purpose. I'd advocate to be more specific on which kind of limit it is trying to solve or instead update the opening message so it can be a general issue for all limits we don't have (or don't know yet?).

In particular, we also don't have limits for (example):
- Max supported number of tables in a cluster
- Max number of shards in a Scylla cluster
- Max number of columns in a partition
- Max number of partitions in a table
etc.

**Comment by denesb** [comment]
Of course, the things we don't have limits for is limitless.
We can start with those that people commonly ask about and amend as people come up with new questions.

**Comment by fee-mendes** [comment]
> Of course, the things we don't have limits for is limitless.

Well, I'd say that limitless is likely impossible. But then someone will tell me to prove it and I won't have the machine/resources/time to... :-) #11054 is an example of when "limitless" is reached.

>  We can start with those that people commonly ask about and amend as people come up with new questions.

Agreed. And as a contribution, and since the opening message mentions Cassandra documentation, I think it would be a good idea to break it down to [CQL Limits](https://docs.datastax.com/en/cql-oss/3.x/cql/cql_reference/refLimits.html) and Alternator limits, [Table limits](https://docs.datastax.com/en/dse-planning/doc/planning/planningAntiPatterns.html#planningAntiPatterns__AntiPatTooManyTables), and Cluster limits (never saw a mention of that one, but many sources indicate that there's a point where your performance no longer scales linearly), so perhaps for the "limitless" stuff we could mention what we tested and the fact we have _theoretically_ no limits?.

**Comment by nyh** [comment]
In https://github.com/scylladb/scylladb/issues/10070#issuecomment-1312525114 @Bessonov has a good list of limits he would have liked to know about - such as the maximum recommended number of items per collection or largest recommended blob, and he rightly asks about the performance implications of going beyond these recommendations. In other words, these are not hard limits, but still there's a reason not to overdo them and a user would probably like to know why.

**Comment by tzach** [comment]
@denesb see
https://opensource.docs.scylladb.com/stable/reference/limits.html

**Comment by denesb** [comment]
> @denesb see https://opensource.docs.scylladb.com/stable/reference/limits.html

This is pretty much what I had in mind. Thanks.
