### ISSUE TITLE
Recycled-CommitLog-X-XXXXXXXXX files fill the disk without limits

### ISSUE THREAD

**Issue by pgoron** [scylladb/scylladb#11184]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version: 4.4.6 and 4.6.3
Cluster size: 35 nodes and 70 nodes
OS: CentOS 7

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): on-premise kubernetes
Hardware: sockets=2 cores=8 hyperthreading=yes memory=256GB
Disks: 1 SSD disk 6TB

One year after installation of our clusters, we observe that their disk is almost full whereas dataset is far from consuming all available space. When looking at disk content, we observed up to 3TB consumed by commitlog, mostly by Recycle-CommitLog-XXX files.
cf. output of ls -l /var/lib/scylla/commitlog

[scylla-commitlog-ls.txt.gz](https://github.com/scylladb/scylladb/files/9234492/scylla-commitlog-ls.txt.gz)

```
$  zcat ../scylla-commitlog-ls.txt.gz | grep Recycled | awk '{s+=$5} END {print s}'
3327123259392 => 3TB
```

```
$  zcat ../scylla-commitlog-ls.txt.gz | grep -v Recycled | awk '{s+=$5} END {print s}'
140156862464 => 127GB
```

Here are our commitlog parameters from scylla.yaml :
```
commitlog_segment_size_in_mb: 32
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_total_space_in_mb: -1
```

From our understanding of scylla code (db/commitlog/commitlog.cc):
- at startup, scylla doesn't initialize _recycled_segments with Recycled-CommitLog-XXX files already present on disk
- so they aren't accounted in disk space consumed by commitlog
- and if for any reason scylla doesn't properly shutdown, Recycled-CommitLog-XXX files created during process lifetime won't be deleted and will stay forever on disk.

We believe it would make sense to reuse and account already created Recycled-CommitLog-XXX at scylla startup.

**Comment by elcallio** [comment]
This was fixed in ed8f0df10580a47ae5bc5c6f3536d758015b58d0 - it takes disk footprint into account when deciding which (recycled) segments to re-recycle/delete.

**Comment by elcallio** [comment]
That being saidf though, there might be issues even there, with how we are comparing size/footprint...

**Comment by pgoron** [comment]
Hi @elcallio, if there are Recycled-commitLog-X-XXX files already present on disk when starting scylla, shouldn't you add them to _recycled_segments queue to be able to reuse them (if their size match segment_size) ?

Existing Recycled-commitLog-X-XXX are in segments_to_replay, but during recovery, they seems to be discarded by commitlog::read_log_file because they don't start with expected prefix (see https://github.com/scylladb/scylladb/blob/master/db/commitlog/commitlog.cc#L2828) (my interpretation by reading the code, I might be wrong).

**Comment by elcallio** [comment]
Technically,. we could, but recycled segments do _not_ count into disk footprint as such. They are considered "deleted". What we do instead is include the recycles into the replay set (where they will be ignored since the file names do not match content - and even if they were not, it would not be a problem). They are then added for deletion, at which point the idea is that we finally decide whether to keep them as recycled or not depending on the current disk footprint. 
The problem here is that before the patch above, that footprint is only counting segment _newly_ created this session. Assuming the allowed footprint is then high enough, we will probably _not_ actually delete the replay segments, but instead put them as recycled ones. Possibly making our true recycle footprint higher than allowed. We can then hit a state where we keep adding recycled segments (instead of deleting), and if we have another crash, it will only get worse. 

Simplest fix is to (as patch does) include the replay set into initial foot print, so the logic for segment deletion fully applies to these segments as well.

**Comment by pgoron** [comment]
Thanks for the clarification

**Comment by avikivity** [comment]
@elcallio @michoecho please advise about backports. Since there were many issues and fixes which caused regressions here and there, I'd like to backport all commitlog fixes in a batch, so please name all relevant commits here.

**Comment by elcallio** [comment]
All? Hard to do since #12950 is still not merged.

**Comment by avikivity** [comment]
I don't want to backport all commitlog fixes, only critical ones, but I don't want to backport a subset that creates its own regressions.

**Comment by elcallio** [comment]
I'd say https://github.com/scylladb/scylladb/pull/12950 is one of the critical ones.

**Comment by mykaul** [comment]
> I'd say #12950 is one of the critical ones.

Now that it is merged, what's next should be backported?
