### ISSUE TITLE
randomized_nemesis_test.cc: remove_leader_with_forwarding_finishes: Assertion `std::holds_alternative<std::monostate>(result)' failed.

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11235]
Seen in https://jenkins.scylladb.com/job/scylla-master/job/build/1119/artifact/testlog/x86_64/debug/randomized_nemesis_test.remove_leader_with_forwarding_finishes.2201.log
scylla version 7f80602b010a973dd24953cf39161699e7afcb42
```
random-seed=872648260
randomized_nemesis_test: test/raft/randomized_nemesis_test.cc:2387: auto remove_leader_with_forwarding_finishes::run_test_case()::(anonymous class)::operator()(environment<ExReg> &, ticker &) const: Assertion `std::holds_alternative<std::monostate>(result)' failed.
Aborting on shard 0.
Backtrace:
  0x2153b50
  0x2a0624d
  0x2a05e4c
  0x28526a4
  0x287e17e
  0x295fefc
  0x296015d
  0x295ff8a
  0x7f64f8820a1f
  /lib64/libc.so.6+0x3d2a1
  /lib64/libc.so.6+0x268a3
  /lib64/libc.so.6+0x26788
  /lib64/libc.so.6+0x35a15
  0x226741c
  0x22a2b7d
  0x22a28d8
  0x287152e
  0x287799e
  0x287c602
  0x287a171
  0x3701c61
  0x36ff7c5
  0x36d3b1d
  0x36d33b2
  0x36d3262
  0x36d2c22
  0x29b0cd9
  0x2c38f6b
  /lib64/libpthread.so.0+0x92a4
  /lib64/libc.so.6+0x100322
```

We can't decode the backtrace since the collected unit test binary is stripped (when will the fix reach master @benipeled?)

**Comment by bhalevy** [comment]
Cc @kbr-

**Comment by kbr-** [comment]
I'm guessing the `modify_config` call timed out. It's probably the usual - some slowness in Jenkins test environment causing timeouts...

Although these tests don't do any IO, and time is measured with a logical clock which the test is responsible for ticking, so if there's a slowdown, it should equally affect the ticking, i.e. time should run slower.

It's a relatively new regression test added with a bugfix in 6cdd5b9ff543755442ff680fbdebfa866cd4f856 (cc @gusev-p)
Maybe the bugfix doesn't cover all cases and sometimes `modify_config` gets stuck...

But I ran the test 10000 (yes, ten thousand) times locally and the failure didn't reproduce...

Is there some way to gain stats from Jenkins how often a given test fails, the set of runs in which it failed, or sth like that?

**Comment by bhalevy** [comment]
> Is there some way to gain stats from Jenkins how often a given test fails, the set of runs in which it failed, or sth like that?

@roydahan / @fruch

**Comment by benipeled** [comment]
> I'm guessing the modify_config call timed out. It's probably the usual - some slowness in Jenkins test environment causing timeouts...

The tests are running on the Jenkins runners - mostly `r5ad.8xlarge` 32cpu,256ram - same as running it on a workstation so I'm not sure how/if the Jenkins platform can cause it (frontend slowness has nothing with build, tests and other work running directly on the runners)

> Is there some way to gain stats from Jenkins how often a given test fails, the set of runs in which it failed, or sth like that?

From the Jenkins side I can say that the test is running 3 times on each mode (9 in total) and it fails once/twice randomly on different modes. The test_results_analyzer page [0] provides some basic numbers-information

![image](https://user-images.githubusercontent.com/31824530/184526188-fc8e2556-2789-4275-9654-247eadaea6bf.png)

Maybe @fruch can provides more useful information from QE's ELK

[0] https://jenkins.scylladb.com/view/enterprise-2021.1/job/enterprise-2021.1/job/next/test_results_analyzer/

**Comment by fruch** [comment]
> > I'm guessing the modify_config call timed out. It's probably the usual - some slowness in Jenkins test environment causing timeouts...
> 
> The tests are running on the Jenkins runners - mostly `r5ad.8xlarge` 32cpu,256ram - same as running it on a workstation so I'm not sure how/if the Jenkins platform can cause it (frontend slowness has nothing with build, tests and other work running directly on the runners)
> 
> > Is there some way to gain stats from Jenkins how often a given test fails, the set of runs in which it failed, or sth like that?
> 
> From the Jenkins side I can say that the test is running 3 times on each mode (9 in total) and it fails once/twice randomly on different modes. The test_results_analyzer page [0] provides some basic numbers-information
> 
> ![image](https://user-images.githubusercontent.com/31824530/184526188-fc8e2556-2789-4275-9654-247eadaea6bf.png)
> 
> Maybe @fruch can provides more useful information from QE's ELK
> 
> [0] https://jenkins.scylladb.com/view/enterprise-2021.1/job/enterprise-2021.1/job/next/test_results_analyzer/

We are collecting data in ELK only from dtests, not from scylla unittests, so I don't have much more data to add here.

**Comment by bhalevy** [comment]
@benipeled the table you pasted is for `background_reclaim`.
This issue is about `randomized_nemesis_test`

**Comment by benipeled** [comment]
oh no, I got confused with the annoying 2021 issue #8851, please ignore the table above, you can check the test_results_analyzer page for build on https://jenkins.scylladb.com/job/scylla-master/job/build/test_results_analyzer/

**Comment by gusev-p** [comment]
For the `io_fiber` [stepdown code](https://github.com/scylladb/scylladb/blob/master/raft/server.cc#L903) to work, both the `joint` and the final `non-joint` configuration must pass through `fsm`, this ensures that `_non_joint_conf_commit_promise` [will be set](https://github.com/scylladb/scylladb/blob/master/raft/server.cc#L883) at that point. This can however happen before the code in `set_configuration`[ gets to the wait](https://github.com/scylladb/scylladb/blob/master/raft/server.cc#L1306) for `_non_joint_conf_commit_promise`, and we can still get `commit_status_unknown` on [`wait_for_entry`](https://github.com/scylladb/scylladb/blob/master/raft/server.cc#L1297) for `joint`-configuration if io_fiber already [dropped the waiters](https://github.com/scylladb/scylladb/blob/master/raft/server.cc#L910).

It seems that we can just look for `commit_status_unknown` in this [try/catch](https://github.com/scylladb/scylladb/blob/master/raft/server.cc#L1299) and not throw an exception, 
if `_non_joint_conf_commit_promise` already set, since in fact it means that the operation succeeded.

**Comment by kbr-** [comment]
> It seems that we can just look for commit_status_unknown in this [try/catch](https://github.com/scylladb/scylladb/blob/master/raft/server.cc#L1299) and not throw an exception,
if _non_joint_conf_commit_promise already set, since in fact it means that the operation succeeded.

Perhaps that would solve this particular problem.

However I think we're onto something bigger here. When a leader commits an entry that removes it, it should mark all waiters that can be marked at this point before dropping waiters. This would improve liveness in general, not just for this problem. So we should move the check and the call to `drop_waiters` until after we called `notify_waiters`.

**Comment by avikivity** [comment]
raft = experimental, not backporting.
