### ISSUE TITLE
raft/randomized_nemesis_test.basic_generator_test: ticker::tick(ticker::on_tick_t, uint64_t): Assertion `false' failed.

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11288]
Seen in e.g in https://jenkins.scylladb.com/view/scylla-5.1/job/scylla-5.1/job/build/5/artifact/testlog/x86_64/release/randomized_nemesis_test.basic_generator_test.2234.log
```
random-seed=3471357543
INFO  2022-08-10 17:08:18,481 [shard 0] randomized_nemesis_test - basic_generator_test: forwarding: true, frequent snapshotting: true
WARN  2022-08-10 17:08:18,602 [shard 0] raft - [00000000-0000-0000-0000-000000000001] the server 00000000-0000-0000-0000-000000000004 already exists in configuration as voter
WARN  2022-08-10 17:08:18,693 [shard 0] raft - [00000000-0000-0000-0000-000000000009] the server 00000000-0000-0000-0000-000000000004 already exists in configuration as voter
WARN  2022-08-10 17:08:18,693 [shard 0] raft - [00000000-0000-0000-0000-000000000009] the server 00000000-0000-0000-0000-000000000001 already exists in configuration as non-voter
WARN  2022-08-10 17:08:19,529 [shard 0] raft - [00000000-0000-0000-0000-000000000004] the server 00000000-0000-0000-0000-000000000004 already exists in configuration as voter
WARN  2022-08-10 17:08:19,529 [shard 0] raft - [00000000-0000-0000-0000-000000000004] the server 00000000-0000-0000-0000-000000000001 already exists in configuration as voter
WARN  2022-08-10 17:08:19,529 [shard 0] raft - [00000000-0000-0000-0000-000000000004] the server 00000000-0000-0000-0000-000000000005 already exists in configuration as non-voter
WARN  2022-08-10 17:08:19,529 [shard 0] raft - [00000000-0000-0000-0000-000000000004] the server 00000000-0000-0000-0000-000000000007 already exists in configuration as non-voter
ERROR 2022-08-10 17:08:41,550 [shard 0] randomized_nemesis_test - ticker: limit reached
randomized_nemesis_test: ./test/raft/ticker.hh:61: future<> ticker::tick(ticker::on_tick_t, uint64_t): Assertion `false' failed.
Aborting on shard 0.
Backtrace:
  0x638a08
  0x668112
  0x7fbd3e9f0a1f
  /lib64/libc.so.6+0x3d2a1
  /lib64/libc.so.6+0x268a3
  /lib64/libc.so.6+0x26788
  /lib64/libc.so.6+0x35a15
  0x4fdcc7
  0x648194
  0x649577
  0x6487cc
  0x998c88
  0x998161
  0x993ffd
  0x62dbda
  /lib64/libpthread.so.0+0x92a4
  /lib64/libc.so.6+0x100322
```

Test binary is stripped so I can't decode the backtrace.

**Comment by bhalevy** [comment]
Cc @kostja @kbr-

**Comment by bhalevy** [comment]
Hit again https://jenkins.scylladb.com/job/scylla-5.1/job/next/12/artifact/testlog/x86_64/debug/randomized_nemesis_test.basic_generator_test.6678.log

**Comment by eliransin** [comment]
@DoronArazii figure out if this is important enough for a high label.
cc @slivne

**Comment by kbr-** [comment]
I don't think it is, Raft is experimental and the test is for Raft.
But I'll investigate it now anyway.

**Comment by bhalevy** [comment]
Maybe raft is experimental, but it's strategic for us since several other important features depend on it, like tablets.

**Comment by kbr-** [comment]
The following code in raft/server.cc, `set_configuration` can sometimes hang:
```cpp
    auto f = _non_joint_conf_commit_promise.emplace().get_future();
    try {
        co_await wait_for_entry({.term = e.term, .idx = e.idx}, wait_type::committed, as);
    } catch (...) {
        // We need to 'observe' possible exceptions in f, otherwise they will be
        // considered unhandled and cause a warning.
        (void)f.handle_exception([id = _id] (auto e) {
            logger.trace("[{}] error while waiting for non-joint configuration to be committed: {}", id, e);
        });
        throw;
    }
    co_await std::move(f);
```

on `co_await std::move(f)`. That's because we may get removed from the configuration after committing the joint config entry (so the `co_await wait_for_entry(...)` line finishes), but before we commit the non-joint config entry. So some other node will finish the config change and we'll never learn about it.

There are two problems:
- the code should register a callback on the `abort_source` provided by `set_configuration` that will resolve `_non_joint_conf_commit_promise` with an exception
- we should also probably set exception on `_non_joint_conf_commit_promise` when we lose leadership

One could also argue that if the server was removed from the configuration, it's going to be shutdown, so this doesn't matter (the test does not shutdown such servers, that's why the call hangs; the server may even get readded to the config later and the call would eventually finish).

cc @gusev-p, @gleb-cloudius 

I'll prepare a fix which will handle aborts from the `abort_source`. It's probably less important to set exception on leadership loss: if we don't get removed from the config, the promise should eventually be resolved anyway, and if we do, we'll be shutdown so whatever.

**Comment by avikivity** [comment]
Raft = experimental, not backporting.
