### ISSUE TITLE
test_shutdown_all_and_replace_node: node fails to start: waiting for schema information to complete

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11316]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/78/testReport/replace_address_test/TestReplaceAddress/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split012___test_shutdown_all_and_replace_node_rbo_enabled_/
and https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/78/testReport/replace_address_test/TestReplaceAddress/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split012___test_shutdown_all_and_replace_node_rbo_disabled_/
with scylla version 055340ae39ba

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/78/artifact/logs-full.release.012/1660794787841_replace_address_test.py%3A%3ATestReplaceAddress%3A%3Atest_shutdown_all_and_replace_node%5Brbo_enabled%5D/node4.log
```
INFO  2022-08-18 03:44:09,650 [shard 0] gossip - Gossip not settled after 1 polls.
INFO  2022-08-18 03:44:12,650 [shard 0] gossip - Gossip settled after 1 extra polls; proceeding
WARN  2022-08-18 03:44:12,651 [shard 0] gossip - Node 127.0.5.3 does not contain SUPPORTED_FEATURES in gossip or system table
INFO  2022-08-18 03:44:12,651 [shard 0] storage_service - entering JOINING mode
INFO  2022-08-18 03:44:12,654 [shard 0] compaction - [Compact system.local 063fd8e0-1ea8-11ed-b1e2-fc9abd2f643d] Compacting [/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-_kyays8f/test/node4/data/system/local-7ad54392bcdd35a684174e047860b377/mc-12-big-Data.db:level=0:origin=memtable,/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-_kyays8f/test/node4/data/system/local-7ad54392bcdd35a684174e047860b377/mc-10-big-Data.db:level=0:origin=compaction]
INFO  2022-08-18 03:44:12,654 [shard 0] storage_service - waiting for ring information
INFO  2022-08-18 03:44:12,654 [shard 0] storage_service - waiting for schema information to complete
INFO  2022-08-18 03:44:12,692 [shard 0] compaction - [Compact system.local 063fd8e0-1ea8-11ed-b1e2-fc9abd2f643d] Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-_kyays8f/test/node4/data/system/local-7ad54392bcdd35a684174e047860b377/mc-14-big-Data.db:level=0]. 81kB to 40kB (~50% of original) in 37ms = 1MB/s. ~256 total partitions merged to 1.
INFO  2022-08-18 03:44:13,654 [shard 0] storage_service - waiting for schema information to complete
[repeated many times]
INFO  2022-08-18 03:53:04,692 [shard 0] storage_service - waiting for schema information to complete
INFO  2022-08-18 03:53:04,801 [shard 0] compaction_manager - Asked to stop
...
ERROR 2022-08-18 03:53:04,842 [shard 0] init - Startup failed: seastar::sleep_aborted (Sleep is aborted)
```

**Comment by bhalevy** [comment]
@kbr- could this be related to 08842444b412857d9bf758639fb6788193afc2d8?

**Comment by bhalevy** [comment]
Cc @asias

**Comment by bhalevy** [comment]
> @kbr- could this be related to [0884244](https://github.com/scylladb/scylladb/commit/08842444b412857d9bf758639fb6788193afc2d8)?

verified by git bisect

**Comment by DoronArazii** [comment]
@avikivity ^^

**Comment by kbr-** [comment]
The test shuts down all 3 nodes, then restarts 2 of them. When they restart, they no longer remember the `SUPPORTED_FEATURES` application state of the 3rd node, because application states of other nodes is not persisted. When the 4th node wants to replace the 3rd node, it doesn't learn its `SUPPORTED_FEATURES` and calculates empty common features by the cluster.

Before my patch it would ignore that missing node in features calculation.

I think that:
- the features of 3rd node should be taken into account when calculating common features by the new node, even though its down
- when some node reports empty feature set, perhaps it should be considered an error
- the 4th node should be able to learn the features of the 3rd node. The cluster shouldn't forget them. So perhaps the problem is that we don't persist application states of remote nodes?

Maybe we should revert my patch for now, and think about a more holistic solution to this problem...
cc @avikivity @tgrabiec @asias

**Comment by avikivity** [comment]
Reverted.

**Comment by tgrabiec** [comment]
This is similar to https://github.com/scylladb/scylladb/issues/6088

We already persist supported features in `system.peers`. Perhaps other nodes should gossip this on behalf of the nodes which are down. We already do this for TOKENS and HOST_ID. See `gossiper::add_saved_endpoint()`.

**Comment by kbr-** [comment]
> Perhaps other nodes should gossip this on behalf of the nodes which are down.

In order to do this correctly, we would need to persist the *version* of the application state as well - otherwise our regossiping on behalf of others may overwrite a new value with a higher version gossiped by the source.

We should also have a generic correct mechanism for making application states of other nodes persistable, not solve it for each state separately in a buggy way.

**Comment by kbr-** [comment]
> We should also have a generic correct mechanism for making application states of other nodes persistable, not solve it for each state separately in a buggy way.

I would imagine we could have a table which for each application state marks whether it should be persisted or not.
The ones that don't affect safety (such as CACHE_HITRATES) would not be persisted. The ones that do, would be.

**Comment by tgrabiec** [comment]
The way it currently works is that endpoint states are added with generation 0, which means they will be overwritten by anything which actually comes from the node which is down, possible through the memory of some other node. This is not monotonic unfortunately, the persisted view may be newer. We should persist generation and version like you mentioned.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
