### ISSUE TITLE
Add large_collections table

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#11449]
We've hit high write latency in the field where the culprit appears to be collections with too many items.
Although we already have tracking for large_cells, it is possible that a collection will have too many items but still won't cross the large cell threshold.

So @avikivity wrote:
> let's add a large_collections table that stores pointers to collections that have too many values.

**Comment by nyh** [comment]
> We've hit high write latency in the field where the culprit appears to be collections with too many items. Although we already have tracking for large_cells, it is possible that a collection will have too many items but still won't cross the large cell threshold.

Recently @hopugop noticed the bizarre handling of large-collection warning in Alternator as well: In Alternator, all non-key attributes are stored together in one big map (called `:attrs`), so when you have a very large item (DynamoDB jargon for what we call "row") it gets reported by Scylla as a **large cell**, because it considers the entire collection to be one "cell". I found this very counter-intuitive (in the old sstable nomenclature, a "cell" is just one of the items in the map) but it was correctly documented in `docs/dev/system_keyspace.md` (though not in other documents).

What I don't understand, though, is why is it important that we have all three concepts: 1. large cell, 2. large collection, 3. large row.
It seems to me that a large collection can be reported as a "large cell" (as happens today) or "large row" (as I think makes more sense), but why is it important or useful to make the third distinction - between a large collection and a large row? Isn't a large collection a problem precisely because it causes a large row, with all the problems associated with a large row?

Or, is your proposal specifically about the **number** of items, as opposed to about their total size? If so, why?

I understand that it's always possible to be (un)lucky enough that "it is possible that a collection will have too many items but still won't cross the large cell threshold" as you wrote, but why is this an interesting case? If we think that a 1MB cell is fine, why isn't a 1MB collection fine too?

**Comment by bhalevy** [comment]
We have a distinction between large partitions, based on their size, and large partitions that have too many rows.
But both are kept in system.large_partitions, where each record there has both the partition size and number of rows so a user can defer which of it is too large.

We could use similar logic to store large rows, according to their size, and rows that have too many cells, in system.large_rows,
and in the same spirit large cells, according to their size, plus large collections, having many keys, in system.large_cells.

The reason for having multiple system tables is that the size threshold we use is exponentially decreasing.

**Comment by bhalevy** [comment]
> I understand that it's always possible to be (un)lucky enough that "it is possible that a collection will have too many items but still won't cross the large cell threshold" as you wrote, but why is this an interesting case? If we think that a 1MB cell is fine, why isn't a 1MB collection fine too?

We're tackling here 2 different problems: one is memory allocation related to the cell footprint.
The other is reactor stalls related to processing of the collection items (and similarly to many cells in a single row),
where we do not add maybe_yield calls in such loops on purpose so not to sacrifice the common-case performance on the hot path for rare corner cases that the user should be alerted about and fix them by reconsidering their application data model.

**Comment by nyh** [comment]
> We're tackling here 2 different problems: one is memory allocation related to the cell footprint. The other is reactor stalls related to processing of the collection items (and similarly to many cells in a single row),

Right, which is why I believe a large collection should trigger a "large row" warning. If you want to make the definition of "large" have two thresholds (large in bytes, and large in number of cells), you can do that too - it can still be the same for "rows" and "collections" - I think.

I was just suggesting that maybe we don't need to invent a new table for "large collections" and the existing "large row" that we already have is good enough (and better than the "large cell" one we trigger right now when this case happens).

In particular, in Alternator, I think the user only cares that one item ("row" in CQLish) grew too big - the user wouldn't care that the collection `:attrs` (which they aren't even aware exists) is the one that grew too big.

**Comment by bhalevy** [comment]
The schema for the system.large_rows table doesn't have a column for storing which cell (column) is too large, or in case of a collection which collection has too many items.  If the row has a number of collection, it is useful to record which of them (could be more than one collection column) has too many items, so I'm inclined to keep the large collection in system.large_cells rather than system.large_rows - it will be easier to be used by FE and/or the end-user.

So the hierarchy could be:
- large_partitions
  - using the partition size or number of rows thresholds
- large rows
  - using the existing row size threshold, and adding a "number of cells" threshold
- large cells
  - using the existing cell size threshold, and adding a "number of collection items" threshold.

**Comment by bhalevy** [comment]
Note that the reason we currently don't have a "number cells in a row" threshold is that it doesn't grow dynamically - it is determined by the number of columns, while number of rows in a partition and number of items in a collection grow dynamically by cql insertion.

**Comment by avikivity** [comment]
@nyh there are two cell concepts:

1. a table cell - an intersection of a row and a column (primary key + column name)
2. an atomic cell - a CRDT building block

large_cells refers to the first one.
