### ISSUE TITLE
Issue in page Upgrade Guide - Scylla 4.5 to 4.6 for Ubuntu 20.04

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylladb#11456]
I would like to report an issue in page https://docs.scylladb.com/master/upgrade/upgrade-opensource/upgrade-guide-from-4.5-to-4.6/upgrade-guide-from-4.5-to-4.6-ubuntu-20-04

### Problem
command `cat scylla-packages-xxx-x86_64.txt | sudo xargs -n1 apt-get -y` is not correct - there's missing `install`
###  Suggest a fix
It should be: `cat scylla-packages-xxx-x86_64.txt | sudo xargs -n1 apt-get install -y`
Fix should be applied also to example.

**Comment by soyacz** [comment]
I found this command is not efficient. Better fix would be to replace it with:
`sudo apt-get install $(awk '{print $1'} scylla-packages-xxx-x86_64.txt) -y`
cc @annastuchlik @yaronkaikov

**Comment by annastuchlik** [comment]
The issue with the command you reported has been fixed with the PRs listed above. 
However, the page where you found it shouldn't include that command at all... The "Update 3rd party and OS packages" section should only be added to the upgrade guides for the ScyllaDB **image**., for example:
https://docs.scylladb.com/master/upgrade/upgrade-opensource/upgrade-guide-from-4.6-to-5.0/upgrade-guide-from-4.6-to-5.0-image.html
 The section has been removed from other guides, but not from the one you found. I'll open another PR t fix that bug.

**Comment by soyacz** [comment]
Thanks @annastuchlik 
Closing issue as fixed.
