### ISSUE TITLE
Messaging service mis-configures tcp_nodelay for verbs

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#11465]
Messaging wants to turn nodelay ON for gossiper verbs since c4ae2206c79dd929d029d6d3a0aba9068194d887:

```c++
    auto must_tcp_nodelay = [&] {
        if (idx == 1) {
            return true; // gossip
        }
        if (_cfg.tcp_nodelay == tcp_nodelay_what::local) {
            return is_same_dc(id.addr);
        }
        return true;
    }();
```

however, idx == 1 was gossiping messages up until 16d8cdadc9dfc511bec52cdf000570b6b639f4ed, after it gossiper verbs moved to index 0. Other than that, index 1 (0 nowadays) also includes more verbs, exactly `GET_SCHEMA_VERSION` and `*_GROUP0_*` ones.

@avikivity , what's the real intent for tcp_nodelay ?

**Comment by avikivity** [comment]
It should be on by default (low latency), but disabled for cross-dc communication to reduce bandwidth. Most cross-dc traffic is not latency sensitive (LOCAL_QUORUM -> asynchronous replication).

For gossip we do want low latency even cross-dc to avoid marking a node as failed incorrectly.

**Comment by avikivity** [comment]
Looks like the breakage was introduced in 16d8cdadc9dfc511bec52cdf000570b6b639f4ed (4.2). So broken for quite some time, but we never noticed.

I guess it's not a big deal. Lacking nodelay means a possible extra 40ms latency, but in fact it should be rare, since gossip looks more like request-reply than telnet where nagle kicks in.

Still, worth a backport.

**Comment by avikivity** [comment]
Backported to 4.6, 5.0, 5.1.

**Comment by avikivity** [comment]
@benipeled why did this not have a Backport candidate label?

**Comment by benipeled** [comment]
> @benipeled why did this not have a Backport candidate label?

@avikivity same as described on https://github.com/scylladb/scylladb/issues/11497#issuecomment-1246764267
The merged commit https://github.com/scylladb/scylladb/commit/13ace7a05e8a977b807586f8b2430092765344e9 parsed by the backport script but not the commit (the child) themselves,

One of the options to deal with it is to parse the list of commits by using the Jenkins function `build.changeSets()` but in this case, the backport script becomes Jenkins-depended,

I'm trying to figure out if there is a git-native way for this case, or maybe we should improve the backport flow currently in use as discussed on https://github.com/scylladb/scylla-pkg/issues/3090

**Comment by avikivity** [comment]
How are you searching for the commits? git log old..new would show the child commits too.

This is a big hole.

**Comment by avikivity** [comment]
(re-backported to 5.1)

**Comment by benipeled** [comment]
> How are you searching for the commits? git log old..new would show the child commits too.
> 

That's the point - as described on the other issue - it doesn't work that way but going one by one from start (next head) to end (master head)

> This is a big hole.

yes, and not sure who wrote it but that's how it "works" **since ~2020**

The plan is to refactor the backport script to gather the relevant commits by github API `/compare/{master-head}...{next-head}` and parse the results
