### ISSUE TITLE
Cache hitrates leak

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#11497]
The per-table hitrates are reset only on this codepath:

```
messaging_service::remove_error_rpc_client
storage_proxy::remote::connection_dropped
table::drop_hit_rate
```

the `remove_error_rpc_client` is called only on explicit error seen on client. However, if the peer node goes down or advertises cql shutdown, then 

```
storage_service::notify_down
messaging_service::remove_rpc_client
```
 is called which doesn't kick connection-dropped notifier and leaves hitrates not cleaned.

**Comment by xemul** [comment]
@nyh , please comment -- what's the expected lifecycle for per-table hitrates, should it survive any "temporary down" remote node states, or should it be as simple as "no remote node -- no hitrates"?

**Comment by nyh** [comment]
These hitrates supposed to be a recent estimate of the cache hit rate of a node. The current code in db/consistency_level.cc already ignores estimates older than a full second. So it is fine fine to forget the estimates as soon as a node goes down, even temporarily.

When we don't have a hitrate ratio estimate for a node, we send *some* requests to it (this is `max_hit_rate` in db/consistency_level.cc), and the idea is that fresh new hit rate estimates will be piggybacked on the responses.

CC @gleb-cloudius

**Comment by avikivity** [comment]
@benipeled what happened to the backport candidate label?

**Comment by benipeled** [comment]
The backport script is using next-HEAD and master-HEAD as start & end commits to go through git history and parse commits (the end commit is not included) - see the code here [0]

In this case, we had

- \045b05322 - Update seastar submodule **<-- next:HEAD**
- \62ac3432c - Merge "Always notify dropped RPC connections" from Pavel E
- \27e326652 - build_docker.sh:fix python2 dependency **<-- master:HEAD**

The script parsed the merge commit \62ac3432c but didn't parse the child-commits since they merged early in the history (chronological order)

I'm not sure how it worked until now, more likely it didn't, and that's probably the reason for the missing-backports we've seen from time to time (and discussed on https://github.com/scylladb/scylla-pkg/issues/3090),


[0] https://github.com/scylladb/jenkins/blob/b828646a3b271103077b48741fe5292c0d44e97f/backport-queue/backport-queue.py#L41
next job: https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/5264/
backport job: https://jenkins.scylladb.com/job/releng/job/scylla-backport-queue/2104/
