### ISSUE TITLE
offline-installer: oel81 is failing when installing unified relocatable package

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#11584]
on oel81 when installing unified relocatable package, cqlsh is failing to run from a user which isn't root (when root did the install)
```
07:45:21  Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "desc keyspaces" 10.4.2.93 9042'
07:45:21  Exit code: 1
07:45:21  Stdout:
07:45:21  Stderr:
07:45:21  /etc/bashrc: line 99: TMOUT: readonly variable
07:45:21  /etc/bashrc: line 100: TMOUT: readonly variable
07:45:21  Traceback (most recent call last):
07:45:21  File "/opt/scylladb/share/cassandra/bin/cqlsh.py", line 169, in <module>
07:45:21  from cqlshlib import cql3handling, cqlhandling, pylexotron, sslhandling, cqlshhandling
07:45:21  ImportError: No module named cqlshlib
```

**Comment by yaronkaikov** [comment]
happens in `master` and also in `5.1` and `2022.2` releases

**Comment by yaronkaikov** [comment]
@avikivity can you please backport this to 5.1 and 2022.2... it currently failing offline installer oel81 test

**Comment by DoronArazii** [comment]
@avikivity ^^

**Comment by avikivity** [comment]
Backported to 5.1. Presumably older branches are okay since we've seen no complaints.

**Comment by fgelcer** [comment]
either the fix is not enough, or it is missing/broken from 2022.2.0~rc3:


## Installation details

Kernel Version: 4.18.0-147.0.3.el8_1.x86_64
Scylla version (or git commit hash): `2022.2.0.rc3-20221009.994a5f0fbb4` with build-id `756ea8d62c25ed4acdf087054e11b3d07596a117`
Relocatable Package: http://downloads.scylladb.com/unstable/scylla-enterprise/enterprise-2022.2/relocatable/2022-10-09T10:39:11Z/scylla-enterprise-x86_64-package.tar.gz
Cluster size: 1 nodes (i3.large)

Scylla Nodes used in this run:
- artifacts-oel81-jenkins-db-node-f0de5275-1 (34.245.28.218 | 10.4.1.145) (shards: 2)


OS / Image: `ami-0e883e67243efea62` (aws: eu-west-1)

Test: `artifacts-oel81-test`
Test id: `f0de5275-cdfc-4396-89c6-18fe148aabbb`
Test name: `enterprise-2022.2/artifacts-offline-install/artifacts-oel81-test`
Test config file(s):

- [oel81.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9818d76f6d1584c8d4652429a6aa1c616b6bb3c2/test-cases/artifacts/oel81.yaml)

## Issue description

**>>>>>>>**

```
2022-10-09 12:12:44.629: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=21cfbbf5-9d25-45af-b987-e42094d19b07, source=ArtifactsTest.test_scylla_service (artifacts_test.ArtifactsTest) [check cqlsh installation]() message=Traceback (most recent call last):
File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/artifacts_test.py", line 338, in test_scylla_service
self.check_cqlsh()
File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/artifacts_test.py", line 129, in check_cqlsh
output = self.node.run_cqlsh("desc keyspaces")
File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/cluster.py", line 2720, in run_cqlsh
cqlsh_out = self.remoter.run(cmd, timeout=timeout + 30,  # we give 30 seconds to cqlsh timeout mechanism to work
File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
return func(*args, **kwargs)
File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/jenkins/slave/workspace/enterprise-2022.2/artifacts-offline-install/artifacts-oel81-test/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "desc keyspaces" 10.4.1.145 9042'
Exit code: 1
Stdout:
Stderr:
/etc/bashrc: line 99: TMOUT: readonly variable
/etc/bashrc: line 100: TMOUT: readonly variable
Traceback (most recent call last):
File "/opt/scylladb/share/cassandra/bin/cqlsh.py", line 169, in <module>
from cqlshlib import cql3handling, cqlhandling, pylexotron, sslhandling, cqlshhandling
ImportError: No module named cqlshlib
```

**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor f0de5275-cdfc-4396-89c6-18fe148aabbb`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f0de5275-cdfc-4396-89c6-18fe148aabbb)
- Show all stored logs command: `$ hydra investigate show-logs f0de5275-cdfc-4396-89c6-18fe148aabbb`

## Logs:
- **db-cluster-f0de5275.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f0de5275-cdfc-4396-89c6-18fe148aabbb/20221009_121325/db-cluster-f0de5275.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f0de5275-cdfc-4396-89c6-18fe148aabbb/20221009_121325/db-cluster-f0de5275.tar.gz)
- **sct-runner-f0de5275.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f0de5275-cdfc-4396-89c6-18fe148aabbb/20221009_121325/sct-runner-f0de5275.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f0de5275-cdfc-4396-89c6-18fe148aabbb/20221009_121325/sct-runner-f0de5275.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/artifacts-offline-install/job/artifacts-oel81-test/6/)

**Comment by fgelcer** [comment]
@avikivity , did the backport reach enterprise 2022.2?

**Comment by rayakurl** [comment]
seems like it happened on 2022.2 :

## Installation details

Kernel Version: 4.18.0-147.0.3.el8_1.x86_64
Scylla version (or git commit hash): `2022.2.0.rc3-20221009.994a5f0fbb4` with build-id `756ea8d62c25ed4acdf087054e11b3d07596a117`
Relocatable Package: http://downloads.scylladb.com/unstable/scylla-enterprise/enterprise-2022.2/relocatable/2022-10-09T10:39:11Z/scylla-enterprise-x86_64-package.tar.gz
Cluster size: 1 nodes (i3.large)

Scylla Nodes used in this run:
- artifacts-oel81-jenkins-db-node-f0de5275-1 (34.245.28.218 | 10.4.1.145) (shards: 2)


OS / Image: `ami-0e883e67243efea62` (aws: eu-west-1)

Test: `artifacts-oel81-test`
Test id: `f0de5275-cdfc-4396-89c6-18fe148aabbb`
Test name: `enterprise-2022.2/artifacts-offline-install/artifacts-oel81-test`
Test config file(s):

- [oel81.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9818d76f6d1584c8d4652429a6aa1c616b6bb3c2/test-cases/artifacts/oel81.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor f0de5275-cdfc-4396-89c6-18fe148aabbb`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f0de5275-cdfc-4396-89c6-18fe148aabbb)
- Show all stored logs command: `$ hydra investigate show-logs f0de5275-cdfc-4396-89c6-18fe148aabbb`

## Logs:
- **db-cluster-f0de5275.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f0de5275-cdfc-4396-89c6-18fe148aabbb/20221009_121325/db-cluster-f0de5275.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f0de5275-cdfc-4396-89c6-18fe148aabbb/20221009_121325/db-cluster-f0de5275.tar.gz)
- **sct-runner-f0de5275.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f0de5275-cdfc-4396-89c6-18fe148aabbb/20221009_121325/sct-runner-f0de5275.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f0de5275-cdfc-4396-89c6-18fe148aabbb/20221009_121325/sct-runner-f0de5275.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.2/job/artifacts-offline-install/job/artifacts-oel81-test/6/)

**Comment by avikivity** [comment]
It as missing from 2022.2, will be there once the next promotion happens.
