### ISSUE TITLE
Scylla setup: `--setup-nic-and-disks` doesn't improve performance in cassandra-stress

### ISSUE THREAD

**Issue by d-mankowski-synerise** [scylladb/scylladb#11595]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.6.7
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04 (Azure)

*Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker): 3x Azure Standard_L8s_v3
Hardware: sockets=1 cores=4 hyperthreading=enabled (2 threads/core) memory=64GB
Disks: (SSD/HDD, count): nVME, 1

I've setup 2 clusters (each one is made of 3 identical nodes).

First cluster:
- On the first node, I ran `scylla_setup --disks {{ disk }} --nic {{ network_interface_name }} --setup-nic-and-disks --swap-directory /var/lib/scylla --io-setup 1 --no-version-check`
- On the other 2 nodes I ran `scylla_setup --disks {{ disk }} --nic {{ network_interface_name }} --setup-nic-and-disks --swap-directory /var/lib/scylla --io-setup 0 --no-version-check`
- And then copied `/etc/scylla.d/io.conf` and `/etc/scylla.d/io_properties.yaml` from the first node

Second cluster:
- On each node I ran `scylla_setup --disks {{ disk }} --nic {{ network_interface_name }} --setup-nic-and-disks --swap-directory /var/lib/scylla --io-setup 1 --no-version-check`

And then, on both clusters, I ran 3 `cassandra-stress` commands with CL=QUORUM and RF=3, just as we use in production:
- `cassandra-stress write cl=QUORUM n=100000000 -rate threads=50  -schema "replication(factor=3)" -node 172.19.24.5 -mode native cql3 user=cassandra password=cassandra`
- `cassandra-stress read cl=QUORUM n=100000000 -rate threads=50  -schema "replication(factor=3)" -node 172.19.24.5 -mode native cql3 user=cassandra password=cassandra`
- `cassandra-stress mixed cl=QUORUM n=100000000 -rate threads=50  -schema "replication(factor=3)" -node 172.19.24.5 -mode native cql3 user=cassandra password=cassandra`

I expected that the first setup would show somehow better results, but in each test those were slightly worse than the second setup:
- write: `39,987 op/s` vs `40,955 op/s`
- read: `37,578 op/s` vs `37,975 op/s`
- mixed: `36,242 op/s` vs `36,475 op/s`

Option `--setup-nic-and-disks` claims to `greatly improves performance`, but above doesn't show that. Also, this option is disabled (`No`) by default. My questions are:

- Are these unexpected results an outcome of a poorly setup benchmark, and in real production workload I should a noticeable QPS qain?
- Why is `--setup-nic-and-disks` not being setup by default? Does it affect stability, etc., or does it work only under certain circumstances?

**Comment by dorlaor** [comment]
The performance changes you indicate are tiny - only ~1% change.
There is no indication whether you stress the disk at all.
First, check that you manage to maximize a resource (like net, memory, disk) and then prove your
point in Grafana

**Comment by michoecho** [comment]
@d-mankowski-synerise

> First cluster:
> 
>     On the first node, I ran scylla_setup --disks {{ disk }} --nic {{ network_interface_name }} --setup-nic-and-disks --swap-directory /var/lib/scylla --io-setup 1 --no-version-check
>     On the other 2 nodes I ran scylla_setup --disks {{ disk }} --nic {{ network_interface_name }} --setup-nic-and-disks --swap-directory /var/lib/scylla --io-setup 0 --no-version-check
>     And then copied /etc/scylla.d/io.conf and /etc/scylla.d/io_properties.yaml from the first node
> 
> Second cluster:
> 
>     On each node I ran scylla_setup --disks {{ disk }} --nic {{ network_interface_name }} --setup-nic-and-disks --swap-directory /var/lib/scylla --io-setup 1 --no-version-check

You say you wanted to check the effect of `--setup-nic-and-disks`, but the option is present for both clusters. Is this a typo?

Regardless of the above, your benchmark is set up in a way that most likely measures network latency rather than server throughput: in cassandra-stress, every worker thread is synchronous — it sends a request, waits for the response, and only then sends the next request. So the maximum throughput of a single client thread is `1s / latency`, and the maximum throughput of the entire client instance is `number of threads / latency`.

Your number of client threads is 50. Solving `50 / latency = 40000/s` for latency, you get `latency = 1.2ms`, which seems reasonable. If that was the average latency during your test, the results check out. If that's the case, the benchmark is client-bound, not server-bound, so naturally server-side improvements won't improve the result. (However, if average latency was lower than 1.2ms, then maybe something really is amiss). With CL=QUORUM, RF=3, and 3 nodes with 8 vCPUs each, IIRC the cluster should be able to handle more than 100k ops/s at max throughput. (Although that very much depends on the hardware and I'm not familiar with Azure machines.)

IIUC the main improvement done by `perftune` (the thing enabled by `--setup-nic-and-disks`) comes from tweaking interrupt affinity — in particular from centralizing network interrupt handling on a dedicated CPU core. This takes the interrupt processing load from other cores, and — even though Scylla itself has less cores available, the total performance is better. The benefits depend on the setup, I guess, but IIRC `greatly improves performance` translates to something like a 30% throughput improvement for AWS machines. (`perftune` also does some other things, like tweaking disk interrupt affinity and setting some parameters in sysfs. I'm not familiar with them).

I'm not sure why the default suggestion for `--setup-nic-and-disks` is `No`. Are there potential downsides, or maybe it's simply too invasive (since it does something global to the system) to suggest enabling it by default? @vladzcloudius Maybe you can answer this question?

**Comment by vladzcloudius** [comment]
Unless I'm missing something here, based on the description you, @d-mankowski-synerise, give `--setup-nic-and-disks` when you configure both of your clusters.

The only difference I see is that for the first cluster you make sure that `io.conf` and `io_properties.yaml` are the same across all your nodes while for the second you leave whatever `--io-setup 1` (and therefore `iotune`) calculates on each node.

And thus I'm not sure I understand the source of your complain. 

To remove any doubt let's take a look of actual configuration: please, collect and upload the output of `healthcheck` command on each of your two clusters.

If it turns out that I'm right and you enabled it on both clusters - then it explains similar performance results. However this is obviously easily fixable.

However regardless I'd like to make a few notes about Azute LS8_v3 VMs configuration:
* Make sure you enable Accelerated Networking: this will attach a Mellanox SR-IOV NIC VF to your instance instead of using a virtual device.
* Scylla version that you have has a perftune.py that would auto-detect the tweaking mode in a wrong way on a 8 vCPU VM. I recommend using `perftune.py` from the `master` instead because of https://github.com/scylladb/seastar/pull/949

**Comment by d-mankowski-synerise** [comment]
Sorry, a typical copy&paste typo, `--setup-nic-and-disks` was used only in the first setup.

@michoecho Thanks for the great explanation! The QPS seemed suspiciously low to me, I wasn't aware of synchronous nature of cassandra-stress. Will keep it in mind for the future.

@vladzcloudius Accelerated networking was enabled; I will rerun benchmark with another client and `perftune` from master

I think I will follow Ivan Prisyazhynyy's article from [Scylla's site](https://www.scylladb.com/2021/03/04/best-practices-for-benchmarking-scylla/)
Thanks again!

**Comment by d-mankowski-synerise** [comment]
@michoecho @vladzcloudius I would like to ask about one more thing - you said that 

> This takes the interrupt processing load from other cores, and — even though Scylla itself **has less cores available** — the total performance is better

Since Scylla has shard per core architecture, is it safe to re-run setup with `--setup-nic-and-disks`? In other words, if right now there are 32 shards on machine with 32 vCPUs, will taking away 1 vCPU do any harm?

**Comment by michoecho** [comment]
> Since Scylla has shard per core architecture, is it safe to re-run setup with --setup-nic-and-disks? In other words, if right now there are 32 shards on machine with 32 vCPUs, will taking away 1 vCPU do any harm?

Restarting a node with a different number of shards is fine. But be aware that this will trigger a _resharding_ on restart — a rewrite/restructurization of the entire dataset on the node to prepare it for the new number of shards. Since it has to process the entire dataset, the restart may take a long time to complete, depending on how much data there is.

However, I don't remember if re-running the entire `scylla_setup` on a populated node is safe, though. But in this case you only want to update the config, not to re-run the entire setup with RAID setup and so on. To update just the pieces of config which are relevant here, you can use `sudo scylla_sysconfig_setup --setup-nic-and-disks`.

(Details of how this works: `scylla_sysconfig_setup` modifies the relevant — as described by the CLI flags — lines in `/etc/default/scylla-server`, re-generates `/etc/scylla.d/cpuset.conf` and deletes `/etc/scylla.d/perftune.yaml` if it exists. On startup, the `scylla-server` systemd service uses the relevant lines in `/etc/default/scylla-server` to generate `/etc/scylla.d/perftune.yaml` when it's not present, applies the settings from `/etc/scylla.d/perftune.yaml` to the system (by setting IRQ affinities and tweaking sysfs), and appends the options from `/etc/scylla.d/cpuset.conf` to the new `scylla` process).

Of course, as usual, when you change configs which require a restart, be sure to do it one node at a time: https://docs.scylladb.com/stable/operating-scylla/procedures/config-change/rolling-restart.html

**Comment by d-mankowski-synerise** [comment]
Thank you for the explanation
