### ISSUE TITLE
Scylla setup doesn't handle symlinks in `--disks` option

### ISSUE THREAD

**Issue by d-mankowski-synerise** [scylladb/scylladb#11634]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.6.8
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04 (Azure)

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): Azure, Standard_D4s_v5
Hardware: sockets= cores= hyperthreading= memory= doesn't really matter
Disks: (SSD/HDD, count) SSD, 1 (Premium SSD LRS)

Let me give you some brief description how Azure attaches disks to VM - it will help you to understand the issue.

When we create and attach a disk to a VM, we can only specify disk's LUN (Logical Unit Number). The path to block device to which this disk will be mapped to on OS level is basically random - it might be `/dev/sda`, `/dev/sdb`, `/dev/sdc`, and so on.

<img width="1067" alt="image" src="https://user-images.githubusercontent.com/101267779/192051576-76047840-fd0b-49bb-b19f-7f57d359d68a.png">

As a workaround, Azure adds a symlink in: `/dev/disk/azure/scsi1`

```
root@scylladb-backup-test-s-0:/dev/disk/azure/scsi1# ll
total 0
lrwxrwxrwx 1 root root 12 Sep 23 20:16 lun1 -> ../../../sdb
```

So in other words, (this time) disk having LUN 1 was mapped to `/dev/sdb`. But on other VM it could be `/dev/sda`, for example. And now, to the issue - after creating VMs + disks via Terraform, we want to deploy ScyllaDB by using Ansible. And since we can't be sure to which block device this disk got mapped to (without actually checking it on the server), we use `raid_disks: /dev/disk/azure/scsi1/lun1` and Ansible runs `scylla_setup --disks {{ raid_disks }} ...`, which translates to `scylla_setup --disks  /dev/disk/azure/scsi1/lun1`.

And this fails.

```
root@scylladb-backup-test-s-0:~# scylla_setup --disks /dev/disk/azure/scsi1/lun1 --nic eth0 --setup-nic-and-disks --swap-directory /var/lib/scylla  --io-setup 1  --no-version-check
This is a supported kernel version.
ntp is already configured, skip setup
/dev/disk/azure/scsi1/lun1 is busy
RAID setup failed.
```

However, if I use `/dev/sdb` instead of `/dev/disk/azure/scsi1/lun1` - then, it works fine.

**Comment by avelanarius** [comment]
It looks like `/dev/disk/azure/scsi1/lun1 is busy` message comes from here: https://github.com/scylladb/scylladb/blob/ad2f1dc704c008241f2a49aa7ecc296e037378cb/dist/common/scripts/scylla_raid_setup#L65-L66

I tested `is_unused_disk` code on instance on Azure:
https://github.com/scylladb/scylladb/blob/a0ffbf3291b74a238e89fd18d3eb3aecc8d00858/dist/common/scripts/scylla_util.py#L199-L209

I can confirm that `is_unused_disk` doesn't work correctly when passed `/dev/disk/azure/scsi1/lun1`, but works correctly when passed `/dev/sda`. The culprit is in `if not os.path.isdir('/sys/class/block/{dev}'.format(dev=dev.replace('/dev/', ''))):`

The contents of `/sys/class/block/` are as follows on an Azure instance with a single attached disk:
```
$ ls /sys/class/block/
loop0  loop1  loop2  loop3  loop4  loop5  loop6  loop7  sda  sdb  sdb1  sdb14  sdb15  sdc  sdc1  sr0
```

A possible fix is for the function to first resolve symlinks before checking `/sys/class/block/` directory. I'm not sure if this is the correct approach.

cc @syuu1228

**Comment by syuu1228** [comment]
@avelanarius Okay, seems like a script bug, I will fix it.

**Comment by denesb** [comment]
> @syuu1228 - do we need to backport this to 5.1?

Not anymore, 5.1 is EOL. Removing Backport label.
