### ISSUE TITLE
How to define fields of type JSON

### ISSUE THREAD

**Issue by a11enhuang** [scylladb/scylladb#11631]
I have a field of type JSON (fields may be multi-level and the structure is indeterminate), and some properties in this field will be used for searching (different structures have different fields), how can I get define this kind of field? I noticed map type data, but it's not generic (hard to do multi-level) and can't create an index for it; or use UDT fields, if that's the case every time the data structure changes it means I need to Change the definition of UDT, I'm not sure if this is a correct way to use it.
Is there any better way for me to handle this need?

**Comment by nyh** [comment]
Hi, this is a bug and issue tracker, not a place to ask question. There are other good places to ask questions, including the scylladb-dev mailing list (https://groups.google.com/g/scylladb-dev), our slack channel and even stackoverflow (which is the best place for your questions to help others later).  If after discussing all your options you conclude that Scylla is missing a feature, and you are ready to explain why this would be a good/important feature, then you can come here and open a feature request - but not in the form of a question.

In any case, since you're already here, I'll answer: You are right that CQL (both Scylla and Cassandra) does not offer a nested CRDT type (sort of like a nested map where you can update some deep piece of the structure without touching any other part). You can use a map of frozen maps, and things like that, but it won't allow you a completely general json with a different structure in each item.

One workaround you can have is to keep the JSON as a serialized string (or a map containing the first level, with each of the second levels being serialized as a string - this is what we do in Alternator). You're right that this won't allow you to index those deeper values. Depending on your use case, perhaps it makes sense to "denormalize" the data - have a second copy of the deeper data which you need to index in a way that *can* be indexed. Note that we recently added support in Scylla to indexing all the values in a collection, so maybe you can "project" the nested structure into some kind of single-level collection that can be indexed.
