### ISSUE TITLE
test.py: pass ASAN/UBSAN options to Scylla servers used in tests

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#11698]
The code does attempt to pass these options through environment variable and it even prints a very suggestive log message. In `run_test` (test.py):
```python
        UBSAN_OPTIONS = [
            "halt_on_error=1",
            "abort_on_error=1",
            f"suppressions={os.getcwd()}/ubsan-suppressions.supp",
            os.getenv("UBSAN_OPTIONS"),
        ]
        ASAN_OPTIONS = [
            "disable_coredump=0",
            "abort_on_error=1",
            "detect_stack_use_after_return=1",
            os.getenv("ASAN_OPTIONS"),
        ]
        try:
            log.write("=== TEST.PY STARTING TEST {} ===\n".format(test.uname).encode(encoding="UTF-8"))
            log.write("export UBSAN_OPTIONS='{}'\n".format(
                ":".join(filter(None, UBSAN_OPTIONS))).encode(encoding="UTF-8"))
            log.write("export ASAN_OPTIONS='{}'\n".format(
                ":".join(filter(None, ASAN_OPTIONS))).encode(encoding="UTF-8"))

...

            process = await asyncio.create_subprocess_exec(
                path, *args,
                stderr=log,
                stdout=log,
                env=dict(os.environ,
                         UBSAN_OPTIONS=":".join(filter(None, UBSAN_OPTIONS)),
                         ASAN_OPTIONS=":".join(filter(None, ASAN_OPTIONS)),
                         # TMPDIR env variable is used by any seastar/scylla
                         # test for directory to store test temporary data.
                         TMPDIR=os.path.join(options.tmpdir, test.mode),
                         **env,
                         ),
                preexec_fn=os.setsid,
            )
```

The spawned process is `pytest`.

But then in test/pylib/scylla_cluster.py:
```python
    async def start(self) -> None:
        """Start an installed server. May be used for restarts."""

        # Add suite-specific command line options
        scylla_args = SCYLLA_CMDLINE_OPTIONS + self.cmdline_options
        env = os.environ.copy()
        env.clear()     # pass empty env to make user user's SCYLLA_HOME has no impact
        self.cmd = await asyncio.create_subprocess_exec(
            self.exe,
            *scylla_args,
            cwd=self.workdir,
            stderr=self.log_file,
            stdout=self.log_file,
            env=env,
            preexec_fn=os.setsid,
        )
```

The actual Scylla process is spawned with an empty enviroment.
And even if we didn't do `env.clear()`, it seems that `env` does not contain `ASAN_OPTIONS`/`UBSAN_OPTIONS` - maybe `pytest` doesn't forward the environment?

cc @kostja @nyh

**Comment by nyh** [comment]
What do you mean "pytest doesn't forward the environment"? Isn't it code in test.py, not in individual pytest tests, which runs Scylla?
These environment variables worked in test/cql-pytest/run.py - I checked when I added them. I don't know what in test.py made them disappear.

**Comment by nyh** [comment]
Looking at the code you pasted, it appears buggy and adds these environment variables in the wrong place... So it's straightforward to fix, no?

**Comment by kbr-** [comment]
> Isn't it code in test.py, not in individual pytest tests, which runs Scylla?

Ahh you're right.
It doesn't matter what we pass to `pytest`.

So this code which passes `ASAN_OPTIONS`/`UBSAN_OPTIONS` in `run_test` is only relevant when we're running tests through run.py - because then they are passed to run.py and run.py starts the Scylla server.

The tests which are not using run.py (topology, cql approval) were actually never passing these options.

**Comment by nyh** [comment]
> > Isn't it code in test.py, not in individual pytest tests, which runs Scylla?
> 
> Ahh you're right. It doesn't matter what we pass to `pytest`.
> 
> So this code which passes `ASAN_OPTIONS`/`UBSAN_OPTIONS` in `run_test` is only relevant when we're running tests through run.py - because then they are passed to run.py and run.py starts the Scylla server.

Oh :-) By the way, it's also not necessary for run.py - because that script knows the user can run it directly, **not** through test.py, so it cannot and does not assume anything from the caller's environment. You can see in test/cql-pytest/run.py that it sets these variables itself (this is since a8b02f7965787ec20396b9c852b34cb178f8fc81).

I think the one place that these environment variables had an effect in the current test.py was the C++ unit tests.

**Comment by temichus** [comment]
so I did some investigations and there is results

UnitTest and  BoostTest use ASAN/UBSAN options that mentioned in the issue 

 CQLApprovalTest, PythonTest, TopologyTest - uses ScyllaServer class that as I see now put own ASAN/UBSAN options at server start
 
 https://github.com/scylladb/scylladb/blob/a4e26585e56e08d852a11e676e4b8be86b6eeccf/test/pylib/scylla_cluster.py#L530-L538
  
 RunTest - also put own ASAN/UBSAN options 
 
 https://github.com/scylladb/scylladb/blob/a4e26585e56e08d852a11e676e4b8be86b6eeccf/test/cql-pytest/run.py#L250-L268
 
 
 ToolTest - for this test,  this case  looks like is not applicable because  ToolTest do not need a Scylla cluster set-up for them
 but can be put here if needed, during start jmx/scylla process:
 https://github.com/scylladb/scylladb/blob/a4e26585e56e08d852a11e676e4b8be86b6eeccf/test/nodetool/conftest.py#L197-L210
 
 So my suggestion is to remove log.write about export options but leave modifying env because these options are used in 2 types of tests 
 
@denesb, I need your advice regarding  ToolTest, does these tests need  ASAN/UBSAN options or not? 

cc @kostja, @kbr-scylla

**Comment by nyh** [comment]
I think much of the discussion in the beginning of this issue is outdated. I have a sense of deja-vu, we recently discussed it elsewhere. The current code has test.py set and export these variables, for its children, but then when running a child process, the code deliberately clears the environment and these variables are lost. We should NOT clear the environment but there was a specific environment variable that bothered @kostja (I can't find now the reference to this discussion) which how we got this environment clearing.

In any case, as you know I don't see any problem with the "duplication" of this setting to a few places, and I wouldn't go running to remove it, especially not from code (specifically test/cql-pytest/run.py) which does not run only from inside test.py. Maybe nothing needs to be done about this issue.

**Comment by denesb** [comment]
> @denesb, I need your advice regarding ToolTest, does these tests need ASAN/UBSAN options or not?

The ToolTest suite indeed doesn't start a scylla server, but it does start scylla instances, because the tools that are tested are hosted by the scylla executable. So yes, it does need the options. Typically these tests invoke the tool in a fixture, e.g. the nodetool fixture in the nodetool suite.

**Comment by kbr-scylla** [comment]
> So my suggestion is to remove log.write about export options but leave modifying env because these options are used in 2 types of tests

I think logging the passed env might be useful, just make sure we log the env that we're indeed going to use in the end, not something that will be later replaced.

**Comment by temichus** [comment]
> hese options are used in 2 types of tests

as I mentioned these options are used, but only in 2 types of tests.

**Comment by temichus** [comment]
PR merged, close the issue
