### ISSUE TITLE
scylla_setup "provisioning in a similar environment" message is missing a value for `--online-discard` parameter

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylladb#11700]
*Installation details*
HEAD: 95f31f37c1d2

*Description*
`scylla_setup` printed the following message at the end of the interactive execution when "online discard" mount option has been selected:

```
ScyllaDB setup finished.
scylla_setup accepts command line arguments as well! For easily provisioning in a similar environment than this, type:

    scylla_setup \
                 --disks /dev/nvme0n1,/dev/nvme0n2 \
                 --online-discard --nic ens5 --io-setup 1 \
                 --no-version-check --no-fstrim-setup --no-rsyslog-setup
```

However the `--online-discard` requires a boolean parameter hence the command above fails with the following error when attempted:

```
sudo scylla_setup --disks /dev/nvme0n1,/dev/nvme0n2 --online-discard --nic ens5 --io-setup 1 --no-version-check --no-fstrim-setup --no-rsyslog-setup
usage: scylla_setup [-h] (--disks DISKS | --no-raid-setup) [--raid-level-5] [--online-discard ONLINE_DISCARD] [--nic NIC] [--ntp-domain NTP_DOMAIN] [--swap-directory SWAP_DIRECTORY] [--swap-size SWAP_SIZE] [--ami]
                    [--setup-nic-and-disks] [--developer-mode] [--no-ec2-check] [--no-kernel-check] [--no-verify-package] [--no-enable-service] [--no-bootparam-setup] [--no-ntp-setup] [--no-coredump-setup] [--no-sysconfig-setup]
                    [--io-setup {0,1}] [--no-io-setup] [--no-version-check] [--no-node-exporter] [--no-cpuscaling-setup] [--no-fstrim-setup] [--no-memory-setup] [--no-swap-setup] [--no-rsyslog-setup]
                    [--rsyslog-server RSYSLOG_SERVER]
scylla_setup: error: argument --online-discard: expected one argument
```

The correct command would look like this:

```
sudo scylla_setup --disks /dev/nvme0n1,/dev/nvme0n2 --online-discard 1 --nic ens5 --io-setup 1 --no-version-check --no-fstrim-setup --no-rsyslog-setup
```

In addition to that some parameters chosen in the interactive mode (like `--setup-nic-and-disks`) are not even printed making the message in question totally BOGUS!

**Comment by vladzcloudius** [comment]
@DoronArazii FYI

**Comment by DoronArazii** [comment]
@avikivity please have a look

**Comment by syuu1228** [comment]
This is because we construct "provisioning in a similar environment" message from type of variables in `args`, and default value of `--online-discard` is set to `True`, so the code expect the option should be configured as `action='store_true'` which use boolean type, so the code print `--online-discard` without option, as @vladzcloudius described avobe.

But --online-discard is actually doesn't specified action option, so it configured as `action='store'` which use string type, since it's default value.

I think this is bug of this option, because default value and specified value will use different type.

To fix the bug, I think we should modify this option to use this int type and make choices only 0 and 1, just like `--io-setup` does today:
```
    parser.add_argument('--io-setup', default=1, choices=[0, 1], dest='io_setup', type=int,
                        help='Run I/O configuration setup (i.e. iotune). Defaults to 1.')
```

I will post the patch.

**Comment by syuu1228** [comment]
Note: We cannot modify `--online-discard` to use `action='store_true', default=True`, since we cannot pass False to store_true option since it doesn't take parameter.
To use `action='store_true'`, we need change the option to `--no-online-discard` and use `action='store_true', default=False`.
But probably which is not what we want, so better to use int like `--io-setup`.

**Comment by avikivity** [comment]
Backported to 5.0, 5.1.
