### ISSUE TITLE
Scylla documentation missing for AzureSnitch

### ISSUE THREAD

**Issue by apesaDS** [scylladb/scylladb#11712]
I am working with Intel in Azure and noticed our Azure Image is using the AzureSnitch. When looking throuogh docs for Scylla Snitches I noticed the AzureSnitch is not documented.

**Comment by annastuchlik** [comment]
@yaronkaikov @tarzanek We've added support for Azure snitch (https://github.com/scylladb/scylladb/pull/9084), but it was never documented. Could you help me with that or refer me to somebody who could?
The documentation should explain when and how to use the Azure snitch and provide an example.
It should be added to this page: https://docs.scylladb.com/stable/operating-scylla/system-configuration/snitch.html

**Comment by tarzanek** [comment]
@annastuchlik sorry for late reply
so I can help you, since I reviewed Pekkas code and I partially know where he came from

anyhow
if you copy GoogleCloudSnitch section from your docs link
and replace GoogleCloudSnitch -> AzureSnitch  (GCE -> Azure ,  region -> location )
you WILL get complete docs
I can review it if you want

hth
L

**Comment by annastuchlik** [comment]
Thanks! I'll open a PR.

**Comment by denesb** [comment]
Documentation fix, removing label.
