### ISSUE TITLE
docs: Issue in page Upgrade Guide - ScyllaDB 5.0 to ScyllaDB Enterprise 2022.1 for Ubuntu

### ISSUE THREAD

**Issue by goodwinbg1906** [scylladb/scylladb#11796]
I would like to report an issue in page https://docs.scylladb.com/master/upgrade/upgrade-to-enterprise/upgrade-guide-from-5.0-to-2022.1/upgrade-guide-from-5.0-to-2022.1-ubuntu

### Problem
In the instructions for **Start the node** we state to start scylla service the command is `sudo service scylla-enterprise-server start`

###  Suggest a fix
The resolution should be `sudo service scylla-server start`

**Comment by tomer-sandler** [comment]
@annastuchlik ^^

**Comment by annastuchlik** [comment]
Thanks for reporting the issue. It has been fixed with this commit: https://github.com/scylladb/scylladb/commit/922f6ba3dd30a3856ca18190a3fd66c8765efa38
The changes are available online: https://docs.scylladb.com/master/upgrade/upgrade-to-enterprise/upgrade-guide-from-5.0-to-2022.1/upgrade-guide-from-5.0-to-2022.1-ubuntu
