### ISSUE TITLE
view_builder doesn't clean up view_build_status table after removed nodes

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#11836]
If nodes are removed while view building is going on, entries corresponding to these nodes are not cleaned up from said table, potentially resulting in unnecessary view update generation for node operations in the future, adding significant excess load to the affected nodes.

**Comment by tarzanek** [comment]
another scenario to consider is if records are cleaned up, when the nodes get decommissioned before view is rebuilt

**Comment by vladzcloudius** [comment]
@denesb @nyh @asias What I still don't understand is why the view build status has any impact on the way a streamed data is handled?

In particular, why a base table streamed data has to go via staging EVEN IF there is an ongoing view building?

**Comment by asias** [comment]
> @denesb @nyh @asias What I still don't understand is why the view build status has any impact on the way a streamed data is handled?
> 
> In particular, why a base table streamed data has to go via staging EVEN IF there is an ongoing view building?

Because if the view building is half done, streaming the existing view table + handling pending writes for view update is not enough.

**Comment by asias** [comment]
A safer way is to ignore the host id that is not currently part of the cluster.  view_status has returned the host id. check_view_build_ongoing should check if the host id is valid. 

```
future<bool> check_view_build_ongoing(db::system_distributed_keyspace& sys_dist_ks, const sstring& ks_name, const sstring& cf_name) {
    return sys_dist_ks.view_status(ks_name, cf_name).then([] (std::unordered_map<utils::UUID, sstring>&& view_statuses) {
        return boost::algorithm::any_of(view_statuses | boost::adaptors::map_values, [] (const sstring& view_status) {
            return view_status == "STARTED";
        });
    });
}
```

**Comment by vladzcloudius** [comment]
> > @denesb @nyh @asias What I still don't understand is why the view build status has any impact on the way a streamed data is handled?
> > In particular, why a base table streamed data has to go via staging EVEN IF there is an ongoing view building?
> 
> Because if the view building is half done, streaming the existing view table + handling pending writes for view update is not enough.

I had a call with Botond and he explained to me why this is needed in general. 
However the current implementation seems to be a "poor people" one because it's hard to imagine something less optimal than this:
1) Since the leaving node is going to continue view building till it leaves this is going to make all that data to be processed twice: by both old and new owners of the base table tokens.
2) (Related to (1)) View building is a heavy process that is hard on the base table replica. The current implementation is going to apply this overhead both on the old and new base table replicas, which in line is going to make the topology change operation even slower by saturating resources. CPU in particular.

To address (1) instead of blindly re-processing in-coming base table data on a new replica without stopping it on a leaving node we could, for instance, send token where the old replica has left as the last thing it does in the context of unbootstrapping so that the new (base table) replica can continue the unfinished view building process.

To address (2), in order to speed up the topology change operation, we could take the view building to the node(s) that are *not* joining or leaving as long as streaming is going on:
1) When we bootstrap - make old replicas build the view.
2) When we decommission - make receiver replicas build the view.

As a result the topology change operation is going to complete a lot faster.

**Comment by DoronArazii** [comment]
@cvybhu it's in your queue for 5.2?

**Comment by cvybhu** [comment]
> @cvybhu it's in your queue for 5.2?

Probably not, sadly I'm not well acquainted with MVs yet

**Comment by nyh** [comment]
> @cvybhu it's in your queue for 5.2?

Closing this issue (either fixing it or closing it) is on our queue for this quarter, but not aimed at any specific release. In any case, if I understand correctly, @denesb 's fix of https://github.com/scylladb/scylladb/issues/11905 made fixing this issue much less interesting because there is no performance penalty - to the point we need to consider if this issue needs fixing at all. I think it is more important that https://github.com/scylladb/scylladb/issues/11905 be backported.

**Comment by DoronArazii** [comment]
@denesb can we close it?

**Comment by denesb** [comment]
> @denesb can we close it?

It is debatable. With https://github.com/scylladb/scylladb/issues/11905 these problematic stale entries are now ignored and are not causing trouble anymore. They don't take up a lot of space either, as we are talking about a handful of rows and an administrator can always delete them manually if needed. So I would argue that we should close this as we have much more meaningful tasks to spend our time on. We can re-visit this issue if/when these rows ever become problematic again. Since @nyh suggested the same above, I'm going ahead and closing this issue, like I said we can re-open if we find a good reason (or an easy way) to clean up these rows properly.
