### ISSUE TITLE
Use newer zstd version and/or lz4

### ISSUE THREAD

**Issue by mykaul** [scylladb/scylladb#11857]
Scylla is using a rather old zstd version. Newer version offer substantially improved performance (mainly decompression, also across multiple archs, including ARM). For comparison:

```
Compressor name | Ratio | Compression | Decompress.
zstd 1.4.0 -1 | 2.884 | 530 MB/s | 1360 MB/s
zstd 1.5.1 -1 | 2.887 | 530 MB/s | 1700 MB/s
zstd 1.5.1 --fast=4 | 2.148 | 710 MB/s | 2300 MB/s
lz4 1.9.3 | 2.101 | 740 MB/s | 4500 MB/s
snappy 1.1.9 | 2.073 | 550 MB/s | 1750 MB/s
```

It makes sense to decide that we prefer lz4 with slightly lower general compression ratio but with much faster performance, btw.

**Comment by nyh** [comment]
Why are you saying that Scylla is "using a rather old zstd version"? As far as I can tell, Scylla is simply using the build system's libstd version, and I checked our dbuild (I think it uses Fedora 34? I don't remember) and it includes /usr/lib64/libzstd.so.1.5.2. Where did you see an older version?

Also, you are suggesting that we should decide to prefer lz4 over zstd, but don't we already? Isn't lz4 already the default? Or was it _uncompressed_ the default now? @kbr- you added zstd support (issue #2613), maybe you remember what is our default and its justification?

I see multiple Google results suggesting that lz4 is still our default (e.g., https://www.scylladb.com/2019/10/04/compression-in-scylla-part-one/, https://docs.scylladb.com/stable/architecture/sstable/sstable2/sstable-compression.html), and most importantly our official documentation https://docs.scylladb.com/stable/cql/ddl.html says that our default compressor is lz4. If this is not true, it should be fixed. In any case, ddl.html must be at best incomplete, if not wrong, because it is missing mentioning the possibility of zstd completely :-(

**Comment by mykaul** [comment]
> Why are you saying that Scylla is "using a rather old zstd version"? As far as I can tell, Scylla is simply using the build system's libstd version, and I checked our dbuild (I think it uses Fedora 34? I don't remember) and it includes /usr/lib64/libzstd.so.1.5.2. Where did you see an older version?
> 
> Also, you are suggesting that we should decide to prefer lz4 over zstd, but don't we already? Isn't lz4 already the default? Or was it _uncompressed_ the default now? @kbr- you added zstd support (issue #2613), maybe you remember what is our default and its justification?

https://github.com/scylladb/zstd

> 
> I see multiple Google results suggesting that lz4 is still our default (e.g., https://www.scylladb.com/2019/10/04/compression-in-scylla-part-one/, https://docs.scylladb.com/stable/architecture/sstable/sstable2/sstable-compression.html), and most importantly our official documentation https://docs.scylladb.com/stable/cql/ddl.html says that our default compressor is lz4. If this is not true, it should be fixed. In any case, ddl.html must be at best incomplete, if not wrong, because it is missing mentioning the possibility of zstd completely :-(

@annastuchlik , please review.

**Comment by nyh** [comment]
@mykaul, @avikivity removed the **use** of the zstd submodule in in Scylla in commit 0dc78d38f174e5a064ff9b65e60f20472603fb31, so we no longer use that repository which you found - as I said we are using Fedora 34's zstd package which is fairly recent (1.5.2), and as we update the dbuild environment, zstd package will continue to get updated. 
The repository https://github.com/scylladb/zstd which you found is only in use by antique branches, and I'm not sure when (if ever...) we can go and remove it :-( But something I think we *can* do is to create a commit on that repository making it empty and adding a README.md saying it is obsolete.

I also believe (but please correct me if I'm wrong) that your suggestion that zstd is our default and we should change it to lz4 is wrong, and lz4 is already the default. The code says:
```c++
compression_parameters::compression_parameters()
    : compression_parameters(compressor::lz4)
{}
``

If that is the case suggest that I'll close this issue and open a documentation issue instead, @mykaul do you agree?

**Comment by nyh** [comment]
Opened a documentation issue https://github.com/scylladb/scylladb/issues/11858 and closing this issue. @mykaul feel free to reopen if you feel there's anything left to do here besides the documentation issue.
