### ISSUE TITLE
doc: add the rollback procedure for the ScyllaDB image

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylladb#11909]
With [this PR](https://github.com/scylladb/scylla-docs/issues/4124), we extended the upgrade guides for the ScyllaDB image with the procedure to upgrade ScyllaDB and update the OS packages in one step. 
However, the upgrade guide is missing the appropriate rollback procedure: it explains how to rollback ScyllaDB, but not the updated packages.
@yaronkaikov Could you describe the procedure here so that I can add it to the upgrade guides for the ScyllaDB image, for example: https://docs.scylladb.com/stable/upgrade/upgrade-opensource/upgrade-guide-from-5.0-to-5.1/upgrade-guide-from-5.0-to-5.1-image.html

**Comment by yaronkaikov** [comment]
@annastuchlik Since we dropped the OS-packages part i think we can close this

**Comment by yaronkaikov** [comment]
@annastuchlik See https://github.com/scylladb/scylla-pkg/issues/3120#issuecomment-1321039805 . we probably should revert those changes

**Comment by tzach** [comment]
@yaronkaikov to validate. Is this part

```
cat scylla-packages-5.2.0-x86_64.txt | sudo xargs -n1 apt-get install -y
```

And the entire [EC2/GCP/Azure Ubuntu Image section](https://opensource.docs.scylladb.com/stable/upgrade/upgrade-opensource/upgrade-guide-from-5.1-to-5.2/upgrade-guide-from-5.1-to-5.2-generic.html#download-and-install-the-new-release)
Is not relevant any more?
Since which release?
How should one upgrade the OS when upgrading Scylla Image?

**Comment by roydahan** [comment]
We didn't/don't do that.
Upgrade OS packages is not part of any testing or certification process.

**Comment by tzach** [comment]
@annastuchlik lets remove the Image section and point image users to the Ubuntu instructions

**Comment by mykaul** [comment]
We do not roll back OS packages.
