### ISSUE TITLE
Docs: Update cluster admin procedures to the post Raft era

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#12174]
All relevant admin procedures need to be update, and tested.

- [Create a Scylla Cluster - Single Data Center (DC)](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/create-cluster.html)
- [Create a Scylla Cluster - Multi Data Center (DC)](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/create-cluster-multidc.html) [1]
- [Create a Scylla Cluster on EC2 (Single or Multi Data Center)](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/ec2-dc.html)
- [Remove a Data-Center from a Scylla Cluster](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/decommissioning-data-center.html) [1]
-  [Remove a Seed Node from Seed List](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/remove-seed.html)
- [Safely Start or Restart Your Cluster](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/safe-start.html)

### Node Management
- [Adding a New Node Into an Existing Scylla Cluster - Out Scale](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/add-node-to-cluster.html)
- [Adding a New Data-Center Into an Existing Scylla Cluster - Out Scale](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/add-dc-to-existing-dc.html) [1]
- [Remove a Node from a Scylla Cluster - Down Scale](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/remove-node.html)
- [Replace a Dead Node in a Scylla Cluster](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/replace-dead-node.html)
- [Replace More then One Dead Node in a Scylla Cluster](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/replace-dead-node-or-more.html)
- [Replace a Seed Node in a Scylla Cluster](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/replace-seed-node.html)
- [Replace a Running Node in a Scylla Cluster](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/replace-running-node.html)
- [Safely Remove a Joining Node](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/safely-removing-joining-node.html)
- [What to do if a Node Starts Automatically](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/clear-data.html)
- [Add a Decommissioned Node Back to a Scylla Cluster](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/revoke-decommission.html)
- [Cluster Membership Change Notes](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/membership-changes.html)
- [Add Bigger Nodes to a Cluster](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/scale-up-cluster.html#add-bigger-nodes-to-a-cluster)

[1] Reccomend a 3 DC toplogy (not 2)

**Comment by kbr-** [comment]
I wonder what exactly we should write - because the user interface generally does not change, all procedures are performed in the same way.

One thing we could perhaps raise the awareness of, is maintaining a majority of nodes at all times, e.g. the recommendation of using 3 DCs instead of 2 so that losing one of them won't cause a majority loss.

But maybe we shouldn't repeat ourselves in each of these articles, instead link to the Raft article which describes the issue in detail.

**Comment by tzach** [comment]
As a first step, we need to validate that all the procedures does work as documented @roydahan 

Can we simplify 
https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/add-dc-to-existing-dc.html
to add more than one node at a time?

**Comment by roydahan** [comment]
Whatever we support now should be listed somewhere in a centralized place.
I have no idea what it means.
Do we support adding more than one node in parallel now?
If so, I need it as a "separate feature" somewhere.

**Comment by mykaul** [comment]
> > Can we simplify
> > https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/add-dc-to-existing-dc.html
> > to add more than one node at a time?
> 
> We don't support adding more than one node at a time.

We don't support, or (with raft?) it will add one node after another (serialize the process) ?

**Comment by kbr-** [comment]
> We don't support, or (with raft?) it will add one node after another (serialize the process) ?

Once we have the Raft-based topology coordinator, topology operations will be serialized.
Currently we only serialize schema changes.

**Comment by kostja** [comment]
@tzach and @roy I went over this list and read the mentioned chapters. I don't believe we should be changing any of those.  Chapters   [Replace More then One Dead Node in a Scylla Cluster](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/replace-dead-node-or-more.html)
and  [Cluster Membership Change Notes](https://docs.scylladb.com/stable/operating-scylla/procedures/cluster-management/membership-changes.html) may receive a refreshment, mentioning we're now using Raft rather than gossip to distribute schema information and we store cluster topology in Raft **in addition** to gossip as a transitory measure to fully Raft based topology changes. 
But really, these are a few sentences at best, so what exactly do we wish to change in the docs?

@mykaul @kbr- is writing that with or without raft, the procedure today is to add one node at a time. And it won't change until gleb's patches are in.
@roydahan we support all the same features as before, but with Raft they have become safe with regard to schema changes. There is nothing to update, really, the necessary documentation edits have been made.

**Comment by kbr-scylla** [comment]
> There is nothing to update, really, the necessary documentation edits have been made.

In that case I'm closing the issue
