### ISSUE TITLE
test.py: after-test check may fail to detect a crashed instance in some cases

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#12360]
In scylla-enterprise branch, we have the following test.py.log:
```
------ Ending test test_clustering_order.1 ------
------ Starting test test_describe.2 ------
INFO  2022-12-19 12:55:33,754 [shard 0] migration_manager - Create new Keyspace: KSMetaData{name=cql_test_1671447333753, strategyClass=org.apache.cassandra.locator.NetworkTopologyStrategy, strategyOptions={datacenter1=1}, cfMetaData={}, durable_writes=1, userTypes=org.apache.cassandra.config.UTMetaData@0x6000006bc1a0}
INFO  2022-12-19 12:55:33,756 [shard 0] schema_tables - Creating keyspace cql_test_1671447333753
WARN  2022-12-19 12:55:33,758 [shard 0] storage_service - Failure to update pending ranges for keyspace cql_test_1671447333753 ignored
INFO  2022-12-19 12:55:33,775 [shard 0] schema_tables - Schema version changed to 481b1ada-e093-35a2-a986-5e788cb4e0e5
scylla: seastar/include/seastar/core/sharded.hh:796: Service &seastar::sharded<audit::audit>::local() [Service = audit::audit]: Assertion `local_is_initialized()' failed.
Aborting on shard 0.
Backtrace:
  0x3630f78
  0x36591d2
  /lib64/libc.so.6+0x3cb4f
  /lib64/libc.so.6+0x8ce7b
  /lib64/libc.so.6+0x3caa5
  /lib64/libc.so.6+0x267fb
  /lib64/libc.so.6+0x2671a
  /lib64/libc.so.6+0x35655
  0x24140f8
  0x2412f64
  0x1d08338
  0x1d125d7
  0x1d005d8
  0x185dbe2
  0x187237b
  0x185d7bd
  0x18597be
  0x1886471
  0x1887c2b
  0x1887ab9
  0x18877b4
  0x35fb613
  0x363eab4
  0x363fba7
  0x363f059
  0x35f34c3
  0x35f2738
  0x10356f4
  0x1064f60
  0x10349a7
  /lib64/libc.so.6+0x2750f
  /lib64/libc.so.6+0x275c8
  0x1033ce4
------ Starting test test_filtering.2 ------
------ Starting test test_frozen_collection.2 ------
------ Starting test test_json.3 ------
------ Starting test test_large_cells_rows.2 ------
------ Starting test test_logs.1 ------
------ Starting test test_lwt.1 ------
------ Starting test test_materialized_view.1 ------
------ Starting test test_minmax.3 ------
------ Starting test test_non_deterministic_functions.3 ------
------ Starting test test_null.3 ------
------ Starting test test_range_and_slice.1 ------
------ Starting test test_scan.1 ------
------ Starting test test_secondary_index.1 ------
------ Starting test test_service_levels.1 ------
------ Starting test test_shedding.1 ------
------ Starting test test_ssl.1 ------
------ Starting test test_sstable.1 ------
------ Starting test test_static.1 ------
------ Starting test test_system_tables.1 ------
------ Starting test test_tombstone_limit.2 ------
------ Starting test test_tools.2 ------
------ Starting test test_ttl.2 ------
------ Starting test test_type_duration.2 ------
------ Starting test test_type_string.3 ------
------ Starting test test_type_time.3 ------
------ Starting test test_uda.1 ------
------ Starting test test_use.2 ------
------ Starting test test_using_timeout.2 ------
------ Starting test test_utf8.2 ------
------ Starting test test_validation.2 ------
------ Starting test test_virtual_tables.3 ------
```

This shows that test.py keeps trying to use a crashed instance for a test.

How to reproduce:

It's unclear, but let's start by adding an abort() call to e.g. storage_proxy::cas, and issuing a CAS from a test. This would lead to a server crashing on any test that has an LWT in it -and not crashing in tests which don't use LWT, so not crashing right away. This server should not be returned to the pool.

**Comment by nyh** [comment]
@kostja noticed that this bug is specific to how test.py runs cql-pytest tests - test.py no longer runs `test/cql-pytest/run` and instead runs Scylla with its own code and then runs individual test pytest files, individually. While cql-pytest correctly detects if Scylla goes down between test functions and stops the entire pytest run (see `test/cql-pytest/conftest.py`, the `cql_test_connection` autouse fixture), it can't prevent test.py from reusing the dead Scylla to run pytest again on additional test files. test.py needs to test Scylla is still alive itself before reusing it it for the next test file.

@kostja wrote on the mailing list that we do have such a feature in test.py - it's just not used for cql-pytest tests, and it should be:

> cql-pytest uses its own suite type. When we roll out additional test.py features we don't
> roll them out to all suites types ...  I see now that you'd like pre/post liveness checks to
work in cql-pytest, I don't think it'll be a big deal to add it.

By the way, if someone is curious why the fact that test.py runs cql-pytest with a dead Scylla causes not just one failed test function (the first one) per test file, but each and every test function to fail (in one Jenkins run we saw over 2000 failed tests), the explanation is as follows: The `cql_test_connection` fixture, which is supposed to detect Scylla failures and stop the run (instead of showing every single test to have failed) currently assumes that a test starts with a working Scylla, and detects if Scylla broke by the end of the test. When the test starts with Scylla already broken, the "cql" fixture will fail to be created, and each test using it will fail individually. This makes it almost impossible to understand which test really failed (i.e., caused Scylla to crash), and that's why it's important to fix this issue.

**Comment by kostja** [comment]
@alecco this should be a fairly straightforward fix to apply, just a few lines in cql-pytest fixtures, correct?

**Comment by alecco** [comment]
`test/topology/conftest.py` has support for checking cluster sanity before/after test. If the cluster is not fine, a new one is spawned for the test. But this involves very different code and fixtures. For example, we can't have a driver connection session fixture (aka "`cql`") with `pytest` scope `session`. 

There are 3 ways I see for this:

1. We add yet another before test fixture, and stop testing with a broken cluster
2. We change `test/cql-pytest/conftest.py` to use `test/topology/conftest.py` logic
3. We unify both in a single `pytest` library where common fixtures reside (removing all the duplicate logic)

@nyh, what do you think/suggest?  (cc @kostja )

**Comment by nyh** [comment]
I think all three options are wrong. There's absolutely nothing wrong with test/cql-pytest/conftest.py and it shouldn't be touched. test/cql-pytest/conftest.py is used when someone does "cd test/cqlpytest; pytest" (or similarly, test/cql-pytest/run, which also start Scylla) and works well for that case.

Please correct me if I'm wrong, but test.py runs the external "pytest" command separately for each test file. Each of these invocations uses conftest.py seperately, and it's correct. The only problem is that before starting the next run, test.py doesn't check that Scylla is still alive. *That's* what needs to be fixed.

If you're asking why test.py needs to contain code to test Scylla, well, that's a side-effect of the fact it already contains code to **start** Scylla. Of course it doesn't need to be in test.py itself - it can be in a library which test.py uses (where you already have the code to start Scylla).

**Comment by kostja** [comment]
@nyh each test file contains multiple test cases. Each of them can break Scylla. So the check has to happen within test cases, not between different pytest invocations. 
I am personally for 2/3

**Comment by kostja** [comment]
test.py can have an extra check at the end of the test - to maintain test.py invariants - but that would not be enough, it would barely work to safety of re-cycling the scylla insteances, user experience will continue to suffer.

**Comment by nyh** [comment]
> test.py can have an extra check at the end of the test - to maintain test.py invariants - but that would not be enough, it would barely work to safety of re-cycling the scylla insteances, user experience will continue to suffer.

I'll try to make it very clear: Since `test.py` took it upon itself to contain code to **start** Scylla servers (unlike my approach of having an external script do that), it's its duty to check that this server which it started is still up before handing it out to an external "pytest" invocation. There's no reason why this should "not be enough", would "barely work" or that "user experience will continue to suffer".

Yes, topology/ tests need to be able to start and stop additional servers so need all sorts of convoluted interfaces into test.py's cluster-handling mechanisms. But cql-pytest don't need that and will never need it. A cql-pytest just assumes that when it starts, it was handed a functioning Scylla server. This functioning server can break in the middle of a test, and cql-pytest can handle this case - but it should start functional. And test.py usually ensures that (by starting Scylla on its own), but it needs to ensure that also when recycling an already-existing Scylla. It must not try to recycle a dead Scylla.

**Comment by nyh** [comment]
> @nyh each test file contains multiple test cases.

A fact which test.py blissfully ignores (to my sadness), and is not about to change now, and doesn't need to change now.

> Each of them can break Scylla. So the check has to happen within test cases, not between different pytest invocations. I am personally for 2/3

You didn't read what I wrote above. cql-pytest already takes care of the "check between test cases". In fact you copied this already-working-well code to your new libraries. The only thing that doesn't work is that cql-pytest assumes that when it is started, the server is functional. It can break during a test, but not before a test.

Seems like I can't convince you guys about my suggestion (which I repeated multiple times above) so I'll implement myself option 4 that doesn't need any cooperation from test.py:

4. have cql-pytest check Scylla before running *any* test, and if Scylla was never up, exit the test immediately not reporting any specific tests having failed.

**Comment by alecco** [comment]
@nyh OK. Let's see if I follow: add a check before test is run in the fixture `cql_test_connection`, and if so... mark skip?

**Comment by nyh** [comment]
Not exactly - we don't need to check the connection before each test (it's already tested after the previous one), just before the first one. I'll send a patch and ask you to review it.

**Comment by nyh** [comment]
I'm reopening because the fix did not fully solve the problem. 

Take a look at https://jenkins.scylladb.com/job/releng/job/Scylla-CI/3857/testReport/junit/(root)/non-boost%20tests/cql_pytest_test_count_debug_1/ - the test `cql-pytest.test_count.1` (the test file `cql-pytest/test_count.py`) crashed Scylla. We still see that test.py tried to run a lot of other test files:
```
------ Starting test cql-pytest.test_describe.1 ------
------ Starting test cql-pytest.test_distinct.1 ------
------ Starting test cql-pytest.test_empty.1 ------
------ Starting test cql-pytest.test_filtering.1 ------
------ Starting test cql-pytest.test_frozen_collection.1 ------
------ Starting test cql-pytest.test_keyspace.1 ------
------ Starting test cql-pytest.test_large_cells_rows.1 ------
------ Starting test cql-pytest.test_logs.1 ------
------ Starting test cql-pytest.test_lwt.1 ------
------ Starting test cql-pytest.test_materialized_view.1 ------
------ Starting test cql-pytest.test_minmax.1 ------
------ Starting test cql-pytest.test_non_deterministic_functions.1 ------
------ Starting test cql-pytest.test_null.1 ------
------ Starting test cql-pytest.test_paging.1 ------
------ Starting test cql-pytest.test_permissions.1 ------
------ Starting test cql-pytest.test_restrictions.1 ------
------ Starting test cql-pytest.test_scan.1 ------
------ Starting test cql-pytest.test_secondary_index.1 ------
------ Starting test cql-pytest.test_service_levels.1 ------
------ Starting test cql-pytest.test_shedding.1 ------
------ Starting test cql-pytest.test_ssl.1 ------
------ Starting test cql-pytest.test_sstable.1 ------
------ Starting test cql-pytest.test_system_tables.1 ------
------ Starting test cql-pytest.test_tombstone_limit.1 ------
------ Starting test cql-pytest.test_tools.1 ------
------ Starting test cql-pytest.test_ttl.1 ------
------ Starting test cql-pytest.test_type_duration.1 ------
------ Starting test cql-pytest.test_type_time.1 ------
------ Starting test cql-pytest.test_type_timestamp.1 ------
------ Starting test cql-pytest.test_uda.1 ------
------ Starting test cql-pytest.test_using_timeout.1 ------
------ Starting test cql-pytest.test_utf8.1 ------
------ Starting test cql-pytest.test_validation.1 ------
------ Starting test cql-pytest.test_virtual_tables.1 ------
```

The good news is that each of these test files did nothing - and didn't report hundreds of individual tests failing. But still, each of these test files was started and reported as a failure (see 73 failures in https://jenkins.scylladb.com/job/releng/job/Scylla-CI/3857/). They shouldn't. If Scylla is dead and we don't intend to start a new one (I think this was the decision here), we shouldn't bother running other test files - and certainly not report those test files as having failure.

**Comment by nyh** [comment]
@kbr- does your https://github.com/scylladb/scylladb/pull/12560 solve this latest version of the problem?

**Comment by kbr-scylla** [comment]
I don't think it will solve this problem.
- cql-pytests don't use `ScyllaClusterManager` (which checks the `is_dirty` flag and decides to setup a new cluster based on that). Looking at the code, cql-pytests don't care about `is_dirty` at all. The code in `PythonTest.run()` (in test.py) always unconditionally returns a cluster back to the pool, irrespective of whether Scylla crashed or not, whether the test failed or not.
- furthermore, the logic modified in #12560 only applies to exceptions when setting up clusters, not exceptions which happen during a test. Your previous post describes a crash in the middle of a test.

**Comment by nyh** [comment]
Thanks Kamil.
So it sounds to me like your fix in https://github.com/scylladb/scylladb/pull/12560 is incomplete. You discover that Scylla is down in just one place, but missed other places.

A thought: Why doesn't the code that **reuses** a cluster check that it's alive before actually reusing it? Clearly, when you bring up a cluster you already have some code which checks that the cluster came up (because it can take time for the cluster to come up, and you need to check when it came up). So **reusing** a pre-existing cluster can do the same check, to check that the cluster is still usable. If it isn't, it can't be reused, and you need to fall back to reusing a different cluster, or starting another one if none remain.

**Comment by nyh** [comment]
Alternatively, maybe you/we need to add the same sort of ad-hoc "dirty" marker which you added in #12560 also in PythonTest.run?

**Comment by nyh** [comment]
I'll try to prepare a patch myself.

**Comment by nyh** [comment]
@kbr-scylla @kostja unfortunatel Pythontest.run() (in test.py) is too weird for me to fix it, I need your help:

This function calls cluster.after_test() after every test, which recognizes Scylla is down and throws an exception - but then this exception is outright ignored, instead of replacing Scylla or exiting cleanly.

If I remove one level of indentation from:
```python
            except Exception as e:
                self.server_log = cluster.read_server_log()
                self.server_log_filename = cluster.server_log_filename()
                if self.is_before_test_ok is False:
                    print("Test {} pre-check failed: {}".format(self.name, str(e)))
                    print("Server log of the first server:\n{}".format(self.server_log))
                    # Don't try to continue if the cluster is broken
                    raise
```
to
```python
            except Exception as e:
                self.server_log = cluster.read_server_log()
                self.server_log_filename = cluster.server_log_filename()
                if self.is_before_test_ok is False:
                    print("Test {} pre-check failed: {}".format(self.name, str(e)))
                    print("Server log of the first server:\n{}".format(self.server_log))
                # Don't try to continue if the cluster is broken
                raise
 ```

Then things work reasonably well - when after_test fails, test.py stops instead of continuing to fail on a few dozen more test files - but I the failure is ugly and I doubt that this is what you wanted to do. The problem that I don't understand what you guys tried to do there, or what the various flags like is_after_test_ok, dirty and so on an so on are supposed to do.

Please help me fix this. And if at all possible, please move this weird logic out of Pythontest.run() where you never notice the bugs, into some shared code where you do notice the bugs ;-)

**Comment by kbr-scylla** [comment]
> So it sounds to me like your fix in https://github.com/scylladb/scylladb/pull/12560 is incomplete.

#12560 does exactly what it says: marks clusters as dirty if they fail to boot.
Whether the user of the cluster checks the dirty flag or not is up to them. My fix is in the context of topology tests which use `ScyllaClusterManager` which decides whether to recycle a cluster based on the `is_dirty` flag.

**Comment by kbr-scylla** [comment]
> This function calls cluster.after_test() after every test, which recognizes Scylla is down and throws an exception

actually, there is no such check. Maybe it throws an exception because `_get_keyspace_count()` cannot work on a dead cluster...
```
    def after_test(self, name) -> None:
        """Check that the cluster is still alive and the test
        hasn't left any garbage."""
        assert self.start_exception is None
        if self._get_keyspace_count() != self.keyspace_count:
            raise RuntimeError("Test post-condition failed, "
                               "the test must drop all keyspaces it creates.")
        for server in itertools.chain(self.running.values(), self.stopped.values()):
            server.write_log_marker(f"------ Ending test {name} ------\n")
```

`ScyllaCluster` is just one big pile of bugs and it was not designed to be used outside `ScyllaClusterManager`.

**Comment by nyh** [comment]
@kbr-scylla I'm lost in the details here. scylla_cluster.py is not some sort of generic library, it was something that is written specifically to work with test.py. If cluster.py sets "is_dirty" but only some code in test.py checks is_dirty and others don't, it's a bug, which I can't fix because I don't understand what you guys were trying to do and why.

If "ScyllaClusterManager" is the new thing(TM), maybe Pythontest.run() in scylla_cluster.py needs to use it?

I just don't understand this code well enough to fix it. Let's just keep in mind that this is not a cql-pytest bug (test/cql-pytest/run doesn't suffer from it), this is a test.py bug, and someone who is an expert on test.py (i.e., not me) needs to fix it...

**Comment by alecco** [comment]
@nyh I'll be happy to change `cql-pytest` to use `Topology` test suite and add a fixture to recycle the cluster. Would you like me to do this?

**Comment by kbr-scylla** [comment]
> Exactly - I thought this was intentional - the get_keyspace_count does a SELECT, which will fail (with an exception) if Scylla is down).

I'm pretty sure it wasn't intentional, since this logic doesn't work for clusters that have more than 1 node.

**Comment by nyh** [comment]
> @nyh I'll be happy to change `cql-pytest` to use `Topology` test suite and add a fixture to recycle the cluster. Would you like me to do this?

@alecco Maybe you didn't understand me. I didn't want to change cql-pytest (test/cql-pytest/*) at all. There's nothing wrong there. I just want you guys to fix test.py whenever it is broken. In this case, test.py decides to run "pytest" again against the same Scylla cluster which is in fact down, without recognizing it is down (actually, it does recognize it is down, but then ignores this fact). Correct behavior in this case would be to either:
1. Stop running any more tests files in this suite. I'm fine with that - the user will see the error which crashed Scylla and will need to fix it before seieing more errors.
2. Start a new cluster and continue to run the next test files from this suite.

None of this requires any changes to anything in test/cql-pytest.

**Comment by alecco** [comment]
> > @nyh I'll be happy to change `cql-pytest` to use `Topology` test suite and add a fixture to recycle the cluster. Would you like me to do this?
> 
> @alecco Maybe you didn't understand me. I didn't want to change cql-pytest (test/cql-pytest/*) at all. There's nothing wrong there. I just want you guys to fix test.py whenever it is broken. In this case, test.py decides to run "pytest" again against the same Scylla cluster which is in fact down, without recognizing it is down (actually, it does recognize it is down, but then ignores this fact). Correct behavior in this case would be to either:
> 
> 1. Stop running any more tests files in this suite. I'm fine with that - the user will see the error which crashed Scylla and will need to fix it before seieing more errors.
> 2. Start a new cluster and continue to run the next test files from this suite.
> 
> None of this requires any changes to anything in test/cql-pytest.

OK, I can modify `Python` test suite to add a check after each `pytest` and recycle the cluster.

**Comment by kostja** [comment]
> > Exactly - I thought this was intentional - the get_keyspace_count does a SELECT, which will fail (with an exception) if Scylla is down).
> 
> I'm pretty sure it wasn't intentional, since this logic doesn't work for clusters that have more than 1 node.

It does but not reliably. The select can go to any connection.

**Comment by avikivity** [comment]
Test only, not backporting.
