### ISSUE TITLE
test_remove_node_during_mv_insert_4_nodes: sstable - failed reading index: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#12603]
Regression seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-release/179/testReport/materialized_views_test/TestMaterializedViews/Run_Dtest_Parallel_Cloud_Machines___FullDtest___full_split013___test_remove_node_during_mv_insert_4_nodes/
With scylla version aab5954cfb65
```
failed on teardown with "AssertionError: Unexpected errors found: [('node3', ['ERROR 2023-01-19 06:13:55,457 [shard 0] sstable - failed reading index for /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-9ngjriog/test/node3/data/mview/users-51f7426097bf11ed978b68c684f7542b/me-42-big-Data.db: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)', 'ERROR 2023-01-19 06:13:55,460 [shard 0] sstable - failed reading index for /jenkins/workspace/scylla-master/dtest-daily-release/scylla/.dtest/dtest-9ngjriog/test/node3/data/mview/users-51f7426097bf11ed978b68c684f7542b/me-8-big-Data.db: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)' ...
```

@denesb please look into this asap

**Comment by denesb** [comment]
There are reports like this in the logs of node3:
```
INFO  2023-01-19 06:13:55,453 [shard 0] reader_concurrency_semaphore - Semaphore _read_concurrency_sem with 99/100 count and 20408624/10192158 memory resources: timed out, dumping permit diagnostics:
permits	count	memory	table/description/state
99	99	19M	mview.users/shard-reader/waiting_for_memory
249	0	16K	mview.users/multishard-mutation-query/active/unused
150	0	0B	mview.users/shard-reader/waiting_for_admission
```
This seems to be a kind of deadlock: the top-level multishard reader is waiting for its shard readers. Its shard readers are all blocked on memory, the semaphore is waiting for the multishard readers to release some to make progress.
I think we need a special breakout condition here.

**Comment by denesb** [comment]
After staring at the code hard enough for long enough it finally confessed and I reproduced this with a unit test, on a smaller scale:
```
Semaphore test_reader_concurrency_semaphore_blessed_read_goes_inactive with 2/3 count and 5120/3072 memory resources: user request, dumping permit diagnostics:
permits count   memory  table/description/state
1       1       3K      ks.cf/permit3/waiting_for_memory
1       1       2K      ks.cf/permit2/waiting_for_memory
1       0       0B      ks.cf/permit1/waiting_for_admission

3       2       5K      total
```
The problem happens when a permit becomes blessed, then it is registered inactive, then it is evicted and thus have to wait for readmission. If the situation is just right, the permit is queued on the admission queue, while still being the blessed permit. If the semaphore is above the serialize limit and reads don't release memory, the situation seen above can happen: all reads get queued on memory, with no progress because the blessed permit is waiting for admission. Deadlock.
The solution is to release the blessed status upon becoming inactive.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
