### ISSUE TITLE
Crash when reporting error on invalid CQL query involving field selection from a user-defined type

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#12739]
A bad cast can cause a crash during error reporting.

**Comment by avikivity** [comment]
Fixed by 186ceea009fe36b401cff7cbbc2ed16512d72318

**Comment by avikivity** [comment]
@tchaikov when fixing crashers, please file issues, they're required for backports.

**Comment by avikivity** [comment]
Backported to 5.0, 5.1, 5.2.

**Comment by tchaikov** [comment]
> @tchaikov when fixing crashers, please file issues, they're required for backports.

sure. will do.

**Comment by roydahan** [comment]
@avikivity / @tchaikov from the commit message I couldn't understand much and how it's related to crash, but do we have a test for this fix?

**Comment by tchaikov** [comment]
@roydahan hi Roy, we do have a test for it, see https://github.com/scylladb/scylladb/blob/f51762c72a7ed651695a7bb10409b1c85c55f5e3/test/cql-pytest/cassandra_tests/validation/operations/select_test.py#L2633-L2638, which was added in 6fb762630b760353297f5b4fb43a689c6e039177. if our code works as expected, "k2" should be printed in the place of "k2" in the test. before the fix, a small number, 2 in this case is used as the address of the string, in general, an address of `0x00000002` is not mapped to application's address space, if scylla tries to read from that address, a page fault would be raised and then the OS would translate it to a segfault, and yell at us.

the tested failure happens when the type of parameter does not match with the one expected by function. cassandra rejects the query in that case, it seems we also handles this case, and throw an exception with an error message with the expected format, see https://github.com/scylladb/scylladb/blob/f51762c72a7ed651695a7bb10409b1c85c55f5e3/cql3/functions/functions.cc#L528-L530. but according to the test and the commit message of 6fb762630b760353297f5b4fb43a689c6e039177, we are not able to validate or print out the expected error message. the issue tracking is #10448 .
