### ISSUE TITLE
docs: Issue in page How to Report a Scylla Problem -> wrong link for "generate core dumps"

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylladb#12731]
I would like to report an issue in page https://docs.scylladb.com/branch-5.1/troubleshooting/report-scylla-problem

### Problem
In this section: https://docs.scylladb.com/stable/troubleshooting/report-scylla-problem.html#troubleshooting-core-dump
`generate core dumps` link is pointing to the wrong URL:
https://docs.scylladb.com/stable/operating-scylla/admin.html#admin-core-dumps --> WRONG

###  Suggest a fix
Correct URL: https://docs.scylladb.com/stable/operating-scylla/admin.html#core-dumps --> CORRECT

**Comment by annastuchlik** [comment]
The link is correct.
I guess that you assume that the link is incorrect because the section title is Core Dumps, so the automatically generated link includes "core-dumps". However, when you change the section title, the link will be broken. For this reason, we don't use automatically generated links or section titles to produce links. Instead, we use anchors (also called bookmarks), which are stable and content-intependent.
Here's what the anchor in question looks like in the source file:
![image](https://github.com/scylladb/scylladb/assets/37244380/fbcccb97-2bfd-421b-8812-62c45eaaedf9)

That's why we can use it to produce the stable link:
![image](https://github.com/scylladb/scylladb/assets/37244380/00f06ade-c418-4e1f-ace5-36fcfbffd39a)

See [Links](https://sphinx-theme.scylladb.com/stable/examples/links.html) for details.

Closing.
