### ISSUE TITLE
Alternator: Return throughput values set in CreateTable/UpdateTable in DescribeTable

### ISSUE THREAD

**Issue by ojii** [scylladb/scylladb#12930]
- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): Docker image `scylladb/scylla@sha256:6f0d41d1af3aaaf1023f5e771d800b86310f269fe03620364c048525385c3100`
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

Currently, Alternator always returns 0 for `ProvisionedThroughput` in `DescribeTable`, as implemented in #11298.

To more closely mirror AWS DynamoDB, I think it should return the last value set in either `CreateTable` or `UpdateTable`. 

The reason I request this is that I maintain a DynamoDB client library and I would like to have it also support ScyllaDB, but [one of our tests](https://github.com/HENNGE/aiodynamo/blob/dcf67351c339d3689ae3570f0cad2678e486eabf/tests/integration/test_client.py#L286-L305) is currently failing when run against ScyllaDB Alternator since it checks that the throughput values returned in `DescribeTable` are what we set in `CreateTable`.

**Comment by nyh** [comment]
Note that Alternator doesn't just return 0 for `ProvisionedThroughput` - it also always returns `PAY_PER_REQUEST` as the billing mode - and the `ProvisionedThroughput=0` is a necessary part of that. We explain this situation in https://github.com/scylladb/scylladb/blob/master/docs/alternator/compatibility.md :

> When creating a table, the `BillingMode` and `ProvisionedThroughput` options are ignored by Scylla. Tables default to a Billing mode of `PAY_PER_REQUEST` and `DescribeTable` API calls will return a value of 0 for the RCUs, WCUs and `NumberOfDecreasesToday` within the response.

Indeed, Scylla can save the specific billing mode and provisioned throughput when the table is created, and return exactly the same thing when `DescribeTable` is later called. This is basically what you're asking for in this issue.

However, I'm completely sure we should do it. One might argue that a real application can never assume that after setting provisioned throughput it can read the same values back - because it is always possible that another concurrent application or the user using the Web UI modified the settings of this table. In fact, Scylla **does** behave as if immediately after the user created a table with provisioned throughput, someone went ahead and overrode the previous setting to one with pay-per-request billing (so no throughput caps, see also #5068) so it is correct that `DescribeTable` says that the table is now in `PAY_PER_REQUEST` (no throughput caps) mode.

Can you think of a real DynamoDB application which does what your test does - create a table and then reads back its configuration and complain if it changed between the two calls? If applications do this, then we should definitely consider this an Alternator bug and fix it. If not, perhaps your test shouldn't test it? Or maybe allow this specific test to fail on Alternator (although now that I think about it, I don't remember how code can actually tell Alternator apart from DynamoDB, if that is something you want to do let me know and I'll prepare a function that does this).

> The reason I request this is that I maintain a DynamoDB client library and I would like to have it also support ScyllaDB, but [one of our tests](https://github.com/HENNGE/aiodynamo/blob/dcf67351c339d3689ae3570f0cad2678e486eabf/tests/integration/test_client.py#L286-L305) is currently failing

Thanks for taking the time to run your tests against Alternator, and to report the failures to us. Was this the only failure on Alternator? If you'll ever see more failures, I'll be happy to know (well, not really _happy_, but grateful).

**Comment by ojii** [comment]
> Can you think of a real DynamoDB application which does what your test does - create a table and then reads back its configuration and complain if it changed between the two calls?

To be honest, I cannot think of a use-case outside of our test suite, which assumes that it is the only thing that interacts with the database and thus expects nothing else to touch the tables it creates (like Scyllas `UpdateTable` immediately after the `CreateTable`).

> If not, perhaps your test shouldn't test it?

The reason this test even exists is that this is a client library, so the test is there to check that it correctly handles` DescribeTable`. To do so, it needs to know what output to expect. 

However, looking at our implementation of `DescribeTable`, I realize that it handles the `PAY_PER_REQUEST` billing mode incorrectly, so I think I'll just use this Alternator behavior to instead test for this case instead (since I don't think other non-AWS DynamoDB implementations handle this billing mode).

> Thanks for taking the time to run your tests against Alternator, and to report the failures to us. Was this the only failure on Alternator? If you'll ever see more failures, I'll be happy to know (well, not really _happy_, but grateful).

Yes, in our test suite (which is far from comprehensive, though it did find #9542 in the past) this is the only failure.
