### ISSUE TITLE
replace operation takes "too long"

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylladb#13044]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): `5.3.0~dev.20230225.61e67b865a68 with build-id 1985d8fa72f490f46e7b907acf09aa36738d53bc`
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-073bcec02daa7acc6` [`eu-west-1`]

last result of the new test of latency during operations performance test, resulted in write ending before end of the operations (3x decommission did not run at all).
taking a closer look into the results, we can clearly see that `manager repair` operation is taking >3 times in write (comparing with mixed workload), and also, replace operation is taking more than twice time (additional 3 hours).

[write email report](https://groups.google.com/a/scylladb.com/g/scylla-perf-results/c/wnAxpY0jKxU)
[mixed email report](https://groups.google.com/a/scylladb.com/g/scylla-perf-results/c/YFIQEFN22OA)
[read email report](https://groups.google.com/a/scylladb.com/g/scylla-perf-results/c/R6Az1bl_Ebw)

from these reports, there are screenshots, logs and if needed, a link to recreate the monitor stack.

**Comment by fgelcer** [comment]
[running](https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/reproducer_13044/job/a/2/) with 5.1 to see if we have same behavior

**Comment by mykaul** [comment]
@asias - will you (or @nuivall ?) have time to look at this?

**Comment by asias** [comment]
We need to understand if this is a recent regression. What is the number for 5.1 release?

**Comment by mykaul** [comment]
> [running](https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/reproducer_13044/job/a/3/) with 5.1 to see if we have same behavior

@fgelcer - can you share the 5.1 results?

**Comment by fgelcer** [comment]
> > [running](https://jenkins.scylladb.com/job/scylla-staging/job/fabio/job/reproducer_13044/job/a/3/) with 5.1 to see if we have same behavior
> 
> @fgelcer - can you share the 5.1 results?

it had a failure in the test, so i don't have full results now, but will try to mine from logs

**Comment by fgelcer** [comment]
for 5.1 write workload, replace node operation took 4 hours

[data.log](https://github.com/scylladb/scylladb/files/10957451/data.log)

**Comment by fgelcer** [comment]
run with 5.0.dev, 5.1.dev and 5.2.dev to have data to compare (only write workload)

**Comment by fgelcer** [comment]
maybe be dup of #12101 and #10665

if same (or similar) we shall close them, and leave this one alive for now

**Comment by asias** [comment]
I looked at the metrics for repair in both WRITE workload and MIXED workload tests.

1) WRITE
3h to finish
compaction 350MB/s
commit log  100MB/s
memtable flush  100MB/s
stream 120MB/s

2) MIXED
1h to finish
compaction <200MB/s
commit log  20MB/s
memtable flush 20MB/s with spikes to 75MB/s
stream 300MB/s

In mixed workload, streaming io is getting almost 3 times more disk io than write workload, which translates to ~3 time faster repair time  we saw.

**Comment by mykaul** [comment]
> @avikivity @fgelcer @mykaul Write workload has 4X more writes than writes in mixed workload.
> 
> 1. WRITE
>    writes = 80k ops/s
>    reads = 0
> 2. MIXED
>    writes = 17k ops/s
>    reads = 12k ops/s

And out of those 12k reads, 25% will miss the cache and therefore consume disk iops as well.

**Comment by fgelcer** [comment]
i'm not sure what we have to adjust in the test, other than changing the definition in the acceptance criteria (but here i mean the high latency we see on replace operation, on mixed workload)

**Comment by asias** [comment]
I think I found the reason we had a latency spike during replace. Well, actually, not during, but right after the replace.

The time frame for replace ops is around 2023.2.26 10:56 to 12:40. The big latency spike happens during 12:34 to 12:38.  Note at 12:34, the replacing node has finished all the streaming and has finished replacing, it started to take reads.  As soon as the replacing node took writes, there was a sharp drop of reads on existing nodes .67 and .168 from 17.5K/s to 6K/s.  But the writes on .67 and .168 skyrocketed from 17.5K/s to 80K/s, this is where we saw the read latency went as high as 1s.

It looks like the loader was doing something unexpected. Why would it send 80K/s  in the first place?


![image](https://user-images.githubusercontent.com/320076/227398509-5c76aa73-0a59-4031-803a-c9e3fd829877.png)


![image](https://user-images.githubusercontent.com/320076/227398040-d4eb8414-db31-4574-919c-d0f901b0c949.png)


![image](https://user-images.githubusercontent.com/320076/227397671-7b83fd69-0823-4a4e-a88f-df07e44ed705.png)

**Comment by asias** [comment]
According to https://github.com/scylladb/scylladb/issues/13044#issuecomment-1479093913, not a bug.

**Comment by fgelcer** [comment]
> According to [#13044 (comment)](https://github.com/scylladb/scylladb/issues/13044#issuecomment-1479093913), not a bug.

but if i understand your https://github.com/scylladb/scylladb/issues/13044#issuecomment-1482178808 , it may be an issue?

**Comment by asias** [comment]
> > According to [#13044 (comment)](https://github.com/scylladb/scylladb/issues/13044#issuecomment-1479093913), not a bug.
> 
> but if i understand your [#13044 (comment)](https://github.com/scylladb/scylladb/issues/13044#issuecomment-1482178808) , it may be an issue?

The comment https://github.com/scylladb/scylladb/issues/13044#issuecomment-1482178808 is about the temporary latency spike.  The latency issue is tracked here: https://github.com/scylladb/scylladb/issues/12101

This comment https://github.com/scylladb/scylladb/issues/13044#issuecomment-1479093913 explains why it takes longer because it get less bandwidth from the scheduler.

**Comment by piodul** [comment]
Sorry to post comments under an issue that is already closed, but there multiple comments under some issues that point to Asias' explanation and I wanted to refer to it.

I don't think that the latency spike after replace is the fault of C-S or the java driver; I suspect that these are hints. On the third image [in this comment](https://github.com/scylladb/scylladb/issues/13044#issuecomment-1482178808) you can see a large spike on the "Hints sent per Instance", around 40k per node, which correlates in time with the spike of "Writes per Instance - Replica".

Nodes collect hints per destination IP. After the node being replaced is shut down, nodes store hints for the IP of the replaced node. After the node is finally replaced, there is no longer a node with its IP so the default behavior is to send them out to all of their current replicas. Given that hints are not yet properly isolated on the IO level (https://github.com/scylladb/scylladb/issues/8624), they can compete with user operations and can reduce throughput/increase latency.

Two things will help:

- Migrating hints to use host IDs instead of IPs - still not perfect but reduces the amount of work and only the receiving node will be overloaded,
- Fixing https://github.com/scylladb/scylladb/issues/8624 .

That said, while I agree it is an issue, it happens after replace finishes so I don't think it explains any spikes that happen during repair. Regardless - this issue is about repair taking long and not about latency spikes, and we already have issues open about the latency problems, so I'll continue investigation there.

**Comment by mykaul** [comment]
@piodul - when replacing a node, shouldn't all other nodes just delete the hints they've accumulated for that IP? (What happens on decommission, for example?)

**Comment by piodul** [comment]
> @piodul - when replacing a node, shouldn't all other nodes just delete the hints they've accumulated for that IP?

I'm not sure. Technically speaking, CL=ANY exists which is even lower than CL=ONE, if no replica is available then it only guarantees that a hint is stored. In such case, hints could have some information that no replica has and repair would not account for that. With hints, if you have RF=1 and use CL=ANY then you would lose data.

However, I checked with the [Datastax docs](https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/operations/opsRepairNodesHintedHandoff.html) and it looks like Cassandra drops the hints on removenode, and the setup I described above is... well, only for very brave people, I think (I can't think of a less convoluted one where a hint contains data that no replica has).

I'd rather have an implementation of hints that has proper isolation so that it doesn't cause problems even in this scenario, but maybe we should do the same as Cassandra - the precedent is already set by them...

> (What happens on decommission, for example?)

After a decommission, we will have a similar situation as we have here; additionally, the decomissioned node will try to send out its hints to whoever it can.
