### ISSUE TITLE
Botched up "token function arguments must be in partition key order" message

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#13468]
When the `token()` function is used on the left-hand side of an expression, it requires all the partition key columns to be listed in order. If we have the partition key `a` and use `token(b)`, Scylla currently generates the following error message:
```
The token function arguments must be in the partition key order: [0x60000506d928]
```
It appears that we intended to print a list of column names, but instead printed the address of the list :-)

The following failing test (it causes the error to be shown), inserted into test/cql-pytest/test_filtering.py, reproduces this bug:

```python
def test_filter_token(cql, table1):
    cql.execute(f'SELECT a FROM {table1} WHERE token(b) = 0 ALLOW FILTERING')
```

CC @cvybhu (I also think this may be a bug in wrong array formatting, the kind of which @tchaikov looked into recently).

**Comment by tchaikov** [comment]
i think we should print out the partition keys of the table instead of the ones passed to `token()` , so user can compare his/her CQL statement with the feedback, and fix it accordingly.

this is not a bug in array formatting.  this is just how we print arrays, see https://github.com/scylladb/scylladb/blob/fd817e199c81f391d95c601f09d6be1918ce506e/utils/to_string.hh#L30 . if we were using fmtlib here, it won't compile at all. but `operator<<` just prints out the value of the pointer, which is the referenced by the `begin`.

**Comment by avikivity** [comment]
Minor, not backporting.
