### ISSUE TITLE
Table metrics can register twice under keyspace drop/create scenario

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylladb#13548]
When running Scylla with the  ```--enable-keyspace-column-family-metrics 1``` flag, the test ```test_secondary_index.py``` fails.

It's easier to reproduce with raft enabled because raft would crash when creating a keyspace fails.
When testing it, it almost always happens when Raft is enabled (sometimes, I run the test twice so it would happen). It's not as frequent when running without Raft. I'm unsure if there's a relation or a timing issue.

It wasn't identified before because no one runs Scylla with ```--enable-keyspace-column-family-metrics``` enabled.

The most likely reason for such an exception is that a new table object is created before the old table object with the same name is destroyed.

**Comment by amnonh** [comment]
@mykaul I don't think the problem is with the test, it seems like a bug that we didn't hit and for some reason when raft is enabled it's easier to reproduce.

This issue blocks https://github.com/scylladb/scylladb/issues/2198

**Comment by mykaul** [comment]
@eliransin , @psarna - can you look into this, as it blocks an (unrelated) feature going into 5.3? I'm not sure it's secondary index related, but that's the failing test.

**Comment by mykaul** [comment]
> @eliransin , @psarna - can you look into this, as it blocks an (unrelated) feature going into 5.3? I'm not sure it's secondary index related, but that's the failing test.

Re-Ping, @eliransin , @ptrsmrn (right Piotr this time!) - please handle - this is blocking a merge of a seemingly unrelated PR.

**Comment by amnonh** [comment]
Just to make it clear, (see the original description),  the reason the metrics throws an exception, is because scylla tries to register the same metrics twice, in this case the same table.

That means that for some reason, someone tries to create a table object, but there's already such an object

**Comment by amnonh** [comment]
@ptrsmrn Metrics do not register and deregister explicitly, instead, there's a member in an object (in this case, the table) when that object is created, the metrics are registered, and the object destructor deregisters the metrics.

To my understanding, the situation is that there are two table objects with the same name, which shouldn't be possible.

The problem is not with the metrics, the problem is with those two **table** objects

**Comment by ptrsmrn** [comment]
@amnonh

> Metrics do not register and deregister explicitly, instead, there's a member in an object (in this case, the table) when that object is created, the metrics are registered, and the object destructor deregisters the metrics.

Yes, column family metrics are registered in [table's constructor](https://github.com/scylladb/scylladb/blob/master/replica/table.cc#L1553) and deregistered in its dtor. 

> To my understanding, the situation is that there are two table objects with the same name, which shouldn't be possible.

AFAIK it is possible, and I actually believe that this is precisely what is happening:

1. A table object exists in memory (the table also exists  in schema, disk, everywhere)
2. This table gets dropped by a user by performing a CQL DROP statement
3. First the table is removed from schema, but its dtor hasn't completed yet
4. In this short time window when the table's dtor is still being executed, another table with the same name is created by CQL CREATE TABLE statement. It is allowed, since there's no table witch such name in the schema.
5. We're usually OK with that, because the old table's object in memory is destructed, and the new one is being created, but new table wants to register the same column family metrics, which haven't been deregistered by the old table object yet.
6. An exception is thrown (plz see https://github.com/scylladb/scylladb/issues/13548#issuecomment-1527726482)


> The problem is not with the metrics, the problem is with those two table objects
 

So I believe the tables are OK (they are OK if you don't enable `--enable-keyspace-column-family-metrics 1` metrics), but the way we handle metrics deregistration can fail in specific cases. 


I am using "believe" word, because since last week I'm no longer able to reproduce the issue. @amnonh is it possible for you to provide me some logs from the moment the issue reproduces? Debug/trace level would be perfect. I think the logs I posted [here](https://github.com/scylladb/scylladb/issues/13548#issuecomment-1536183069) already tell what's happening, but they aren't explicit enough.

**Comment by amnonh** [comment]
@ptrsmrn if there's a scenario that a new table object can be created while the same table already exists (like in the create after delete you just describe) we need to to handle it on the metrics level.

I don't think this used to be the case, I'm also not sure why it happend more frequently when using raft

**Comment by amnonh** [comment]
@ptrsmrn I've pulled and compiled master, tested it in debug and it still happens.

**Comment by ptrsmrn** [comment]
@amnonh OK, so could you please send me the logs from when the issue happens? As I said, I have a really hard time reproducing it, somehow everything works smoothly on my PC.

**Comment by amnonh** [comment]
I run  everything on my laptop, 
```
./tools/toolchain/dbuild ./build/debug/scylla --workdir tmp --smp 4 --developer-mode 1 --enable-keyspace-column-family-metrics 1 |& tee -a log1.txt
```
[log1.txt](https://github.com/scylladb/scylladb/files/11433165/log1.txt)

**Comment by ptrsmrn** [comment]
@amnonh 
thanks for the logs, I'll investigate and let you know what I've learned. The remark about use after free is very interesting - perhaps my reasoning is wrong and something else is happening, because my explanation wouldn't explain that, and with my explanation (once you enable creating 2nd table), everything should be fine (maybe except for messed up table metrics's values).

> the blocked issue is the ability to enable per-table metrics by default

got it.

**Comment by ptrsmrn** [comment]
@amnonh thanks for the logs, but unfortunately I don't see anything only with INFO level, can you enable debug or trace level? It's `--default-log-level debug` cmd line prameter.

> I run everything on my laptop,

Me too, and I use the very same command you are using. Kostja also cannot get it reproduced, so you can consider yourself lucky ;)

**Comment by ptrsmrn** [comment]
@amnonh nevermind the logs, I was able to reproduce it again myself (with clean clone and clean master build). I'm returning to debugging.

**Comment by ptrsmrn** [comment]
@amnonh I believe my [theory](https://github.com/scylladb/scylladb/issues/13548#issuecomment-1539635085) is correct, and when I added logs to both metrics' (de)registering calls and table's create/drop functions, I was able to really see the order in which tests execution happens. So, just to reiterate, in the logs below you'll see that the 2nd tests' table `cql_test_1683751006073.cql_test_1683751006087` is created, and with it the metrics are registered, but then we get an exception that such metrics already exist. And they do exist, because the previous test hasn't finished cleanup yet, and there's a table object `cql_test_1683751006073.cql_test_1683751006087` (name of the table is the same for both tests) **marked** to be disposed, but nevertheless **it still exists in memory and metrics with it**.

```
// 2nd test begins
INFO  2023-05-10 22:36:46,418 [shard 0] schema_tables - Creating cql_test_1683751006073.cql_test_1683751006087 id=61c7aee0-ef72-11ed-901d-f553b0a55f86 version=2af7cf7a-f8d5-3189-8fd1-08121cc57eedWARN  2023-05-10 22:36:46,418 [shard 0] seastar - add_registration column_family_memtable_switch
WARN  2023-05-10 22:36:46,418 [shard 3] seastar - add_registration column_family_memtable_switch
WARN  2023-05-10 22:36:46,418 [shard 1] seastar - add_registration column_family_memtable_switch
WARN  2023-05-10 22:36:46,418 [shard 3] table - Creating cql_test_1683751006073.cql_test_1683751006087 table
WARN  2023-05-10 22:36:46,419 [shard 1] table - Creating cql_test_1683751006073.cql_test_1683751006087 table
WARN  2023-05-10 22:36:46,419 [shard 2] seastar - add_registration column_family_memtable_switch
WARN  2023-05-10 22:36:46,419 [shard 2] table - Creating cql_test_1683751006073.cql_test_1683751006087 table
ERROR 2023-05-10 22:36:46,422 [shard 0] raft - [673a8c40-6abb-49e3-8221-6f9cda7be916] applier fiber stopped because of the error: std::_Nested_exception<raft::state_machine_error> (State machine error at raft/raft.hh:299): seastar::metrics::double_registration (registering metrics twice for metrics: column_family_memtable_switch)
// only now 1st test's table gets deleted
WARN  2023-05-10 22:36:47,205 [shard 0] table - Deleting cql_test_1683751006073.cql_test_1683751006087 table
WARN  2023-05-10 22:36:47,205 [shard 0] seastar - remove_registration column_family_memtable_switch
```

To wrap up the conclusions, scylla permits half-dead and new tables to co-exist simultaneously. And it wasn't an issue until we decided for per-table metrics to inherit table's name, which currently results in a name clash.
I already tried some ideas, but don't see a clear way how to proceed:
1. First, I don't think we should forbid to create a new table if an identical table with the same name hasn't been fully removed yet. This hadn't been an issue until per-table metrics arrived, and I don't think we should impose such limitations on ourselves just for the sake of per-table metrics to work.
2. I naively moved metrics declaration to the top of the table class in database.hh, thinking that maybe that would speed up metrics removal process, but the table's destructor is called way after the 2nd table is created, and no delay in desctructor will fix it, so this is not a solution.
3. Adding additional if statement in metrics.cc to verify if metrics with the same name exist, but the table has been marked to be removed, isn't aligned with the metrics design, I believe, because the metrics.cc file doesn't #include much and probably shouldn't depend upon database.
4. What worked for me was to remove throwing metric's double-registration exception, but: (1) probably we want to leave this check for other cases and (2) you said you got "double free" error - I didn't but maybe removing this exception could result in double free under other circumstances. 
5. Obviously, adding a universally unique identifier (UUID) name for per-table metrics would've solved the issue. Actually, when I implemented that simple change, all of `test_secondary_index.py` passed smoothly, and there're at least 2 tests in this suite that caused the error, so this is at least some workaround to the problem, if not a solution. I don't know if I could proceed with that change, but it makes sense to me, since we allow 2+ table objects with the same name, so there also has to be a possibility for 2+ metrics with "nearly the same name" to exist. @vladzcloudius @avelanarius what do you think?

**Comment by vladzcloudius** [comment]
> First, I don't think we should forbid to create a new table if an identical table with the same name hasn't been fully removed yet. This hadn't been an issue until per-table metrics arrived, and I don't think we should impose such limitations on ourselves just for the sake of per-table metrics to work.

From the user perspective the moment `DROP TABLE` returns with a success he/she should be able to create a table with the same name.

Hence if `DROP` returns a success before the table is actually deleted - this is a bug.

**Comment by amnonh** [comment]
> 5. Obviously, adding a universally unique identifier (UUID) name for per-table metrics would've solved the issue. Actually, when I implemented that simple change, all of `test_secondary_index.py` passed smoothly, and there're at least 2 tests in this suite that caused the error, so this is at least some workaround to the problem, if not a solution. I don't know if I could proceed with that change, but it makes sense to me, since we allow 2+ table objects with the same name, so there also has to be a possibility for 2+ metrics with "nearly the same name" to exist. @vladzcloudius @avelanarius what do you think?

Did you try calling using the Prometheus while doing so?
I did a similiar change (e.g. and a uid to resolve the conflict) but then, when I called the prometheus API (http://ip:9180/metrics) It crashed scylla with used after free, probably because the table is in mid-disctruction

**Comment by ptrsmrn** [comment]
@amnonh OK, understood. Then I think I should proceed with the solution @vladzcloudius [proposed](https://github.com/scylladb/scylladb/issues/13548#issuecomment-1542918621), which is to wait with reporting that a table has been destroyed until the corresponding table object in memory is destroyed/deallocated.

**Comment by amnonh** [comment]
@ptrsmrn I don't understand how it relates to the reply to the user, it seems that there's a point in time, were at least one shard deleted a table without this table object being deleted and yield at this piont in time, someone else (regardless of the spcific test) someone else can create that table.
Also, it seem that during that period that a table is start to be deleted and until that object is completely destructed, it's in an unsafe mode

**Comment by ptrsmrn** [comment]
@amnonh Please see the explanation in my draft PR - https://github.com/scylladb/scylladb/pull/13910
@nyh can you also please take a look and comment? (It refers to your changes).
This is only a draft that proposes a fix and shows where the issue is, please ignore the style - it's only raw idea, I'll refine it later.

**Comment by nyh** [comment]
> @ptrsmrn I don't understand how it relates to the reply to the user, it seems that there's a point in time, were at least one shard deleted a table without this table object being deleted and yield at this piont in time, someone else (regardless of the spcific test) can re-create that table. Also, it seem that during that period that a table is start to be deleted and until that object is completely destructed, it's in an unsafe mode

I agree with Amnon. This specific test indeed DROPS a table, waits for it to finish, and only then creates another table with the **same** name (if you're curious why the same name, check out https://github.com/scylladb/scylladb/issues/7620). But other users might try CREATE TABLE at random times, not waiting for anything, and we expect such an operation to either succeed or fail on "table already exists" - not to crash.

@amnonh one thing I don't understand at all is why should the "metric registration" fail if the table name already exists. The metrics are **per table**, not per table **name**. Even if there is a possibility (even for a very short time) that two tables "exist" with the same name, so what?

But I think (?) I have an even easier solution: We can decide that as soon as we *start* dropping a table, it unregisters its metrics. Be drop those metrics before ever touching the schema tables. We don't need to see metrics from the last millisecond of the table's existance! If we drop the metrics before dropping the schema, not after, don't we solve this problem completely?

**Comment by amnonh** [comment]
@nyh about your first question, if you try to register two metrics with the same name and labels (in the case the table name is part of the labels). the metrics would throw an exception.
I did some experiment with resolving that conflict by introducing a uuid label but that cause a use-after-free exception, which bring me to a though that the duration that a table is beeing deleted (maybe your secondary index assumption has something todo with it) is unsafe from the metrics perspective.

Like you, I think a better approach would be to delete the metrics object first thing, it would be a simpler and safer solution.

**Comment by ptrsmrn** [comment]
@nyh @amnonh 

> But I think (?) I have an even easier solution: We can decide that as soon as we start dropping a table, it unregisters its metrics. Drop those metrics before ever touching the schema tables. We don't need to see metrics from the last millisecond of the table's existance! If we drop the metrics before dropping the schema, not after, don't we solve this problem completely?

The table object gets removed too late (after another table with the same name is created), and unregistering the metrics first wouldn't work, that would be too late as well. Actually, I already tried moving metrics member in table object to the top (so it gets removed first), and it (obviously) doesn't work.
If you mean to deregister the metrics as soon as we execute the CQL's DROP or `database::remove(const table& cf)`, then it'd leave the table object, which is potentially used by other objects, in a kind-of invalid state. If someone refers to these metrics, I think we end up with a different crash. **But I can try it**. With Amnon we tried to register per-table metrics using uuid, not the table's name, but even if it worked for me, it caused a crash on his machine, so I am not entirely convinced this will work and I generally wonder if only metrics are the issue here, maybe the general design or maybe the lack of knowledge that the design allows for "duplicated" table objects.

> you can create a separate test that reproduces it more reliably

I added a simple pytest reproducer to the draft PR. It currently does work for me, but this doesn't mean it'll work for you, unfortunately, since it's a timing issue, it depends on the CPUs load etc.

**Comment by amnonh** [comment]
> @nyh @amnonh
> 
> > But I think (?) I have an even easier solution: We can decide that as soon as we start dropping a table, it unregisters its metrics. Drop those metrics before ever touching the schema tables. We don't need to see metrics from the last millisecond of the table's existance! If we drop the metrics before dropping the schema, not after, don't we solve this problem completely?
> 
> The table object gets removed too late (after another table with the same name is created), and unregistering the metrics first wouldn't work, that would be too late as well. Actually, I already tried moving metrics member in table object to the top (so it gets removed first), and it (obviously) doesn't work. If you mean to deregister the metrics as soon as we execute the CQL's DROP or `database::remove(const table& cf)`, then it'd leave the table object, which is potentially used by other objects, in a kind-of invalid state. If someone refers to these metrics, I think we end up with a different crash. **But I can try it**. With Amnon 

This is what @nyh and I mean, make the **_metrics** member erasable, and remove it as soon as you get the DROP command. In this we mean, add a method to remove the metrics.

This will ensure the metrics will be de-register, and no one will call them.

**Comment by nyh** [comment]
> If you mean to deregister the metrics as soon as we execute the CQL's DROP or `database::remove(const table& cf)`, then it'd leave the table object, which is potentially used by other objects, in a kind-of invalid state.

Why is this an invalid states? It sounds to me a very valid state - it means the table still maintains its statistics for the last millisecond of its life, but our Prometheus server won't send these statistics any more. Sounds very reasonable to me.

>  If someone refers to these metrics, I think we end up with a different crash. **But I can try it**.

If I understand correctly, our code always has the metrics as variables, and those aren't freed and nothing will crash. If I understand correctly, the only thing that "unregistering" the metric does is to tell our Prometheus server not to publish those metrics from this table any more. But please correct me if I'm wrong.

> I added a simple pytest reproducer to the draft PR. It currently does work for me, but this doesn't mean it'll work for you, unfortunately, since it's a timing issue, it depends on the CPUs load etc.

By "works for me" I hope you mean it *fails* for you, not that it really *works* for you :-)
 
> I was also taking into account @vladzcloudius's comment that co-existing table objects is basically a bug - [#13548 (comment)](https://github.com/scylladb/scylladb/issues/13548#issuecomment-1542918621) - BUT since co-existing table objects seem to be a part of a design (keeping a shared_ptr by `database` which allows for others to keep the table object alive is what I refer to as deign), I'm, again, leaning more towards solving only the metrics issue, not the whole desing issue.

I'm not sure it's a bug. It would definitely be a bug if we have code that looks for a table with a given name (e.g., commit fbdf52acf66659ee3eb549432d966b54b06f7843) and finds some defunct deleted table. But that will **not** happen - the deleted table can no longer be found based on its name. So what does it matter that just the object continues to exist for a little while longer?

**Comment by ptrsmrn** [comment]
@nyh @amnonh here's the PR - https://github.com/ptrsmrn/scylladb/pull/1
I hope you can comment on it. This time I avoided creating a draft PR in Scylla OSS, because I didn't want to take/waste reviewers time until we settle on a solution/the solution is good enough.
Taking @nyh's comments on the pytest that reproduces the issue, I don't know if keeping it makes sense.

**Comment by ptrsmrn** [comment]
@amnonh @nyh Just FYI, I opened a PR with the fix.

**Comment by mykaul** [comment]
Code went into 5.4, which is the first GA of Raft. I assume no need to backport.
