### ISSUE TITLE
Garbage collect dangling pieces

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#13670]
Jumbo upload (#13577) works like that:

    user wants to upload foo-Data.db file
    uploader uploads foo-Data.db_1 file using multipart upload
    uploader copies foo-Data.db_1 into foo-Data.db using multipart upload
    uploader deletes foo-Data.db_1

If using [lifecycle management](https://docs.aws.amazon.com/AmazonS3/latest/userguide//mpu-abort-incomplete-mpu-lifecycle-config.html) we can delete both, foo-Data.db and foo-Data.db_1 in case multipart upload of either of them didn't finish, but imagine scylla crashes between steps 2 and 3. Multipart upload for foo-Data.db_1 had completed, multipard upload for foo-Data.db hadn't started yes. There's no (is there?) way to delete foo-Data.db_1 automagically :(

**Comment by nyh** [comment]
Note: this issue was marked "fixed", but it's not fully fixed - and a duplicate issue remains open:
https://github.com/scylladb/scylladb/issues/15518

The fix that was merged (and caused this issue to be closed) only **marked** the dangling pieces with a "piece" tag. But they are not yet garbage-collected (deleted). That code doesn't yet exist.

**Comment by avikivity** [comment]
Not a bug, not backporting.
