### ISSUE TITLE
Experiment with different parser for alternator expressions

### ISSUE THREAD

**Issue by nuivall** [scylladb/scylladb#13671]
Initial investigation showed that antlr is very inefficient, something than can be improved. We already have ragel in the codebase it may be a fit for relatively simple expression grammars.

**Comment by avikivity** [comment]
I think eliminating the parser by caching the result of a parse is simpler and will bring much larger benefits.

**Comment by michoecho** [comment]
> We already have ragel in the codebase it may be a fit for relatively simple expression grammars.

Ragel is a regex parser. So it's impossible to parse arbitrary logical expression with it. Definitely not a fit.

In general, Scylla is not in the business of very fast parsing. So I don't think we should attempt to speed up the parser itself and Avi is right about caching being better.

But if we were to change the parser for any reason, I would rather just see a Pratt parser written by hand, instead of "trying out" different parsers. This isn't something that deserves the dependency, and writing it by hand would yield better syntax errors.

**Comment by nyh** [comment]
> > We already have ragel in the codebase it may be a fit for relatively simple expression grammars.
> 
> Ragel is a regex parser. So it's impossible to parse arbitrary logical expression with it. Definitely not a fit.

I preemptively answered this question in the extensively-commented alternator/expressions.g, 

```
All these expression syntaxes are very simple: Most of them could be parsed as regular expressions,
and the parenthesized condition expression could be done with a simple hand-written lexical analyzer
and recursive-descent parser. Nevertheless, we decided to specify these parsers in the ANTLR3 language
already used in the Scylla project, hopefully making these parsers easier to reason about, and easier to
change if needed - and reducing the amount of boiler-plate code.
````

> In general, Scylla is not in the business of very fast parsing.

If this were true, we wouldn't have recommended all our users to use prepared statements. Since Alternator doesn't have prepared statements, it shouldn't give up on fast parsing. I admit in many cases parsing isn't a big part of the request, but IIRC @nuivall measured it to be around 15% of the request work in some small requests, so it's not negligible.

> So I don't think we should attempt to speed up the parser itself and Avi is right about caching being better.

I agree that caching expression parsing is more important. We have an issue for it: https://github.com/scylladb/scylladb/issues/5023

> But if we were to change the parser for any reason, I would rather just see a Pratt parser written by hand, instead of "trying out" different parsers. This isn't something that deserves the dependency, and writing it by hand would yield better syntax errors.

I agree and it's exactly what I wrote in the comment above. The only reason why I wrote this parser in Antlr, which I hated and wasn't even as good as Yacc which I had used for this purpose 35 years (!!) earlier, is because I was asked to reuse Antlr. I should have just written the parser by hand.

But the CQL language specification is much longer and much more frequently updated, so it would definitely have benefited from choosing a better parser generator.

**Comment by michoecho** [comment]
> If this were true, we wouldn't have recommended all our users to use prepared statements.

My point was that Scylla (and databases in general) prefer to avoid parsing altogether (by caching or explicit preparation) rather than try to speed it up, because that makes more sense.

> Since Alternator doesn't have prepared statements, it shouldn't give up on fast parsing.

Fair enough. Prepared statements are the natural database API; it's sad that someone invented an API without them.

> But the CQL language specification is much longer and much more frequently updated, so it would definitely have benefited from choosing a better parser generator.

My (very limited) experience with CQL is that its syntax errors are remarkably unhelpful. Even for this reason alone I would rather have a hand-written CQL parser too, rather than a generated one.

**Comment by nyh** [comment]
> Fair enough. Prepared statements are the natural database API; it's sad that someone invented an API without them.

Prepared statements are somewhat less natural in a distributed database, where many different nodes may need to handle different stages of a request. 

DynamoDB is even "worse" than you think, because it doesn't have a binary API at all, just a JSON based API, so every requests involves JSON parsing to the very least. The irony here is that this JSON may contain small pieces of trivial "expressions" such as "x, y, z" (a ProjectionExpression) or "SET x = 3" (an UpdateExpression) and because we parse these expressions in Antlr, it becomes the slowest part of the query parsing.

> My (very limited) experience with CQL is that its syntax errors are remarkably unhelpful. Even for this reason alone I would rather have a hand-written CQL parser too, rather than a generated one.

This is an outright bug that I discovered 7 years ago (!) - https://github.com/scylladb/scylladb/issues/1703. I didn't fix it because I was upset with the choice of Antlr in the first place and hoped that one of the Antlr fans would fix it, but maybe it's time that I swallow my pride and try to fix this bug within the existing Antlr. As I note in the issue, Cassandra, which also uses Antl, shows much better syntax error messages with good context, so it's not an Antlr bug - it's **our** bug.

**Comment by michoecho** [comment]
Instead of improving our Syntax errors, we could ask ChatGPT to explain them!

> IIRC @nuivall measured it to be around 15% of the request work in some small requests, so it's not negligible.

I wonder about that. @nuivall Was this measurement done after https://github.com/scylladb/scylladb/issues/12463 was fixed?

**Comment by avikivity** [comment]
I don't understand what's the point of trying to speed up parsing if caching the parse result moves it off the fast path.

Yes, DynamoDB doesn't have prepared statements, but my expectation is that only a small number of expressions will actually be used and the variability will be pushed out to parameters. We should verify this by looking at what SDKs do, but once that's done (and assuming the result is positive), and change an parser speed would be hidden by the caching layer.

**Comment by nuivall** [comment]
Closing for now, I experimented with this idea, for 2 out of 3 types of expressions it's possible to use ragel, speedup is something from 3x to 8x (highest for small/medium projection expressions). Although operator precedence is quite complicated to do with ragel so I won't finish this 3rd type of expression. Although if we ever want to improve parsing speed by couple times it's possible by replacing Antlr3.

I also experimented with different approach - replacing antr3 lexer with custom implementation it also provides some speedup but not something which can be justified by complex and hacky implementation.
