### ISSUE TITLE
docs: Issue in page Scylla Large Partitions Table

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylladb#13716]
I would like to report an issue in page https://docs.scylladb.com/branch-5.1/troubleshooting/large-partition-table

### Problem

A user noted in [User Slack](https://scylladb-users.slack.com/archives/C2NLNBXLN/p1682694188659309) that our documentation for Large Partition Table doesn't reflect all relevant parameters taken into consideration while populating the `system.large_partitions` table.

###  Suggest a fix
As of scyllaDB 5.0 - ref commit https://github.com/scylladb/scylladb/commit/a7511cf6000de0e2191e9ca18025f45bfdb04068 - the `large_partitions` table contains one additional rows column which has - by default - a threshold of 100K rows and is populated whenever compaction encounter such partitions.

The LiveUpdatable parameter used to configure such threshold is `compaction_rows_count_warning_threshold`.

@annastuchlik @tzach

**Comment by tzach** [comment]
Thanks @fee-mendes 
feel free to send a PR if you have free cycles

**Comment by annastuchlik** [comment]
This issue was already addressed with this commit: https://github.com/scylladb/scylladb/commit/33924201cc900f98c817c7ab62c98931bb87ec06

Among other improvements, it adds the `rows` column and the description of the `compaction_rows_count_warning_threshold` parameter.

The changes are included in version 5.2, which was released this week, so you can find them now in the live docs:
https://docs.scylladb.com/stable/troubleshooting/large-partition-table.html

Closing.
