### ISSUE TITLE
Schema change statement may fail on validation step due to using stale state, violating DDL linearizability

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#13942]
When executing a schema change statement we perform a Raft read barrier to obtain the latest schema state.

However, before the execution step, there's a separate prepare and validation step, and that step may observe stale state. For example, the node may claim that a table which we want to alter is missing.

To guarantee linearizability we should do the prepare/validation steps after read barrier, i.e. after calling `start_group0_operation()` and obtaining the `group0_guard`. Otherwise we will have those spurious failures (although other than giving an annoying error, they are harmless).

Note that validation is also done while holding the guard, e.g. we won't be able to create an already existing table if we notice that it exists only after taking the guard (which does the read barrier). There is redundancy in those validation checks.

We should probably check if all necessary validation is done under the guard. Perhaps we could simply remove the prepare-stage validation in that case.

cc @gleb-cloudius

**Comment by gleb-cloudius** [comment]
Isn't it exactly how the current code works?

**Comment by kostja** [comment]
The errors are not harmless, they may lead to production-level deployment bugs when DDL spuriously fails because it is sent to a wrong node. E.g. we create a table in version 1 of our deployment script, and in vresion two we add alter table to it. Then we use this script for a fresh deployment, and alter fails because create didn't propagate to all nodes yet.
So the impact for any SQL level dump/restore procedures is quite high.

**Comment by gleb-cloudius** [comment]
Ah, because validation is sometimes done outside of the execute(), but sometimes it is done inside. Yes, I remember now that the code is a mess. May be we can take a guard in `:alter_table_statement::validate()` and store it in the class until execute. Most, if not all overloads of this function for ddl statement are empty anyway (because why follow class hierarchy design?)

**Comment by kbr-scylla** [comment]
The fix was reverted, reopening

**Comment by kbr-scylla** [comment]
3d58e8e424ab51384553cb115aaddf019b9fa39d

**Comment by denesb** [comment]
Consistent schema changes fix, not backporting.

**Comment by kbr-scylla** [comment]
Consistent schema changes are GA in 5.2 so we should in general be backporting them, but in this case I would say the problem is relatively minor, compared to backporting hassle. @kostja might have different opinion though.
