### ISSUE TITLE
Creating a NetworkTopologyStrategy with empty replication factor is allowed

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylladb#13986]
Running this query doesn't fail:

```cql
cqlsh> CREATE KEYSPACE bad_ks WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': ''};
cqlsh> 
```
The replication factor is `''` (an empty string), so I think it should be rejected as invalid data.

In Scylla logs there's:
`INFO  2023-05-22 14:44:54,044 [shard  0] migration_manager - Create new Keyspace: KSMetaData{name=bad, strategyClass=org.apache.cassandra.locator.NetworkTopologyStrategy, strategyOptions={}, cfMetaData={}, durable_writes=1, userTypes=org.apache.cassandra.config.UTMetaData@0x600006b97498}`

`DESC` prints:
```cql
cqlsh> DESC bad_ks;
CREATE KEYSPACE bad_ks WITH replication = {'class': 'NetworkTopologyStrategy'}  AND durable_writes = true;
```

Trying to do the same query with `SimpleStrategy` fails, as expected:
```cql
cqlsh> CREATE KEYSPACE bad_ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': ''};
ConfigurationException: Replication factor must be numeric and non-negative, found ''
```

Refs: #8638

**Comment by nyh** [comment]
The culprit is prepare_options() in cql3/statements/ks_prop_defs.cc.  It starts with "sstring rf" (an empty string), and checks `if (!rf.empty())` to check if it was set, so we miss the fact it might have been set explicitly to an empty string. We can use an `std::optional<sstring>` instead.

Please add a test for this (I think we already have other tests in this area in test/cql-pytest/test_keyspace.py).

**Comment by denesb** [comment]
@cvybhu @nyh please evaluate for backport.

**Comment by nyh** [comment]
This patch improves error handling (when trying to use an empty string as replication factor), but doesn't affect users without errors. We usually don't backport such things. Removing the backport candidate tag.
