### ISSUE TITLE
Scanning a table using consistent read fails, but succeeds on other isomorphic tables

### ISSUE THREAD

**Issue by Rjerk** [scylladb/scylladb#14051]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.6.11
Cluster size: 14 nodes x 3 az
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

-------------

I have a bunch of tables such as obj_1, obj_2... obj_49. These tables have the same part key/sort key and have no GSI/LSI.

When I scan table 'obj_7' with consistent read I got failure:

```bash
# aws dynamodb --endpoint http://10.249.122.3:8000 scan --table-name obj_7 --limit=1 --consistent-read
 
An error occurred (InternalServerError) when calling the Scan operation (reached max retries: 9): Internal server error: exceptions::read_failure_exception (Operation failed for alternator_obj_7.obj_7 - received 0 responses and 1 failures from 3 CL=THREE.)
```

But it works when I disabled the `--consistent-read`

```
# aws dynamodb --endpoint http://10.249.122.3:8000 scan --table-name obj_7 --limit=1
{
    "Count": 1,
    "Items": [
...
    },
    "ScannedCount": 1
}
```

Strangely, it only fails when I scan the 'obj_7' table, the other tables are successful.

And [`nodetool tablestats`](https://gist.githubusercontent.com/Rjerk/aea4949e790df6f62feca129ec08aefa/raw/98c5cdd9e49bbce9078b9eb12bd9d90badfc4046/tablestats) shows that the 'obj_7' table has 728.78 MiB live space, it does not have more data than other tables.

The storage proxy has some messages:

```bash
[shard 61] storage_proxy - Error during read query exceptions::read_failure_exception (Operation failed for alternator_obj_7.obj_7 - received 0 responses and 1 failures from 3 CL=THREE.)
 
 
[shard 61] storage_proxy - Exception when communicating with 10.214.177.4, to read from alternator_obj_7.obj_7: std::runtime_error (Memory usage of unpaged query exceeds hard limit of 1048576 (configured via max_memory_for_unlimited_query_hard_limit))
```

All Scylla instances are `UN` states.

The config `max_memory_for_unlimited_query_hard_limit` has 100MB, but the logs show it has 1 MB. Does it have a special meaning?

**Comment by mikulely** [comment]
Hi @nyh would you mind take a look?  Thanks.

**Comment by Rjerk** [comment]
Scan timeout can observe from the alternator dashboard:

![image](https://github.com/scylladb/scylladb/assets/13392282/8c48c30d-27bd-4225-86b3-c2a7c3ddf139)

The load surged to 25% and the storage proxy coordinator has some read repairs when scanning the table (the blue line below):

![image](https://github.com/scylladb/scylladb/assets/13392282/1fe8bcb0-5fc0-49f4-acb1-fe1aeb995e82)

I guess the mutation data has been damaged and the read repair process happens to repair data replicas during a read request.

**Comment by nyh** [comment]
I think you've reached some correct conclusions:

Since a Scan is by definition a **paged** query, and a "consistent" read uses CL=QUORUM, this must mean that the read that failed - which reported an _unpaged_ read with _CL=THREE_ - must be something else. I think your guess that this is **read repair** is a good one: Indeed, read-repair can happen with "consistent read" (CL=QUORUM) when the read sees two different scanned pages, and can't happen with non-"consistent read" (CL=ONE) because the read sees just one version of the data and has no chance of finding a mismatch and wanting to repair it.

My guess is that the following happens:
1. Read repair wants to read the inconsistent page again from all nodes (CL=THREE, I don't remember why we do that).
2. Because it wants to read the whole page, this is an "unpaged" query but for a single page.
3. Because our default page size is 1MB, the data that will be read by the read repair will be around 1MB, but perhaps a tiny bit more. We can't have the "hard limit" and the typical read size have the same size!
4. If the "hard limit" of unpaged read is 1MB and not 100MB (@raphaelsc @denesb maybe you remember how this can be??), we can hit that hard limit, and because read repair fails, Scylla fails the read.

If this understanding is correct, this is a serious bug (CC @eliransin), and should be fairly easy to reproduce (I'll try to do it!). It means that any small inconsistency in data between two nodes will cause a paged Scan to fail when attempting to read the page where the inconsistency resides and the read is deemed an "unpaged read exceeding hard limit". It should be easy to test if my guess is corect, and I'll do this.

If this is the problem, perhaps you can work around the bug by asking Scan for smaller pages (e.g., 1000 results) instead of the 1MB default. Maybe Scylla will survive the scan this way (of course, it's not a good solution, just a temporary workaround to allow you to read your data).

**Comment by nyh** [comment]
I just realized you are using Scylla open source 4.6. This is an ancient (relatively speaking ;-)) version, and isn't supported any more, and we had fixes in *exactly* this area of mixing up the page size and the configurable memory limit in later versions (e.g., 7fa3fa6e65c4e6aee05b7cf2c8c8db30813140ee).

So please upgrade your cluster to a newer version and check if the problem still happens. I am hoping the problem will go away (the scan will still need to do read repair, but it will succeed and the scan will proceed normally). If it doesn't, we may still have a bug in this area.

**Comment by denesb** [comment]
> 4\. If the "hard limit" of unpaged read is 1MB and not 100MB (@raphaelsc @denesb maybe you remember how this can be??), we can hit that hard limit, and because read repair fails, Scylla fails the read.

By default, the hard limit is indeed 100MB. This can be changed in the scylla config, via: `max_memory_for_unlimited_query_hard_limit`.

**Comment by denesb** [comment]
Right, I missed that. Indeed, I do recall we had this problem in the past. I think this bug have been long fixed, but maybe not in 4.6 yet.

**Comment by Rjerk** [comment]
I tried to fix this issue by:

1. cherry-pick this PR: https://github.com/scylladb/scylladb/pull/9815/commits to my cluster for trying to fix this issue
2. reduce `page_size` to 256KB to expect the smaller pages.
3. and ran `nodetool repair alternator_obj_7` in every node in the cluster before doing the scan

New `read_timeout_exception` occurs when using `aws dynamodb --endpoint http://10.249.122.3:8000 scan --table-name obj_meta_general_7 --consistent-read --limit=10`: 

> An error occurred (ServiceUnavailable) when calling the Scan operation (reached max retries: 2): Service unavailable: exceptions::read_timeout_exception (Operation timed out for alternator_obj_7.obj_7 - received only 2 responses from 3 CL=THREE.)

But a scan with limit=1 can be successful:

```
$ aws dynamodb --endpoint http://10.249.122.3:8000 scan --table-name obj_7 --consistent-read --limit=1 > scan-result2
$ tail scan-result2
    "ScannedCount": 1,
    "LastEvaluatedKey": {
        "obj": {
            "S": "log_si0215tt18033_SZ_EOS_0508_03827861"
        },
        "bi": {
            "S": "obj_c56bc3dd-d0ce-4765-b78b-3b491d7e74d2tongji1%.941004.1.949"
        }
    }
}
```

We found a `range_timeout` in the Scylla:

![image](https://github.com/scylladb/scylladb/assets/13392282/ebc90678-f7aa-4220-9f34-2e60695cc127)

Perhaps more fixes are needed?

**Comment by Rjerk** [comment]
I also found that after deleting 2000 items, scans with limit=1 may take more time to get a response and are easy to fail.

Maybe it's the tombstones I create through delete-item, which may result in a query reader getting too many tombstones.

Are there more fixes about tombstones and queries after v4.6.11?

**Comment by nyh** [comment]
> I also found that after deleting 2000 items, scans with limit=1 may take more time to get a response and are easy to fail.
> 
> Maybe it's the tombstones I create through delete-item, which may result in a query reader getting too many tombstones.
> 
> Are there more fixes about tombstones and queries after v4.6.11?

Yes, we did improve things with tombstones (see https://github.com/scylladb/scylladb/issues/7933 and the fix by @denesb  - https://github.com/scylladb/scylladb/commit/e9cbc9ee85c25deb5ba9ee67ffa6e3ca9f904660). In the past, a Scan couldn't stop in the middle of a very long string of tombstones and it could cause timeouts in the middle of a Scan. Now it can stop (and return an empty page, if needed). Again, I want to ask if instead of trying to find individual patches and backport them, maybe you can try a more recent release of Scylla?

However, I don't understand how tombstones could be the problem. First of all, 2000 tombstones isn't such a huge number that should cause timeouts. Maybe you have a much bigger number? Second, I don't understand how it explains the "CL=THREE" reads. A normal scan should use CL=QUORUM (with consistent read), which should be 2, not 3.

**Comment by Rjerk** [comment]
> Again, I want to ask if instead of trying to find individual patches and backport them, maybe you can try a more recent release of Scylla?

Fine, we are ready to embrace version 5.1.10.
 
> However, I don't understand how tombstones could be the problem. First of all, 2000 tombstones isn't such a huge number that should cause timeouts. Maybe you have a much bigger number?

Yes, We tested billions PutItem/DeleteItem operations in this table before, maybe there're too many tombstones. BTW, is there any way to get the number of tombstones in a keyspace?

> Second, I don't understand how it explains the "CL=THREE" reads. A normal scan should use CL=QUORUM (with consistent read), which should be 2, not 3.

We changed the number of replicas for writing to three AZs, and each AZ wrote 2 replicas, while consistent reads would obtain one replica from each AZ. Will there be any hidden issue in this way?

**Comment by nyh** [comment]
> > Again, I want to ask if instead of trying to find individual patches and backport them, maybe you can try a more recent release of Scylla?
> 
> Fine, we are ready to embrace version 5.1.10.

Please note that 5.2 is already out, and https://github.com/scylladb/scylladb/commit/e9cbc9ee85c25deb5ba9ee67ffa6e3ca9f904660 is not in 5.1 but it is in 5.2.

> Yes, We tested billions PutItem/DeleteItem operations in this table before, maybe there're too many tombstones. BTW, is there any way to get the number of tombstones in a keyspace?

Excessive tombstones is a known weak spot in Scylla, so perhaps you'd best not use a table where you recently (see gc_grace_seconds) deleted _billions_ of items. @asias has been working on tombstone removal that is not driven by gc_grace_seconds, maybe something is available for you guys to test?

> > Second, I don't understand how it explains the "CL=THREE" reads. A normal scan should use CL=QUORUM (with consistent read), which should be 2, not 3.
> 
> We changed the number of replicas for writing to three AZs, and each AZ wrote 2 replicas, while consistent reads would obtain one replica from each AZ. Will there be any hidden issue in this way?

I see. So you changed the ScyllaDB source code to do that? Because AFAIR we didn't make the CL of consistent reads configurable (https://github.com/scylladb/scylladb/issues/7428). We thought that LOCAL_ONE (i.e., read from two nodes in this AZ) was the right choice. Your choice of reading one replica from AZ has two downsides: 1. high read latency (need to read from far-away DC), and 2. no high-availability (if any DC is down or network to it is down, you can't read).

**Comment by nyh** [comment]
> Excessive tombstones is a known weak spot in Scylla, so perhaps you'd best not use a table where you recently (see gc_grace_seconds) deleted _billions_ of items. @asias has been working on tombstone removal that is not driven by gc_grace_seconds, maybe something is available for you guys to test?

What I referred to is "repair-based tombstone GC" and is described in https://www.scylladb.com/2022/06/30/preventing-data-resurrection-with-repair-based-tombstone-garbage-collection/

This was an experimental feature since ScyllaDB 5.0 (a8ad385ecd3e2b372db3c354492dbe57d9d91760), but has since improved and is officially available and not experimental only since ScyllaDB 5.2, so it's another reason for you to try 5.2. It allows you to perform a "repair" on your table and it can immediately delete all the tombstones from your table - even without waiting for 10 days to pass (gc_grace_seconds).

**Comment by Rjerk** [comment]
> 2. no high-availability (if any DC is down or network to it is down, you can't read).

We can read three copies from 3 DCs, not each az provides one. If an AZ is down, three replicas can read from other DC.

> It allows you to perform a "repair" on your table and it can immediately delete all the tombstones from your table - even without waiting for 10 days to pass (gc_grace_seconds).

That's remarkable.

But there's still one concern: Is it too radical and risky to upgrade from 4.6.11 to 5.2.2? I remember that the default format of sstable has been changed. Is there any risk of losing existing data?

**Comment by nyh** [comment]
> > 2. no high-availability (if any DC is down or network to it is down, you can't read).
> 
> We can read three copies from 3 DCs, not each az provides one. If an AZ is down, three replicas can read from other DC.

I see. I'm not sure I fully follow the numbers, but if you have 3 DCs with RF=2 on each (?), and using CL=3 and want your reading from 3 nodes out of 6 to be "strongly consistent" (as the DynamoDB parameter suggests), then please make sure that you modified the write CL as well, to QUORUM (i.e., 4) - not the default LOCAL_QUORUM (which will be two nodes, if I understand your numbers correctly) .

> But there's still one concern: Is it too radical and risky to upgrade from 4.6.11 to 5.2.2? I remember that the default format of sstable has been changed. Is there any risk of losing existing data?

The open-source ScyllaDB upgrade policy is to upgrade one version at at time - this is what we test (and we verify there is no loss of data, of course), and what we document (https://docs.scylladb.com/stable/upgrade/upgrade-opensource/index.html). So you would need to upgrade from 4.6.11 to 5.0.*, from there to 5.1.*, and then to 5.2.1. By the way, for Enterprise users, there is also a "long term support" version that gets bug fixes without frequent major upgrades.

**Comment by Rjerk** [comment]
> then please make sure that you modified the write CL as well, to QUORUM (i.e., 4) - not the default LOCAL_QUORUM

That's how we did it.

> By the way, for Enterprise users, there is also a "long term support" version that gets bug fixes without frequent major upgrades.

It seems that we have communicated before, does Scylla have agents in China?

**Comment by nyh** [comment]
How can we make progress on this issue? If I understand correctly, the problem was seen on an old, unsupported version of Scylla, and involved a huge number (even "billions") of tombstones and both scanning-through-tombstones and getting rid of tombstones via repair were improved in recent versions, so may have solved this problem.

I'm removing my assignment until I have a better understand what we want to do here, feel free to close the issue if it's no longer relevant.

**Comment by Rjerk** [comment]
After upgrading to 5.2.2, the problem is resolved. Thanks.
