### ISSUE TITLE
DESCRIBE can't be used to describe user defined types

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylladb#14170]
Trying to `DESC` a UDT using cqlsh throws an error: `'my_udt' not found in keyspace 'ks'`:

```cql
CREATE KEYSPACE ks WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 1};
CREATE TYPE ks.my_udt (a int, b int);
DESC ks.my_udt;

'my_udt' not found in keyspace 'ks'
```

It's possible to see information about the UDT by describing the whole keyspace:
```cql
DESC ks;

CREATE KEYSPACE ks WITH replication = {'class': 'NetworkTopologyStrategy', 'datacenter1': '1'}  AND durable_writes = true;

CREATE TYPE ks.my_udt (
    a int,
    b int
);
```
So the code for describing a UDT is already there, but it isn't triggered when someone tries to `DESCRIBE` the type directly.

Interestingly, it doesn't work on Cassandra as well.

\cc @Jadw1

**Comment by Jadw1** [comment]
This is because you are using generic describe (without specifying what you want to describe) and  generic describe looks for(in order): keyspace, table, index. It doesn't check UDTs, UDFs nor UDAs.

If you use `DESC TYPE ks.my_udt` it works.
I've followed Cassandra's implementation, but we can easily extend our implementation to include missed items.

**Comment by cvybhu** [comment]
Ah you're right, `DESC TYPE ks.my_udt` works.

It's a bit unintuitive, I expected `DESC` to just describe any entity I specify.
I think it would be nice to extend it to also handle UDTs, UDFs, etc.

But we can also say that the user should just read the documentation, if you think it's not worth it feel free to close this issue.
