### ISSUE TITLE
docs: Issue in page ScyllaDB and Apache Cassandra Compatibility - broken links to internal pages

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#14490]
I would like to report an issue in page https://opensource.docs.scylladb.com/master/using-scylla/cassandra-compatibility

### Problem

Broken links from many in-table links, like Snitches::SimpleSnitch and others
The problem is links in the format of

```
/operating-scylla/system-configuration/snitch/#simplesnitch
```

Note the internal page link format: ``/#`` it should be ``#``.

For example the following patch should fix the issue for one case:
```
-.. _SimpleSnitch: /operating-scylla/system-configuration/snitch/#simplesnitch
+.. _SimpleSnitch: /operating-scylla/system-configuration/snitch#simplesnitch
```

**Comment by dgarcia360** [comment]
To have more robust links, especially when multiversion is enabled, it's best to use  `:ref:` directive.

`_SimpleSnitch: /operating-scylla/system-configuration/snitch#simplesnitch` translates to `docs.scylladb.com/operating-scylla/system-configuration/snitch#simplesnitch`. As you can see, it won't work in production since `/<VERSION>/` is missing.
