### ISSUE TITLE
[branch 5.3] pretty_printed_data_size: index out of range

### ISSUE THREAD

**Issue by tanlosav** [scylladb/scylladb#14702]
Compaction has a potential "index out of range" operation inside operator "<<" when operator prints more than petabyte data size.

[compaction/compaction.cc](https://github.com/scylladb/scylladb/blob/branch-5.3/compaction/compaction.cc#L160)

```c++
std::ostream& operator<<(std::ostream& os, pretty_printed_data_size data) {
    static constexpr const char* suffixes[] = { " bytes", "kB", "MB", "GB", "TB", "PB" };

    unsigned exp = 0;
    while ((data._size >= 1000) && (exp < sizeof(suffixes))) {
        exp++;
        data._size /= 1000;
    }

    os << data._size << suffixes[exp];
    return os;
}
```

**Comment by nyh** [comment]
@tanlosav did you find this in a code review, or ran into it in practice in an actual installation? I think that having a single node with a petabyte on it is not common which is why we never saw this in our own tests.

**Comment by nyh** [comment]
@tanlosav also, it seems to me that:
1. The problem only happens above 1000 PB, not 1 PB (or am I wrong?)
2. Because this is a C array, there is no protection against index overflow, so there will not be a ""index out of range" exception - we will probably (but who knows...) get garbage output but not a failure

So definitely this issue should be fixed, but I don't see if/how it had a real impact on users?

**Comment by avikivity** [comment]
@tchaikov please prepare a 5.2 backport
