### ISSUE TITLE
sstable_compaction_test:simple_backlog_controller_test creates multiple tables with the same name

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylladb#14767]
Similiar to #14657

**Comment by amnonh** [comment]
Hi @bhalevy and  @tchaikov yet another test :)
I hit those tests when with #13293 that would crash if a table is created twice with the same name

**Comment by bhalevy** [comment]
Can you please share the unit test log?

@tchaikov please look into this.

**Comment by amnonh** [comment]
The logs when runs as-is will not be informative, there's a loop in the test that create tables, it uses the same table name again and again

**Comment by tchaikov** [comment]
@amnonh i understand we create tables using the same "ks.cf" name for 3 times.  but i am also interested where you are  adding metric group, so i can have a better idea where i am supposed to drop the table.

**Comment by tchaikov** [comment]
thank you!

**Comment by bhalevy** [comment]
@amnonh what I don't understand is if the tables are dropped between being recreated.
It should be legal of course to reuse the table name after dropping it.
It will get a different table uuid in this case.

**Comment by amnonh** [comment]
If the tables are dropped then it's fine, just like creating-delete-create scenario.
the uuid is not the issue, the metrics layer will prevent two table objects with the same ks/table name.

**Comment by tchaikov** [comment]
yeah, i am think about if "dropping" a table and recreate it with the same name actually helps in your use case. as you never "remove_group()". -- yeah, i knew, `metrics_groups` does not provide it. it offers `remove()` though.

so, as Benny suggest, probably we should use `_schema->id()` instead?

**Comment by tchaikov** [comment]
@amnonh ^

**Comment by amnonh** [comment]
Originally, like in all parts of the system, de-register a metrics was done using the object destructor, than #13548 came and to handle it, the fix added that remove_group option.

As far as I understand, when you delete a table object, it should delete the table metrics with it, if not, maybe the original fix is not complete.
Maybe @ptrsmrn can add his input

**Comment by tchaikov** [comment]
oh, i see. we are dropping the `metrics_groups` as a whole.

**Comment by ptrsmrn** [comment]
> Originally, like in all parts of the system, de-register a metrics was done using the object destructor, than #13548 came and to handle it, the fix added that remove_group option.
> 
> As far as I understand, when you delete a table object, it should delete the table metrics with it, if not, maybe the original fix is not complete. Maybe @ptrsmrn can add his input

@amnonh 
As far as I recollect, we allow for a situation where 2 objects representing a table with the same name exist simultaneously in memory, but it's possible only if 1 object's table is actually being destroyed and it's just that this destroy operation hasn't completed yet. So there's a small time window when a user executed DROP on a table (and we're in the process of destroying this table, which has not yet finished), and a user CREATEd a table with the same name, which we allow to do if this name has been already removed from the schema.
I see that in your patch you're extending `_metrics` with another group (https://github.com/scylladb/scylladb/pull/13293/files#diff-970063d9f766ba24975f1955091d6bd0b071932333c47936fe2b4ff62032c580R1015) and the patch I created is clearing `_metrics` (https://github.com/scylladb/scylladb/pull/13293/files#diff-970063d9f766ba24975f1955091d6bd0b071932333c47936fe2b4ff62032c580R1031) just before the name of the table is removed from the schema (https://github.com/scylladb/scylladb/pull/13971/files#diff-5f674f2f5beecae883403216eef63b543f1bb5aaa47c95089468386d2f4b9fdfR1037), so "theoretically" we shouldn't experience the same bug :) 
But in order to understand it better, I'd need more details:
1. body of the test
2. what exception are we getting
3. logs from the node
If that doesn't help, I can try and reproduce the issue myself locally.

**Comment by tchaikov** [comment]
@ptrsmrn sorry for the false alarm . i was not quite sure how we managed the life cycle of the metrics in a `table` instance. i thought it would be little bit tricky. as i was under the impression that a `remove_group()` is missing, and we don't call `deregister_metrics()` in `table' 's dtor.

but Amnon pointed it out to me that `metrics_group` 's dtor does the job for us. so all good!

thanks!

**Comment by avikivity** [comment]
test-only, will only backport if we see flakiness
