### ISSUE TITLE
test.py: add log browsing functionality

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#14782]
To write certain tests, we need the ability to browse node logs inside tests.
The following features are useful:
- scrolling to the bottom of the given node's log,
- saving a position in the log (and obtaining a marker object to be used later in the test)
- searching for a pattern in the log (possibly in a range given by marker object(s))
- watching for a pattern to appear with a timeout

For inspiration look at scylla-ccm and the following functions: mark_log, watch_log_for, grep_log. (Let's just shamelessly steal them.)

Example use cases: https://github.com/scylladb/scylladb/pull/14681#pullrequestreview-1528286119,
https://github.com/scylladb/scylladb/pull/14779 (for detecting node crash vs normal shutdown sequence)

Also if we want @kostja's dreams to come true (about not writing dtests anymore), this is a prerequisite.

**Comment by nyh** [comment]
I already did something exactly like this in `test/cql-pytest/test_logs.py`. There is a fixture which automatically finds Scylla's logs, no matter how Scylla was run (but skips the test if not testing a Scylla running on localhost - since the tests may also be run against Cassandra, against Scylla running in the cloud, etc.). Then there is a function to wait for something new to appear in the log.

Here is an example test from `test/cql-pytest/test_logs.py` using the logfile fixture:
```python
# A simple example of testing the log file - we check that a table creation,
# and table deletion, both cause messages to appear on the log.
def test_log_table_operations(cql, test_keyspace, logfile):
    with new_test_table(cql, test_keyspace, 'p int PRIMARY KEY') as table:
        wait_for_log(logfile, f'Creating {table}')
    wait_for_log(logfile, f'Dropping {table}')
```

Please check it out. As usual for my code, it has a lot of comments explaining what the functions there do and why.

In my opinion, most functional test should limit themselves only to official and user-visible CQL API and should not check the logs, but I agree that in some cases it's necessary or even important, which is why I created this in cql-pytest.

**Comment by avikivity** [comment]
Not a bug, not backporting.
