### ISSUE TITLE
Reduce the size limit of the schema commitlog

### ISSUE THREAD

**Issue by piodul** [scylladb/scylladb#14802]
Currently, the size of the schema commitlog is practically unbounded - the limit is 10 terabytes (2^20 megabytes):

https://github.com/scylladb/scylladb/blob/decbc841b749d8dd3e2ddd4be4817c57d905eff2/replica/database.cc#L953

We should reduce the limit in order for it not to waste space.

According to Tomek's comment (https://github.com/scylladb/scylladb/pull/14704#issuecomment-1638201751), the limit should have been 10 MB (2^20 bytes), equal to the combined memory limit for tables in system keyspaces.

Avi's suggestion (https://github.com/scylladb/scylladb/pull/14704#issuecomment-1637635484) is to set its size to 2 * schema commitlog segment size.

**Comment by kbr-scylla** [comment]
@patjed41 -- the issue wasn't closed automatically because you sent a single-commit PR and the commit message did not contain a `Fixes` tag. In single-commit PRs, the PR cover letter is ignored and only the commit message is taken (there is no merge commit created).

Please remember to include a `Fixes` tag to commit messages in single-commit PRs in the future.

**Comment by avikivity** [comment]
Fixed by e7077da12d520818326c165d5c5a90556201cc2b

**Comment by avikivity** [comment]
I want to backport it, but I'm worried we'll trigger regressions id we don't backport other fixes.
