### ISSUE TITLE
sstable_compaction_test.compaction_manager_basic_test in fails

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#14865]
```
build/debug/test/boost/sstable_compaction_test --run_test=compaction_manager_basic_test --report_level=no --logger=HRF,test_suite:XML,test_suite,/jenkins/workspace/scylla-master/build/scylla/testlog/x86_64/debug/xml/boost.sstable_compaction_test.compaction_manager_basic_test.1.xunit.xml --catch_system_errors=no --color_output=false -- -c1 -m2G --overprovisioned --unsafe-bypass-fsync 1 --kernel-page-cache 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --max-networking-io-control-blocks=100
...
random-seed=2719666668
...
test/boost/sstable_compaction_test.cc(181): fatal error: in "compaction_manager_basic_test": critical check cm.get_stats().pending_tasks == 0 && cm.get_stats().active_tasks == 0 has failed
```

see https://jenkins.scylladb.com/job/scylla-master/job/build/1549/artifact/testlog/x86_64/debug/boost.sstable_compaction_test.compaction_manager_basic_test.1.log

**Comment by tchaikov** [comment]
not reproduciable locally with
```console
$ sstable_compaction_test --run_test=compaction_manager_basic_test -- -c1 -m2G --overprovisioned --unsafe-bypass-fsync 1 --kernel-page-cache 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --max-networking-io-control-blocks=100 --random-seed 2719666668
```

**Comment by bhalevy** [comment]
looking at the code, I think that requiring pending to be 0 might be bogus since there is a momentary state in https://github.com/scylladb/scylladb/blob/1554b5cb61699a21a018c97dbb88ea696e882892/compaction/compaction_manager.cc#L1084
where pending is incremented, but the regular compaction hasn't noticed yet it has nothing more to do, in https://github.com/scylladb/scylladb/blob/1554b5cb61699a21a018c97dbb88ea696e882892/compaction/compaction_manager.cc#L1094

In debug mode we yield in co_await so there could be a very slight chance pending will be caught at this state.
We can extend the do_until condition to check both `completed > 0` and `pending == 0`

**Comment by tchaikov** [comment]
thanks. it make sense to me.

```mermaid
sequenceDiagram
  participant t as test
  participant c as regular compaction
  c --> c: none
  t -->> c: trigger
  c -->>+ c: pending 
  c --> c: active
  c --> c: done
  c -->>- c: none
  t -->> c: wait for completed_task > 0
  c -->>+ c: pending
  t -->> c: pending task > 0?
  c -->>- c: none
```

**Comment by avikivity** [comment]
test-only fix, and code has changed, so will only backport if we see flakiness
