### ISSUE TITLE
Missing whitespace in table options in server-side DESCRIBE

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylladb#14895]
*Installation details*
Scylla version (or git commit hash): 7351c8424df316eb7da993af2bec381e98664cd6

Current (as of 7351c8424df316eb7da993af2bec381e98664cd6) server-side DESCRIBE implementation prints map-based property option values without whitespace after `,` (and sometimes missing whitespace after `:`):

```
CREATE TABLE [...] WITH [...]
    AND caching = {'keys': 'ALL','rows_per_partition': 'ALL'}
    AND tombstone_gc = {'mode':'timeout','propagation_delay_in_seconds':'3600'}
    AND cdc = {"delta":"full","enabled":"true","postimage":"false","preimage":"false","ttl":"86400"};
```

instead of:

```
CREATE TABLE [...] WITH [...]
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND tombstone_gc = {'mode': 'timeout', 'propagation_delay_in_seconds': '3600'}
    AND cdc = {"delta": "full", "enabled": "true", "postimage": "false", "preimage": "false", "ttl": "86400"};
```

This is of course a valid CQL query, but the client-side DESCRIBE prints it differently - with additional whitespace. Additionally, it's easier to read with the additional whitespace. The direct reason for this issue is that cqlsh tests hardcode the expected response and they expect the whitespace (of course this is more of a cqlsh problem, but nethertheless a proper formatting in Scylla would have made it easier to make those tests pass).

**Comment by mykaul** [comment]
Perhaps need git bisect to find out what changed it?

**Comment by avelanarius** [comment]
> Perhaps need git bisect to find out what changed it?

I believe this was the case from the beginning of server-side DESCRIBE. The other snippet I posted is from cqlsh client-side DESCRIBE, not some previous version of server-side DESCRIBE.

**Comment by mykaul** [comment]
> > Perhaps need git bisect to find out what changed it?
> 
> I believe this was the case from the beginning of server-side DESCRIBE. The other snippet I posted is from cqlsh client-side DESCRIBE, not some previous version of server-side DESCRIBE.

In that case, I'm pretty sure any change to either side will break something :-/

**Comment by avelanarius** [comment]
> > > Perhaps need git bisect to find out what changed it?
> > 
> > 
> > I believe this was the case from the beginning of server-side DESCRIBE. The other snippet I posted is from cqlsh client-side DESCRIBE, not some previous version of server-side DESCRIBE.
> 
> In that case, I'm pretty sure any change to either side will break something :-/

I don't think changing server-side DESCRIBE at this point will break anything - it's currently effectively unused (cqlsh doesn't use it as of yet: https://github.com/scylladb/scylla-cqlsh/issues/17)

**Comment by nyh** [comment]
> The direct reason for this issue is that cqlsh tests hardcode the expected response and they expect the whitespace (of course this is more of a cqlsh problem,

I think this is an **invalid** reason to fix anything. First of all, the "cqlsh tests" shouldn't insist on details that aren't necessary for correctness. Since whitespace isn't necessary, these tests can easily ignore them while comparing strings. Secondly, you said it's "more of a cqlsh problem" - it isn't - unless I'm missing something cqlsh doesn't have a problem with the missing whitespace. It's just the test:

By the way, the really right way to check the result of DESCRIBE, which I vaguely remember we did in the past in some context (I don't remember where, please have a look), is to do the following:
1. Create a table in some way.
2. DESCRIBE TABLE on this table
3. Run the result of DESCRIBE TABLE with just the name of the table changed to something else.
4. Now that you have two tables, compare that they are exactly the same table except the name - perhaps by looking at the schema tables directly and check they have identical content except table name and perhaps timestamps.

> but nethertheless a proper formatting in Scylla would have made it easier to make those tests pass).

I am not sure what is "proper" about adding more whitespace. Maybe it's prettier, though.

**Comment by denesb** [comment]
@avelanarius do we need to backport this?
