### ISSUE TITLE
test.py: provide an easy-to-remember, univeral way to run scylla with trace level logging

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#14960]
Currently, thanks to many sutie types, remembering the configuration for each suite type has become difficult.

For example, if I want to run a unit test with debug level logging, I need to set custom_args for this unit test in its suite's suite.yaml.
For topology tests, I need to set `extra_scylla_cmdline_options`. 
For other suite types, I don't know what needs to happen, so that it respects my ask.

Finding the right way, debugging it just eats up my time every time I try to trace down a test problem.

**Comment by kbr-scylla** [comment]
We could in general implement a way of passing arguments from `test.py` cmdline to all servers that are started using `ScyllaServer` during this `test.py` run.

**Comment by temichus** [comment]
@kostja , @kbr-scylla 
I did some investigation, and only UnitTestSuite and PythonTestSuite currently have the possibility to change ScyllaDB options from test or config

RunTestSuite - all options are hardcoded per test suite. Currently, only  pylib_test and scylla_gdb use the RunTestSuite type - so I don't think that we should invest in it.



ToolTestSuite- looks like don't need to change log, because it always use trace logging:
https://github.com/scylladb/scylladb/blob/263668bc85b2e1485c4bf11efb372252e4b0282a/test/nodetool/conftest.py#L200-L205

regarding tests debugging. I agree that it is annoying to go and change configuration options per test for UnitTestSuite and per test suite for PythonTestSuite. il will be much easier to append Scylla cmd on the fly via  test.py argument for all UnitTests and PythonTestws


so my suggestion here is to implement test.py argument like --extra-scylla-cmdline-options="--logger-log-level scylla-nodetool=trace --default-log-level=error"

an implement logic to concatenate correctly scylla cmdline options data  from test.py args, config files, tests

**Comment by temichus** [comment]
PR merged, close the task
