### ISSUE TITLE
Capped tombstone local_deletion_time warning does not indicate the respective sstable

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15015]
When a tombstone deletion_time is too far into the future, we need to cap its value to `MAX_INT32 - 1`, so it could fit in signed 32 bits.  See https://github.com/scylladb/scylladb/blob/59c410fb97f3f9d56c8d401de6d58197c58c63b5/sstables/types.hh#L654-L665

This is reported to the log in https://github.com/scylladb/scylladb/blob/59c410fb97f3f9d56c8d401de6d58197c58c63b5/sstables/mx/writer.cc#L670-L673

However, the warning does not include the sstable currently written so the user can't tell the keyspace and table this is happening in - which could help detect the root cause of the value - probably use of max_ttl (20 years), that may cause an expiration time to surpass 2038-01-19 03:14:07 UTC, starting 2018-01-19.

**Comment by tchaikov** [comment]
> @tchaikov can you please write a unit test tat reproduces this warning and add the sstable name?

sure. will do early next week.

**Comment by tchaikov** [comment]
@bhalevy what shall we verify? the metric value or the warning messages sent to log? i think it'd suffice to add a test to verify that `sstables_stats::get_shard_stats()` is updated when a tombstone with a ldt greater than y2k2038.

**Comment by tchaikov** [comment]
i think we will suffer from y2038 problem if we continue using `uint32_t` for the ldt. or we don't really care about it as we have better solutions than `gc_grace_seconds`? otherwise shall we adapt the solution proposed by https://issues.apache.org/jira/browse/CASSANDRA-14092 in order to buy 68 years' time before the day when we can safely gc tombstones without worrying about resurrecting the shadowed data?

**Comment by bhalevy** [comment]
> I think we will suffer from y2038 problem if we continue using uint32_t for the ldt. or we don't really care about it as we have better solutions than gc_grace_seconds?

The problem is with the sstable serialization format that we inherited from Cassandra which has the 32-bit local deletion time. A future sstable format must take that into account and use a 64-bit.

> otherwise shall we adapt the solution proposed by https://issues.apache.org/jira/browse/CASSANDRA-14092 in order to buy 68 years' time before the day when we can safely gc tombstones without worrying about resurrecting the shadowed data?

I'm not sure what exactly they are proposing and whether it holds water and applicable to Scylla.
In any case, this is a very rare corner case that we shouldn't go out of our way to solve right now.
The native solution would be to modernize the on-disk sstable format to be able to represent arbitrary deletion times.

**Comment by bhalevy** [comment]
> @bhalevy what shall we verify? the metric value or the warning messages sent to log? i think it'd suffice to add a test to verify that `sstables_stats::get_shard_stats()` is updated when a tombstone with a ldt greater than y2k2038.

It's ok to test the metric value.
Manual inspection of the log message that should include the sstable filename would suffice.

**Comment by tchaikov** [comment]
> > I think we will suffer from y2038 problem if we continue using uint32_t for the ldt. or we don't really care about it as we have better solutions than gc_grace_seconds?
> 
> The problem is with the sstable serialization format that we inherited from Cassandra which has the 32-bit local deletion time. A future sstable format must take that into account and use a 64-bit.
> 
> > otherwise shall we adapt the solution proposed by https://issues.apache.org/jira/browse/CASSANDRA-14092 in order to buy 68 years' time before the day when we can safely gc tombstones without worrying about resurrecting the shadowed data?
> 
> I'm not sure what exactly they are proposing and whether it holds water and applicable to Scylla. In any case, this is a very rare corner case that we shouldn't go out of our way to solve right now. The native solution would be to modernize the on-disk sstable format to be able to represent arbitrary deletion times.

they switched from `int32_t` to `uint32_t` for the time point.

**Comment by bhalevy** [comment]
> > > I think we will suffer from y2038 problem if we continue using uint32_t for the ldt. or we don't really care about it as we have better solutions than gc_grace_seconds?
> > 
> > 
> > The problem is with the sstable serialization format that we inherited from Cassandra which has the 32-bit local deletion time. A future sstable format must take that into account and use a 64-bit.
> > > otherwise shall we adapt the solution proposed by https://issues.apache.org/jira/browse/CASSANDRA-14092 in order to buy 68 years' time before the day when we can safely gc tombstones without worrying about resurrecting the shadowed data?
> > 
> > 
> > I'm not sure what exactly they are proposing and whether it holds water and applicable to Scylla. In any case, this is a very rare corner case that we shouldn't go out of our way to solve right now. The native solution would be to modernize the on-disk sstable format to be able to represent arbitrary deletion times.
> 
> they switched from `int32_t` to `uint32_t` for the time point.

That sounds reasonable.
We can extend `sstable_feature` for that for safety (although I wouldn't expect negative values - maybe only in testing)

**Comment by bhalevy** [comment]
> they switched from int32_t to uint32_t for the time point.

Was that part of a new sstable format version? (NA/NB?)

**Comment by tchaikov** [comment]
I will check and get back to you tomorrow.

**Comment by tchaikov** [comment]
my reading of [CASSANDRA-14092](https://issues.apache.org/jira/browse/CASSANDRA-14092) and [CASSANDRA-14227](https://issues.apache.org/jira/browse/CASSANDRA-14227) is:

0. c* uses a new sstable format version of "oa" for enabling this feature. see https://github.com/apache/cassandra/blob/825ff89c7089a81365e562a68c25fb16f8e6d927/src/java/org/apache/cassandra/io/sstable/format/big/BigFormat.java#L353 
1. the internal representation of `local_deletion_time` in code was changed from `int` to `long`. this mode is only enabled in 5.x .
2. in the new mode, the on-disk format of `local_deletion_time` was changed from `int32_t` to `uint32_t 
3. in the new mode, when reading a `local_deletion_time` out the range of [0, UINT32_MAX - 2], i.e., after `2106-02-07T06:28:13+00:00`. it emits a `local_deletion_time` with value of `UINT32_MAX - 1`, which indicates an invalid deletion time. and the it will be rewritten with `INT32_MAX - 1` when being scrubbed. 

see also https://github.com/apache/cassandra/blob/trunk/CASSANDRA-14092.txt 

since a negative `local_deletion_time` is invalid, probably we can port the mechinary to scylla without officially introducing the "oa" sstable format support in a wholesale? as it implies much more than "nc" -> "oa", and we only support up to "me".

**Comment by bhalevy** [comment]
let's open a new issue about that and write up the design in a separate design doc.

We can use an sstable feature bit to indicate the use of uint32_t in the sstable. Reading a negative value from sstables using the old format should be discussed. Since these are in the distant past they should already expired so I"d consider mapping them to 0 rather an invalid / maximum value.  Let's continue the discussion offline...

**Comment by tchaikov** [comment]
sure. adding it to my list.

**Comment by tchaikov** [comment]
created at #15116

**Comment by denesb** [comment]
Backported to 5.2 and 5.1.

**Comment by bhalevy** [comment]
@denesb I can't find the backport on 5.2.
Please check again.
Maybe it got dropped by mistake if next-5.2 was edited?

**Comment by denesb** [comment]
> @denesb I can't find the backport on 5.2. Please check again. Maybe it got dropped by mistake if next-5.2 was edited?

https://github.com/scylladb/scylladb/commit/8ed58c7dcacf0ca8cb2a7b97319969b836299f78
Removing labels.
