### ISSUE TITLE
The lwt request reported an error 'Internal server error: exception::mutation_write_timeout_exception' , but the final data was deleted.

### ISSUE THREAD

**Issue by Felix-zhoux** [scylladb/scylladb#15066]
Hi, when I execute some high-concurrency update requests in the cluster, some requests may report an error `mutation_write_timeout`, I will think that these requests have failed to execute, but in the end I found that these requests may be executed successfully.
For example, if I execute putitem, this request reports an error, and it may still be written in the end.
If I execute deleteitem, this request reports an error, and it may still be deleted in the end.

Is this a known issue?  And what can we do to avoid this (an obvious hazard of possible data retention).

**Comment by Felix-zhoux** [comment]
This is a probabilistic problem, not every error request will eventually be executed successfully.

**Comment by nyh** [comment]
Can you please attach the full error message, not just the exception type?

In general, as the the DynamoDB documentations says in https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html, when a request returns an Internal Server Error (i.e., error code 500),

> When you receive a status code 500 on a write operation, the operation may have succeeded or failed. 
> ...
> If the write operation is a single-item write request such as PutItem, UpdateItem, or DeleteItem, then your application should read the state of the item before retrying the operation, and/or use [Condition expressions](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.ConditionExpressions.html) to ensure that the item remains in a correct state after retrying regardless of whether the prior operation succeeded or failed.

The same is also true in Alternator - in such cases it's not clear exactly what happened. Did the operation time out before writing anything, or perhaps after having already writing one or more copies of the data? Maybe the coordinator lost the connection to one of the replicas, and doesn't even know if the replica's write was successful or not? If your operation is _idempotent_ - and `PutItem` and `DeleteItem`  which you mentioned are - you can simply retry the operation after such a failure. If it already succeeded, doing it a second time wouldn't hurt. In general, if the operation returns an error **you cannot assume that it succeeded** (if you're worried about data retention). If it returns error code 500 (InternalServerError) not 400 (ValidationException, etc.) you also cannot assume it did not succeed and should either retry the same write, or read to check what happened. 

A separate question is why the Internal Serer Error happened in the first place. This shouldn't be a usual occurrence. Timeouts are possible when a cluster is severely overloaded, but it is the responsible of the operator of the Scylla cluster to make sure  that the cluster is properly sized, and not severely overloaded. In https://github.com/scylladb/scylladb/issues/9804#issuecomment-1011965209 @kostja suggested that LWT in particular is sensitive to even minor overloads because it tries to do a lot of requests, and if any of them fail, the whole write fails. If  timeouts happen when the machine does not appear overloaded, or the machine appears overloaded for no good reason, it may be a Scylla performance bug that should be fixed.

**Comment by nyh** [comment]
> This is a probabilistic problem, not every error request will eventually be executed successfully.

What do you mean here? Are you saying that for some requests, even if you repeat them many times, some of them will **never** succeed?

**Comment by kostja** [comment]
No feedback since Aug 2023
