### ISSUE TITLE
Arbiter (tie-breaker) DC

### ISSUE THREAD

**Issue by kostja** [scylladb/scylladb#15360]
Add coverage for 2-DC setup when the third DC is explicitly selected to not store any data. The purpose of this DC is to act as a Raft group0 voting node. NetworkTopologyStrategy is used to ensure the explicit data placement in the two "data" DCs. Test auto-expansion of [`replication_factor` works as expected](https://github.com/kbr-/scylla/commit/c9a094d55709b8824bc04ddc0ecafe9d971835bf) (the data is expanded only to the two "data" DCs), and adding/removing nodes to the arbiter DC doesn't affect data placement. 

Update the user manual with instructions for setting up an arbiter DC to avoid split-brain of Raft Group0 in 2-DC setup.

EDIT from @kbr-scylla: it looks like we actually do need to implement the concept of tie-breaker node/DC inside Scylla core itself. See this post: https://github.com/scylladb/scylladb/issues/15360#issuecomment-2123004013

**Comment by kbr-scylla** [comment]
> NetworkTopologyStrategy is used to ensure the explicit data placement in the two "data" DCs

There are keyspaces `system_distributed` and `system_distributed_everywhere` which are using `SimpleStrategy` and `EverywhereStrategy`.

`system_distributed` can be changed to use NTS by the admin, however until they do that, it will be replicated to the arbiter DC. Are we fine with that?

`system_distributed_everywhere` however is more complicated -- the purpose was to make data written to it (CL=ALL) available locally on all nodes (that was before group 0) which can then read it with CL=ONE. If we change to NTS we lose that property. I'm not sure if this is correct. Needs to be investigated. If we cannot change it to NTS then it will also be replicated to arbiter DC.

There is a potential way to deal with this, even in presence of `SimpleStrategy` and `EverywhereStrategy` -- we could implement support for zero-token nodes and use those in the arbiter DC. I don't know how hard it would be, and whether it would be a problem.

The most important question is -- do we want to make sure that the arbiter DC really contains no data, or is it fine if it contains data from internal distributed tables?

cc @tzach @mykaul @avikivity @nyh

**Comment by tzach** [comment]
@kbr-scylla this is https://github.com/scylladb/scylladb/issues/1796

> The most important question is -- do we want to make sure that the arbiter DC really contains no data, or is it fine if it contains data from internal distributed tables?

At least as a first phase, I do not see an issue with the Open Arbiter holding data from internal distributed tables.
The only downside I can think of is the node will be doing some extra work.

**Comment by kbr-scylla** [comment]
Also there are two tables in `system_distributed` that are accessed by CDC clients. (`cdc_streams_descriptions_v2` and `cdc_generation_timestamps`).

**Comment by kbr-scylla** [comment]
We could implement a no-token node. This would ensure that no tables, including the ones accessed by clients (like the CDC metadata tables), or Everywhere startegy tables, would be replicated to these nodes.

Then the arbiter DC would consist of such no-token nodes.

cc @avikivity

**Comment by kbr-scylla** [comment]
If I understand correctly, according to @tzach's comment here:
https://github.com/scylladb/scylla-enterprise/issues/3317#issuecomment-1699619292

What we actually need to do (by 6.0) is:
- update the documentation,
- test coverage

**Comment by mykaul** [comment]
By 6.0, do we want to even support a configuration where you don't have either  (multi-DC with enough regions, or a tie-breaker node) ?

**Comment by kbr-scylla** [comment]
What do you mean by "support"? We could make sure we don't setup such clusters in Scylla Cloud for example, but I don't think we could come up with a reasonable programmatic way that prevents customers from building their clusters like that.

For example, to build a 3-DC cluster, you have to go through a 2-DC cluster intermediate state.

(Unless you mean something like -- "if you setup a cluster like that, your warranty becomes void")

**Comment by mykaul** [comment]
> (Unless you mean something like -- "if you setup a cluster like that, your warranty becomes void")

Exactly.
Note that in Scylla cloud we could enforce correct configuration.

**Comment by kbr-scylla** [comment]
Following discussion on mailing list...

It looks like most people agreed that we need to do something more than update the documentation so the user carefully ensures not to include the "arbiter DC" in their replication strategy configurations. In particular, in presence of such arbiter DC, the user would not be able to use the `'replication_factor': X` auto-expansion feature -- the feature should automatically skip the arbiter DC, meaning we do need a change inside ScyllaDB core.

Furthermore: the "3 DCs rule" can only be a recommendation. There are multiple clusters in Scylla Cloud that use 2 DC configurations. We cannot enforce a 30-40% cost increase for our customers just to avoid losing quorum in disaster scenarios.

@dorlaor mentioned the idea of external tie-breaker --- an external service, that **multiple Scylla clusters** could connect to, which would serve as the "third DC".

I'm not sure if this is possible/viable though; correctness of Raft depends on every voter having the possibility to become a leader and replicate the committed part of Raft log to all other members. Thus the external service would have to store the Raft group 0 log and snapshots of every participating Scylla cluster, and we may hit scalability problems. And it would basically have to act as a real Scylla node because it would have to actually apply the Raft commands locally in order to be able to send snapshots.

Alternatively, (and this would probably be simpler to implement, at least initially), we could implement a "no token node", the purpose of which is to participate in Raft group 0, but not replicate any data or coordinate data path queries. So it would do all group 0 stuff (schema, topology, auth, service levels, etc) but not have any tokens, therefore it would not replicate any data. (And we'd have to hide it from the drivers too / close CQL port)

This is an urgent item, we need to handle it after 6.0, most likely 6.1 should already include it.

cc @avikivity @tzach @mykaul @kostja

**Comment by tzach** [comment]
> @dorlaor mentioned the idea of external tie-breaker --- an external service, that multiple Scylla clusters could connect to, which would serve as the "third DC".

- This will break our security isolation intranet by connecting all clusters to a centralized entity using the inter-node protocol. 
- Which DC will this service live in? If it's in a used region, it won't work.
- The cost of a small node in DC is not high

The non token node makes much more sense to me.

**Comment by gleb-cloudius** [comment]
> Furthermore: the "3 DCs rule" can only be a recommendation. There are multiple clusters in Scylla Cloud that use 2 DC configurations.

Or we can implement  https://github.com/scylladb/scylladb/issues/18793 and add a notion of a "primary" DC. This DC will have majority of voters and will be able to work even if it is isolated from the second one.

**Comment by tzach** [comment]
> Or we can implement #18793 and add a notion of a "primary" DC. This DC will have majority of voters and will be able to work even if it is isolated from the second one.

Assuming each of the DCs has the same chance to fail, this will fix 50% of the DC failures, while Arbiter fix 100%

**Comment by gleb-cloudius** [comment]
> > Or we can implement #18793 and add a notion of a "primary" DC. This DC will have majority of voters and will be able to work even if it is isolated from the second one.
> 
> Assuming each of the DCs has the same chance to fail, this will fix 50% of the DC failures, while Arbiter fix 100%

33%

**Comment by kbr-scylla** [comment]
@dorlaor you basically described https://github.com/scylladb/scylladb/issues/18793 which I planned for Q3 (the plan is still fluent tho) and it's mostly orthogonal to having a voter-only DC.

Arbiter node is basically "voter only" node while what you described is the opposite -- the possibility of having "node that does everything except voting"
