### ISSUE TITLE
Populating tables from several datadirs got broken

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#15418]
Commit 119c0f3983757a9f3d3bedc37668306f4d819391 makes this interesting change

```patch
@@ -558,11 +664,16 @@ future<> distributed_loader::populate_keyspace(distributed<replica::database>& d
         auto sstdir = ks.column_family_directory(ksdir, cfname, uuid);
         dblog.info("Keyspace {}: Reading CF {} id={} version={}", ks_name, cfname, uuid, s->version());
 
+        auto metadata = table_population_metadata(db, ks_name, cfname);
+        std::exception_ptr ex;
+
         try {
             co_await ks.make_directory_for_column_family(cfname, uuid);
-            co_await distributed_loader::populate_column_family(db, sstdir + "/" + sstables::staging_dir, ks_name, cfname, allow_offstrategy_compaction::no);
-            co_await distributed_loader::populate_column_family(db, sstdir + "/" + sstables::quarantine_dir, ks_name, cfname, allow_offstrategy_compaction::no, must_exist::no);
-            co_await distributed_loader::populate_column_family(db, sstdir, ks_name, cfname, allow_offstrategy_compaction::yes);
+
+            co_await metadata.start();
+            co_await distributed_loader::populate_column_family(metadata, sstables::staging_dir, allow_offstrategy_compaction::no);
+            co_await distributed_loader::populate_column_family(metadata, sstables::quarantine_dir, allow_offstrategy_compaction::no, must_exist::no);
+            co_await distributed_loader::populate_column_family(metadata, "", allow_offstrategy_compaction::yes);
         } catch (...) {
             std::exception_ptr eptr = std::current_exception();
             std::string msg =

```

note the `ksdir` and `sstdir` variables. The former is `data_dir + "/" + ks_name` and the latter is `ksdir + "/" + cf_dir_name()`.

Now, before the patch the call to `populate_column_family()` was done over `sstdir + "/" + $location` thus corresponding to different `data_dir` values passed as argument. After the patch both, `ksdir` and `sstdir` become unused in this helper (only printed in logs). And the `populate_column_family()` now happens with `$location` only, because the call prepends the location with `table.dir()`. But (!) table.dir() is just the 0th element of the datadirs.

Cc @bhalevy

**Comment by bhalevy** [comment]
Is there a test reproducing the breakage?

**Comment by xemul** [comment]
No :(

**Comment by bhalevy** [comment]
#15480 fixes this issue at the distributed_populator::table_populator level, but even with that I found out with some additional testing that we don't really support multiple data directories at the moment.

The following patch enables loading sstables from multiple data directories:
[0001-distributed_loader-table_populator-use-_base_path-fo.patch.txt](https://github.com/scylladb/scylladb/files/12686565/0001-distributed_loader-table_populator-use-_base_path-fo.patch.txt)

BUT, the unit test shows that since we don't separate the data directories into compaction groups, we try to compact the sstables together and hit https://github.com/scylladb/scylladb/blob/2392b6a179a3fead205f1a04520b92ceb09a9216/sstables/sstable_directory.cc#L526
