### ISSUE TITLE
automatic schema modifications should be announced once

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#15437]
There are some schema modifications performed automatically (during bootstrap, upgrade etc.) by Scylla that are announced by multiple calls to `migration_manager::announce` even though they are logically one change. All of them should be refactored to announce only once. An example is the FIXME in `system_distributed_keyspace::start`:
```
// FIXME: fix this code to `announce` once
```
In #15435, we detected that we need to catch `group0_concurrent_modification` and retry `announce` in multiple places to fix the concurrent bootstrap in the Raft-based topology. However, before doing that, we should do the refactor mentioned in this issue to make "writing retry loops" easier.

**Comment by kbr-scylla** [comment]
This will not go in 5.4, in fact I think we will not reach the end goal of the issue (having a **single** announce in each case) because as we discussed with @patjed41, the value-to-required-effort ratio is too low.

We should be able to achieve some intermediate state, where the number of `announce`s in each case is reduced to at most 2, this is what https://github.com/scylladb/scylladb/pull/15594 does (@patjed41 please change "Fixes" to "Refs" in the PR description), and that is completely enough for all practical purposes.

And I'll change the milestone of this issue to Yellowfin.
