### ISSUE TITLE
unhandled group0_concurrent_modification exception during concurrent bootstrap

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylladb#15435]
I've been testing concurrent bootstraps that should work in the Raft-based topology (#15423). Sometimes, one of the 3 bootstrapping nodes crashes with
```
ERROR 2023-09-15 16:36:48,131 [shard 0:main] init - Startup failed: service::group0_concurrent_modification (Failed to apply group 0 change due to concurrent modification)
```
The reason is the unhandled `group0_concurrent_modification` exception thrown in `raft_group0_client::add_entry` that is called in `migration_manager::announce_with_raft`.

```
INFO  2023-09-15 16:42:44,674 [shard 0:stre] migration_manager - Create new Keyspace: KSMetaData{name=system_distributed, strategyClass=org.apache.cassandra.locator.SimpleStrategy, strategyOptions={replication_factor=3}, cfMetaData={}, durable_writes=1, userTypes=org.apache.cassandra.config.UTMetaData@0x600004141420}
INFO  2023-09-15 16:42:44,678 [shard 0:comp] compaction - [Compact system.scylla_local 21973b10-53d6-11ee-9b67-27244cebb252] Compacted 2 sstables to [/home/patrykjedrzejczak/forks/scylladb/testlog/dev/scylla-3/data/system/scylla_local-2972ec7ffb2038ddaac1d876f2e3fcbd/mc-14-big-Data.db:level=0]. 63kB to 58kB (~91% of original) in 4ms = 15MB/s. ~256 total partitions merged to 2.
INFO  2023-09-15 16:42:44,755 [shard 0:stre] schema_tables - Creating keyspace system_distributed
INFO  2023-09-15 16:42:44,759 [shard 0:stre] schema_tables - Schema version changed to 8ed4a870-ad4f-3756-b91d-0dab6de3b943
INFO  2023-09-15 16:42:44,760 [shard 0:stre] migration_manager - Create new Keyspace: KSMetaData{name=system_distributed_everywhere, strategyClass=org.apache.cassandra.locator.EverywhereStrategy, strategyOptions={}, cfMetaData={}, durable_writes=1, userTypes=org.apache.cassandra.config.UTMetaData@0x600004141420}
INFO  2023-09-15 16:42:44,856 [shard 0:stre] schema_tables - Creating keyspace system_distributed_everywhere
INFO  2023-09-15 16:42:44,859 [shard 0:stre] schema_tables - Schema version changed to ad8e209a-d451-39fc-9409-5d8975ed86a8
INFO  2023-09-15 16:42:44,860 [shard 0:main] init - Shutting down group 0 service
...
ERROR 2023-09-15 16:36:48,131 [shard 0:main] init - Startup failed: service::group0_concurrent_modification (Failed to apply group 0 change due to concurrent modification)
```

I think the fix is to just catch this exception and retry (like almost everywhere) but I'm not sure. Maybe there is a reason why it's not handled there.

cc @kbr-scylla @gleb-cloudius

**Comment by kbr-scylla** [comment]
cc @kostja 

It is the responsibility of the caller of `announce` to retry a schema change if they get `group0_concurrent_modification`. Indeed, the caller must obtain another guard.

This is because once you get `group0_concurrent_modification`, the schema change mutations you're trying to apply may no longer be correct. You need to create new schema change mutations on the current version of the schema (which might be different than when you tried to apply the first change).

Now I remember... we create a bunch of keyspaces and tables during node startup procedure if we see that they don't exist yet. And all these places -- for example see `system_distributed_keyspace::start()` don't have a retry loop, because they assume there are no concurrent schema changes when you boot the first node! And of course, with concurrent bootstrap, this assumption is no longer true.

So it seems we need to fix all those places...

**Comment by patjed41** [comment]
> So it seems we need to fix all those places...

I opened #15437 that should be done first.

**Comment by denesb** [comment]
@patjed41 @kbr-scylla please evaluate for backport.

**Comment by kbr-scylla** [comment]
Experimental only
