### ISSUE TITLE
[dtest]  test_ks_netw_topology_set_nonexistent_dc timeout on write to paxos

### ISSUE THREAD

**Issue by fruch** [scylladb/scylladb#15606]
lwt_destructive_ddl_test.py::TestLwtDestructiveDDL::test_ks_netw_topology_set_nonexistent_dc

has a log showing timeout on writing to system.paxos:

```
>           raise AssertionError('Unexpected errors found: {}'.format(found_errors))
E           AssertionError: Unexpected errors found: [('node2', ['ERROR 2023-09-29 17:08:57,742 [shard 1:stat] storage_proxy - exception during mutation write to 127.0.98.2: exceptions::mutation_write_timeout_exception (Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE.)'])]
```

### Logs

https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/4953/testReport/junit/lwt_destructive_ddl_test/TestLwtDestructiveDDL/FullDtest___full_split002___test_ks_netw_topology_set_nonexistent_dc/

happened twice in the last 90 days:
https://70f106c98484448dbc4705050eb3f7e9.us-east-1.aws.found.io:9243/goto/3243ef90-6113-11ee-bf28-5927cc3d3ce3

**Comment by ptrsmrn** [comment]
I'm running it over and over again locally, and it always succeeds. Maybe I can decrease the timeout for the fail to appear? But I don't think it's a matter of a test timeout, because the test fails on paxos schema changes, which happen "instantly" when everything is OK, but in this case the 2nd node timeouts after 30s on a failed schema change on shard no. 1:
```
INFO  2023-09-29 17:08:28,538 [shard 0:stat] schema_tables - Schema version changed to 7fbcf268-be29-3bb7-abb7-09a453efd7ed
ERROR 2023-09-29 17:08:57,742 [shard 1:stat] storage_proxy - exception during mutation write to 127.0.98.2: exceptions::mutation_write_timeout_exception (Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE.)
```

I am comparing logs of nodes 2 and 3 (respectively left and right sides on the attached pic; 3 is the coordinator), and see that compaction kicked in, but timestamps say that compaction happened just before the schema changes and it shouldn't matter.
![image](https://github.com/scylladb/scylladb/assets/124208650/ccba72a4-1892-4483-947f-1c11ea2a35d4)

What caught my attention was that for both 1st & 3rd nodes we have `migration_manager` logs, but it's not there for 2nd node:
```
node 3 - migration_manager - Create new Keyspace: KSMetaData{name=ks, strategyClass=org.apache.cassandra.locator.NetworkTopologyStrategy, strategyOptions={dc1=3},...
node 1 - migration_manager - Create new ColumnFamily: org.apache.cassandra.config.CFMetaData@0x6000041bd880[cfId=cf1e9430-5eea-11ee-b0f2-e1bb6b0bde86,ksName=ks,cfName=test,cfType...
```
but a similar log is missing from 2nd node. OTOH these logs are different, one is about creating a KS, the other about creating a CF.

**Comment by ptrsmrn** [comment]
I am analyzing and comparing this failure with logs from a successful run (with `trace` level), but no breaktrhoughs.
The problem still seems to be that schema mutation was OK for shard 0 but wasn't ok for shard 1.

**Comment by mykaul** [comment]
Any updates to this?

**Comment by ptrsmrn** [comment]
@mykaul it's been labeled as potentially infra-related issue, do we have any procedure of handling such issues, or I should just re-run and continue investigating on my own?

**Comment by mykaul** [comment]
Closing - if it happens again, we'll re-open.
