### ISSUE TITLE
pytest picks up incorrect scylla binary

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#15679]
Spotten while validating #15635 

https://jenkins.scylladb.com/job/scylla-master/job/scylla-ci/4142/artifact/testlog/x86_64/debug/object_store.test_basic.1.log

This :point_up: is the log file from debug-mode test. Here's what it contains:

```
test/object_store/test_basic.py Scylla under test: /jenkins/workspace/scylla-master/scylla-ci/scylla/build/release/scylla
```

**Comment by xemul** [comment]
yup
```
$ ls testlog/debug/pytest-of-xemul/pytest-0/test_basic0/test_scylla  -l
lrwxrwxrwx 1 xemul xemul 43 окт 10 10:15 testlog/debug/pytest-of-xemul/pytest-0/test_basic0/test_scylla -> /home/xemul/src/scylla/build/release/scylla
```

**Comment by xemul** [comment]
Cc @tchaikov

**Comment by nyh** [comment]
The code in test/cql-pytest/run.py (which the object-store tests are using), assumes that the environment variable `SCYLLA` is set to point to Scylla - otherwise the latest Scylla executable is picked (which is useful for a developer compiling and testing just a single build version, but is not what you want when running tests over multiple build types).

test.py indeed tries to set the SCYLLA environment variable, but does this by setting some "scylla_env" array and not the actual environment, and it's possible we forget to pass this variable to the actual test? Which means the "scylla_env" array is just a no-op, and never worked? How could we have missed such a bug?

**Comment by xemul** [comment]
> The code in test/cql-pytest/run.py (which the object-store tests are using), assumes that the environment variable SCYLLA is set to point to Scylla - otherwise the latest Scylla executable is picked (which is useful for a developer compiling and testing just a single build version, but is not what you want when running tests over multiple build types).

That was also a huge unpleasant surprise to me. I did this

```
$ ./configure --mode=debug
$ ninja debug-build
$ pytest -s test/...
$ ./configure --mode=dev
$ ninja dev-build
$ pytest -s test/...
```

I believe you know which scylla binary the last pytest invocation picked

> How could we have missed such a bug?

Easily -- if you test dev, release and debug mode tests against a single binary it all just works (or all just doesn't but in this case we don't merge changes)

**Comment by nyh** [comment]
> > The code in test/cql-pytest/run.py (which the object-store tests are using), assumes that the environment variable SCYLLA is set to point to Scylla - otherwise the latest Scylla executable is picked (which is useful for a developer compiling and testing just a single build version, but is not what you want when running tests over multiple build types).
> 
> That was also a huge unpleasant surprise to me. I did this
> 
> ```
> $ ./configure --mode=debug
> $ ninja debug-build
> $ pytest -s test/...
> $ ./configure --mode=dev
> $ ninja dev-build
> $ pytest -s test/...
> ```
> 
> I believe you know which scylla binary the last pytest invocation picked

I don't understand... If the code picks the latest Scylla binary, then it will pick the dev build in the second run. Didn't it?

Anyway, as I noted, test.py already does the right thing for its use case, or tries to do the right thing, of setting the SCYLLA environment to the right version. Obviously something there is wrong, and this variable is not passed to the "pytest" process that is run for the object_store suite. Somebody more experienced with test.py than me should check why this is not happening.

**Comment by tchaikov** [comment]
> > The code in test/cql-pytest/run.py (which the object-store tests are using), assumes that the environment variable SCYLLA is set to point to Scylla - otherwise the latest Scylla executable is picked (which is useful for a developer compiling and testing just a single build version, but is not what you want when running tests over multiple build types).
> 
> That was also a huge unpleasant surprise to me. I did this
> 
> ```
> $ ./configure --mode=debug
> $ ninja debug-build
> $ pytest -s test/...
> $ ./configure --mode=dev
> $ ninja dev-build
> $ pytest -s test/...
> ```
> 

in this case, please point `SCYLLA` env variable to the scylla executable under test.

**Comment by xemul** [comment]
> I don't understand... If the code picks the latest Scylla binary, then it will pick the dev build in the second run. Didn't it?

For some reason it didn't :( I see the sort by mtime in find_scylla(), but it picked the debug binary

**Comment by xemul** [comment]
> in this case, please point SCYLLA env variable to the scylla executable under test.

My concern is that when run without it it pretends that everything is OK, while really it isn't (or maybe I did something wrong)

**Comment by nyh** [comment]
> > I don't understand... If the code picks the latest Scylla binary, then it will pick the dev build in the second run. Didn't it?
> 
> For some reason it didn't :( I see the sort by mtime in find_scylla(), but it picked the debug binary

Maybe your dev build was already fully built, so "ninja dev-build" didn't do anything, and didn't touch the executable.

In any case, as I said, this is a bug, everything was set up in place to fix this (test.py passes the SCYLLA environment variable to what it wants to run, the test uses it) but for some reason, it doesn't work and will need to be fixed by someone familiar with the relevant code (test.py and test/object_store).

By the way, the script test/cql-pytest/run prints the result of find_scylla() so this kind of mistake is very visible when you run cql-pytest manually. This can't be said for test/object_store which uses the test.py and cql-pytest/run.py (not the cql-pytest/run script) and doesn't print its decision so you can't see a mistake even if you run things manually.

**Comment by tchaikov** [comment]
just had an offline discussion with @xemul , i see what his confusion comes from, since he always creates the `build.ninja` file with only a single mode using `configure.py, and he expected `test.py` picks the scylla executable of the specified mode .

but there are two things:

1. `test.py` does not pick the scylla executable based on the output of `ninja mode_list`
2. `ninja` does not rebuild the `scylla` executable if it is updated.

thinking forward, developers are likely working on multiple builds, which share the same source tree. so i will add a `--scylla` option to the tests which launch scylla. without explicitly specifying this option, the test fails unconditionally.

when it comes to `test.py`, will limit the selection of `find_scylla()` to the modes returned by `ninja mode_list`.

**Comment by avikivity** [comment]
Ok, so this isn't really a CI-Stability issue, right? It only affects developers.

**Comment by tchaikov** [comment]
> Ok, so this isn't really a CI-Stability issue, right? It only affects developers.

it's not so far. and i don't really think it will be.

but it does affect both developers and the test performed by CI. the status quo is that `object_store` test is always testing the scylla executable with the newest mtime no matter it is supposed to test the debug build or release build.

**Comment by avikivity** [comment]
Ok. So it doesn't affect stability, but it does affect the quality of the test. I'll commit it once we're more stable.

**Comment by nyh** [comment]
> thinking forward, developers are likely working on multiple builds, which share the same source tree. so i will add a `--scylla` option to the tests which launch scylla. without explicitly specifying this option, the test fails unconditionally.

Why do you need to add an option that test.py will pass to the test, when we already have a convention that test.py passes the executable path in an environment variable, "SCYLLA"?

**Comment by tchaikov** [comment]
> > thinking forward, developers are likely working on multiple builds, which share the same source tree. so i will add a `--scylla` option to the tests which launch scylla. without explicitly specifying this option, the test fails unconditionally.
> 
> 
> 
> Why do you need to add an option that test.py will pass to the test, when we already have a convention that test.py passes the executable path in an environment variable, "SCYLLA"?

I think despite that this convention is part of user interface of the tests, it is not quite visible -- one cannot find it unless he/she knows this convention or read the source code, probably a command line option will help ?

**Comment by nyh** [comment]
> I think despite that this convention is part of user interface of the tests, it is not quite visible -- one cannot find it unless he/she knows this convention or read the source code, probably a command line option will help ?

This issue is becoming impossible to follow, because it discusses several different scripts. test.py has its own conventions, and a "--mode" option. The scripts that do NOT have a "--mode" option, yet, are test/cql-pytest/run and friends - are you referring to them? These **are** documented, in test/cql-pytest/README.md, which explains exactly how the scylla executable is chosen and can be overridden. I agree that a "--mode" option could be useful as another alternative for doing the same thing, if there's interest I can add it. But keep it mind it will only apply to test/cql-pytest/*, **not** to test.py.

**Comment by tchaikov** [comment]
sorry, i didn't make it clear. i was talking about the tests, not their driver -- `test.py`. i wanted to address one of Pavel's pain points:

> That was also a huge unpleasant surprise to me. I did this
> 
> ```
> $ ./configure --mode=debug
> $ ninja debug-build
> $ pytest -s test/...
> $ ./configure --mode=dev
> $ ninja dev-build
> $ pytest -s test/...
> ```

> The scripts that do NOT have a "--mode" option, yet, are test/cql-pytest/run and friends - are you referring to them? These are documented, in test/cql-pytest/README.md

i confess that i was wrong and i should have RTFM'ed.

>  I agree that a "--mode" option could be useful as another alternative for doing the same thing, if there's interest I can add it.

if you don't have the bandwidth i can help on this if the PR will be reviewed.

**Comment by denesb** [comment]
Test only improvement, not backporting.
