### ISSUE TITLE
failure detector apis need to call gossiper on shard 0

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15816]
Legacy versions of gossiper, prior to 38c2347a3ce298945d47d258c93ec3858a43c4fc, do not replicate the endpoint_state heart_beat_state to shards other than 0, so when invoked via `nodetool gossipinfo`, the version and generations may be bogus if the api is not invoked on shard 0.

See also #15088 #12261 and their fix, #15093, for example.

**Comment by bhalevy** [comment]
@kbr-scylla does this fall in your team's realm?

**Comment by kbr-scylla** [comment]
> Legacy versions of gossiper, prior to https://github.com/scylladb/scylladb/commit/38c2347a3ce298945d47d258c93ec3858a43c4fc, do not replicate the endpoint_state heart_beat_state to shards other than 0, so when invoked via nodetool gossipinfo, the version and generations may be bogus if the api is not invoked on shard 0.

This problem can be solved by backporting 38c2347a3ce298945d47d258c93ec3858a43c4fc, @avikivity, but [here](https://github.com/scylladb/scylladb/issues/14794#issuecomment-1779613101) you said "I think this is impractical to backport (greater risk than benefit)."

> See also https://github.com/scylladb/scylladb/issues/15088 https://github.com/scylladb/scylladb/issues/12261 and their fix, https://github.com/scylladb/scylladb/pull/15093, for example.

@bhalevy since you referenced these issues...
I see two ways to fix the problem other than backporting 38c2347a3ce298945d47d258c93ec3858a43c4fc.

First, a simple mechanical change to call the APIs on shard 0. Easy change and easy to backport, and nothing can go wrong. But that's probably not what you had in mind.

Second, a larger change, similar to what `get_live_members_synchronized` does, to provide similar guarantees. `get_live_members_synchronized` ensures that once the endpoint returns, all shards have observed the change. To provide similar guarantees we would have to do some intricate locking and cross shard operations, maintaining "endpoint versions" and so on.

But the larger change becomes even larger than 38c2347a3ce298945d47d258c93ec3858a43c4fc and becomes even riskier to backport. So we miss the entire point.

@bhalevy since you referenced the issues, I understand that you expect we go with the larger change. But then I'd rather backport 38c2347a3ce298945d47d258c93ec3858a43c4fc instead.

On the other hand, we probably don't need the same guarantees that `get_live_members_synchronized` provides, we needed them for some specific purpose related to how Scylla uses liveness information across shards and interaction between Scylla and tests; there is no such situation in this case, we just need the endpoint to return correct information, which is dealt with simply by routing the call to shard 0.

So I'm going to go with the simple mechanical change.

**Comment by bhalevy** [comment]
I'm good with the simple mechanical change.
https://github.com/scylladb/scylladb/commit/38c2347a3ce298945d47d258c93ec3858a43c4fc solves the issue on master and it's too risky to backport.

**Comment by kbr-scylla** [comment]
Queued backports to 5.1, 5.2, 5.4:
https://github.com/scylladb/scylladb/commit/f886581bee2f7537a82371b114d110afc8e993c0
https://github.com/scylladb/scylladb/commit/f76ba217e79fbfc3f84f22f86e86239233f552b9
https://github.com/scylladb/scylladb/commit/66be0fc1ebf8b35b77c442723e6d55810bdedc96
