### ISSUE TITLE
[Proposal] Guardrails: reject empty partition and/or clustering keys

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#15921]
We've seen cases where bugs in the application cause a partition or clustering key to be empty
and consequently this may lead to accumulating bogus data in large partitions.

I think it's safe to presume that an empty key is erroneous, so the proposal is to reject such queries by default, unless they are explicitly enabled.

**Comment by bhalevy** [comment]
Cc @avikivity @nyh @kostja

**Comment by kostja** [comment]
I don't think it's a guardrail, however. Accepting NULL values for primary key values is a bug.

In ANSI PRIMARY KEY constraint can not contain nulls:

```
11.7 <unique constraint definition>
Syntax Rules

…

5) If the <unique specification> specifies PRIMARY KEY, then for each <column name> in the explicit or implicit <unique column list> for which NOT NULL is not specified, NOT NULL is implicit in the <column definition>.
```

The question of unique constraint (non-primary key) containing NULLs is more interesting, they are allowed, but their treatment was ambiguous until SQL:2023, which introduced NULLS DISTINCT clause. Here are a  few of blog posts about it:

https://ocelot.ca/blog/blog/2013/09/11/null-and-unique/
https://peter.eisentraut.org/blog/2023/04/04/sql-2023-is-finished-here-is-whats-new
https://ocelot.ca/blog/blog/2023/06/11/sql2023-and-how-well-mysql-and-mariadb-comply/

**Comment by kostja** [comment]
One issue with applying ANSI guidelines to ScyllaDB/Cassandra is that in BOTH NULLS are still acting as values (tombstone markers), since they have a timestamp associated with them. I think, however, that we should transition to ANSI treatment of NULLs and there is a similar sentiment in Cassandra mailing list:
https://lists.apache.org/thread/qq0jkm6rlkd2slfmhgz7om14tbpys891


Cassandra restricts NULLs in clustering keys only to trailing columns and only if compact storage is enabled:
https://issues.apache.org/jira/browse/CASSANDRA-10147
https://stackoverflow.com/questions/44578787/can-i-have-null-values-in-clustering-columns-of-a-primary-key

**Comment by kostja** [comment]
A guardrail or a change in the default behaviour will not address the existing data anomalies. We will need to fix them with a REPAIR or a similar command.

**Comment by kostja** [comment]
@bhalevy I can't reproduce this:

```
> CREATE TABLE t (pk INT PRIMARY KEY);
OK
> INSERT INTO t (pk) VALUES (NULL);
Error from server: code=2200 [Invalid query] message="Invalid null value in condition for column pk"
> SELECT * FROM t ALLOW FILTERING;
+------+
| pk   |
|------|
+------+
> DROP TABLE t;
OK
> CREATE TABLE t (pk INT, ck INT, PRIMARY KEY(pk,ck));
OK
> INSERT INTO t (pk,ck) VALUES (NULL, NULL);
Error from server: code=2200 [Invalid query] message="Invalid null value in condition for column pk"
> INSERT INTO t (pk,ck) VALUES (1, NULL);
Error from server: code=2200 [Invalid query] message="Invalid null value in condition for column ck"
> SELECT * FROM t ALLOW FILTERING;
+------+------+
| pk   | ck   |
|------+------|
+------+------+
> DROP TABLE t;
OK
```

**Comment by bhalevy** [comment]
Sorry, I wasn't clear, empty doesn't mean NULL.

We indeed don't allow partition keys to contain empty string, but we do allow the clustering key to contain an empty string.

For example:
```
cqlsh:ks> CREATE TABLE t (pk text, ck text, PRIMARY KEY (pk, ck));
cqlsh:ks> INSERT INTO t (pk, ck) VALUES ('', '');
InvalidRequest: Error from server: code=2200 [Invalid query] message="Key may not be empty"
cqlsh:ks> INSERT INTO t (pk, ck) VALUES ('pk1', '');
cqlsh:ks> SELECT * FROM t WHERE pk = 'pk1';

 pk  | ck
-----+----
 pk1 |   

(1 rows)
```

**Comment by nyh** [comment]
> We've seen cases where bugs in the application cause a partition or clustering key to be empty and consequently this may lead to accumulating bogus data in large partitions.
> 
> I think it's safe to presume that an empty key is erroneous, so the proposal is to reject such queries by default, unless they are explicitly enabled.

Please note that this topic has a long history and you have to be careful not to break any of the existing **correct** use cases (it would be hard for you to break anything there, because I have it covered pretty well in test/cql-pytest/test_empty.py. In particular, CQL doesn't generally allow an empty string as a partition key, it does allow an empty string as a **component** of a compound partition key, and does allow an empty string as a clustering key. It also allows a materialized-view or index to index an empty string, and in that case you end up with a bona-fide empty string as a partition key.

I'm not sure I understand why a clustering key of '' is more problematic than 'hello' and we need a guardrail to "protect" the user from it. If the application has a bug creating bogus stuff with key '', what prevents it from having the same bug with the key 'hello'? If you think these bogus rows can't be deleted because we have a bug with `WHERE key=''` (Cassandra used to have such a bug in some cases) we should fix that bug, but it's not a guardrail.

I see @kostja closed this issue, but then assigned it and continued to comment it, so I don't understand if the closing was accidental or deliberate.

**Comment by kostja** [comment]
OK, so empty values is a different story. Empty value is a valid value in ANSI, and I know of no vendor which guardrail it. Accidentally, in Oracle, from ancient times and till the current release (19i last I checked) empty string is equivalent to NULL:

```
Присоединен к:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production
Version 19.3.0.0.0

Ъ > create table bugfeature(name varchar2(15));
Затрач.время: 00:00:00.33
Ъ > insert into bugfeature values('');
Затрач.время: 00:00:00.09
Ъ > select count(*) from bugfeature where name is null;
  COUNT(*)
  1
Затрач.время: 00:00:00.02
Ъ >
```
This contradicts ANSI and pretty much all other vendors on the market. So given even Oracle messed it up no wonder Cassandra engineering got confused.

**Comment by kostja** [comment]
I closed it since the original bug description was referring to NULL values, which are not allowed, so the original description is not correct. I can't reopen it. Guardrailing empty string in the clustering key could be a valid feature request but I'd say a pretty esoteric one - no other vendor does it, like I said. @bhalevy if you still belive it should be done, please reopen or better yet, open another one, with a test case.

**Comment by bhalevy** [comment]
BTW the original issue title referred to "empty" keys, not NULL keys.
In any case, given @nyh's comment https://github.com/scylladb/scylladb/issues/15921#issuecomment-1791346646 I see that this topic was already well thought over, so no need to reopen this issue.
