### ISSUE TITLE
raft: better failures when quorum is missing in topology and schema operations

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#16604]
Currently if you try to decommission a node when no majority is alive, the operation will simply get stuck indefinitely trying to perform a Raft barrier/command which is impossible without quorum.

These operations should have a timeout. Preferably, we should also detect that a quorum is dead and report it as possible cause of the timeout for easier debugging. AFAIK there is no way for Raft library to return this information directly (maybe we should add it somehow?) but we can work around this, e.g. after timeout, check how many nodes are alive in gossip, and if there is no quorum, report this as possible cause (with the list of dead nodes).

**Comment by gleb-cloudius** [comment]
The problem is not decommission specific. All topolopgy commands through raft will stuck without a quorum.

**Comment by kostja** [comment]
This is why we need to store the node UP/DOWN status in Raft. If we store it we immediately know we have no majority and can reject the operation :-)

(@gleb-cloudius I hope you find this one funny :)

But more seriously I think we can begin dealing with this by dynamically adjusting the voters circle as the nodes are being shut down.

This will not fix the issue though. So for the actual fix we might be consulting with gossip status, perhaps?

**Comment by gleb-cloudius** [comment]
> This is why we need to store the node UP/DOWN status in Raft. If we store it we immediately know we have no majority and can reject the operation :-)
> 
> (@gleb-cloudius I hope you find this one funny :)

For a moment it made me angry :)

> 
> But more seriously I think we can begin dealing with this by dynamically adjusting the voters circle as the nodes are being shut down.
> 
> This will not fix the issue though. So for the actual fix we might be consulting with gossip status, perhaps?

We still need to have a timeout since even if gossiper reports state as UP for enough nodes some may be actually down or may crach between the check and the write.

**Comment by temichus** [comment]
REMINDER: remove issues related test disabling from https://github.com/scylladb/scylla-dtest/pull/3836/files when issue closed

**Comment by kbr-scylla** [comment]
Added "schema" to the title. Schema changes are also failing with timeout errors if there's no majority.

**Comment by gusev-p** [comment]
A question about `abort_source`.

`abort_source` used to communicate aborted state through `abort_requested_exception` -- the `abort_source::request_abort` creates an instance of it with no arguments and `abort_source` clients get this exception when they call `abort_source::check`. The problem is that the reason of the abort is lost in this transition -- if there are multiple places in the code which call `request_abort()` we won't be able to tell which of them has triggered it.

This could be solved by enhancing `abort_requested_exception` with the `sstring reason` field or (probably better) with the nested exception `std::exception_ptr original_exception`. There is another problem though - `abort_source` has an `abort_requested()` method, and in some places we handle it like this
```
try {
        co_await (as ? _tick_promise->get_shared_future(*as) : _tick_promise->get_shared_future());
    } catch (abort_requested_exception&) {
        throw request_aborted();
    }
```
so the original abort context is lost here too -- we rethrow custom `raft::request_aborted` with no arguments. Why we need this `raft::request_aborted`? Probably we can just remove the `try/catch` and allow the clients to observe the original `abort_requested_exception` with possible nested exception.

In [this patch](https://github.com/scylladb/seastar/pull/1088) the `request_abort_ex` method was added, which allows to pass an arbitrary exception to trigger. The problem is that the passed exception is rethrown 'as is' to the clients of `abort_source::check`, but most of them don't expect that. Like the code above, they expect specifically the `abort_requested_exception` as a signal of abort.

So, an idea:
* add an `std::exception_ptr original_exception` field into `abort_requested_exception`;
* in `request_abort_ex` wrap the passed exception with `abort_requested_exception`;
* in raft lib allow the `abort_requested_exception` to propagate, or copy the original exception to `raft:: request_aborted`;

The motivation for this comes from the need to add timeouts to raft operations. For example, `join_node_request_handler` calls  `start_operation` and then `read_barrier`. We want to add a timeout on top of `start_operation` call, e.g. 1 minute in production and one second in tests. Now we have two sources of abort - timer and shutdown (from `_group0_as`). To propagate the proper reason of the abort to the caller of `start_operation` we would need to wrap it with try/catch and check the timer again - if it's triggered we throw "tiemout expired..." + check if we lost the quorum, otherwise leave the abort as is or transform it to `stopped_exception` or something. This is awkward - we lose the abort reason inside `abort_source` and then recover it externally.

@kbr-scylla @gleb-cloudius @bhalevy Is the refactoring above worth it?

**Comment by kostja** [comment]
I like it.

**Comment by gleb-cloudius** [comment]
> A question about `abort_source`.
> 
> `abort_source` used to communicate aborted state through `abort_requested_exception` -- the `abort_source::request_abort` creates an instance of it with no arguments and `abort_source` clients get this exception when they call `abort_source::check`. The problem is that the reason of the abort is lost in this transition -- if there are multiple places in the code which call `request_abort()` we won't be able to tell which of them has triggered it.
> 
> This could be solved by enhancing `abort_requested_exception` with the `sstring reason` field or (probably better) with the nested exception `std::exception_ptr original_exception`. There is another problem though - `abort_source` has an `abort_requested()` method, and in some places we handle it like this
> 
> ```
> try {
>         co_await (as ? _tick_promise->get_shared_future(*as) : _tick_promise->get_shared_future());
>     } catch (abort_requested_exception&) {
>         throw request_aborted();
>     }
> ```
> 
> so the original abort context is lost here too -- we rethrow custom `raft::request_aborted` with no arguments. Why we need this `raft::request_aborted`? Probably we can just remove the `try/catch` and allow the clients to observe the original `abort_requested_exception` with possible nested exception.

Having only one type of abort thrown by a library makes life of its users easier. But there are disadvantages as well. They can be addresses by either inheriting `raft::request_aborted` from `abort_requested_exception` (still need to translate one to another here though) or throwing with nested here.

> 
> In [this patch](https://github.com/scylladb/seastar/pull/1088) the `request_abort_ex` method was added, which allows to pass an arbitrary exception to trigger. The problem is that the passed exception is rethrown 'as is' to the clients of `abort_source::check`, but most of them don't expect that. Like the code above, they expect specifically the `abort_requested_exception` as a signal of abort.
> 
> So, an idea:
> 
>     * add an `std::exception_ptr original_exception` field into `abort_requested_exception`;

Will throw with nested work?

> 
>     * in `request_abort_ex` wrap the passed exception with `abort_requested_exception`;
> 
>     * in raft lib allow the `abort_requested_exception` to propagate, or copy the original exception to `raft:: request_aborted`;
> 
> 
> The motivation for this comes from the need to add timeouts to raft operations. For example, `join_node_request_handler` calls `start_operation` and then `read_barrier`. We want to add a timeout on top of `start_operation` call, e.g. 1 minute in production and one second in tests. Now we have two sources of abort - timer and shutdown (from `_group0_as`). To propagate the proper reason of the abort to the caller of `start_operation` we would need to wrap it with try/catch and check the timer again - if it's triggered we throw "tiemout expired..." + check if we lost the quorum, otherwise leave the abort as is or transform it to `stopped_exception` or something. This is awkward - we lose the abort reason inside `abort_source` and then recover it externally.

I would run it through @avikivity since this requires changes to a low level seastar abstraction. It looks like you want to change `abort_source` from a simple notification mechanism to an information passing one.

**Comment by gusev-p** [comment]
> To propagate the proper reason of the abort to the caller of start_operation we would need to wrap it with try/catch and check the timer again - if it's triggered we throw "tiemout expired..." + check if we lost the quorum, otherwise leave the abort as is or transform it to stopped_exception or something. This is awkward - we lose the abort reason inside abort_source and then recover it externally.

In general, all invocations `some_op(abort_source& as)` with the same `as` should be `try/catch`-ed to restore the original reason of the abort.

**Comment by gusev-p** [comment]
@avikivity can you please give your opinion?

`abort_source`  doesn't preserve the reason of the abort, if there are many places in code which call `request_abort()` the caller of the aborted method doesn't have a direct way to distinguish them.

We can try/catch all the aborted call sites and restore the reason by rechecking the condition which triggered the abort, but this is clumsy - we need to wrap all call sites with lambdas and duplicate the abort condition check.

We can use the new `request_abort_ex` method, but:
* there is no method to extract the exception from the `abort_source`, only through subscriptions;
* in some places in Seastar (e.g. here https://github.com/scylladb/seastar/blob/master/include/seastar/core/abortable_fifo.hh#L229)  only the fact of the abort is communicated, with no way to extract the original reason. In `shared_future` (https://github.com/scylladb/seastar/blob/master/include/seastar/core/shared_future.hh#L133) the reason is lost when we rethrow with `std::make_exception_ptr(abort_requested_exception())`.

* do you consider this a problem?
* is it ok to add a method to extract exception from `abort_source`?
* is it ok to change `abortable_fifo.hh` and `shared_future.hh` (maybe something else) to retain the original abort reason?

**Comment by kbr-scylla** [comment]
> there is no method to extract the exception from the abort_source, only through subscriptions;

There is --- `check()`

**Comment by gusev-p** [comment]
> > there is no method to extract the exception from the abort_source, only through subscriptions;
> 
> There is --- `check()`

I mean direct access to exception_ptr without rethrow, for e.g. `co_return coroutine::exception`.

**Comment by gusev-p** [comment]
> @avikivity can you please give your opinion?
> 
> `abort_source` doesn't preserve the reason of the abort, if there are many places in code which call `request_abort()` the caller of the aborted method doesn't have a direct way to distinguish them.
> 
> We can try/catch all the aborted call sites and restore the reason by rechecking the condition which triggered the abort, but this is clumsy - we need to wrap all call sites with lambdas and duplicate the abort condition check.
> 
> We can use the new `request_abort_ex` method, but:
> 
> * there is no method to extract the exception from the `abort_source`, only through subscriptions;
> * in some places in Seastar (e.g. here https://github.com/scylladb/seastar/blob/master/include/seastar/core/abortable_fifo.hh#L229)  only the fact of the abort is communicated, with no way to extract the original reason. In `shared_future` (https://github.com/scylladb/seastar/blob/master/include/seastar/core/shared_future.hh#L133) the reason is lost when we rethrow with `std::make_exception_ptr(abort_requested_exception())`.
> 
> So
> 
> * do you consider this a problem?
> * is it ok to add a method to extract exception from `abort_source`?
> * is it ok to change `abortable_fifo.hh` and `shared_future.hh` (maybe something else) to retain the original abort reason?

@avikivity ping

**Comment by avikivity** [comment]
> @avikivity can you please give your opinion?
> 
> `abort_source` doesn't preserve the reason of the abort, if there are many places in code which call `request_abort()` the caller of the aborted method doesn't have a direct way to distinguish them.
> 
> We can try/catch all the aborted call sites and restore the reason by rechecking the condition which triggered the abort, but this is clumsy - we need to wrap all call sites with lambdas and duplicate the abort condition check.
> 
> We can use the new `request_abort_ex` method, but:
> 
> * there is no method to extract the exception from the `abort_source`, only through subscriptions;
> * in some places in Seastar (e.g. here https://github.com/scylladb/seastar/blob/master/include/seastar/core/abortable_fifo.hh#L229)  only the fact of the abort is communicated, with no way to extract the original reason. In `shared_future` (https://github.com/scylladb/seastar/blob/master/include/seastar/core/shared_future.hh#L133) the reason is lost when we rethrow with `std::make_exception_ptr(abort_requested_exception())`.
> 
> So
> 
> * do you consider this a problem?

yes, likely it predates the ability of abort_source to customize the exception.

> * is it ok to add a method to extract exception from `abort_source`?

I think the correct approach is to pass the exception to the OnAbort callback.

> * is it ok to change `abortable_fifo.hh` and `shared_future.hh` (maybe something else) to retain the original abort reason?

I believe abort_source is a mistake. There end up too many sources of events: timeouts, aborts, and the original events needed by the application. We have to navigate the constraints of the API, and extending it is difficult.

I think the correct approach is condition_variable. You can add as many conditions you want to exit the loop. abortable_fifo ends up being just some std container you choose, and you have complete freedom everywhere. It takes a few more lines of code, but only a few. With coroutines it's likely also faster.
