### ISSUE TITLE
Commitlog replay might resurrect data after tablet cleanup post migration

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#16752]
After https://github.com/scylladb/scylladb/pull/15524 tablet storage is cleaned up after migration,
however there is no protection against commitlog replay that might resurrect data previously written to this tablet replica upon restart.

As discussed in https://github.com/scylladb/scylladb/issues/4734#issuecomment-1883144058,
we're contemplating a solution based on extending system.truncated to include token-range records and filter those out on replay.

See https://github.com/scylladb/scylladb/pull/15524 for initial implementation of `table::cleanup_tablet`, `compaction_group::cleanup`, etc.

**Comment by bhalevy** [comment]
Cc @elcallio @tgrabiec

**Comment by michoecho** [comment]
I started working on a solution based on a new system table, similar to `system.truncated`, but with different replay positions for different token ranges.

@bhalevy The reason why I went with a new table instead of extending `system.truncated` is that the extension would require appending new clustering key columns to an existing table, and I don't know if that's sane, or even doable at all. Is it?

**Comment by michoecho** [comment]
@bhalevy Also, you mentioned backup/restore in a conversation today, but it went over my head, because I don't see the connection. How does backup/restore tie into this at all?

**Comment by bhalevy** [comment]
> @bhalevy Also, you mentioned backup/restore in a conversation today, but it went over my head, because I don't see the connection. How does backup/restore tie into this at all?

I was thinking of restore of the new system table, but rethinking about this, it is indeed not an issue because in the restore case the commitlogs are currently lost.  Only if we back up the commitlog as well and use it to replay in restore then we'll need to also backup and restore the system.commitlog_cleanups table as well.
