### ISSUE TITLE
enable scylla to read sstables containing unowned keys

### ISSUE THREAD

**Issue by tchaikov** [scylladb/scylladb#16825]
`sstable_set::make_local_shard_sstable_reader()` is supposed to filter out keys which don’t belong to local shard, but this is implicitly guaranteed by the fact that we attach only resharded sstables. With tablet splitting and migration, a read may need to access an sstable which contains no longer owned keys.

**Comment by tchaikov** [comment]
while reading the history of the function of `sstable_set::make_local_shard_sstable_reader()`, i noticed the commit of ab9d08d80edb91a95fef68db10fbc82345c60198. after which, we don't filter the mutation stream anymore. the filtering reader is still used when, for instance, performing repair. i think it is for feeding the remote with the mutations expected by the peer. but in the case of `sstable_set::make_local_shard_sstable_reader()`, it only reads the sstables in the `sstable_set` without filtering.

**Comment by denesb** [comment]
Yes, historically this method used to do filtering, in the age of shared-sstables (between shards). This was dropped as we made resharding part of the node startup procedure, and thus guaranteeing that sstables belong to a single shard at all times.
We need to restore this filtering, but conditionally. The caller should detect that there is a split/migration in process and pass down a filter such that the reader will only return owned keys.

**Comment by tchaikov** [comment]
@denesb hi Botond, thank you for your reply. by restoring the filtering, do you mean we are not going to reshard when loading sstables ? or do we use a different strategy to dispatch sstables in, presumably `distributed_loader` ?

**Comment by denesb** [comment]
I don't know, under what exact conditions we will have shared sstables. I also thought we wouldn't.

**Comment by bhalevy** [comment]
Cc @raphaelsc 

I believe this isn't necessary since during splitting (split preparation stage), all sstables in the storage_group, including those that aren't split yet, are still owned and served by the same shard, so there is no need to filter anything by shard.
When splitting is applied, we will split the storage_group into two, where each one will contain either the left or right compaction_groups and the sstables token ranges will be confined to each storage_group, so again, there would be no need to filter.

I think we can close this issue as not planned.
