### ISSUE TITLE
!ERR [shard 0:strm] storage_service - raft topology: CDC generation publisher fiber got error std::runtime_error (value is null)

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#16916]
While running perf_regression_latency_mixed_with_nemesis (with tablets)
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/pavel/job/perf-regression-latency-650gb-grow-shrink/5/consoleText
db-cluster logs: https://cloudius-jenkins-test.s3.amazonaws.com/4ff296a8-39da-4ca0-8093-a043c5d1e1f8/20240120_181410/db-cluster-4ff296a8.tar.gz

The pytest failed after meeting the subj message in db-cluster-4ff296a8/perf-latency-grow-shrink-ubuntu-db-node-4ff296a8-1/messages-scylla.log . In fact, there's tons of such messages in there

**Comment by patjed41** [comment]
I investigated it. It's a bug in the cleaning of `cdc_generation_v3` which is done by the topology coordinator (more specifically, the CDC generation publisher fiber). `system_keyspace::get_cdc_generations_cleanup_candidate` doesn't handle the null tuple value properly. The fix is simple.

There is also a test for the cleaning of `cdc_generation_v3` -- `topology_experimental_raft/test_cdc_generation_clearing.py` -- which should be strengthened, so that it doesn't fail only after the fix.

For now, I'd prefer not to send a direct fix for this issue. I've just opened #17184, which requires major changes in the cleaning of `cdc_generation_v3`. The bug won't be present after fixing #17184 as a side effect. Moreover, `test_cdc_generation_clearing.py` is a white box test. It will be basically rewritten in a fix #17184. Strengthening it now would be basically reverted.
