### ISSUE TITLE
compaction_manager::perform_sstable_scrub(): doesn't take the compaction gate

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#16997]
This could lead to use-after-free if the table is dropped while the scrub is running.
We have seen a similar issue for cleanup: https://github.com/scylladb/scylladb/issues/16770

I think the only reason we didn't hit this yet is because scrub is rarely used.

**Comment by raphaelsc** [comment]
perform_sstable_scrub() -> rewrite_sstables() -> perform_task_on_all_files() -> start_compaction(). the latter returns a gate, which is held throughout scrub lifetime. so I think this issue is invalid

**Comment by denesb** [comment]
Thanks @raphaelsc, closing.

**Comment by ndragazis** [comment]
Adding some more context for clarity:

The compaction manager maintains a compaction state object per table in the `_compaction_states` map. Whenever a function needs to access the compaction state (i.e., calls `get_compaction_state()`), it needs to hold the compaction gate. The compaction manager relies on this convention to decide when to remove a compaction state in `compaction_manager::remove()`.

`perform_sstable_scrub()` doesn't need to hold the gate because it doesn't use the compaction state.

**Comment by raphaelsc** [comment]
> Adding some more context for clarity:
> 
> The compaction manager maintains a compaction state object per table in the `_compaction_states` map. Whenever a function needs to access the compaction state (i.e., calls `get_compaction_state()`), it needs to hold the compaction gate. The compaction manager relies on this convention to decide when to remove a compaction state in `compaction_manager::remove()`.
> 
> `perform_sstable_scrub()` doesn't need to hold the gate because it doesn't use the compaction state.

actually it's important that it holds the gate, to synchronize with table drop / tablet migration / shutdown / whatever wants to stop scrub. otherwise, you're at risk of use-after-free. and perform-sstable_scrub eventually holds the gate in perform_task_on_all_files(), before reaching any preemption point.

**Comment by raphaelsc** [comment]
FWIW, in seastar context, preemption point means a point in which a task may give up the cpu to the seastar reactor after waiting on a future.
