### ISSUE TITLE
This mintimeuuid() call crashes ScyllaDB.

### ISSUE THREAD

**Issue by scripturial** [scylladb/scylladb#17035]
*Installation details*
Scylla version (or git commit hash): ScyllaDB/scylla:latest 
Cluster size: 1 docker node
OS (RHEL/CentOS/Ubuntu/AWS AMI): docker
Platform (physical/VM/cloud instance type/docker): docker

Here is a minimum working sample of a rust project that crashes ScyllaDB. It is the very last lines that cause the crash:

[Archive.zip](https://github.com/scylladb/scylladb/files/14082572/Archive.zip)

I stumbled across this as I was having trouble passing a bigint into the mintimeuuid() function. After updating to the latest (as a few days ago) in docker, that problem went away but the odd (and incorrect presumably) mintimeuuid(totimestamp(?))  workaround I was trying is casing a disconnect/crash of some sort.

<img width="965" alt="image" src="https://github.com/scylladb/scylladb/assets/138373494/3daaf8c0-3fa1-4fbe-8fdd-e823ff16eb03">

**Comment by mykaul** [comment]
Thanks @scripturial - can you please share the Scylla node logs, so we can observe the crash?

**Comment by mykaul** [comment]
Maybe related to https://github.com/scylladb/scylladb/issues/14319

**Comment by nyh** [comment]
Which version of Scylla did you reproduce this issue on? If I understand correctly from @denesb it didn't reproduce for him on the current master. I'll write a test for this and see if I can reproduce it on an older version (and see if we forgot to backport some fix, although at the moment I can't recall what).

Just one question: `totimestamp()` is supposed to convert a **timeuuid** to a timestamp. What are you trying to do when you're passing it a number 50000000000000?

**Comment by denesb** [comment]
Also, please add the schema of this table. I only guessed what it is, maybe we need a specific schema (and data) to reproduce?

**Comment by nyh** [comment]
> Also, please add the schema of this table. I only guessed what it is, maybe we need a specific schema (and data) to reproduce?

He has in the rust code he attached
```
CREATE KEYSPACE tk WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
create type log_field (field text, value text)
create table  if not exists system_log (timeblock bigint, recorded timeuuid, level tinyint, ip text, person text, event text, fields list<frozen<log_field>>, primary key ((timeblock), recorded)) with clustering order by (recorded desc)
```

**Comment by nyh** [comment]
I can reproduce this bug easily on master. Yet another terrible use of assert (https://github.com/scylladb/scylladb/issues/7871, see also https://github.com/scylladb/scylladb/issues/13970) . Here's an adhoc reproducing test in the context of test/cql-pytest/test_native_functions:

```python
def test_17035(cql, table1):
    p = unique_key_int()
    cql.execute(f"INSERT INTO {table1} (p, u) VALUES ({p}, now())")
    print(cql.execute(f"SELECT * FROM {table1} WHERE p={p} and u < mintimeuuid(totimestamp(50000000000000000))"))
```

Crashes Scylla with:
```
test_scylla: utils/UUID_gen.hh:383: static int64_t utils::UUID_gen::create_time(std::chrono::duration<int64_t, std::ratio<N, D>>) [N = 1L, D = 10000000L]: Assertion `!(0xf000000000000000UL & msb)' failed.
```

**Comment by nyh** [comment]
By the way, I just realized what totimestamp(50000000000000000) means.
I was wrong saying that totimestamp expects only a timeuuid - it also accepts a `date` type. And according to https://cassandra.apache.org/doc/stable/cassandra/cql/types.html date can be initialized with an integer, and

> Values of the date type are encoded as 32-bit unsigned integers representing a number of days with “the epoch” at the center of the range (2^31). Epoch is January 1st, 1970

So both 123 and 50000000000000000 are outside the sensible range for this: The number 123 is before the epoch, and 50000000000000000 is more than 32 bits. So there is no reason why these requests should work. They shouldn't crash, obviously, but it shouldn't have worked either. So @scripturial I'm still wondering what you're trying to do in your application.

**Comment by nyh** [comment]
It turns out that both dates 123 (before the epoch, for reasons explained above) and 50000000000000000 are wrapped into a **negative** timestamp, and our UUID_get.hh `create_time()` fails an assertion when getting a negative number. The immediate fix should be easy (hopefully) - we already call a function is_valid_unix_timestamp() to check if a timestamp is outside the valid range, and it was missing a check for negative timestamps.

**Comment by nyh** [comment]
Sent a pull request to fix this crash - https://github.com/scylladb/scylladb/pull/17073.

As I noted above, this is a benign error-path bug which turned into a major bug because of use of assert() turned an error message into a crash. But @scripturial, it was still an error for you to use mintimeuuid(totimestamp(50000000000000000)), and after my patch it also won't work - but it will no longer crash Scylla.

Let me explain: The function totimestamp, when given a number, assumes it is a "date", i.e., a **day** number where 2147483648 is the UNIX epoch (Jan 1st 1970) - yes, weird, I know. So 50000000000000000 means 136 trillion years after the UNIX epoch. I also gets wrapped around and becomes, by chance, a very high negative number - and that caused the assertion failure.

Anyway, I don't think you wanted to use `totimestamp()` at all... You probably just wanted to call mintimeuuid() on something which was already a timestamp, you don't need to convert it *to* a timestamp. Just watch out that the "timestamp" type measures time since the epoch in **milliseconds** - this is different from CQL's "USING TIMESTAMP" which uses microseconds, or other notions of timestamps you might have, so watch out. The number you used, 50000000000000000, also doesn't make sense as a timestamp value, because 50000000000000000 milliseconds since the epoch is the year 1587459 ;-)

**Comment by scripturial** [comment]
Thanks everyone, to be clear, I solved my original problem, but discovered this crash/panic in the process. So I am not intending to report that I am now experiencing a problem, but I am only meaning to report that there is a type of query that causes a crash.

For context, what happened was, I was porting (pretty much line by line) from my go / gocql app across to rust /scylladb, and my query that was passing an integer value into `mintimeuuid()` was causing a panic.  I only attempted `mintimeuuid(to timestamp())` because the cql documentation implied it was an alternative option, and I wanted to see if that would fix the crash/panic I was having.

With regard to the size of the number, I was unsure if the function expected seconds or milliseconds, so I was just poking around trying different numbers. The number in the sample code was just randomly chosen to demonstrate the panic.

Sadly (well happily) my rust code now works how I would expect it when I pass an integer and I am confused about why, but well it works so I am not going to complain.

Thank you all for all the work you have done on this, I am definitely enjoying my venture into rust/scylladb, for the most part it has been an awesome experience.

**Comment by mykaul** [comment]
@nyh - I think it's worth backporting.

**Comment by nyh** [comment]
> @nyh - I think it's worth backporting.

I agree, and will do it now.

**Comment by nyh** [comment]
Backported to next-5.4 (62d8c7274ab6353eb60fbb00098be57097a015cd), next-5.2 (94af1df2cf2f5b6e75c3ff5bc59d1a1c958e1380). So removing backport candidate label.

The backports had easy - but NOT empty - conflicts. I'm thinking about this in the context of starting to do backports automatically. Nevertheless, it would have helped me if the automation created the branch for me, let me fix it, and when I pushed the fix it would do all the compilation and testing for me. That is the part that takes 99% of the time and effort and brain-damage (!) when I do backports manually like I did now.
