### ISSUE TITLE
Alternator/executor: not found mutation write info/error  log level

### ISSUE THREAD

**Issue by qiuqiu-007** [scylladb/scylladb#17157]
When there is an update_item failed we couldn't find an info or error log in scylla, but found mutation_write_time_out_exception in other subsystem. 

- Just found debug exception and trace log level in code？
- Why there is error info in response, not print in log instead ？

Is there any potential problem to set this log to info or error level?

**Comment by nyh** [comment]
In general, when an API request fails, the failure should be returned to the caller - not logged in some log that the caller has no access to and where it's hard to correlate an error to a specific request. For example, if a request has some syntax error or something, there is no benefit in logging it.

What might perhaps make sense is to log (as warning level?) every instance of InternalServerError (HTTP error code 500) we generate. These errors include outright bugs that should definitely be logged (e.g., unexpected exception thrown during the request processing) and as you noticed - timeouts. Some of these things already have their own log messages but I guess you wanted to see a separate log message coming from the Alternator-specific logger? Is this what you're asking for in this issue? If not, what are you asking to happen?

There is some risk in adding more log messages: excessive log messages due to errors can cause an "avalanche" of errors - e.g., imagine that Alternator is overloaded causing timeouts. So we start logging all those timeout messages - and now Alternator is even more overloaded and causing even more timeouts and log messages, and ... you get the idea. The risk of this is minimal if we already have log messages in thus we at worst double the log messages and not cause a new problem.
