### ISSUE TITLE
raft topology: get rid of IP mappings dependency where they may be unobtainable

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#17169]
I noticed there are still some places in raft-topology code where we depend on IP mapping to be present and error out, but in general, it may not be present.

We need to review the code to find such places, write a test case showing a scenario in which IP mapping may not be possible to obtain (if we cannot come up with a scenario, we don't need to touch this place), and fix.

Currently I'm aware of two
```cpp
                                    // FIXME: we should not need to translate ids to IPs here. See #6403.
                                    std::unordered_set<gms::inet_address> ignored_ips;
                                    for (const auto& id : std::get<replace_param>(_topology_state_machine._topology.req_param[raft_server.id()]).ignored_ids) {
                                        auto ip = _group0->address_map().find(id);
                                        if (!ip) {
                                            on_fatal_internal_error(rtlogger, ::format("Cannot find a mapping from node id {} to its ip", id));
                                        }
                                        ignored_ips.insert(*ip);
                                    }
                                    co_await _repair.local().replace_with_repair(get_token_metadata_ptr(), rs.ring.value().tokens, std::move(ignored_ips));

```

and
```cpp
                                // FIXME: we should not need to translate ids to IPs here. See #6403.
                                std::list<gms::inet_address> ignored_ips;
                                for (const auto& ignored_id : std::get<removenode_param>(_topology_state_machine._topology.req_param[id]).ignored_ids) {
                                    auto ip = _group0->address_map().find(ignored_id);
                                    if (!ip) {
                                        on_fatal_internal_error(rtlogger, ::format("Cannot find a mapping from node id {} to its ip", ignored_id));
                                    }
                                    ignored_ips.push_back(*ip);
                                }
                                auto ops = seastar::make_shared<node_ops_info>(node_ops_id::create_random_id(), as, std::move(ignored_ips));
                                return _repair.local().removenode_with_repair(get_token_metadata_ptr(), *ip, ops);
```

They are similar, they are trying to obtain translations of ignored nodes.

I looked how hard it would be to fix the replace one, it shouldn't be hard. The code is obtaining a list of replicas from replication strategy as IP addresses and then filtering out the ignored ones. We can modify the code to work on host IDs easily (replication strategy already provides the interfaces after @gusev-p changes).

cc @gleb-cloudius

**Comment by kbr-scylla** [comment]
Perhaps not a blocker, as @gleb-cloudius said:

> While I agree we should get rid of those I do not see why we would not have the mapping since ignored nodes are still part of the cluster and other nodes should gossip their info. When a node moved to left state we remove it from ignored nodes list.

**Comment by kbr-scylla** [comment]
The only thing to do here is to review the code.

**Comment by kbr-scylla** [comment]
> While I agree we should get rid of those I do not see why we would not have the mapping since ignored nodes are still part of the cluster and other nodes should gossip their info. When a node moved to left state we remove it from ignored nodes list.


One thing I'm worried about here: won't we lose the mapping if we do a full cluster shutdown -> restart of the remaining nodes. Or will mappings be restored from `system.peers`

we need to verify this. If so, we should fix the code to work on host IDs

**Comment by margdoc** [comment]
> One thing I'm worried about here: won't we lose the mapping if we do a full cluster shutdown -> restart of the remaining nodes. Or will mappings be restored from system.peers

> we need to verify this. If so, we should fix the code to work on host IDs

Scylla passes the following test (with `consistent-topology-changes`):
```py
@pytest.mark.asyncio
async def test_remove_node(manager: ManagerClient):
    servers = await manager.servers_add(5)

    await manager.servers_see_each_other(servers)

    for server in servers:
        await manager.server_stop(server.server_id)

    for server in servers[:-1]:
        await manager.server_start(server.server_id)

    await manager.servers_see_each_other(servers[:-1])

    await manager.remove_node(servers[0].server_id, servers[-1].server_id)
```

In `main.cc` I found the following code:
```cpp
// Load address_map from system.peers and subscribe to gossiper events to keep it updated.
ss.local().init_address_map(raft_address_map.local(), generation_number).get();
```

Thus full cluster shutdown won't break the address map.

**Comment by margdoc** [comment]
Let’s introduce some properties:
* Known IP addresses are propagated by gossip
* When a node joins the cluster, all nodes need to do “wait_for_ip” for each joining node (wait for the IP address of this node to be available, i.e. is received by gossip) (raft_topology_cmd::command::wait_for_ip)
```cpp
// When the validation succeeded, it's important that all nodes in the
// cluster are aware of the IP address of the new node before we proceed to
// the topology::transition_state::join_group0 state, since in this state
 // node IPs are already used to populate pending nodes in erm.
// This applies both to new and replacing nodes.
// If the wait_for_ip is unsuccessful, we should inform the new
// node about this failure.
// If the validation doesn't pass, we only need to call wait_for_ip on the current node,
// so that we can communicate the failure of the join request directly to
// the joining node.
```
* When a node is restarted, it loads host ID -> IP mapping from the system.peers (storage_service::init_address_map) 
* IP mapping is removed from the raft_address_map only when a node leaves the cluster (remove node / decommission). The only way to remove this mapping is by calling raft_address_map::set_expiring(raft::server_id) (storage_service::sync_raft_topology_nodes::process_left_node: _group0->modifiable_address_map().set_expiring(id); and raft::server_impl::process_fsm_output: _rpc->on_configuration_change({}, rpc_diff.leaving);)
* (I) When a node is in the normal state (service::node_state::normal) its IP address is known to other nodes (even if it is dead)
* (II) When a node is being replaced it is still a member of a cluster (state = service::node_state::normal)
* (III) When a node is considered dead (topology::ignored_nodes) it is still a member of a cluster (state = service::node_state::normal)
* (IV) When a node is being removed from a cluster it is still a member of a cluster (state = service::node_state::normal)

Cases when a fatal internal error happens if there is no host ID -> IP mapping:
1. storage_service::sync_raft_topology_nodes::process_transition_node::case node_state::replacing:
```cpp
on_fatal_internal_error(rtlogger, ::format("Cannot map id of a node being replaced {} to its ip", replaced_id));
```
- From (I) and (II) it cannot happen
2. storage_service::raft_removenode:
```cpp
on_fatal_internal_error(rtlogger, ::format("Remove node cannot find a mapping from node id {} to its ip", id));
```
- From (I) and (IV) it cannot happen
3. storage_service::raft_topology_cmd_handler::case raft_topology_cmd::command::stream_ranges::case node_state::replacing:
```cpp
for (const auto& id : _topology_state_machine._topology.ignored_nodes) {
  auto ip = _group0->address_map().find(id);
  if (!ip) {
      on_fatal_internal_error(rtlogger, ::format("Cannot find a mapping from node id {} to its ip", id));
  }
  ignored_ips.insert(*ip);
}
```
- From (I) and (III) it cannot happen
```cpp
auto existing_ip = _group0->address_map().find(replaced_id);
assert(existing_ip);
```
- From (I) and (II) it cannot happen
4. storage_service::raft_topology_cmd_handler::case raft_topology_cmd::command::stream_ranges::case node_state::normal:
```cpp
// If asked to stream a node in normal state it means that remove operation is running
// Find the node that is been removed
[...]
auto ip = am.find(id); // map node id to ip
assert (ip); // what to do if address is unknown?
```
- From (I) and (IV) it cannot happen
```cpp
for (const auto& ignored_id : _topology_state_machine._topology.ignored_nodes) {
  auto ip = _group0->address_map().find(ignored_id);
  if (!ip) {
    on_fatal_internal_error(rtlogger, ::format("Cannot find a mapping from node id {} to its ip", ignored_id));
  }
  ignored_ips.push_back(*ip);
}
```
- From (I) and (III) it cannot happen



-------------------


For now, the only concern is what would happen in the following scenario:
- setup one node cluster
- start bootstrapping the second node
- stop all nodes just before the first node saves the IP address of the second node (storage_service::sync_raft_topology_nodes::process_transition_node)
- restart the first node
- do some operations, e.g. create a table and do some writes
I will investigate what can happen here

**Comment by mykaul** [comment]
@margdoc , @kbr-scylla - do we still consider this to be a blocker for 6.0?

**Comment by kbr-scylla** [comment]
Yes. After @margdoc posts our latest findings documenting and confirming that there is nothing critical that should block us from releasing, then I will close the issue.

**Comment by kbr-scylla** [comment]
In the end the analysis spawned two concrete issues:
- https://github.com/scylladb/scylladb/issues/18676 -- this one looks like a blocker for now, but we'll need to dig a bit deeper to understand the consequences
- https://github.com/scylladb/scylladb/issues/18682 -- this one is unimportant

This task can be considered closed.
