### ISSUE TITLE
storage_service/range_to_endpoint_map does not work with tablets

### ISSUE THREAD

**Issue by pwrobelse** [scylladb/scylladb#17343]
```
$ curl -X GET "http://127.0.0.1:10000/storage_service/range_to_endpoint_map/testing"
{"message": "seastar::internal::backtraced<std::runtime_error> (Tried to obtain per-keyspace effective replication map of testing but it's per-table", "code": 500}
```

The issue is related to usage of `keyspace::get_vnode_effective_replication_map()` in `storage_service::get_range_to_address_map()`. It throws the exception when tablets are enabled.

**Comment by bhalevy** [comment]
@denesb / @tgrabiec do we need this api to work with tablets or is the current error ok?

**Comment by bhalevy** [comment]
@pwrobelse please add unit test for this and similar apis in test/rest_api/storage_service.py to make sure scylla doesn't break when invoking these api with tablets keyspaces.
Fow now let's expect an error to be returned.
We can change that later on if and when we modify those api(s) to support tablets.

cc @denesb unless someone else already working on this?

**Comment by bhalevy** [comment]
Depends on #17338

**Comment by denesb** [comment]
> Depends on #17338

I think some of the tests therein are braking exactly because they are trying to access get_vnode_effective_replication_map with a tablets keyspace.

**Comment by bhalevy** [comment]
We can add a "cf" parameter to query ranges for a specific table (that may be useful along with pausing load-balancing)
and keep the error if only the keyspace is given and it is tablet based.

It would be best if we catch the above exception and translate it to something more user friendly, since the user doesn't care that we have an internal effective_replication_map.
We should return an error saying that the range_to_endpoint_map is per-table in the queried keyspace and the user must provide the table name using the "cf" parameter (I'm using "cf" since it is the convention in the api, not because I like it)

**Comment by pwrobelse** [comment]
> We can add a "cf" parameter to query ranges for a specific table (that may be useful along with pausing load-balancing) and keep the error if only the keyspace is given and it is tablet based.
> 
> It would be best if we catch the above exception and translate it to something more user friendly, since the user doesn't care that we have an internal effective_replication_map. We should return an error saying that the range_to_endpoint_map is per-table in the queried keyspace and the user must provide the table name using the "cf" parameter (I'm using "cf" since it is the convention in the api, not because I like it)

Hi @bhalevy, I implemented the logic in the code according to your comment. Also, I created the tests that verify it. The results of manual execution of them was attached to the PR.

I can be found here: https://github.com/scylladb/scylladb/pull/17372
