### ISSUE TITLE
[Raft topology] killing node while another node is decommissioning may not fail the decommissioning process

### ISSUE THREAD

**Issue by temichus** [scylladb/scylladb#17403]
Dtest: test_simple_kill_remained_node_while_decommissioning

      Test a decommissioning node killed is able to rejoin the cluster with data
        1. Create a cluster with a three nodes with rf=1, insert data
        2. Decommission a node
        3. While node is decommissioning kill another one
        4. Boot the node back up
        5. Check that the node rejoins the cluster and works correctly
        
        
 In raft topology mode, the decommissioning process can be replayed  sometimes after steps 3-4(if the node is back quite fast)  and finished successfully 
```
INFO  2024-02-16 18:12:42,857 [shard 0:strm] raft_topology - start streaming
INFO  2024-02-16 18:12:42,857 [shard 0:strm] storage_service - Started batchlog replay for decommission
INFO  2024-02-16 18:12:42,857 [shard 0:strm] storage_service - Finished batchlog replay for decommission
INFO  2024-02-16 18:12:42,857 [shard 0:strm] storage_service - enable_repair_based_node_ops=true, allowed_repair_based_node_ops={decommission ,bootstrap ,rebuild ,removenode ,replace}
INFO  2024-02-16 18:12:42,857 [shard 0:strm] repair - decommission_with_repair: started with keyspaces={system_distributed_everywhere, system_auth, ks, system_traces, system_distributed}, leaving_node=127.0.41.2, ignore_nodes={}
INFO  2024-02-16 18:12:42,857 [shard 0:strm] repair - decommission_with_repair: started with keyspace=system_distributed_everywhere, leaving_node=127.0.41.2, nr_ranges=769
INFO  2024-02-16 18:12:42,858 [shard 0:strm] repair - decommission_with_repair: keyspace=system_distributed_everywhere, range=(-inf, -9172516513831537752], current_replica_endpoints={127.0.41.3, 127.0.41.1, 127.0.41.2}, new_replica_endpoints={127.0.41.3, 127.0.41.1}, neighbors={127.0.41.3}, mandatory_neighbor={}
INFO  2024-02-16 18:12:42,858 [shard 0:strm] repair - decommission_with_repair: keyspace=system_distributed_everywhere, range=(-9172516513831537752,-9133532888713331881], current_replica_endpoints={127.0.41.3, 127.0.41.1, 127.0.41.2}, new_replica_endpoints={127.0.41.3, 127.0.41.1}, neighbors={127.0.41.3}, mandatory_neighbor={}
...

INFO  2024-02-16 18:12:49,247 [shard 1:strm] repair - repair[7a3eff76-6350-47e7-bbf6-0214ac773513]: completed successfully, keyspace=system_distributed
INFO  2024-02-16 18:12:49,248 [shard 0:strm] repair - repair[7a3eff76-6350-47e7-bbf6-0214ac773513]: completed successfully
INFO  2024-02-16 18:12:49,248 [shard 0:strm] repair - repair[7a3eff76-6350-47e7-bbf6-0214ac773513]: sync data for keyspace=system_distributed, status=succeeded
INFO  2024-02-16 18:12:49,248 [shard 0:strm] repair - decommission_with_repair: finished with keyspace=system_distributed, leaving_node=127.0.41.2, nr_ranges=3076, nr_ranges_synced=769, nr_ranges_skipped=0
INFO  2024-02-16 18:12:49,248 [shard 0:strm] repair - decommission_with_repair: finished with keyspaces={system_distributed_everywhere, system_auth, ks, system_traces, system_distributed}, leaving_node=127.0.41.2
INFO  2024-02-16 18:12:49,248 [shard 0:strm] raft_topology - streaming completed
```

This behaviour reproduced in 12 test runs of 500 

logs:
[1708107289859_update_cluster_layout_tests.py__TestUpdateClusterLayout__test_simple_kill_remained_node_while_decommissioning[2].zip](https://github.com/scylladb/scylladb/files/14334087/1708107289859_update_cluster_layout_tests.py__TestUpdateClusterLayout__test_simple_kill_remained_node_while_decommissioning.2.zip)

test error:
```
        # When node1 stops, the decommission of node2 will fail. We should not
        # test node2 is still in UL here. Test node2 is in either UL or UN.
>       wait_for_nodes_status(node3, [["UN", "UL", "UN"], ["UN", "UN", "UN"]])

AssertionError: found statuses: ['UN', 'UN']
``` 

test code: 
https://github.com/scylladb/scylla-dtest/blob/c1241aa08819e479751cbde833f6cf06b94a7a60/update_cluster_layout_tests.py#L1075

**Comment by kbr-scylla** [comment]
So this dtest expects that shutting down some node when another node is decommissioning will interrupt the decommission operation.

However in raft-topology mode it may sometimes happen (but not always) that the operation will resume and succeed. This happens if the node we kill is the coordinator, and without it there is no quorum to select another coordinator, so when it restarts, it may become the coordinator again, not notice that anything was wrong because it simply observes the `write_both_read_old` state and proceeds.

One could argue that this is a regression, not an improvement, because it was a working method to cancel a decommission, even enshrined by a dtest, but we now made it unreliable, it may or may not work. 

@gleb-cloudius @kostja @avikivity WDYT?

If we consider it a regression, we can "fix" Scylla so it does not retry such a failed decommission. (We just need to get rid of `retrier` in `raft_topology_cmd_handler` IIUC).

If not, we can adjust the test to allow the decommission to finish, although the dtest stops serving its initial purpose. So there's no reason to keep it.

**Comment by kostja** [comment]
I don't think it's a regression, but the test needs to be stabilized with the new topology coordinator - please let the test restore the majority so that the operation can always succeed.

**Comment by kbr-scylla** [comment]
> I don't think it's a regression, but the test needs to be stabilized with the new topology coordinator - please let the test restore the majority so that the operation can always succeed.

The operation is supposed to fail in this test, not succeed.

**Comment by kbr-scylla** [comment]
> Depending on where the killing of the node happens

In the middle of streaming

**Comment by gleb-cloudius** [comment]
> > Depending on where the killing of the node happens
> 
> In the middle of streaming

In the test. But we are talking about a user expected behaviour and user may kill it before streaming and then retrier removal will not help. Or is the goal is to make the test happy?

**Comment by kbr-scylla** [comment]
> I think we need saner way to cancel operation then killing random nodes.

At the same time, we want to release ASAP.
I created https://github.com/scylladb/scylladb/issues/17514 but I put 6.1 milestone on it.

@temichus I believe there is a way to make the test work in raft-topology mode, cancelling the decommission operation by killing node 1 as before. But we need to modify the test to wait until decommission actually fails before restarting node 1.

So the test flow in raft-topology mode would be as follows:
- kill node 1 during streaming (as it already does)
- wait for decommission to fail
- only then restart node 1
- check statuses

How to wait for decommission to fail? I think we can do it by waiting for the following statuses: [DN, UN, UN]. Because I believe that during decommission, node 2 is in state UL (please verify that this is still true in raft-topology mode.) And since we kill node 1, it will be DN. So if we see [DN, UN, UN], it means that decommission got canceled and rolled back.

Then we can restart node 1 and wait for [UN UN UN] as the test did before.

@temichus please check if this way works.

**Comment by temichus** [comment]
> > I think we need saner way to cancel operation then killing random nodes.
> 
> At the same time, we want to release ASAP. I created #17514 but I put 6.1 milestone on it.
> 
> @temichus I believe there is a way to make the test work in raft-topology mode, cancelling the decommission operation by killing node 1 as before. But we need to modify the test to wait until decommission actually fails before restarting node 1.
> 
> So the test flow in raft-topology mode would be as follows:
> 
> * kill node 1 during streaming (as it already does)
> * wait for decommission to fail
> * only then restart node 1
> * check statuses
> 
> How to wait for decommission to fail? I think we can do it by waiting for the following statuses: [DN, UN, UN]. Because I believe that during decommission, node 2 is in state UL (please verify that this is still true in raft-topology mode.) And since we kill node 1, it will be DN. So if we see [DN, UN, UN], it means that decommission got canceled and rolled back.
> 
> Then we can restart node 1 and wait for [UN UN UN] as the test did before.
> 
> @temichus please check if this way works.

@kbr-scylla I've created PR https://github.com/scylladb/scylla-dtest/pull/3991
