### ISSUE TITLE
raft topology: replace-with-same-IP failure in test: `attempt to send acceptance response to ... failed`

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#17515]
Observed failure in test `test_replace::test_replace_reuse_ip_using_host_id`

test was trying to perform replace-with-same-IP
```python3
    async def test_replace_reuse_ip_using_host_id(manager: ManagerClient) -> None:
        """Replace an existing node with new node using the same IP address and same host id"""
        servers = await manager.servers_add(3, config={'failure_detector_timeout_in_ms': 2000})
        await manager.server_stop(servers[0].server_id)
        replace_cfg = ReplaceConfig(replaced_id = servers[0].server_id, reuse_ip_addr = True, use_host_id = True)
>       await manager.server_add(replace_cfg)
```
and timed out

failure in test.py logs looks as follows:
```
22:08:30.847 ERROR> [dev/topology_custom.test_replace.1] Failed to start Scylla server at host 127.196.104.38 in scylla-1134: failed to start the node, timeout reached, server_id 1134, IP 127.196.104.38, workdir scylla-1134, host_id 56d62aed-72fd-4fde-9dd7-6e81d1c5176f, cql [not connected]
Check the log files:
/scylladir/testlog/x86_64/test.py.debug-release-dev.log
/scylladir/testlog/x86_64/dev/scylla-1134.log
22:08:30.848 ERROR> [dev/topology_custom.test_replace.1] Exception when executing _cluster_server_add: failed to start the node, timeout reached, server_id 1134, IP 127.196.104.38, workdir scylla-1134, host_id 56d62aed-72fd-4fde-9dd7-6e81d1c5176f, cql [not connected]
Check the log files:
/scylladir/testlog/x86_64/test.py.debug-release-dev.log
/scylladir/testlog/x86_64/dev/scylla-1134.log
Traceback (most recent call last):
  File "/jenkins/workspace/scylla-master/next/scylla/test/pylib/scylla_cluster.py", line 1143, in catching_handler
    ret = await handler(request)
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/jenkins/workspace/scylla-master/next/scylla/test/pylib/scylla_cluster.py", line 1291, in _cluster_server_add
    s_info = await self.cluster.add_server(replace_cfg, data.get('cmdline'), data.get('config'),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/jenkins/workspace/scylla-master/next/scylla/test/pylib/scylla_cluster.py", line 816, in add_server
    await server.install_and_start(self.api, expected_error)
  File "/jenkins/workspace/scylla-master/next/scylla/test/pylib/scylla_cluster.py", line 285, in install_and_start
    await self.start(api, expected_error)
  File "/jenkins/workspace/scylla-master/next/scylla/test/pylib/scylla_cluster.py", line 511, in start
    report_error('failed to start the node, timeout reached')
  File "/jenkins/workspace/scylla-master/next/scylla/test/pylib/scylla_cluster.py", line 485, in report_error
    raise RuntimeError(message + "\nCheck the log files:\n"
RuntimeError: failed to start the node, timeout reached, server_id 1134, IP 127.196.104.38, workdir scylla-1134, host_id 56d62aed-72fd-4fde-9dd7-6e81d1c5176f, cql [not connected]
Check the log files:
/scylladir/testlog/x86_64/test.py.debug-release-dev.log
/scylladir/testlog/x86_64/dev/scylla-1134.log

22:08:30.848 INFO>  [25/Feb/2024:21:51:50 +0200] "PUT /cluster/addserver HTTP/1.1" 500 0 "-" "Python/3.11 aiohttp/3.9.3"
22:08:30.884 INFO> [dev/topology_custom.test_replace.1] Test topology_custom.test_replace.1 failed 
22:08:30.884 INFO> [dev/topology_custom.test_replace.1] ScyllaManager stopping for test dev/topology_custom.test_replace.1
22:08:30.884 INFO> [dev/topology_custom.test_replace.1] ScyllaManager: Scylla cluster ScyllaCluster(name: 4c4b79c2-d417-11ee-a367-a8a159ead570, running: ScyllaServer(1128, 127.196.104.12, ac7eea86-de4b-4ad5-8e7c-7ebda58d148e), ScyllaServer(1127, 127.196.104.34, f649e437-3f36-498a-9a1d-125d17affe45), stopped: ScyllaServer(1126, 127.196.104.38, e81e4353-0b50-4da5-9dca-243291c44fc8)) is dirty after dev/topology_custom.test_replace.1, stopping it
```

attaching logs of relevant servers

[scylla-1126.log](https://github.com/scylladb/scylladb/files/14397891/scylla-1126.log)
[scylla-1127.log](https://github.com/scylladb/scylladb/files/14397892/scylla-1127.log)
[scylla-1128.log](https://github.com/scylladb/scylladb/files/14397893/scylla-1128.log)
[scylla-1134.log](https://github.com/scylladb/scylladb/files/14397894/scylla-1134.log)

The replacing node was 1134. The topology coordinator during this time was 1128.

In coordinator's logs we see:
```
INFO  2024-02-25 21:51:51,911 [shard 0: gms] gossip - Node 127.196.104.38 has restarted, now UP, status = UNKNOWN
WARN  2024-02-25 21:51:51,911 [shard 0: gms] gossip - Fail to send EchoMessage to 127.196.104.38: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
DEBUG 2024-02-25 21:51:51,915 [shard 0:strm] raft_topology - raft_topology_cmd::wait_for_ip done [{56d62aed-72fd-4fde-9dd7-6e81d1c5176f}]
INFO  2024-02-25 21:51:51,915 [shard 0:strm] raft_topology - updating topology state: replace: accept node
DEBUG 2024-02-25 21:51:51,916 [shard 0:strm] raft_topology - reload raft topology state
DEBUG 2024-02-25 21:51:51,917 [shard 0:strm] raft_topology - topology_state_load: the last committed CDC generation ID: (2024/02/25 19:51:45, 4e529ef8-d417-11ee-9bd5-a2b33515fd56)
INFO  2024-02-25 21:51:51,917 [shard 0:strm] raft_topology - entered `join group0` transition state
INFO  2024-02-25 21:51:51,917 [shard 0:main] raft_group_registry - marking Raft server 56d62aed-72fd-4fde-9dd7-6e81d1c5176f as alive for raft groups
INFO  2024-02-25 21:51:52,639 [shard 0: gms] gossip - InetAddress 127.196.104.38 is now UP, status = UNKNOWN
INFO  2024-02-25 21:51:52,639 [shard 0:strm] gossip - InetAddress 127.196.104.38 is now DOWN, status = UNKNOWN
WARN  2024-02-25 21:51:52,640 [shard 0:strm] raft_topology - attempt to send acceptance response to 56d62aed-72fd-4fde-9dd7-6e81d1c5176f failed. The node may hang. It's safe to shut it down manually now. Error: connection is closed
```

we see gossiper acting weird, marking the node as UP twice and then as DOWN.

Perhaps old gossip message from replaced node reverted the IP mappings, so we tried to send the acceptance response to the old node? But I recall we fixed that at some point by using proper generation numbers when updating the IP mappings. Perhaps we regressed it again?

cc @gusev-p

**Comment by kbr-scylla** [comment]
> Perhaps old gossip message from replaced node reverted the IP mappings, so we tried to send the acceptance response to the old node? But I recall we fixed that at some point by using proper generation numbers when updating the IP mappings. Perhaps we regressed it again?

That doesn't make sense, the mappings are ID->IP, and the ID of the replacing node is a new one.

**Comment by kbr-scylla** [comment]
Hmm, on replacing node we see
```
INFO  2024-02-25 21:51:52,007 [shard 0:strm] messaging_service - Dropping connection to 127.196.104.12 because it was created without topology information
```

But this happened ~600ms before coordinator tried to send accept response, so it should have no effect on that.

**Comment by piodul** [comment]
Observation:

```
INFO  2024-02-25 21:51:52,639 [shard 0: gms] gossip - InetAddress 127.196.104.38 is now UP, status = UNKNOWN
INFO  2024-02-25 21:51:52,639 [shard 0:strm] gossip - InetAddress 127.196.104.38 is now DOWN, status = UNKNOWN
```

It seems that some messages about node going `DOWN` are printed on the streaming scheduling group. Notably, the gossiper failure detector runs on the streaming scheduling group - implicitly, because `main.cc` uses the streaming scheduling group to call `storage_service::join_cluster` -> `storage_service::join_token_ring` -> `gossiper::start_gossiping` which finally starts the failure detector. On the other hand, RPC handlers and the main gossiper loop runs on the gossiper scheduling group.

The failure detector sometimes calls `gossiper::convict()` on nodes that it thinks that are down, which ultimately calls the logic that calls `mark_dead` which prints the message. Perhaps there is a race between the failure detector and a notification coming from the other node. This is my main suspicion right now but I need to confirm it.

**Comment by kbr-scylla** [comment]
Another occurrence: https://github.com/scylladb/scylladb/issues/17663

coordinator logs from that one:
```
INFO  2024-03-05 12:09:42,051 [shard 0: gms] gossip - Node 127.180.207.9 has restarted, now UP, status = UNKNOWN
WARN  2024-03-05 12:09:42,052 [shard 0: gms] gossip - Fail to send EchoMessage to 127.180.207.9: seastar::rpc::remote_verb_error (Not ready to respond gossip echo message)
DEBUG 2024-03-05 12:09:42,054 [shard 0:strm] raft_topology - raft_topology_cmd::wait_for_ip done [{2724e8d2-5a24-4378-8238-c8e1dd1325c5}]
INFO  2024-03-05 12:09:42,054 [shard 0:strm] raft_topology - updating topology state: replace: accept node
DEBUG 2024-03-05 12:09:42,055 [shard 0:strm] raft_topology - reload raft topology state
DEBUG 2024-03-05 12:09:42,055 [shard 0:strm] raft_topology - topology_state_load: the last committed CDC generation ID: (2024/03/05 10:09:36, 78a5e148-dad8-11ee-1d1c-cff1a92895af)
INFO  2024-03-05 12:09:42,056 [shard 0:strm] raft_topology - entered `join group0` transition state
INFO  2024-03-05 12:09:42,056 [shard 0:main] raft_group_registry - marking Raft server 2724e8d2-5a24-4378-8238-c8e1dd1325c5 as alive for raft groups
INFO  2024-03-05 12:09:42,389 [shard 0: gms] gossip - InetAddress 127.180.207.9 is now UP, status = UNKNOWN
INFO  2024-03-05 12:09:42,389 [shard 0:strm] gossip - InetAddress 127.180.207.9 is now DOWN, status = UNKNOWN
WARN  2024-03-05 12:09:42,389 [shard 0:strm] raft_topology - attempt to send acceptance response to 2724e8d2-5a24-4378-8238-c8e1dd1325c5 failed. The node may hang. It's safe to shut it down manually now. Error: connection is closed
INFO  2024-03-05 12:09:42,389 [shard 0:strm] raft_topology - updating topology state: bootstrap: failed to accept 2724e8d2-5a24-4378-8238-c8e1dd1325c5
```

**Comment by kbr-scylla** [comment]
I wonder if this and https://github.com/scylladb/scylladb/issues/17062 don't have the same root cause

**Comment by piodul** [comment]
I've ran the test_replace.py suite 1000 times on Jenkins with gossiper logging set to `trace` and it failed twice. In both cases there was an issue with gossiper marking the joining node UP and then immediately DOWN, causing connections to be dropped.

In the first case (293) connection drop occurred while delivering acceptance response like described in the issue. In the second case (416) it happened later, while streaming data to the replacing node.

Here are the logs from the runs:

[293.zip](https://github.com/scylladb/scylladb/files/14558023/293.zip)
[416.zip](https://github.com/scylladb/scylladb/files/14558025/416.zip)

The race is between the gossiper main loop (`gossiper::run()`) and gossiper failure detector (`gossiper::failure_detector_loop`). Here is how it works:

1. Node A is the topology coordinator, node B is alive, node C was just shut down. All events are described from the perspective of A unless explicitly noted.
2. Node A still considers both B and C to be alive, so the failure detector runs two failure sub-detectors (`failure_detector_loop_for_node`) for node B and C. The main failure detector's loop waits until the sub-detectors exit their loop.
3. Sub-FD for B and C send echo messages. B finishes first and enters a 2-second sleep until it re-sends the echo message. C finishes right after that and decides that C was dead for long enough and calls `gossiper::convict(C)`. This updates the live endpoints so the Sub-FD for C's loop exits, but Sub-FD for B needs to do one more iteration until it notices and stops.
4. Node D starts and wants to replace C.
5. Roughly two seconds since point 3, the gossiper main loop decides to gossip with C to see if it is alive (`gossiper::do_gossip_to_unreachable_member`). We receive a response; we send a gossip echo and get a successful response again, so we *decide* to mark node B as alive and will call `gossiper::real_mark_alive`.
6. **At the same time**, the Sub-FD for node B finally quits and unblocks the main FD loop. We enter a piece of code which looks at which nodes stopped being alive since the last iteration and *decide* to call `gossiper::convict` for those nodes.
7. `real_mark_alive` and `convict` update the list of live endpoints and are synchronized with an endpoint lock. The gossiper main loop wins the race and `real_mark_alive` does its work first (`InetAddress {} is now UP, status = UNKNOWN`), only then `convict` runs (`InetAddress {} is now DOWN, status = UNKNOWN`).

**Comment by mykaul** [comment]
> 5\. Roughly two seconds since point 3, the gossiper main loop decides to gossip with C to see if it is alive (`gossiper::do_gossip_to_unreachable_member`). We receive a response; we send a gossip echo and get a successful response again, so we _decide_ to mark node B as alive and will call `gossiper::real_mark_alive`.

I did not understand this step - we gossip with C, see it's alive and mark B as alive?

**Comment by piodul** [comment]
> I did not understand this step - we gossip with C, see it's alive and mark B as alive?

No, it was supposed to be "C" instead of "B" here. Thanks for catching, I corrected it.
