### ISSUE TITLE
Remove consistent-topology-changes experimental feature

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#17802]
Raft-based topology is planned GA for 6.0, so we need to take off the experimental feature.

Best to do it before branching.

We'll need to coordinate the change in ScyllaDB repo with changes in scylla-dtest and scylla-pkg, maybe more repositories. They all refer to this experimental feature.

Similar effort was done when we removed consistent_cluster_management: https://github.com/scylladb/scylladb/pull/16334, https://github.com/scylladb/scylla-pkg/pull/3722, https://github.com/scylladb/scylla-dtest/pull/3770 (@patjed41)

cc @mykaul @avikivity @kostja 

---

We decided that we will replace the experimental flag with a flag which will allow **disabling raft-topology** when starting new cluster (basically, the reverse of the current experimental feature).

The flag is not to be used by customers/users, the purpose is to continue testing gossip-mode operations in dtests and SCT.

The dtest jobs will have to be adjusted as well; we'll need to continue running the gossip-mode jobs.

**Comment by kbr-scylla** [comment]
Not sure if we want to wait with this until we fix all dtest failures.

Fixing dtest failures first may make the process simpler -- there should be fewer adjustments needed for scylla-dtest in that case.

**Comment by kbr-scylla** [comment]
After discussion on today's status, we decided that we will replace the experimental flag with a flag which will allow **disabling raft-topology** when starting new cluster (basically, the reverse of the current experimental feature).

The flag is not to be used by customers/users, the purpose is to continue testing gossip-mode operations in dtests and SCT.

cc @temichus @enaydanov @aleksbykov @avikivity @mykaul @kostja @bhalevy

**Comment by patjed41** [comment]
> The flag is not to be used by customers/users

Have we ever introduced such a flag?

What `value_status` should it have? I think the only reasonable choice is `Used`, but then this flag will be automatically documented and visible to users. Maybe we need a new `Internal` value?

cc @avikivity

**Comment by tzach** [comment]
> Have we ever introduced such a flag?

https://github.com/scylladb/scylladb/commit/4f23eec44feae692411ae9a49c5f589f1d919647

**Comment by bhalevy** [comment]
Please see https://github.com/scylladb/scylla-dtest/pull/4066#issuecomment-2027757489
We need to make sure not to break tablets in the process.

**Comment by patjed41** [comment]
Since fixing this issue will require merging multiple PRs in different repos, I post the plan, so we don't get lost.

We will make `consistent-topology-changes` unused and introduce `disable-consistent-topology-changes` that allows testing with raft-topology disabled. These changes require corresponding adjustments in dtest:
- tests using raft-topology should stop using `consistent-topology-changes`
- tests not using raft-topology must start using `disable-consistent-topology-changes`

We want to merge changes to Scylla and to dtest in a way that ensures that all tests are run correctly during the whole process. If we merged all changes to Scylla first, all tests would run with raft-topology and the ones excluded in raft-topology would fail. We also can't merge all changes to dtest first.

Here is the proposed merging plan:
1. scylladb: introduce unused `disable-consistent-topology-changes`
2. scylla-dtest: use `disable-consistent-topology-changes` in jobs that run without raft-topology (this change won't have any effect for now)
3. scylladb: add all required changes, in particular making `consistent-topology-changes` unused and `disable-consistent-topology-changes` used
4. scylla-dtest: remove redundant uses of  the `consistent-topology-changes` flag and make the `consistent-topology-changes` feature (the one responsible for including and excluding tests if raft-topology is used) depend on passing `disable-consistent-topology-changes`

After merging all changes above, we will still have a small issue. Using raft-topology will become default, but Jenkins jobs' names won't reflect it. For example, we will have `gating-dtest-release` (not using raft-topology)  and `gating-dtest-release-with-consistent-topology-changes`, but we would like to have `gating-dtest-release` (using raft-topology) and `gating-dtest-release-with-gossip-topology-changes`. This issue can be fixed later to simplify the initial process. At least, we will need to:

- scylla-pkg: rename `gating-dtest-release-with-consistent-topology-changes` to `gating-dtest-release-with-gossip-topology-changes`
- scylla-dtest: stop passing `disable-consistent-topology-changes` to jobs not using raft-topology, start passing it to jobs using it (the ones named with "with-raft-topology"), and rename "with-raft-topology" jobs to "with-gossip-topology"
- Jenkins: fix Script Path in jobs' configurations according to the changes in scylla-dtest above

@scylladb/scylla-maint @fruch @yaronkaikov

**Comment by kostja** [comment]
@kbr-scylla unless Tzach explicitly requested "disable-" I join Avi's opinion and prefer to avoid double negation.

**Comment by tzach** [comment]
AFAIK, I did not request a "disable-" fleg

**Comment by patjed41** [comment]
The new proposal is `force-gossip-topology-changes`. See discussion in https://github.com/scylladb/scylladb/pull/18284.

**Comment by kbr-scylla** [comment]
Step 4 of the plan https://github.com/scylladb/scylladb/issues/17802#issuecomment-2056836938 was done, so I'm closing the issue as done.

@patjed41 please create a follow-up issue for the cleanups you mentioned at the end.

**Comment by patjed41** [comment]
> Step 4 of the plan [#17802 (comment)](https://github.com/scylladb/scylladb/issues/17802#issuecomment-2056836938) was done, so I'm closing the issue as done.
> 
> @patjed41 please create a follow-up issue for the cleanups you mentioned at the end.

I opened #18600
