### ISSUE TITLE
Host ID shown as `null` in nodetool status when node is joining (regression)

### ISSUE THREAD

**Issue by kbr-scylla** [scylladb/scylladb#17857]
The reason Host ID is shown as null for the joining node is because` nodetool status` uses the `/storage_service/host_id` HTTP endpoint, which uses `token_metadata::get_endpoint_to_host_id_map_for_reading()` underneath. If a node is not included in the map returned by this function, status will show its host ID has null.

This function was changed in https://github.com/scylladb/scylladb/pull/14844 to only return normal token owners. That's when the regression was introduced.

**Comment by bhalevy** [comment]
Cc @denesb

**Comment by denesb** [comment]
Do we have to revert https://github.com/scylladb/scylladb/pull/14844?

**Comment by bhalevy** [comment]
> Do we have to revert #14844?

This might resurrect https://github.com/scylladb/scylladb/issues/14843
unless it got fixed in a different way since then.
And it might break other users of the host_id api, like tesrs, that now rely on it returning only normal token owners.
I suggest that we use a different api for nodetool's use case, like the gossip api that can provide the inet_address to host_id mapping at any state.
