### ISSUE TITLE
[test.py] generate xunit and junit report which are duplicated

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylladb#17851]
...causing the wrong number of tests/failures in the Jenkin test result

I have done some tests to show this issue:

**Next, x86 dev mode only**: https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/next/1145/
Based on the test.py output in the log we have 9204 tests
```
00:13:12  [9204/9204] topology_custom   dev   [ PASS ] topology_custom.test_tablets_migration.2 560.33s
```
while the test result shows 9930 - https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/next/1145/testReport/

**Faied gating job** https://jenkins.scylladb.com/job/scylla-master/job/next/7393/  - while log show only one failure in `aarch64`
```
14:12:54  [1340/9179] topology_custom release [ FAIL ] topology_custom.test_raft_recovery_basic.1 79.48s
```

The test result shows 2 - https://jenkins.scylladb.com/job/scylla-master/job/next/7393/testReport/

![image](https://github.com/scylladb/scylladb/assets/9914527/13698769-5133-4f71-9f9b-d2d76e9bc9b0)

**Comment by yaronkaikov** [comment]
/cc @mykaul @roydahan 

@kostja if I am not mistaken you are the owner of `test.py` so I assigned it to you. if not, please feel free to remove yourself

**Comment by benipeled** [comment]
The reason for the test duplication in the example above is the fact that Jenkins parses two different XML files that include the same failure

1. junit.xml - one file includes all tests (generated by test.py)
2. topology_custom.test_raft_recovery_basic.1.xunit.xml - dedicated junit file generated by pytests

The purpose of junit.xml (and boost.xunit.xml) is to have one file that we can parse instead of going through all XMLs, I'm not sure what changed that caused this multi-parse

**Comment by benipeled** [comment]
...so it seems that the solution is simple - parse the `junit.xml` only,
But as part of another issue I'm working on - https://github.com/scylladb/scylla-pkg/issues/3849 - I found two issues with the `junit.xml` that at least the first one block us from parsing the `junit.xml` only,
1. It missed the `time` attribute hence Jenkins shows  duration=0 for all non-boost tests 
2. Instead of containing the exact error (similar to the junit files generated by pytest), it contains the entire log which requires scrolling down to find the error among all the other log-events

**Comment by xtrey** [comment]
@benipeled  @yaronkaikov never thought that I'd say it, but it's a feature in the current implementation. You are right the reason is that we are parsing two files with the same test result just with different levels of aggregation. The solution is simple: parse only one file.
1. This is how it will look like if we parse aggregated results https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/xtrey/job/scylladb_test.py/9/testReport/
2. This is how it will be without aggregated results for Python test https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/xtrey/job/scylladb_test.py/10/testReport/

@benipeled The reason for aggregation is to add the log of test.py to the test itself which should provide the additional information. The solution here can be the reporting tool that supports attaching files to the test result, like allure for example. So on top, there will be exceptions thrown from pytest and attachments with any files we want to be there.

**Comment by xtrey** [comment]
@benipeled @piodul @kbr-scylla to fix this bug we need to stop parsing one of the reports. Which one we should leave?

[Here](https://drive.google.com/file/d/19cqa-1y8lz6datjU5dvEktdsNAAHkfyt/view?usp=drive_link) the example of allure report.

**Comment by kbr-scylla** [comment]
> This is how it will look like if we parse aggregated results https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/xtrey/job/scylladb_test.py/9/testReport/

I like this one better, it seems to show more details like the mode in which failure happened.

**Comment by benipeled** [comment]
> > This is how it will look like if we parse aggregated results https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/xtrey/job/scylladb_test.py/9/testReport/
> 
> I like this one better, it seems to show more details like the mode in which failure happened.

I'm fine with this option that AFAIU uses the consolidated `juni.xml` and include both pytest and non-pytest tests but the "problem"  is that it includes the whole log and sometimes requires toggling to find the failure,

On dtest, @fruch uses properties to refer to the logfile, ex. https://jenkins.scylladb.com/job/scylla-master/job/gating-dtest-release/8878/testReport/junit/compaction_additional_test/TestTimeWindowDataSegregation/FullDtest___full_split006___test_reshape_sstables_different_size_after_change_window_size/

**Comment by kbr-scylla** [comment]
> I'm fine with this option that AFAIU uses the consolidated juni.xml and include both pytest and non-pytest tests but the "problem" is that it includes the whole log and sometimes requires toggling to find the failure,


"toggling"? WDYM?

Anyway, the "Standard Output" part (like here https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/xtrey/job/scylladb_test.py/9/testReport/(root)/non-boost%20tests/topology_custom_test_multidc_debug_1/) is almost always useless, for multi-node tests at least, the output is always truncated, you have to go to artifacts and find the full file, and anyway the test output itself is almost always not enough since you need to look at node logs too.

Providing a link to the correct mode and architecture subdirectory inside artifacts on that page would be much more useful.

**Comment by benipeled** [comment]
> > I'm fine with this option that AFAIU uses the consolidated juni.xml and include both pytest and non-pytest tests but the "problem" is that it includes the whole log and sometimes requires toggling to find the failure,
> 
> "toggling"? WDYM?

Scroll down to the bottom of the long test page to find the failure
 
> Anyway, the "Standard Output" part (like here https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/xtrey/job/scylladb_test.py/9/testReport/(root)/non-boost%20tests/topology_custom_test_multidc_debug_1/) is almost always useless, for multi-node tests at least, the output is always truncated, you have to go to artifacts and find the full file, and anyway the test output itself is almost always not enough since you need to look at node logs too.

So IIUC, you are saying that the output/error-msg/traceback is irrelevant in both cases because you have to go to check the logs? I understand, but I'd still go with the second option that includes the Error Message and Stacktrace because it helps sometimes to find the issue (and not contains the whole logfile)

> Providing a link to the correct mode and architecture subdirectory inside artifacts on that page would be much more useful.

Yes, I agree that a link directly to the relevant logs would be useful - @xtrey if you want to implement it on test.py

**Comment by nyh** [comment]
Guys, I can't follow the details of this discussion, but let me offer two pieces of advice I'd like you to please follow:

1. Some of the behavior that exists today exists because it was useful to debug test failures. Please don't remove this behavior before you actually try to debug test failures (even fake failures) yourself and see what is helpful and what isn't helpful. For more on this, look up "Chesterton’s Fence".

2. It's awkward and difficult to jump between different log files. Please make sure when you enter a test failure HTML page on Jenkins, you'll see as much content as you can immediately, something that is helpful in 90% of the cases (doesn't need to be 100%! and doesn't need to contain a full explanation - just at least a beginning). Please, please, not just a single line saying "look at log xyz". If you really must say "look at log xyz", please make an effort to make it a functioning link in HTML, and not a hint or inaccurate file name (e.g, a patch that is later moved and isn't exactly the path that the user will see).

**Comment by temichus** [comment]
agree with @kbr-scylla,  test.py logs are useless for multi-node tests. but it can be reworked by writing log file by pytest itself 

From what i see we just put some additional info into the test that for me useless:
```

**Comment by temichus** [comment]
@kbr-scylla @benipeled,  I suggest in the scope of this task stopping using the consolidated report in Topology tests(at least) and leaving Run/Boos this lot of logic

Also in the scope of this task try to add more information to current logs(that consolidated report has)
1) add a run number, mode  in the JUnit report (by allure lib)
2) add a separate pytest log per pytest run for test failure investigation with more info in logging like: file name, Coro name, thread num, test name 
3) add links to server logs

1,2 is a must before removing the consolidated report from Topology tests, 3 will be optional 

WDYT?
cc @xtrey @kostja

**Comment by kbr-scylla** [comment]
> agree with @kbr-scylla, test.py logs are useless for multi-node tests

I didn't say that.
test.py logs are useful.
The jenkins page is useless. You need to look at multiple node log files i.e. you need to go into artifacts to understand the failure.

**Comment by mykaul** [comment]
> I mean exactly that - "Standard Output" that I see in JUnit when tried to investigate issues

Agree, and I keep complaining on this - it's not straightforward to get to the location of all those logs. @yaronkaikov - it'd be great if we could improve this part.

**Comment by nyh** [comment]
> > I mean exactly that - "Standard Output" that I see in JUnit when tried to investigate issues
> 
> Agree, and I keep complaining on this - it's not straightforward to get to the location of all those logs.

Right, I mentioned this above. We should have direct HTML links to all relevant logs, or if some reason we can't have links (?) at least accurate file names - all file names - and not rely on the person doing the debugging familiar with test.py esoteric knowledge.

Additionally, I  believe that the test suite should make an effort to collect pieces of information which it thinks might be _most_ useful and dump it to "stdout" and have it displayed in Jenkins. For example, we could automatically extract from the logs only the sections that happened during the test. We could filter out log spam (e.g., compactions). The full logs will still be available if needed, but the shorter "stdout" could perhaps be enough for 90% of the problems, instead of 90% of the problems requiring fetching logs.

**Comment by temichus** [comment]
> > I mean exactly that - "Standard Output" that I see in JUnit when tried to investigate issues
> 
> Agree, and I keep complaining on this - it's not straightforward to get to the location of all those logs. @yaronkaikov - it'd be great if we could improve this part.

@xtrey and I  already working on the proposal that will be shared here

**Comment by temichus** [comment]
> Right, I mentioned this above. We should have direct HTML links to all relevant logs, or if some reason we can't have links (?) at least accurate file names - all file names - and not rely on the person doing the debugging familiar with test.py esoteric knowledge.

with the consolidated report, we will be able to attach logs only per pytest run, not test
if we put the responsibility of making report in pytest itself we will be able to implement logic to store Python and Scylla log that connect only to this particular test (full pytest and Scylla output will be saved like now as well in case of some global, not  test issues  ) 

> 
> Additionally, I believe that the test suite should make an effort to collect pieces of information which it thinks might be _most_ useful and dump it to "stdout" and have it displayed in Jenkins. For example, we could automatically extract from the logs only the sections that happened during the test. We could filter out log spam (e.g., compactions). The full logs will still be available if needed, but the shorter "stdout" could perhaps be enough for 90% of the problems, instead of 90% of the problems requiring fetching logs.

agree dump "stdout" may be useful, but only in case of global, not  test issues

**Comment by kbr-scylla** [comment]
BTW @temichus @xtrey one easy way that would immediately improve finding relevant logs, would be to put the different clusters into their own directories. Now all node logs reside in the same directory, and you have to find each node separately in the pytest log. But if we created a subdirectory for a cluster (e.g. using the cluster ID as the name) you'd only have to find the cluster ID in pytest logs and just download the directory. It seems like an easy change to do.

**Comment by temichus** [comment]
> @kbr-scylla how about having the failed test directory where all related logs: Scylla logs for specific cluster and the only part that was added during the run of the test, test.py logs, and pytest logs? Something like that https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/xtrey/job/scylladb_test.py/18/artifact/testlog/x86_64/dev/failed_test/test_query_dc_with_rf_0_does_not_crash_db.dev.1/. Currently adding the catching the logs only related to the test itself rather than the whole suite.

cc @piodul

**Comment by kbr-scylla** [comment]
@xtrey so we're copying the log files? I'm worried that this could unnecessarily waste space, these log files might grow pretty big, especially if we have some bugs that cause printing a message in the loop etc.

Perhaps a solution in between: use symlinks?

Generally it looks good from the user experience POV.

Also remember that:
- clusters might be reused between tests. A single cluster could potentially be used in two failed tests so in that case both failures would have to refer to the cluster
- test failure could happen when test.py was trying to add new node to the cluster. We need to make sure that this node logs will be accounted too (IIUC the node is not part of `ScyllaCluster` object before we finish adding it)

**Comment by xtrey** [comment]
@kbr-scylla symlinks would not work. I do not fully copy the whole log, only the part that was produced during the test. So yes it will increase the disk space required for that, but this is only done for the failed test.
The logic of the current solution is next:
1. Before a test mark the current log position
2. perform a test
3. after a test save the current position of the logs
4. read the log between these marks and put it to the failed dir

Potentially when a node is not added to the cluster it still should be added to the stopped dict and then it should be visible, except when there will be an exception. But I guess it's still possible to catch such cases with additional logic but not in this PR.

**Comment by kbr-scylla** [comment]
>  The logic of the current solution is next:

Copying only part of the log will be confusing and sometimes not enough --- what happened in the cluster before the test could be relevant.

**Comment by xtrey** [comment]
Work in progress for that. There was a fix for TopologySuiteTest, but occasionally deleted one class and it was not committed in https://github.com/scylladb/scylladb/pull/18277. Currently working on an implementation for all tests.
