### ISSUE TITLE
Alternator: counts create table is not exactly or properly

### ISSUE THREAD

**Issue by qiuqiu-007** [scylladb/scylladb#17943]
metrics: `scylla_alternator_operations`
When I use aws `create-table` or `update-table` it plus one whatever it done successfully or failed.

Obviously, here the create_table is failed, but it plus one.
![屏幕截图 2024-03-14 174551](https://github.com/scylladb/scylla-monitoring/assets/143240433/2a4f378a-052d-4382-b429-e5b572b05920)

Maybe it is better to set a label or metric to count the successful operations or failed operations.

**Comment by qiuqiu-007** [comment]
This is a situation that we met in production, if a user send request to app, then app sends it to Scylla, but the request gets failed. It is confused to figure out whether it is Scylla returns failure or network error.  In that case, we think it might better to collect failure requests and successful requests independently. Or is there any nicer ideas to solve this problem ?

**Comment by nyh** [comment]
> This is a situation that we meet in production, if a user send a request to app, then app sends it to Scylla, but the request gets failed. It is confused to figure out whether it is Scylla returns failure or network error.

Why is it confusing? The DynamoDB API does have various types of errors, and there are also error strings. When you call CreateTable, you definitely know if it succeeded or failed, and don't need counters to tell you that... Can you give me a more specific example of your problem?

> In that case, we think it might better to collect failure requests and successful requests independently. Or is there any nicer ideas to solve this problem ?

I don't disagree that it would be nice to have, in addition to the total number of requests, also counts for requests that "failed" or failed in different ways (as I noted above, it's not always obvious what a "failure" means for different types of requests). But would we add these counters per request type (e.g., how many times GetItem returned a ValidationException) or overall (how many times any request returned ValidationException)? Or maybe make it per request type but not error type (how many times GetItem returned any non-success response)? We can do all these things, but the question is what we _want_ to do, and what will be useful and not add too many metrics (each of these metrics "costs" us in monitoring performance).

**Comment by qiuqiu-007** [comment]
This situation might be more clear, when there is a **PutItem failure of network timeout**, then we don't know whether it is put successfully or failed, because there is no error counter.

**Comment by nyh** [comment]
> This situation might be more clear, when there is a **PutItem failure of network timeout**, then we don't know whether it is put successfully or failed, because there is no error counter.

This is indeed a problem: If a `PutItem` fails with a network error reported by the client library, or with a `InternalServerError` reported by the server, you don't know whether the write succeeded or failed. If the update is _idempotent_, the appopriate thing to do would be to retry the same write. But if the write is not idempotent - e.g., a counter increment - and retrying it might change the result - you're out of luck, there is simply no reliable way to do this with `PutItem`. DynamoDB introduced ` TransactWriteItem` to solve (among other things) to solve this problem of idempotent retry, but ScyllaDB doesn't yet support this (https://github.com/scylladb/scylladb/issues/5064). The DynamoDB documentation covers this problem in https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html (section "InternalServerError"), so it's not unique to ScyllaDB's implementation but an inherent limitation of the API.

Adding a counter of successful requests would do little to improve this situation. If you do a single request, then in theory you can check using the counter if it failed or passed before the network error, but what if you do a thousand or a million requests every second - how would you know if a specific request passed or failed? But even in the single-request case, it's not fool-proof: For example, it's always possible that the request was 99% done, and already wrote all the data and the data has become readable - but at that last moment, the coordinator died, did not return success to the client, and did not increment the success counter.

Finally, you created this issue with CreateTable being the example, and I pointed out above that since CreateTable is  _idempotent_ (you can run it again if you're not sure if the previous call succeeded), you already have a great solution for this case - just retry the request - and don't need any counters to do that. In fact, the AWS SDKs already do exactly that - if the request fails with a "retryable" error (like network problem or `InternalServerError`), the SDK retries the same request automatically without even letting the caller know there was a problem. As explained in https://docs.aws.amazon.com/sdkref/latest/guide/feature-retry-behavior.html, the SDK retries by default three times before giving up and returning the error to the caller. 

So although I agree that having success/failure counters and/or failure type counters of all requests and/or individual types of requests might have some uses, I don't think that the specific use case you envision for it would be a good one. 

Because adding more metrics also has costs (in size of data that ScyllaDB and the monitoring stack needs to deal with), we should be convinced that the new metrics will be useful before just adding them.

**Comment by qiuqiu-007** [comment]
> For example, it's always possible that the request was 99% done, and already wrote all the data and the data has become readable - but at that last moment, the coordinator died, did not return success to the client, and did not increment the success counter.
A not smart idea, maybe this could count the rows of a table, if number of row plus one, it succeed.

And in this case, can there return an error info that specified this error happened on which node, and for which reason ? For example, in a three node cluster, a GetItem request is timeout, can I get an error like "GetItem timeout due to node1 is down" or "GetItem is timeout due to network of node1 is broke"

**Comment by nyh** [comment]
> A not smart idea, maybe this could count the rows of a table, if number of row plus one, it succeed.

Again, how would you use this idea if you're making many updates all the time? The number of rows might have increased because in the background someone else added another row - not because your own write succeeded.
Not to mention that there is no efficient way to get an accurate count of the rows in a table (remember, this is a distributed database).

> And in this case, can there return an error info that specified this error happened on which node, and for which reason ? For example, in a three node cluster, a GetItem request is timeout, can I get an error like "GetItem timeout due to node1 is down" or "GetItem is timeout due to network of node1 is broke"

There's already an attempt to tell you what went wrong in a query. A "ValidationException" (something wrong in the query) is very different than "ResourceNotFoundException" (the query is fine but the table doesn't exist) or "InternalServerError" (something went wrong in the server). The last one has some text attached which can sometimes tell you what went wrong on which node, but not always. There's also the case of an actual timeout on the client - the client doesn't get any answer (not InternalServerError or anything), e.g., because the Scylla node it contacted went down.
In some cases of InternalServerError or client-side timeout, you really can't tell what went wrong:

For example, consider that you sent your request to node1, and never get back a reply because node1 rebooted. Did node1 manage to write the data just before rebooting, or didn't it? Did it manage to send this data to another node2 and the new data lives there? You can't know without trying to **read** the data.
As another example, consider that you sent your request to node2, and node2 tried to send it to node3 and never got back an ack because node3 just rebooted. Did node3 write the data, or didn't? You can't know.

In any case, I ask that you please keep this issue open only if you really want the actual feature you opened this feature for (adding a counter of failed requests). If you want to discuss the finer details of error handling in the DynamDB API or Alternator, I suggest that we do this in the scylladb-dev@googlegroups.com mailing list, not here.

**Comment by nyh** [comment]
This was a long and interesting discussion, but it did not culminate in a well-justified feature request, so I'm closing this issue. Feel free to reopen this issue (or to create a new issue) if you have a more concrete request that you can justify.
