### ISSUE TITLE
Add a source_dc option for repair api

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#17963]
Currently the rebuild api allows the user to specify the source_dc for rebuild, but for repair we choose it internally
and there is no way to override it.
Repair could be used directly instead of rebuild and in this case it should either perform a global repair (considering all nodes in the cluster), or the user can provide a `source_dc` option to tell repair the preferred datacenter to use for repairing the node.

This is also tangentially related to https://github.com/scylladb/scylladb/issues/16826 where replacing a node in a DC that does not have enough remaining replicas is unsafe, representing another use case for stating a source_dc for repair.

**Comment by bhalevy** [comment]
Cc @denesb @asias

**Comment by asias** [comment]
Currently we can already limit the dc with the dataCenters options. For example, if we want to limit the source_dc, we can set dataCenters="source_dc, my_local_dc". This way, the node running repair will sync data from the source_dc and my_local_dc.  For the rebuild for adding new dc case, it makes to sense to actually sync the data to peer nodes in the local dc as well (not just source_dc and node running repair/rebuild in the local dc).  It is more efficient than repair with source_dc + node_running_rebuild_in_local_dc. Repair the same range on all replicas in the new dc RF times.  

E.g.,

RF: dc1:2 dc2:2

dc1: n1, n2, n3
dc2: n4, n5, n6


When building the new dc n4, n5, n6

We could run repair on n4, limiting repair to sync n1, n2, n3, n4 (only n4 on the local dc, n5, n6 will sync the data on their own again).

Or 

We could run repair on n4, limiting repair to sync n1, n2, n3, n4, n5, n6  (n5, n6 will skip the range that has been repaired by n4)

Apparently, the second method is more efficient because we only need to read data on n1,n2, n3 once. 

This is another reason why making adding new dc a single node ops coordinated by the group0 leader is better than tracking nodetool rebuild for each node individually.

**Comment by bhalevy** [comment]
Makes sense.
I'll let other chime in, and if there are no objections we can close the issue as not planned.
(But at least it captures this discussion which is a good thing on its own :))

**Comment by bhalevy** [comment]
Closing as not planned.
