### ISSUE TITLE
reader-concurrency-semaphore: saved readers can refer to dangling tablets if tablet is migrated away

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#18110]
Saved readers do not keep an effective replication pointer instance, so a tablet migration can migrate away the tablet they were reading from. To prevent this, tablet cleanup should also call into the semaphore to clear any inactive reader which refers to the migrated away tablet.

**Comment by avikivity** [comment]
Not just on migration, also on split, since the captured range will have changed.

Have to be careful of the ABA problem - migrated away, then migrated back, but data in buffers is now outdated.

We can keep the erm in saved readers, IIRC they time out after a second. It's not a disaster if topology changes are delayed by a second.

**Comment by denesb** [comment]
The timeout is 10 seconds. And inactive reads have no timeout at all. So I think a better way is to drop all readers which overlap with the migrated range.

**Comment by mykaul** [comment]
@denesb - is anyone working on this?

**Comment by denesb** [comment]
> @denesb - is anyone working on this?

I am, it is work in progress.

**Comment by denesb** [comment]
See https://github.com/scylladb/scylladb/pull/18179 (it was missing the Fixes).
