### ISSUE TITLE
read from dangling row_cache iterator during reverse queries

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#18119]
(to be filled)

**Comment by avikivity** [comment]
Fixed by 295b27a07b9aa306a91b43887fcbabb76ec356c6

**Comment by avikivity** [comment]
@michoecho please supply some text for the description, I imagine we'll need to backport it

**Comment by michoecho** [comment]
Ugh, I created an issue for this (and even mentioned the issue number in a comment in the code), but apparently I forgot to paste it into the commit message.

The issue is https://github.com/scylladb/scylladb/issues/18045.

And it has already been backported, by https://github.com/scylladb/scylladb/pull/18075.
