### ISSUE TITLE
system.snapshots doesn't list snapshots from dropped tables

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#18313]
It's not tested, but it's seed from the code that the table in question walks replica::database object for the list of ks:cf-s then calls get_snapshot_details() on the found table object. Thus, dropped tables are missing. Can be seen with test extension

```patch
--- a/test/cql-pytest/test_virtual_tables.py
+++ b/test/cql-pytest/test_virtual_tables.py
@@ -19,6 +19,17 @@ def test_snapshots_table(scylla_only, cql, test_keyspace):
         assert res[0][1] == tbl
         assert res[0][2] == 'my_tag'
 
+def test_snapshots_dropped_table(scylla_only, cql, test_keyspace):
+    with util.new_test_table(cql, test_keyspace, 'pk int PRIMARY KEY, v int') as table:
+        cql.execute(f"INSERT INTO {table} (pk, v) VALUES (0, 0)")
+        nodetool.take_snapshot(cql, table, 'my_tag', False)
+    res = list(cql.execute(f"SELECT keyspace_name, table_name, snapshot_name, live, total FROM system.snapshots"))
+    assert len(res) == 1
+    ks, tbl = table.split('.')
+    assert res[0][0] == ks
+    assert res[0][1] == tbl
+    assert res[0][2] == 'my_tag'
+
 def test_clients(scylla_only, cql):
     columns = ', '.join([
         'address',
```

Unlike the system table, the api handler lists all snapshots, including those for deleted tables, as it just scans the datadir (disclaimer: I didn't check it explicitly, but it looks like it should)

Yet, there's [C* issue](https://issues.apache.org/jira/browse/CASSANDRA-16843) that nodetool listsnapshots doesn't list dropped tables and it's considered as bug

Cc @denesb , @bhalevy , gents, what's your take on it?

**Comment by bhalevy** [comment]
with auto-snapshot enabled, we take a snapshot before dropping a table.  We should allow listing and deleting it otherwise the only access to it would to ssh into the node.

BTW, an advanced feature that was proposed by @nyh IIRC was to represent the snapshot as a read-only tabls via CQL and then ot could be self-served to restore any data, and it could be deleted by dropping that table, but it's out of scope of course for this issue.

**Comment by nyh** [comment]
@bhalevy my proposal to replace the deleted-table "snapshot" implementation (https://github.com/scylladb/scylladb/issues/7123) is _not related_ to this issue: This issue does not involve auto-snapshot at all. Note that both test.py and cql-pytest/run disable auto_snapshot (to improve test performance), and his test involves explicitly creating a snapshot, not an auto-snapshot-at-drop-time. This issue is about explicit snapshots created for tables which are **later** deleted not being listed in the virtual table (but *are* listed in the REST API).

It sounds to me like the virtual table is simply using the wrong source of information, and it needs to use the same source as the REST API (namely, the filesystem).

**Comment by bhalevy** [comment]
> @bhalevy my proposal to replace the deleted-table "snapshot" implementation (#7123) is _not related_ to this issue: This issue does not involve auto-snapshot at all. Note that both test.py and cql-pytest/run disable auto_snapshot (to improve test performance), and his test involves explicitly creating a snapshot, not an auto-snapshot-at-drop-time. This issue is about explicit snapshots created for tables which are **later** deleted not being listed in the virtual table (but _are_ listed in the REST API).
> 
> It sounds to me like the virtual table is simply using the wrong source of information, and it needs to use the same source as the REST API (namely, the filesystem).

Agreed.

Yet, automatic or not, I think that on the long term exposing snapshots as read only tables is a good idea.

**Comment by bhalevy** [comment]
@paszkow please add to your team's queue

**Comment by xemul** [comment]
> Yet, automatic or not, I think that on the long term exposing snapshots as read only tables is a good idea.

We already have such an API -- it's the mentioned `system.snapshots` table. Or do you misunderstand your point? @bhalevy

**Comment by bhalevy** [comment]
> > Yet, automatic or not, I think that on the long term exposing snapshots as read only tables is a good idea.
> 
> We already have such an API -- it's the mentioned `system.snapshots` table. Or do you misunderstand your point? @bhalevy

Yeah, you misunderstood.  I'm okay with the current representation of snapshots metadata via the virtual table (modulo fixing this issue)

The advanced idea I mentioned is to represent the **content** of a snapshot as a read-only table so it could be used as a self-served backup.

So for a keyspace "ks", live table "tbl1", and dropped table "tbl0", one could have
ks.snapshots, and in it: tbl1-snapshot-* tables and ks.snapshots/tbl0-snapshot-* even after tbl0 was dropped.
this way all snapshots are listed as part of this "virtual schema" for ks.snapshots.
To delete a snapshot one could issue DROP TABLE to the particular snapshot table.

That said, there's a gotcha since we're not replicating those snapshots so if nodes are replaced they will eventually be gone.

**Comment by bhalevy** [comment]
reassigned back to @xemul as it's only anecdotally related to auto-snapshots (as part of tablet-truncate)
