### ISSUE TITLE
topology/test_change_ip very rarely fails with " cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.194.33.11:9042 datacenter1>: ConnectionException('Host has been marked down or removed')})"

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylladb#18547]
Logs: 

[topology.test_change_ip.3886.log](https://github.com/scylladb/scylladb/files/15235757/topology.test_change_ip.3886.log)
[scylla-11658.log](https://github.com/scylladb/scylladb/files/15235787/scylla-11658.log)
[scylla-11657.log](https://github.com/scylladb/scylladb/files/15235788/scylla-11657.log)
[scylla-11656.log](https://github.com/scylladb/scylladb/files/15235789/scylla-11656.log)

**Comment by kbr-scylla** [comment]
Likely Scylla notifications causing driver reconnections (even after we explicitly did `reconnect_driver` after restarting servers) which race with queries. Similar to https://github.com/scylladb/python-driver/issues/317 but not caused by node bootstrap, but node restart. (Perhaps restarting with different IP also causes `on_add` notification?)

Driver DEBUG logs from the test should support or deny this
