### ISSUE TITLE
bloom-filter: default value for components_memory_reclaim_threshold is too strict

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#18607]
`components_memory_reclaim_threshold` controls when we start evicting bloom filters from memory. It defaults to 0.1, which comes down to 10% of the shard's memory. It looks like this is too strict and causes unnecessary bloom filter eviction in otherwise healthy clusters. One cluster which was impacted by this, had a BF/memory ratio of 0.6. The eviction mechanism was introduced to avert OOM disasters, not to enforce lean bloom filters and so the default should be adjusted accordingly and increased to as high as 0.8 or even maybe 0.9. The idea is that by default it should only kick in when OOM is iminent, it should not intervene on clusters which have high BF memory consumption but are otherwise fine.

**Comment by vladzcloudius** [comment]
According to what @avikivity wrote before the OOM is "imminent" when it reaches 0.5.
However we know for a fact this is not true universally - we saw nodes surviving 0.6 and more just fine.
OOM happens not because BF occupies this or that amount of RAM but because the allocation fails.

BF amount can contribute but this is not the root cause - it's just a trigger.

IMO we should not enable this feature by default just like we don't enable compaction I/O bandwidth throttling by default.

Instead we should invest in the actual fixing of the problem:
1) Make sure BF size always correct: we know exactly how many partitions sstable has right before we seal it. Using estimations like we do today is a performance optimization and it should be always discarded when it gets in a way of a correctness. Instead we keep on "fighting" for that heuristics piling up spaghetti code for no good reason whatsoever.
2) If we want to restrict the BF memory size we should implement proper caching (we have a few objects in the code that can make it pretty straight forward, e.g. `loading_cache.hh`).
2.1) If we do that we should add a configurable to control the maximum amount of RAM consumed by BF cache.
