### ISSUE TITLE
alterantor suite.yaml uses unsupported method to create roles

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#18744]
suite.yaml inserts directly into auth_v2.roles instead of using CREATE ROLE.

**Comment by nyh** [comment]
This is not a bug.
If you use CREATE ROLE you still need to **read** the salted hash. The alternative used now is to write what we want as a the faux salted hash.
Both approaches are equally ugly - the one used today is not worse.

**Comment by nyh** [comment]
I forgot to mention that I'm talking about the *alternator* tests. I don't know if you found this construct in other places.

**Comment by avikivity** [comment]
It's a bug. There's no guarantee that writing directly to the table will continue to work.

**Comment by nyh** [comment]
> It's a bug. There's no guarantee that writing directly to the table will continue to work.

It tests an **Alternator feature**, and this is how this Alternator feature currently works - you either need to write the salted hash yourself - or let CREATE ROLE write it for you and then you need to read it. In either way, it looks bad - but that's the way the Alternator feature works today, it's not the job of the test to fix it. 

We can consider changing this approach and finding a different way to configure the Alternator keys, but this would be a different issue, it's not a test issue.

**Comment by avikivity** [comment]
I'm talking about writing to a raft group 0 managed table directly. It's not supported. It's completely unrelated to alternator.

**Comment by nyh** [comment]
So it seems that @avikivity is saying that the approach of:

1. Write some known string (e.g., "alternator_pass") to the "salted hash" field.
2. Use that "alternator_pass" as the secret key to contact Alternator

Is now considered "illegal", and we should stop using it in tests, and instead we should switch the tests to use the other approach:

1. Create a role in the official way ("CREATE ROLE"), give it some password.
2. Read the salted hash from the system table - and use *that* as the secret key for Alternator.

Note that both approaches need to use the ugly system table, so in that respect they are equivalent - but Avi is saying now because of Raft it is ok to read from that table, but a faux-pas to write to it, so the first approach (the one we use today) is out of the question.

@avikivity am I right that **reading** from the auth system table - to read the salted hash - is fine? There is no CQL command that can read the salted hash without the system tables, right?

Changing this is very easy, but needs to be done in four places (test/alternator/run, test/alternator/suit.yaml, test/alternator/conftest.py (to use what is written by the previous two), and dtest).

CC @nuivall @fruch @xtrey

**Comment by nuivall** [comment]
For new auth backup method we'll probably need a mechanism to insert password as hash, this could eliminate the need of select.

**Comment by avikivity** [comment]
Agree a CQL extension to insert salted password is reasonable here.

**Comment by avikivity** [comment]
btw, why do you need to know the salted password?

**Comment by nuivall** [comment]
> btw, why do you need to know the salted password?

because in alternator context it's a shared secret, not a password.

**Comment by nyh** [comment]
> btw, why do you need to know the salted password?

This is a historical accident. When we (Piotr Sarna) added the Alternator authentication configuration, we needed to take some "secret value" from somewhere. It made sense to just use the CQL password, but this isn't available - only the salted hash of the password. So that's what we used for the password.

Arguably, it would have made more sense to just have completely separate user setup (names and keys) for Alternator, but this would have required Scylla Cloud, for example, to add support for that, and we wanted to avoid that.

**Comment by nyh** [comment]
I just realized that Scylla has by default a role "cassandra" with a NULL salted hash, which apparently allows CQL connections to that user without a password. But in Alternator, when we see a missing salted hash, we **refuse** the login instead of allowing. Why? It doesn't help security (if an attacker can anyway use CQL to log into that user). But it makes writing the test harder - I need to read the system table using CQL instead of Alternator :-(

**Comment by avikivity** [comment]
> > btw, why do you need to know the salted password?
> 
> because in alternator context it's a shared secret, not a password.

I see.

Is this the only authentication option available?

**Comment by nuivall** [comment]
> > > btw, why do you need to know the salted password?
> > 
> > 
> > because in alternator context it's a shared secret, not a password.
> 
> I see.
> 
> Is this the only authentication option available?

so far yes, until we add support for external/delegated auth

**Comment by nuivall** [comment]
> has by default a role "cassandra" with a NULL salted

I think it should be salted "cassandra" password by default unless you specify `auth_superuser_salted_password` config

**Comment by nyh** [comment]
> > has by default a role "cassandra" with a NULL salted
> 
> I think it should be salted "cassandra" password by default 

Wow, you are right. Which actually means all that business of creating the "alternator" role is completely unnecessary, and I'll remove it from test/alternator/run and suite.yaml and this will simplify everything. But I do need the new code (that I'm writing now) in test/alternator/conftest.py to use CQL to extract any valid user (in our case, "cassandra"). It doesn't need to be named "alternator"!

**Comment by nuivall** [comment]
It's similar in SCT: https://github.com/scylladb/scylla-cluster-tests/pull/7439/files#r1606446017 @fruch maybe you can follow Nadav's patch

**Comment by fruch** [comment]
> It's similar in SCT: https://github.com/scylladb/scylla-cluster-tests/pull/7439/files#r1606446017 @fruch maybe you can follow Nadav's patch

I think it's better to follow the sequence we'll be showing our users, i.e. create a new dedicated role, and not take shortcuts like assuming/using the default admin user.

**Comment by nyh** [comment]
> > It's similar in SCT: https://github.com/scylladb/scylla-cluster-tests/pull/7439/files#r1606446017 @fruch maybe you can follow Nadav's patch
> 
> I think it's better to follow the sequence we'll be showing our users, i.e. create a new dedicated role, and not take shortcuts like assuming/using the default admin user.

I'll send my patch shortly, but basically the idea is to follow the sequence we're showing our users, which is to **read** the salted hash, not to write it. The question of whether you need to "create a new dedicated role" or not I think isn't interesting - if our default setup already has a "cassandra" account, what's the point of creating another one? In fact, ironically, to create another account, you need to use the existing cassandra account to create the new account :-) When I found myself doing that, I realized how silly that is... If I already have the "cassandra" account and need to use it, I can just use it for Alternator too, and don't bother with creating additional accounts.

**Comment by fruch** [comment]
> > > It's similar in SCT: https://github.com/scylladb/scylla-cluster-tests/pull/7439/files#r1606446017 @fruch maybe you can follow Nadav's patch
> > 
> > I think it's better to follow the sequence we'll be showing our users, i.e. create a new dedicated role, and not take shortcuts like assuming/using the default admin user.
> 
> I'll send my patch shortly, but basically the idea is to follow the sequence we're showing our users, which is to **read** the salted hash, not to write it. The question of whether you need to "create a new dedicated role" or not I think isn't interesting - if our default setup already has a "cassandra" account, what's the point of creating another one? In fact, ironically, to create another account, you need to use the existing cassandra account to create the new account :-) When I found myself doing that, I realized how silly that is... If I already have the "cassandra" account and need to use it, I can just use it for Alternator too, and don't bother with creating additional accounts.

Well our docs recommend creating a different super user

https://opensource.docs.scylladb.com/stable/operating-scylla/security/enable-authorization.html#set-a-superuser

And docs urge the user not to use the default one, and I do remember parts of the code referring to it and behaving differently (at a time, don't know if those parts are still there)

**Comment by nyh** [comment]
> And docs urge the user not to use the default one, and I do remember parts of the code referring to it and behaving differently (at a time, don't know if those parts are still there)

Obviously, for security, you shouldn't keep the "cassandra" user with the default password. But tests don't care about security.

**Comment by fruch** [comment]
> > And docs urge the user not to use the default one, and I do remember parts of the code referring to it and behaving differently (at a time, don't know if those parts are still there)
> 
> Obviously, for security, you shouldn't keep the "cassandra" user with the default password. But tests don't care about security.
> 

Docs state performance, and security reasons, but regardless what the docs says that what should be tested by default
