### ISSUE TITLE
View update backlog is not updated after workload stops on shards different than 0

### ISSUE THREAD

**Issue by wmitros** [scylladb/scylladb#18783]
The `node_update_backlog` is updated (using the `storage_proxy::get_view_update_backlog` call) with the values from the `view_update_concurrency_sem` only in the following scenarios scenarios:
1. When replying to replica write requests:
https://github.com/scylladb/scylladb/blob/bc596a3e76da39ec4c3d64495150e853c6bb16a2/service/storage_proxy.cc#L545-L546
https://github.com/scylladb/scylladb/blob/bc596a3e76da39ec4c3d64495150e853c6bb16a2/service/storage_proxy.cc#L583-L590
2. Each 1s, only on shard 0 when gossiping the backlog:
https://github.com/scylladb/scylladb/blob/bc596a3e76da39ec4c3d64495150e853c6bb16a2/service/misc_services.cc#L237-L245

Because of that, when the last write of some workload is performed on a shard different than 0, the shard's backlog in `node_update_backlog` will not be updated until another request comes in. If the last backlog was high, until the next request on this shard, the MV flow control will unnecessarily delay all requests that affect this node, and when we add MV admission control, it may even prevent them from ever being done

**Comment by nyh** [comment]
Thanks for finding this issue, and fixing it.

Next time, I would appreciate it if you could give some thought (and write down) on what you think might be the **implication** of such a bug.  Your fix for this issue suggest that it only matters if we'll have admission control. Can you give an example of how it causes problems with admission control? Are you worried about a deadlock, where the backlog thinks it's full, so it doesn't start any new request, but because it doesn't start any new request, it doesn't update the backlog which remains forever full?
