### ISSUE TITLE
Tablets should be enabled by default

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#18875]
To facilitate the transition from vnodes to tablets, we should take tablets out of the experimental features list and enable them by default in master and OSS releases.

**Comment by mykaul** [comment]
I'm unsure what's the status of this item (I see many dtest fixes that reference it)

**Comment by tchaikov** [comment]
@mykaul many references actually. each commit referencing this issue pushed to github creates a reference. the related PR on dtest which got merged is https://github.com/scylladb/scylla-dtest/pull/4341 . and the scylla end fix is https://github.com/scylladb/scylladb/pull/18898 . i am closing this issue, unless @xemul thinks otherwise.
