### ISSUE TITLE
Tablets warning message is too long and complex

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#18876]
Instead of the long:

> Tables in this keyspace will be replicated using tablets, and will not support the CDC feature (issue #16317) and LWT may suffer from issue #5251 more often. If you want to use CDC or LWT, please drop this keyspace and re-create it without tablets, by adding AND TABLETS = {'enabled': false} to the CREATE KEYSPACE statement.

I sugget:

> Tables in this keyspace will be replicated using Tablets and will not support CDC  and LWT features.
> To use CDC or LWT, drop this keyspace and re-create it without tablets by adding AND TABLETS = {'enabled': false} to the CREATE KEYSPACE statement.

The extra info is not helpful for casual users.

**Comment by nyh** [comment]
Your proposal has another advantage: When this text was written, LWT just "suffered" from a bug. Shortly afterwards, we outlawed LWT completely. So your shorter text is also more correct because it says CDC and LWT are both **not supported**.

If you're already editing the message, you should also mention counters as not supported (see https://github.com/scylladb/scylladb/issues/19449).

The advantage of the issues was that users can: 1. read a bit more **why** this is happening, and 2. if the issue was already fixed the user can learn in which version the fix is included. But I admit it's not critical.
