### ISSUE TITLE
Proposal: make it easier to map shard to host

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylladb#19069]
Time to time  cluster administrator have a need to know which shard belongs to which host.
I did not find any tool that could help do it easy way.
So my proposal is to have a table that would contain shard to host mapping, something like:
```
CREATE TABLE system.shard_info (
    host_id uuid,
    shard int,
) WITH CLUSTERING ORDER BY (shard ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'information about table truncation'
    AND compaction = {'class': 'IncrementalCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 0
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

**Comment by mykaul** [comment]
I assume you are not looking for https://opensource.docs.scylladb.com/stable/operating-scylla/admin-tools/scylla-sstable.html#shard-of ?
What's the use case?

**Comment by mykaul** [comment]
> You reshaped cluster, added/removed a node, you want to see new shard layout and/or if all shards are getting connected to.

I don't really understand the use case a cloud user will need to see this. The driver connects (or should) to all nodes, all shards, and know how to go to the right (or mostly right) shard based on the hash. What's missing exactly?

**Comment by michoecho** [comment]
@dkropachev You are using unfamiliar terminology. "Which shard belongs to which host"? "Shard to host mapping"?

Every shard belongs to a single node and it is *identified* by its index within that node. It doesn't make sense to say "shard 5 belongs to nodes A and C, but not B". It only makes sense to say "nodes A and C have 5 shards, node B has 4 shards".

A node can't have shards `1, 3, 8`. If a node has 3 shards, they will always be `0, 1, 2`. That's why the table you proposed puzzles me. It suggests otherwise.

Anyway, if you are looking for a way to check how many shards each node has (without iterating over nodes with a script), perhaps monitoring is enough? Or is that not reliable enough for your use case?

> and/or if all shards are getting connected to

This should also be covered by metrics.

**Comment by dkropachev** [comment]
@mykaul, @michoecho ,  sorry for confusion, there was misunderstanding on my part, i thought that there is a place in scylla where shards are cluster-wide enumerated, which is doable but does not make lot's of sense, other than observability.

Since it is not the case, this request makes no sense, i am closing it.
