### ISSUE TITLE
compaction: validate the checksums+digest of input sstables

### ISSUE THREAD

**Issue by denesb** [scylladb/scylladb#19071]
Compaction is not latency sensitive, so we can afford checking checksums and digests of all input sstables. This can be done as we read the sstable, just like we do it for compressed sstables (although reading compressed sstables doesn't check the digest).
This will provide us with semi-regular checksum+digest checks and hopefully will allow us to discover any problems early.

We could extend the checks to repair/streaming as well. Once we have the infrastructure in place (a checksum+digest validating file impl interposer), this will be easy to add.

**Comment by ndragazis** [comment]
### Code exploration and first thoughts

We are interested in the read path of compaction.

Compaction creates a reader for each sstable in the compacting sstable set. The call chain is the following:
`compaction::run()` ->
`compaction::consume()` ->
`compaction::setup_sstable_reader()`

The latter creates one reader per owned range by calling `compaction::make_sstable_reader()`. This is a pure virtual function implemented by each compaction type. All implementations create a combined reader over a set of readers for all compacting sstables. Factory methods from the `sstable_set` class are used for this.

So, eventually, each compaction task requests a reader for each compacting sstable from the sstable layer. The sstable layer offers two functions for creating a reader:
* `sstable::make_reader()`
* `sstable::make_full_scan_reader()`

The latter already offers an `integrity_check` option to enable checksum and digest checking on the underlying stream. This was added to support checksum and digest checking in scrub-validate (see https://github.com/scylladb/scylladb/pull/20207 and https://github.com/scylladb/scylladb/pull/20720).

However, all compaction types except for `scrub_compaction` create readers via the `sstable::make_reader()` instead.

A few options we have:
* Switch all compaction tasks to use `sstable::make_full_scan_reader()`. This probably won't work because the implementation of `compaction::setup_sstable_reader()` implies that compaction can work on ranges.
* Add a new option in `query::partition_slice`. This may not be a good idea because the existing options concern higher-level settings.
* Add a new parameter in `sstable::make_reader()`. This seems the most promising.

**Comment by denesb** [comment]
Streaming and repair part is extracted into its own issue: https://github.com/scylladb/scylladb/issues/21776.
Closing this, compaction was handled in https://github.com/scylladb/scylladb/commit/3a6c0a9b36b38a8f2a8b777abc664c8eca8ec4b5.
