### ISSUE TITLE
Unnecessary building of view updates (during RMW) in pending replica

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylladb#19152]
Turns out pending replica is doing all the RMW work only to realize later that it's not responsible for doing the view updates. See db::view::get_view_natural_endpoint():

```
    ....
    assert(base_endpoints.size() == view_endpoints.size());
    auto base_it = std::find(base_endpoints.begin(), base_endpoints.end(), me);
    if (base_it == base_endpoints.end()) {
        vlogger.info("this node is not an owner of this token {}", base_token);
        // This node is not a base replica of this key, so we return empty
        // FIXME: This case shouldn't happen, and if it happens, a view update
        // would be lost. We should reported or count this case.
        return {};
    }
```

The check is enough for correctness, but it happens very late, and we need to move it early (possibly to view_update_builder, which in turn is used by view_update_generator::generate_and_propagate_view_updates()) such that we can get rid of this inefficiency. This affects both vnodes and tablets. Maybe it's amplified with tablets, since tablets allow for more elasticity, triggering topology changes more often.

**Comment by piodul** [comment]
@raphaelsc @nyh currently, pending base replicas _can_ generate view updates. If there is a pending _view_ replica, then all _base_ replicas send an update to it - including the _pending base_ replica:

```c++
        auto target_endpoint = get_view_natural_endpoint(base_ermp, view_ermp, network_topology, base_token, view_token, use_legacy_self_pairing);
        auto remote_endpoints = view_ermp->get_pending_endpoints(view_token);
```

We take both variables into consideration when sending out the view updates. Is the idea here to unconditionally prevent the pending base replica from sending out view updates?

**Comment by nyh** [comment]
@piodul this is a good point. You're saying that in the case where this node is a pending base replica for base_token **and** this view_token **also** has a pending view replica, then the existing code not only builds the view update from incomplete data (because the pending base replica has incomplete data!), it sends the wrong update to the pending view.

I think this extra issue isn't particularly serious - I think that when the pending base replica reads the base row, it will either have the new data or nothing at all, so at worst it will send a partial view update (e.g., writing an update but not deleting the old value, or writing only some of the columns) but those will be reconciled from the view updates sent by the other base replicas, and (I think...) will cause no harm.

So this just affirms the request in this issue for the pending base replica not to start performing any view updates (don't do reads-before-write, don't prepare view updates, and don't send them.)

The case you mentioned also falls into another waste - if there is a pending view replica, all three (and as you noted, even four!) base replicas send the data to it. But that is a separate issue - https://github.com/scylladb/scylladb/issues/7711.
