### ISSUE TITLE
Update tablet documentation in scylla.yaml

### ISSUE THREAD

**Issue by Michal-Leszczynski** [scylladb/scylladb#19456]
Tablets are still listed in the commented experimental features section. Even though enabling this feature doesn't seem to do anything, it's still a little bit confusing:
https://github.com/scylladb/scylladb/blob/794440eb85b4da9f959a82de280d27836f489878/conf/scylla.yaml#L273-L279

Also, the new tablet feature description says:
https://github.com/scylladb/scylladb/blob/794440eb85b4da9f959a82de280d27836f489878/conf/scylla.yaml#L615-L616

I find this confusing, as I understood it as the option to control the default behavior when creating keyspace without the `tablets = {'enabled': true/false}` option specified. So that it would be possible to have tablets enabled in the cluster (so being able to create tablet keyspace), but still have vnode as the default replication type. 
On the other hand, it seems like it's working exactly like the previous experimental feature - it controls whether it's even possible to create tablet keyspace (and if it is possible, it makes it the default).

cc: @annastuchlik

**Comment by bhalevy** [comment]
> Tablets are still listed in the commented experimental features section. Even though enabling this feature doesn't seem to do anything, it's still a little bit confusing:

Correct.  They are not an experimental feature anymore so this needs to be corrected.

> 
> https://github.com/scylladb/scylladb/blob/794440eb85b4da9f959a82de280d27836f489878/conf/scylla.yaml#L273-L279
> 
> Also, the new tablet feature description says:
> 
> https://github.com/scylladb/scylladb/blob/794440eb85b4da9f959a82de280d27836f489878/conf/scylla.yaml#L615-L616
> 
> I find this confusing, as I understood it as the option to control the default behavior when creating keyspace without the `tablets = {'enabled': true/false}` option specified. So that it would be possible to have tablets enabled in the cluster (so being able to create tablet keyspace), but still have vnode as the default replication type.

No, it doesn't work like that.
`enable_tablets` controls the tablet feature as a whole, so if it's enabled, tablets are enabled by default for new keyspaces, and could be explicitly disabled using the `tablets = {'enabled': false}` replication option in `CREATE KEYSPACE`.
But with `enable_tablets: false`, the tablets feature is disabled and new keyspaces will always be created with no tablets support.  I'm not sure what about existing keyspaces that were previously created with tablets enabled.  I don't think we guarantee access to them in that case, or that they will support topology changes, since tablet migration would be disabled.

> On the other hand, it seems like it's working exactly like the previous experimental feature - it controls whether it's even possible to create tablet keyspace (and if it is possible, it makes it the default).
> 

correct.
