### ISSUE TITLE
Not sure the bug or the feature.

### ISSUE THREAD

**Issue by ipyton** [scylladb/scylladb#19492]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.
Hello, I met some questions about the query. This is my schema :
create table resource(movieId text,  resource text, name text,gid text,status text, primary key (movieId, resource));
When I update using"update movie.resource set status = ? where movieId = ? and resource=?" and  "update movie.resource set gid = ? where movieId = ? and resource = ?", the old one is not been replaced. And I can use this "select * from movie.resource where movieId = ?") to get 2 rows with the same movieId and resource. I am not sure this is a bug or an feature. And I do not want to maintain the invalid data. Could you please give me more information? Thank you!

*Installation details*
Scylla version (or git commit hash):5.3
Cluster size:1
OS (RHEL/CentOS/Ubuntu/AWS AMI):Centos

**Comment by ipyton** [comment]
Chatgpt told me they should not be 2 rows with same partitionkey and clustered key. If I am wrong, please correct me. Thank you.

**Comment by nyh** [comment]
Chatgpt was right - there **cannot** be two rows with the same partition key and clustering key. You're probably doing something wrong, because it is highly unlikely that Scylla has such a basic bug that nobody noticed for years.
I can't say what you're doing wrong because you didn't include an accurate example of your code and its output.

If you're sure you have found a bug and can include an accurate example of what you tried and what went wrong, you can re-open this issue. For now, I'll close it.
