### ISSUE TITLE
Make sure S3 DELETE is idempotent

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#19532]
A theory: when issuing `DELETE /object` request server may (?) delete the object, but fail to return us the response with success status. If the failure renders into transport error (connection closed by server) , seastar will try replay the request again.

refs: #19461

**Comment by mykaul** [comment]
It may fail (the 2nd time) though, if the 1st succeeded.

**Comment by nyh** [comment]
> It may fail (the 2nd time) though, if the 1st succeeded.

Yes, what worries me here (and in the similar issue https://github.com/scylladb/scylladb/issues/19533) is that a successful DELETE on the server may have an unclear result, e.g., maybe the connection broke while sending its result. In that case Seastar may (after https://github.com/scylladb/scylladb/pull/19461) retry the same operation it and then fail because the object doesn't exist. This can confuse Scylla. I agree with this issue's title that Scylla's DELETE function should be made idempotent, i.e., the operation should be "make sure object X is gone" instead of "delete object X". In other words, it should be fine to delete a non-existent object (like "rm -f"), and if Scylla is not sure if the deletion succeeded or not, we should retry it - I don't think we can really count on Seastar to do this for us, I don't think Seastar's retires capture all the possible failure modes.

**Comment by mykaul** [comment]
> S3 DELETE is idempotent by its nature, you can call it multiple times for the same object with the same 204 http response. Do we want to add such a test to our existing `s3_test`? @mykaul /@xemul

We probably should retry on anything that doesn't return to us 204, no?

**Comment by kreuzerkrieg** [comment]
> > S3 DELETE is idempotent by its nature, you can call it multiple times for the same object with the same 204 http response. Do we want to add such a test to our existing `s3_test`? @mykaul /@xemul
> 
> We probably should retry on anything that doesn't return to us 204, no?

Like what? `PUT` for example? We have another [issue](https://github.com/scylladb/scylladb/issues/19533) for it.

The concern was about the `DELETE`  - what if on http failure returned by S3 we will retry to delete and since in fact the object (maybe) was already deleted we will keep retrying indefinitely. Right?

**Comment by mykaul** [comment]
> > > S3 DELETE is idempotent by its nature, you can call it multiple times for the same object with the same 204 http response. Do we want to add such a test to our existing `s3_test`? @mykaul /@xemul
> > 
> > 
> > We probably should retry on anything that doesn't return to us 204, no?
> 
> Like what? `PUT` for example? We have another [issue](https://github.com/scylladb/scylladb/issues/19533) for it.
> 
> The concern was about the `DELETE` - what if on http failure returned by S3 we will retry to delete and since in fact the object (maybe) was already deleted we will keep retrying indefinitely. Right?

The original concern was that we do not get a (positive) response at all - the connection gets dropped (but the object was deleted). And in this case, we need to retry - which is OK - but  Scylla should make sure an object doesn't exist is just as a good as a 'managed to delete it'.

**Comment by xemul** [comment]
Not quite. The "make sure ... is idempotent" issues here are to handle automatic http request retrying.

S3 client creates http client like this: 

```c++
client::group_client::group_client(std::unique_ptr<http::experimental::connection_factory> f, unsigned max_conn)
        : http(std::move(f), max_conn, http::experimental::client::retry_requests::yes)
{           
}   
```

so in case http request `DELETE /object` fails, the http client may issue it again without asking s3 client. In that case it may happen that the object was deleted after the 1st attempt, so the 2nd one may return something else rather than `no_content` status.

**Comment by kreuzerkrieg** [comment]
> Not quite. The "make sure ... is idempotent" issues here are to handle automatic http request retrying.
> 
> S3 client creates http client like this:
> 
> ```c++
> client::group_client::group_client(std::unique_ptr<http::experimental::connection_factory> f, unsigned max_conn)
>         : http(std::move(f), max_conn, http::experimental::client::retry_requests::yes)
> {           
> }   
> ```
> 
> so in case http request `DELETE /object` fails, the http client may issue it again without asking s3 client. In that case it may happen that the object was deleted after the 1st attempt, so the 2nd one may return something else rather than `no_content` status.

No it cant, whatever happens on S3 side the `DELETE` request always returns 204, even if you try to delete object that never existed on S3

**Comment by kreuzerkrieg** [comment]
Closing after discussing it with @mykaul and @xemul
