### ISSUE TITLE
Alternator: warning 'correct liveness management'

### ISSUE THREAD

**Issue by doublex** [scylladb/scylladb#19807]
Warning in `journalctl`:
`
alternator-executor - Only 1 regular column from the base table should be used in the GSI key in order to ensure correct liveness management without assumptions 
`

Not sure if this is a problem with the alternator or the [compatibility docs](https://opensource.docs.scylladb.com/stable/alternator/compatibility.html).

Steps to reproduce:
````python
import boto3
dynamodb = boto3.resource(
    'dynamodb', endpoint_url='http://127.0.0.1:8000', 
    region_name='None', aws_access_key_id='None', aws_secret_access_key='None' )

response = dynamodb.create_table(
    TableName='test_table',
    AttributeDefinitions=[
        {
            'AttributeName': 'key',
            'AttributeType': 'S',
        },
        {
            'AttributeName': 'partition_key',
            'AttributeType': 'S',
        },
        {
            'AttributeName': 'range_key',
            'AttributeType': 'S',
        }
    ],
    KeySchema=[
        {
            'AttributeName': 'key',
            'KeyType': 'HASH',
        },
    ],
    GlobalSecondaryIndexes=[
        {
            'IndexName': 'index',
            'KeySchema': [
                {
                    'AttributeName': 'partition_key',
                    'KeyType': 'HASH',
                },
                {
                    'AttributeName': 'range_key',
                    'KeyType': 'RANGE',
                },
            ],
            'Projection': {
                'ProjectionType': 'KEYS_ONLY',
            },
        }
    ],
    BillingMode='PAY_PER_REQUEST',
    TableClass='STANDARD' )
````

**Comment by mykaul** [comment]
https://github.com/scylladb/scylladb/commit/0e6338ffd98e726f9c3ef1e72878c09617d0e8be introduced it and it's a warning only, no?

**Comment by doublex** [comment]
If it is just a warning:
Is there a knob to use a second non-key column in a `create materialized view` statement via `cqlsh`?

**Comment by nyh** [comment]
As @mykaul said this is just a warning that perhaps should not have been printed at all. Issue https://github.com/scylladb/scylladb/issues/6714 is about documenting why this limitation exists in CQL, and why we made an exception for Alternator and allowed it to create a view with two new key columns.

Unfortunately, there is currently no knob currently in CQL to allow it to create such a view - in the CQL statement, the CREATE MATERIALIZED VIEW statement is failed in this case without an option to allow it. It's trivial to disable this check if you compile Scylla yourself, but if you don't, you're out of luck.

Anyway, please clarify what problem you're reporting in this issue:
1. The warning in Alternator is bothering you?
2. Or, the error in CQL, you would have liked to change it to a warning (or add an option to allow it)?
 
When it's clearer what this issue is about, please update its title accordingly, and/or close the issue if it's not really a bug. Thanks.

**Comment by doublex** [comment]
Tried to workaround huge data duplication in Alternator (`:attrs`) due to missing `KEYS_ONLY` property - https://github.com/scylladb/scylladb/issues/5036
The issue was opened because this warning sounds frightening ("correct liveness").
