### ISSUE TITLE
docs: Issue on page Alternator: DynamoDB API in Scylla - a ToC atthe end of the page

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#19823]
I would like to report an issue on page https://opensource.docs.scylladb.com/branch-6.0/alternator/alternator

### Problem
The  table of contents (ToC) at the end of the page seems out of place. 
![image](https://github.com/user-attachments/assets/07f14341-6a57-4704-a0e7-dcff4f4a7ecb)

###  Suggest a fix

Remove the ToC, keep the two high level items as "Also See"
- Getting Started With ScyllaDB Alternator
- ScyllaDB Alternator for DynamoDB users

**Comment by nyh** [comment]
It seems @dgarcia360 added this TOC to that file in commit 1304f6a0bb4 whose comment message was "docs: fixed warnings". I don't know why the lack of TOC generated a warning, if it did (I see we have other pages without a TOC...).

Anyway, I agree that this TOC at the end of the document is really strange - I think it should either be completely removed (the TOC links on the right side of the page are enough!) or moved to the top of the page. I would completely remove it.

**Comment by dgarcia360** [comment]
> I don't know why the lack of TOC generated a warning

All pages must be included in at least one table of contents so that they are linked from the left-side navigation. Otherwise, Sphinx will raise a warning.

Normally, the TOC is defined in the index page of the module. In this case [`alternator/alternator.md`](https://github.com/scylladb/scylladb/blob/master/docs/index.rst?plain=1#L66)

The TOC can be hidden from the end of the page by using the `hidden` option:

![image](https://github.com/user-attachments/assets/be3ae888-04d0-4df5-8545-0c10bb592ff8)

**Comment by nyh** [comment]
> Also, I should move the Alternator docs next to the CQL reference, as agreed with @tzach.

What do you mean "next" - in the directory hierarchy? Why? Changing the directory hierarchy will, in my opinion, just confuse developers (who care about directory structure) and break existing links. Ordinary users do not care about the directory hierarchy - they just use links, and don't even look at the directory names in the URLs.

**Comment by tzach** [comment]
Next in the left Menu.
CQL and Alternator APIs are both developer, data APIs, and should be placed next to each other  
![image](https://github.com/user-attachments/assets/7d0218b2-eafd-4f02-9829-11cf53f2521b)
