### ISSUE TITLE
 tagged_tagged_integer::operator value_type() should be removed 

### ISSUE THREAD

**Issue by bitpathfinder** [scylladb/scylladb#20081]
Currently this tagged_tagged_integer allows implicit conversions from the `value_type`, which can potentially lead to mistakes, when this type is compared with other types with different semantics. An example of such an issue https://github.com/scylladb/scylladb/issues/20080, when an index_t was compared to a number, which is incorrect and led to a bug. We need to enforce explicit conversion for the type, so in such cases a compiler error will be raised.

**Comment by kbr-scylla** [comment]
cc @bhalevy WDYT?

**Comment by bhalevy** [comment]
I agree.  The whole point of the tagged integer type is ro provide strong type semantics.  Converting to a plain value type is the exception and should be done explicitly and with care, sometimes even worth a comment explaining why it is needed and safe.

Making it easier by implicit type conversion goes against the purpose of the tagged integer type.

**Comment by lersek** [comment]
As expected, the one-word change

~~~
diff --git a/utils/tagged_integer.hh b/utils/tagged_integer.hh
index dd432cdef2e8..0e231d47fd08 100644
--- a/utils/tagged_integer.hh
+++ b/utils/tagged_integer.hh
@@ -35,7 +35,7 @@ class tagged_tagged_integer {
     }

     value_type value() const noexcept { return _value; }
-    operator value_type() const noexcept { return _value; }
+    explicit operator value_type() const noexcept { return _value; }

     explicit operator bool() const { return _value != 0; }
~~~

produces many build errors. For fixing those up, I propose that we *remove* the conversion operator, rather than fixing it up.

Consider the following build error, for example:

~~~
gms/gossiper.cc:151:32: error: no matching function for call to 'abs'
  151 |         int32_t diff_version = ::abs(version - g_digest.get_max_version());
      |                                ^~~~~
~~~

The subtraction occurs between `version_type = tagged_tagged_integer<struct final, struct version_type_tag, int32_t>` values, which is supported. But, the resultant difference (which is also of `version_type`) no longer converts to `int` implicitly.

There are four ways to silence this:
1. `::abs((version - g_digest.get_max_version()).value())`
2. `::abs(static_cast<version_type::value_type>(version - g_digest.get_max_version()))`
3. `::abs(version.value() - g_digest.get_max_version().value())`
4. `::abs(static_cast<version_type::value_type>(version) - static_cast<version_type::value_type>(g_digest.get_max_version()))`

Choices 3 and 4 are poor because we want to operate in tagged integer space (for type safety) for as long as we can (and subtraction is supported between integers in the same tagged integer type).

And between choice 1 and 2, the first one wins, simply because it's a lot easier to read, IMO.

Thoughts?

**Comment by lersek** [comment]
@tchaikov can you advise on [the above](https://github.com/scylladb/scylladb/issues/20081#issuecomment-2284481610) perhaps? Thanks!

**Comment by bitpathfinder** [comment]
I agree, in this case value() duplicates the operator value_type(), so makes sense to leave only one.

**Comment by lersek** [comment]
... I believe to have implemented a v1 for this as much as possible; however, there are two obstacles to completing (and unit-testing) the series:
1. The patch series for this ticket will conflict with the patch series that fixes #20080 (or more precisely, this patch set *depends* on the set for #20080). The `preserve_log_entries > snap.idx` expression quoted in https://github.com/scylladb/scylladb/issues/20080#issue-2455675191 does not compile with the implicit conversion ("implicit untagging") removed; however, the right fix is not explicit untagging (that would just perpetuate the bug), but the actual fix of the bug (elimination of the offending line) -- per https://github.com/scylladb/scylladb/issues/20080.
2. I can't decide if a particular line of code has a similar (semantic) bug (in which case it should be fixed under https://github.com/scylladb/scylladb/issues/20080), or if it is functionally OK, just needs some cleanup for tagging/untagging (in which case it belongs to this ticket / my series for it). See https://github.com/scylladb/scylladb/issues/20080#issuecomment-2287140360.

**Comment by tchaikov** [comment]
> @tchaikov can you advise on [the above](https://github.com/scylladb/scylladb/issues/20081#issuecomment-2284481610) perhaps? Thanks!

i'd prefer the first solution. as to cast the tagged interger to the underlying type is practically repeating the type. unlike, for instance,  the `bool` operator for a smart pointer.

**Comment by tchaikov** [comment]
> (EDIT: needed to break up the markdown list into independent paragraphs, [because](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls#issues-and-pull-requests):
> 
> > If you reference an issue, pull request, or discussion in a list, the reference will unfurl to show the title and state
> 
> [How](https://github.com/isaacs/github/issues/1020#issuecomment-890502360) [annoying](https://github.com/orgs/community/discussions/4321)!)

could use:

- [#20080](#20080)

```
- [#20080](#20080)
```

**Comment by lersek** [comment]
> I believe to have implemented a v1 for this as much as possible

Turns out I need to update unit tests as well!

**Comment by lersek** [comment]
Can we express dependencies between github tickets? The patch set for this ticket now depends on fixing both #20080 and #20151.

**Comment by mykaul** [comment]
> Can we express dependencies between github tickets? The patch set for this ticket now depends on fixing both #20080 and #20151.

Nope :(

**Comment by tchaikov** [comment]
we could use task list to manually track the dependencies. better than nothing..

**Comment by lersek** [comment]
@bitpathfinder per prior discussion, can you please `s/made explicit/removed/` in the title? (I don't seem to have permission to do it.) Thanks.

**Comment by lersek** [comment]
@tchaikov 

> we could use task list to manually track the dependencies

I've decided to compete with the fixes for those (orthogonal) problems; whichever series gets merged first, the others will have to be rebased, due to conflicts :) (I'm happy rebase myself, of course.) Thanks!

**Comment by bitpathfinder** [comment]
> @bitpathfinder per prior discussion, can you please `s/made explicit/removed/` in the title? (I don't seem to have permission to do it.) Thanks.

Updated the title.

**Comment by lersek** [comment]
@bitpathfinder Apologies, no clue. I've never touched clang-tidy before.

**Comment by tchaikov** [comment]
> @tchaikov @lersek clang-tidy warns about that issue, but the check is not enabled currently: `'operator type-parameter-0-2' must be marked explicit to avoid unintentional implicit conversions (fix available)clang-tidy[google-explicit-constructor](https://clang.llvm.org/extra/clang-tidy/checks/google/explicit-constructor.html)' `
> 
> I believe enabling this and other checks(eg const correctness) in clang-tidy will contribute to avoiding many issues. Are there any plans of revising the checks that we have?

@bitpathfinder are you proposing add this check to https://github.com/scylladb/scylladb/blob/8fb746a5d23542d1a1874a6721e9585f0fe85658/.github/workflows/clang-tidy.yaml#L17 ?

**Comment by tchaikov** [comment]
@bitpathfinder i am for this idea. just need time to make it happen. please note, "bugprone-use-after-move" are already reporting a bunch of warnings. we addressed some of them, but there are some more to attend before we claim "bugprone-use-after-move" free.

**Comment by lersek** [comment]
I'm closing this one now, because #20159 has been merged. (I think I didn't properly word the blurb of #20159, and therefore github hasn't closed this one automatically now.) Wrt. the clang-tidy feature (per above discussion), I think a separate ticket would be best.

**Comment by lersek** [comment]
Uggghhh, I guess github doesn't even allow me to close this one??? @bitpathfinder can you please do the deed? Thanks.
