### ISSUE TITLE
Test suite topology_experimental_raft is misnamed

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#20193]
Raft is no longer experimental, so the suite should not indicate so.

**Comment by muthu90tech** [comment]
https://github.com/scylladb/scylladb/pull/20552

**Comment by nyh** [comment]
While we can "rename" topology_experimental_raft, the underlying problem is all the meaningless subdirectories in test/ - how is `topology_experimental_raft` different from `topology`,  `topology_custom`, and half a dozen other subdirectories? In other words the bug is https://github.com/scylladb/scylladb/issues/16026.

I think we should have one directory test/mtest (since the word "dtest" is taken ;-)), and "mtest" will be the new framework for "multinode" tests, or maybe "stest" for "scylla test" or "system test", or whatever - and all the "topology" tests - many of which have nothing to do with topology tests - should move there.

**Comment by nyh** [comment]
Concretely, I propose that we begin by merging the two directories test/topology_experimental_raft and test/topology_custom into one directory, called stest or something else (better ideas welcome) - because these two directories have (or can have) identical suite.yaml.

test/topology_random_failures and topology_tasks can probably be merged into it too.

test/topology still can't be merged into it because of the "initial_size" idea, but once we get rid of this misdirected idea (why should all the tests that need 3 nodes be in one directrory?) that could be merged to. But let's begin with the easy part.

**Comment by nyh** [comment]
@kostja @kbr-scylla @xtrey please weigh into this. I can send a patch to merge a couple of these test directories, but I don't want to "step on your feet" - so please consider doing it yourself (and you can have the honor of naming the new test suite - which doesn't need the words "topology" or "raft" in its name).

**Comment by mykaul** [comment]
> [@kostja](https://github.com/kostja) [@kbr-scylla](https://github.com/kbr-scylla) [@xtrey](https://github.com/xtrey) please weigh into this. I can send a patch to merge a couple of these test directories, but I don't want to "step on your feet" - so please consider doing it yourself (and you can have the honor of naming the new test suite - which doesn't need the words "topology" or "raft" in its name).

ping @kostja , @kbr-scylla , @xtrey

**Comment by kostja** [comment]
Now that my PR moving entire test.py to tablets is merged, I can look into this one.
