### ISSUE TITLE
Alternator - Query/Scan Operations return empty 'Items' field when hitting through many tombstones

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylladb#20474]
A user noted via Slack that querying an Index via Alternator sometimes exhibit and return a different behavior than DynamoDB.

For brevity, follows the relevant quote from the original report:

> (...) Everything works as expected except sometimes I am getting a LastEvaluatedKey with an empty array when I'm querying an index. This isn't the same behavior I was getting with Dynamodb so I'm curious if anyone knows what could be happening.
>
> The expected behavior is Alternator would return all the items it can and if there are leftovers then provide the last evaluated key (cursor) to continue "paginating" through the table. It looks like the cursor still works, because when I use it, it finally returns the orders but they should be returned initially (without using the cursor)

The user in question also shared the relevant response he observed:

![image](https://github.com/user-attachments/assets/b062d411-a370-41a6-ac40-b959b70e8d31)

As the user correctly states, this behavior is indeed different than DynamoDB. Note however, that - contrary to what I previously had pointed out, Alternator **correctly** fills the `LastEvaluatedKey` field to be used in subsequent page fetches. This issue only covers the specific situation where an empty page is returned to the client, and isn't a behavior present in AWS DynamoDB (notably because there is no concept of tombstones whatsoever in DDB).

The actual root cause for it is due to `query_tombstone_page_limit`. Given that Alternator uses the same paging infrastructure as CQL, scanning through an Index poses a higher chance of hitting a large tombstone run, given how MVs work. 

The situation still exists for base tables, but it is more likely to manifest in workloads with many deletes, or during Scan operations. 

It is not clear to me whether this is something we should consider simply as an implementation detail, or as a bug. Probably not a bug, as it works as designed from what I understand. Therefore, we probably want to document this.

@nyh @annastuchlik

**Comment by fee-mendes** [comment]
Btw @nyh after playing with this a bit I've came up with the following question:

Wouldn't it make sense to empty-page less often back to the client? With CQL prefetching is something doable, but with Alternator we are placing too much data on the wire (no compression, nor token/shard/whatever awareness) and - even then - most people just "page manually" by checking for the presence of `LastEvaluatedKey`.

So maybe this isn't a bug, but can be optimized. Alternator timeout is already high, and many SDKs have even higher timeouts.

**Comment by nyh** [comment]
Hi @fee-mendes thanks for taking the time to report the issue with all these details and also to edit it later with the more accurate details - this is very helpful (and I find these correctness issues to be very important).

First, I claim that as I think you came to the conclusion yourself, it is **not a bug** for Alternator to return an empty `Items` array in a request, if it correctly moved `LastEvaluatedKey` forward. In fact, DynamoDB can return empty pages too! But DynamoDB only does this when the Scan/Query have a `FilterExpression`: The DynamoDB documentation clearly explains (and I verified this experimentally) that when the scan has filtering, the `Limit` of the page - requested number of results (or default of 1MB) - is counted pre-filtering, and post-filtering there will be **fewer** results than requested in the page. This "fewer" can even be zero: Consider a filter expression that doesn't match any item at all, or matches just a few items out of millions being scanned. In this case, DynamoDB can return completely empty pages - an empty `Items`  with a valid increasing `LastEvaluatedKey` - and the SDK and user **must** be able to allow that. 

I have a test in the Alternator test suite which takes this to the extreme: I create a partition with 20 items, only half of them matching some filter expression. I then `Query` this partition with that filter expression, and set `Limit=1`. As the test verifies, DynamoDB (and also Alternator) will for each page read just one item, and since half of them don't match the filter - half of the returned pages will be completely empty (and the other half of the pages will have just one item).

So "empty pages" (`Items` is an empty array) is a completely valid case, and an application that thinks an empty `Items` marks the end of the iteration is simply wrong and will break if `FilterExpression` is introduced to the query.

However...

It is true is that if an application does **not use a `FilterExpression`**, then in DynamoDB it will always get back full pages (requested number of results set by `Limit`). DynamoDB does not have tombstones (it uses btrees, not LSM). In Alternator, we do have tombstones, and there is the theoretical possibility that you could have a million tombstones between two results, so Alternator can't afford to insist on always bring back full pages when there is no filter. So it doesn't. In theory the application shouldn't care - the paging API doesn't change for when `FilterExpression` is used or not used - nothing in the documentation suggests that paging code should behave different in the two cases.

Regarding the performance implication of the smaller returned pages:

Yes, if you wanted to get back pages of 1000 results and only get back 100 you waste some performance on the extra requests you need to get all the data. But I think this view misses the bigger problem: The bigger problem is that before Scylla prematurely ended that page, it had to process a very large number of tombstones - `query_tombstone_page_limit` (which defaults to 10,000 IIRC) - until it gave up and ended the page. This processing of all these tombstones is probably a more serious problem than the extra request. It suggests that the database has much more deleted data than undeleted data - a completely empty page suggest a consecutive string of 10,000 tombstones! And it suggests that the tombstones do not get GCed as we hope.

So why aren't tombstones getting GCed in this user's case?

I think it's not a coincidence that we're talking about scanning an **index** here (which is a materialized view). We do have a problem with tombstone GC in a materialized view, which @bhalevy just solved a few days ago in the pull request https://github.com/scylladb/scylladb/pull/20446 (that is still being discussed and reviewd, but I believe it to be correct). Basically, in some cases, a view with large partitions that continuously get updates will never GC any tombstones even if you do "major compaction" on the materialized view (while the workload still goes on). This is a real bug that needs to be solved. If this user is hitting this bug, they can have the number of un-GCed tombstones continue growing indefinitely.

To summarize,

1. I claim that empty `Items` is not a correctness bug, and a correctly written application needs to handle it properly (stopping iteration only when `LastEvaluatedKey` is no longer returned).
2. I can definitely mention this difference - the possibility of undersized pages in Query/Scan even without FilterExpression - in compatibilty.md. I don't think anybody should care about this difference, but maybe it's worth writing it down somewhere...
3. I claim that if un-GCed tombstones are causing undersized pages (or even empty pages), the existence of these tombstones are a bigger problem to performance than just the existence of undersized pages, so this problem should be solved.
4. So although we can increase `query_tombstone_page_limit` - perhaps 10,000 isn't as large as we can make it - I don't think it will help performance, and will just temporarily hide the tombstone problem until it hits this user even harder (with terrible scan performance and the disk being filled with tombstones).

**Comment by nyh** [comment]
> I think we can, although I think the executor could perhaps prefetch in the background until it reaches some live data to prevent an app back and forth paging and thus save on some latency.

Thanks. Please note my observation that this problem only becomes a noticeable problem when you have a huge number of tombstones, and those are already a big problem not just because of the extra page fetches but other reasons too. So what is bad about this user's workload is why we had so many tombstones, and https://github.com/scylladb/scylladb/pull/20446 fixed exactly that problem (when materialized views are involved - just like in the workload in this issue).
