### ISSUE TITLE
Equip backup task status with "progress"

### ISSUE THREAD

**Issue by xemul** [scylladb/scylladb#20653]
There's native support for progress in task manager API. It reports current/limit pair of numbers. Need to accumulate those and report back.

@Michal-Leszczynski , there  are several options here -- progress in number of sstables, files or bytes. Is manager looking for some particular one, or just any that can be converted into a progress bar would do?

**Comment by Michal-Leszczynski** [comment]
Rclone jobs return progress in the following form:
```json
    "JobProgress": {
      "type": "object",
      "properties": {
        "status": {
          "description": "status of the job",
          "type": "string",
          "enum": [
            "success",
            "error",
            "running",
            "not_found"
          ]
        },
        "started_at": {
          "description": "time at which job started",
          "type": "string",
          "format": "date-time"
        },
        "completed_at": {
          "description": "time at which job completed ",
          "type": "string",
          "format": "date-time"
        },
        "error": {
          "description": "string description of the error (empty if successful)",
          "type": "string"
        },
        "uploaded": {
          "description": "number of bytes that are successfully uploaded",
          "type": "integer"
        },
        "skipped": {
          "description": "number of bytes that were skipped",
          "type": "integer"
        },
        "failed": {
          "description": "number of bytes that failed transfer",
          "type": "integer"
        }
      }
    },
```
So SM is used to handling rclone job progress in bytes.
SM displays backup task progress in bytes and % values (percentages are calculated based on bytes).
So it would be preferable if Scylla reported the progress in bytes as well.

**Comment by Michal-Leszczynski** [comment]
So the progress is mostly about the "uploaded" bytes, but SM is also interested in the "skipped" and "failed" bytes.

In the first iteration, SM will be handling deduplication, so "skipped" bytes will be calculated on SM side
(I think that we assume that SM is calling Scylla backup API when all sstables in snapshot dir need to be uploaded).

**Comment by Michal-Leszczynski** [comment]
The "failed" bytes come from the fact, that rclone upload API does not stop the job on failure.
If a single file couldn't be uploaded because of some error, rclone will continue to upload other files while reporting the "failed" bytes progress.
This behavior is quite useful as it allows to perform most of the work at the first try. The retries will target only the files that failed to be uploaded (and we hope that there won't be much of them).

How does such behavior integrate with task manager API? Is it possible to make backup API follow the same way?
If not (meaning that Scylla backup API returns on first encountered error), I don't think that's a deal breaker.
SM could always report "failed" as limit-current when the Scylla backup API task finishes.

**Comment by Michal-Leszczynski** [comment]
The started_at, completed_at fields can be calculated on SM side, but it would be nice to get the error message on failure.

**Comment by Michal-Leszczynski** [comment]
cc: @karol-kokoszka
