### ISSUE TITLE
docs: Dark mode issue in some pages

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#20881]
I would like to report an issue on page https://opensource.docs.scylladb.com/branch-6.1/operating-scylla/procedures/config-change/index

Dark mode seems to miss part of the page

### Problem
![image](https://github.com/user-attachments/assets/8d3fdd82-5ef0-4749-a197-6368cbaaebc1)

**Comment by tzach** [comment]
@dgarcia360 FYI

**Comment by tzach** [comment]
as a side quest, we should move away from raw HTML

**Comment by dgarcia360** [comment]
In this case, the issue is not with the `raw::html` directive but with the component hardcoded on the directive: https://github.com/scylladb/scylladb/edit/master/docs/operating-scylla/procedures/config-change/index.rst

Instead, it should be using the panel box: https://sphinx-theme.scylladb.com/stable/examples/panel-box.html

@annastuchlik Let's coordinate to apply these changes.
