### ISSUE TITLE
test_view_build_status.test_view_build_status_migration_to_v2.debug failed with assertion failure

### ISSUE THREAD

**Issue by emdroid** [scylladb/scylladb#21060]
The test failed with assertion failure in #20394:

```
        # Check that new writes are written to the v2 table
        await create_mv(cql, "vt2")
        await wait_for_view_v2(cql, "ks", "vt2", 3)
    
        result = await cql.run_async("SELECT * FROM system.view_build_status_v2")
>       assert len(result) == 6
E       AssertionError: assert 5 == 6
E        +  where 5 = len([Row(keyspace_name='ks', view_name='vt2', host_id=UUID('7247f9dd-4161-4165-a71e-c0c33c4094fd'), status='SUCCESS'), Row(keyspace_name='ks', view_name='vt2', host_id=UUID('89adefb5-20de-4bb5-afa9-2a68f038c786'), status='SUCCESS'), Row(keyspace_name='ks', view_name='vt1', host_id=UUID('7247f9dd-4161-4165-a71e-c0c33c4094fd'), status='SUCCESS'), Row(keyspace_name='ks', view_name='vt1', host_id=UUID('89adefb5-20de-4bb5-afa9-2a68f038c786'), status='SUCCESS'), Row(keyspace_name='ks', view_name='vt1', host_id=UUID('af354425-16f8-4396-a5c3-4a5ab8f5fbdb'), status='SUCCESS')])

test/topology_custom/test_view_build_status.py:241: AssertionError
```

This ticket is to investigate if this might be caused by #20338.

**Comment by emdroid** [comment]
It appears that one row is missing, i.e. might be that some operation (that would create the entry) didn't complete.

**Comment by emdroid** [comment]
The logs:

[scylla-5491.log](https://github.com/user-attachments/files/17341188/scylla-5491.log)
[scylla-5502.log](https://github.com/user-attachments/files/17341190/scylla-5502.log)
[scylla-5521.log](https://github.com/user-attachments/files/17341189/scylla-5521.log)
[stacktrace.log](https://github.com/user-attachments/files/17341200/stacktrace.log)

**Comment by emdroid** [comment]
This also seems to be very rare occurrence, happened in one run 1 out of 100 and didn't reproduce in 500 runs locally (with pool_size=20)

**Comment by piodul** [comment]
The test creates a materialized view (vt2) after migration of view_build_status to raft. It waits until vt2 is built (via `wait_for_view_v2(cql, "ks", "vt2", 3)`) by waiting until there are as many rows for given view in the view_build_status_v2 table as there are nodes:

```python
async def view_is_built_v2(cql, ks_name, view_name, node_count, **kwargs):
    done = await cql.run_async(f"SELECT COUNT(*) FROM system.view_build_status_v2 WHERE keyspace_name='{ks_name}' \
                                 AND view_name = '{view_name}' AND status = 'SUCCESS' ALLOW FILTERING", **kwargs)
    return done[0][0] == node_count or None

async def wait_for_view_v2(cql, ks_name, view_name, node_count, **kwargs):
    await wait_for(lambda: view_is_built_v2(cql, ks_name, view_name, node_count, **kwargs), time.time() + 60)
```

But then it reads from the table again (`ql.run_async("SELECT * FROM system.view_build_status_v2")`) and there are only 2 rows for view `vt2`:

```
[
    Row(keyspace_name='ks', view_name='vt2', host_id=UUID('7247f9dd-4161-4165-a71e-c0c33c4094fd'), status='SUCCESS')
    Row(keyspace_name='ks', view_name='vt2', host_id=UUID('89adefb5-20de-4bb5-afa9-2a68f038c786'), status='SUCCESS')
    Row(keyspace_name='ks', view_name='vt1', host_id=UUID('7247f9dd-4161-4165-a71e-c0c33c4094fd'), status='SUCCESS')
    Row(keyspace_name='ks', view_name='vt1', host_id=UUID('89adefb5-20de-4bb5-afa9-2a68f038c786'), status='SUCCESS')
    Row(keyspace_name='ks', view_name='vt1', host_id=UUID('af354425-16f8-4396-a5c3-4a5ab8f5fbdb'), status='SUCCESS')
]
```

I suppose this is because of how `view_is_built_v2` function is written - it only queries one node at a time. It might happen that it queries `view_build_status_v2` on one node and decides that the view is built, but a different node didn't catch up with the leader yet and the second query will return outdated results.

The fix is to change `view_is_built_v2` to make sure that it returns only after all nodes saw that the view was fully built.
