### ISSUE TITLE
View building is performed in the gossip scheduling group

### ISSUE THREAD

**Issue by wmitros** [scylladb/scylladb#21232]
When we create a new view, the schema changes. This is done by raft, in the `gossip` scheduling group, and this triggers the view building to start. The call stack is something like:
`raft -> ... -> service::group0_state_machine::apply -> service::group0_state_machine::merge_and_apply() -> ... -> db::schema_tables::do_merge_schema() -> db::schema_tables::merge_tables_and_views() -> service::migration_notifier::create_view() -> db::view::view_builder::on_create_view() -> ...`
Because the view building can create a lot of work, it shouldn't be executed in the `gossip` scheduling group (in particular, to not interfere with raft commands execution). The user is also ready to wait for the view to build for a long time, without interfering with execution of their other statements, so it should be done in a separate, low priority scheduling group - for example the maintenance/streaming group, or perhaps a new one, just for view updates

**Comment by nyh** [comment]
Wow, good catch, how did you discover this?
I think in addition to fixing this specific issue, we should also:
1. Think whether other lengthy operations might also get the gossip scheduling group by mistake.
2. Write regression tests that verify that certain lengthy operations indeed mostly happen in the desired scheduling group. I already wrote a test like this for Alternator TTL after it turned out pieces of it reverted to another scheduling group. But we should also have tests that other operations like view building (for this issue), repair, compaction, tablet migration, etc., result in mostly work in the expected scheduling group and not some other one.
