### ISSUE TITLE
compaction_manager::stop might leak exceptions

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylladb#21298]
As seen in https://github.com/scylladb/scylladb/pull/20729#issuecomment-2440001278,
despite https://github.com/scylladb/scylladb/issues/19753 that has already been fixed
An exception can be thrown in compaction_manager::stop when stopping the task manager module
causing terminate since stop() is called in a deferred_action destructor.

**Comment by tchaikov** [comment]
@bhalevy hi Benny, I noticed that the `backport/*` labels were removed manually. Would you confirm if you're planning not to backport this fix? I've added the `backport/none` label to maintain consistency, so that the PR fixing this issue can have matching backport labels. Of course, please feel free to adjust this if I've misunderstood the intention here.

**Comment by bhalevy** [comment]
> [@bhalevy](https://github.com/bhalevy) hi Benny, I noticed that the `backport/*` labels were removed manually. Would you confirm if you're planning not to backport this fix? I've added the `backport/none` label to maintain consistency, so that the PR fixing this issue can have matching backport labels. Of course, please feel free to adjust this if I've misunderstood the intention here.

Sorry, I'm not sure how that happened.
I added the `ci stability` label using my phone so maybe I removed the backport labels by mistake this way.
Anyhow, as I said in https://github.com/scylladb/scylladb/pull/21299#issue-2616595311, I prefer to backport the fix to 6.2 and 6.1, on top of https://github.com/scylladb/scylladb/commit/8cc99973ebaf9d664c4c2a20b8ce3f1b2eb7100a

**Comment by dawmd** [comment]
Seen again in scylladb/scylladb#21352

**Comment by bhalevy** [comment]
Duplicate of #21159
