### ISSUE TITLE
test/topology_experimental_raft/test_alternator.py is flaky when running locally

### ISSUE THREAD

**Issue by wmitros** [scylladb/scylladb#21322]
When running `test_alternator` locally, it sometimes fails with `Exception: Failed to add servers`.
The server that's failing to add finishes with a message
```
inti - Startup failed: std::runtime_error (Snitch check failed. This node cannot join the cluster because it uses org.apache.cassandra.locator.SimpleSnitch and not org.apache.cassandra.locator.GossipingPropertyFileSnitch)
```
This seems to be caused by the `test_localnodes_multi_dc_multi_rack` case in the test, where we add servers with `'endpoint_snitch': 'GossipingPropertyFileSnitch'` in config. This is most likely a problem if it's the first case that we start - in that scenario, nodes in other cases are unable to start because they use `SimpleSnitch` instead of the `GossipingPropertyFileSnitch` as in this case.
When I removed all test cases from `test_alternator` and left only `test_localnodes_multi_dc_multi_rack` and one other (I used `test_alternator_ttl_scheduling_group`), the test fails almost half of the runs

The `test_alternator` was written in a way where many tests can run on the same cluster (`alternator3`), but the  `test_localnodes_multi_dc_multi_rack` doesn't seem to use it, so it's not clear why other test cases also seem to run on the same cluster

I haven't seen this in any CI/master jobs, so perhaps we have some workaround for this there, and it's only failing when running locally

**Comment by wmitros** [comment]
cc @nyh

**Comment by nyh** [comment]
Note: this issue is about `test/topology_experimental_raft/test_alternator.py` - it took me a while to figure out about *which* of the Alternator tests you were talking about ;-)

**Comment by wmitros** [comment]
> Note: this issue is about `test/topology_experimental_raft/test_alternator.py` - it took me a while to figure out about _which_ of the Alternator tests you were talking about ;-)

I updated the title. I didn't find the `test_alternator` string anywhere in this repo but I see we also have some dtests that are named similarly

**Comment by nyh** [comment]
Interesting. The test `test_localnodes_multi_dc_multi_rack` indeed configures a large (8 node) cluster with `GossipingPropertyFileSnitch` and property_file option to servers_add().  When this test ends, all eight servers are expected to shut down so the next test, whatever it is (e.g., test_alternator_ttl_scheduling_group and its "alternator3" fixture) can't possibly want to connect to that old cluster, because supposedly it is dead. But apparently, the 8-server cluster or some small part of it was NOT yet dead when the new test started.

So I am guessing that what happens is:
1. The framework does not wait **enough** time for the 8 servers to shut down (in your experience we see this problem only sometimes - but CI never experienced it).
2. Then, if some of these 8 servers are still alive, the framework when it asks for a manager_internal in the alternator3  for some reason decides to join the existing cluster instead of creating a new cluster. I have no idea why that happened - I assumed that manager_internal starts a new cluster every time it is executed (`manager_internal()`). Maybe @kostja can comment about that.

Both these things seem like bugs in the framework, the first one (not waiting enough time for all the servers to exit when a cluster is NOT reused) is probably easier and more important to fix. Or so I hope.

**Comment by kostja** [comment]
@xtrey @temichus @kbr-scylla  I think we saw something similar in another race? 
Haven't you @xtrey fixed this?

**Comment by nyh** [comment]
I looked at the relevant framework core (topology/conftest.py). The "manager" fixture used by `test_localnodes_multi_dc_multi_rack is a function-scoped fixture, meaning it is destroyed when the test ends. But I couldn't figure out where the cluster is actually being destroyed...  The manager fixture destruction code includes:
```
await manager_internal.stop()  # Stop client session and close driver after 
```
But this seems (beyond this comment, I also looked at  the ManagerClient::stop() implementation (pylib/manager_client.py)) that this indeed just stops the connections to the cluster, doesn't kill the cluster.

So as far as I see the cluster is NOT shut down at the end of the test.
The next question is - is the cluster shut down at the beginning of the **next** test, realizing that the previous cluster is irrelevant?
Do we wait for this shutdown? 
And how could starting a new cluster possibly connect to an existing cluster - even if for some reason the old one hasn't completed shutting down - how does the new cluster even find the nodes in the old cluster?

Sadly, the code that handles these things is long, spread over many files (and classes, and sockets) and I couldn't figure it out. @kostja please assign someone familiar with this code to debug it.

**Comment by xtrey** [comment]
> [@xtrey](https://github.com/xtrey) [@temichus](https://github.com/temichus) [@kbr-scylla](https://github.com/kbr-scylla) I think we saw something similar in another race? Haven't you [@xtrey](https://github.com/xtrey) fixed this?

This doesn't look familiar to me. I think I need some time for investigations why it happens.

**Comment by kbr-scylla** [comment]
Looks like this `alternator3` fixture is module-scope, and constructs its own `manager_internal()` instance. There are no `before_test` and `after_test` calls etc. Compare to the function-scope `manager` fixture used by the other tests:
```python3
@pytest.fixture(scope="function")
async def manager(request, manager_internal, record_property, mode):
    """Per test fixture to notify Manager client object when tests begin so it can
    perform checks for cluster state.
    """
    test_case_name = request.node.name
    run_id = request.config.getoption('run_id')
    tmp_dir = pathlib.Path(request.config.getoption('tmpdir'))
    xml_path: pathlib.Path = pathlib.Path(request.config.getoption('xmlpath'))
    suite_testpy_log = (tmp_dir /
                        mode /
                        f"{pathlib.Path(xml_path.stem).stem}.log"
                        )
    test_log = suite_testpy_log.parent / f"{suite_testpy_log.stem}.{test_case_name}.log"
    # this should be consistent with scylla_cluster.py handler name in _before_test method
    test_py_log_test = suite_testpy_log.parent / f"{test_case_name}.log"

    manager_internal = manager_internal()  # set up client object in fixture with scope function
    await manager_internal.before_test(test_case_name, test_log)
    yield manager_internal
    # `request.node.stash` contains a report stored in `pytest_runtest_makereport` from where we can retrieve
    # test failure.
    report = request.node.stash[PHASE_REPORT_KEY]
    failed = report.when == "call" and report.failed
    if failed:
        # Save scylladb logs for failed tests in a separate directory and copy XML report to the same directory to have
        # all related logs in one dir.
        # Then add property to the XML report with the path to the directory, so it can be visible in Jenkins
        failed_test_dir_path = tmp_dir / mode / "failed_test" / f"{test_case_name}"
        failed_test_dir_path.mkdir(parents=True, exist_ok=True)
        await manager_internal.gather_related_logs(
            failed_test_dir_path,
            {'pytest.log': test_log, 'test_py.log': test_py_log_test}
        )
        with open(failed_test_dir_path / f"stacktrace", 'w') as f:
            f.write(report.longreprtext)
        if request.config.getoption('artifacts_dir_url') is not None:
            # get the relative path to the tmpdir for the failed directory
            dir_path_relative = f"{failed_test_dir_path.as_posix()[failed_test_dir_path.as_posix().find('testlog'):]}"
            full_url = f"<a href={request.config.getoption('artifacts_dir_url')}/{dir_path_relative}>failed_test_logs</a>"
            record_property("TEST_LOGS", full_url)

    cluster_status = await manager_internal.after_test(test_case_name, not failed)
    await manager_internal.stop()  # Stop client session and close driver after each test
    if cluster_status["server_broken"]:
        pytest.fail(f"test case {test_case_name} leave unfinished tasks on Scylla server. Server marked as broken")
```

important points:
- `after_test` is responsible for marking cluster as dirty in some cases
- `before_test` is responsible for returning cluster back to pool and getting new cluster if the previous one is dirty

**Comment by kbr-scylla** [comment]
BTW I'm not sure if it's correct to construct a private `manager_internal`, it's a session-scope fixture that connects to a `ScyllaClusterManager` on the test.py side created for this session (test file). All communication with that `ScyllaClusterManager` should be serialized through that single `manager_internal`.

It seems like the `alternator3` fixture makes some wrong assumptions about the interface provided by `manager`/`manager_internal` etc.

Basically the architecture of topology framework is:
- we have a `ScyllaClusterManager` per session (test file run)
- all test cases are using that `ScyllaClusterManager` **sequentially**. It manages one cluster at a time. Between test cases in given file the cluster might changed because it was dirtied by the previous test case.
- the `pytest` side of the test run connects to `ScyllaClusterManager` through `manager_internal`.
- There is a wrapper `manager` per test case that asks `manager_internal` to replace the manager cluster if necessary between test cases
- if cluster was replaced by some test case, no further test case might use it

Now apparently `alternator3` fixture assumes that it can get a cluster and use it for the whole duration of the session. But that assumption is wrong if a test case that does not use `alternator3`, but uses the `manager` fixture instead, replaces the cluster (calls `manager_client.after_test + before_test`; the next case that uses `alternator3` then operates on a different cluster

**Comment by nyh** [comment]
Thanks @kbr-scylla. So, I guess the immediate problem is that the alternator3 fixture doesn't call `before_test` - because that function is supposed to delete the old cluster, and it isn't called (curiously, since the test does pass most of the time, I guess it the old cluster does get deleted but just isn't waited for?).

Regarding the bigger problem: Please help me come up for a way to have a session-scope fixture which keeps a cluster alive for multiple tests that want to use the same cluster. I.e., a correct way to do this "alternator3" fixture. Not only do I need it for test_alternator.py, I claim that we **urgently** need this feature before test/topology_experimental_raft becomes as unusable as dtest. It's a disaster that almost all tests in test/topology_experimental_raft and test/topology_custom work like dtest - creating a cluster, using it for a fraction of a second and then shutting down the cluster. This approach may have made some sense in tests that really do topology changes so mess up the cluster - but noawadays only a minority of the multi-node tests actually want to mess up the cluster.

**Comment by nyh** [comment]
> Basically the architecture of topology framework is:
> 
>     * we have a `ScyllaClusterManager` per session (test file run)
> 
>     * all test cases are using that `ScyllaClusterManager` **sequentially**. It manages one cluster at a time. Between test cases in given file the cluster might changed because it was dirtied by the previous test case.

This is a very unfortunate assumption, because it means that if I have in a test file 7 tests that need a one-node cluster and 7 other tests that need a 3-node cluster, there is no way to create both clusters and then run the tests on them. So you end-up with dtest-like code where each test creates and destroys its cluster, and what could take a few seconds now takes minutes :-(

There is no reason why it can't work exactly like I wanted it to work:
1. A "manager" gives you a new cluster every time it is initialized.
2. Some tests will ask for a new manager (the "manager" fixture you already have) and get a new cluster
3. Other tests will save the cluster to be shared between different tests.

Why is there a limitation of only one cluster being alive at a time? I didn't think you have such a limitation!

**Comment by kbr-scylla** [comment]
> Thanks @kbr-scylla. So, I guess the immediate problem is that the alternator3 fixture doesn't call before_test - because that function is supposed to delete the old cluster, and it isn't called (curiously, since the test does pass most of the time, I guess it the old cluster does get deleted but just isn't waited for?).

I suspect it's just reusing whatever cluster it got from previous test case as-is. Well, it's simply adding 3 new servers to it. Could be that the first test case which uses `alternator3` fixture, if there was a previous test case that used `manager`, then `alternator3` will get the cluster from that previous test case and add 3 new servers.

> Regarding the bigger problem: Please help me come up for a way to have a session-scope fixture which keeps a cluster alive for multiple tests that want to use the same cluster. I.e., a correct way to do this "alternator3" fixture. Not only do I need it for test_alternator.py, I claim that we urgently need this feature before test/topology_experimental_raft becomes as unusable as dtest. It's a disaster that almost all tests in test/topology_experimental_raft and test/topology_custom work like dtest - creating a cluster, using it for a fraction of a second and then shutting down the cluster. This approach may have made some sense in tests that really do topology changes so mess up the cluster - but noawadays only a minority of the multi-node tests actually want to mess up the cluster.

I think our best bet is to wait on the rearchitecturization that @temichus and @xtrey are doing.

> Why is there a limitation of only one cluster being alive at a time? I didn't think you have such a limitation!

Different sessions (test files) can have different clusters, but that is the limitation within a test file, and it's just a "feature" of the current bad design.

**Comment by xtrey** [comment]
Tests in one file can reuse and usually using the same cluster. test.py recreating clusters between files. In current architecture, there is no easy way to reuse cluster between files. It will be possible once we will have one global cluster pool size. This is actually where we are going with small steps.

**Comment by nyh** [comment]
> Tests in one file can reuse and usually using the same cluster. test.py recreating clusters between files. In current architecture, there is no easy way to reuse cluster between files. It will be possible once we will have one global cluster pool size. This is actually where we are going with small steps.

Reusing clusters between files is not a major issue, unless you subscribe to the Javaesque notion that every test function needs to be in a separate file (I certainly don't), although it has a solution to (session-scoped fixtures). My more major wish is to avoid the dtest-like situation where each test _function_ needs to start and stop a cluster (which can take a long time), which leads you to one (or both!) of two bad results:
1. People write very long test functions that check 20 different things, just to avoid creating and stopping cluster for every small check.
2. People just live with the fact that while test/alternator runs 1000 tests in 30 seconds, in other frameworks it's normal that 1000 tests should take 30 minutes.

This is why I wanted that "alternator3" fixture - I was hoping that that test file could eventually contain many more tests that all could use the same 3-node Alternator cluster.

Let's get down to earth for a moment:

Today, there is just **one test function** that uses that "alternator3" fixture. I wrote it more as a proof of concept. If we have given up on this idea (or think we're just not ready to implement), it is very easy to change that test to remove the alternator3 fixture, and just create a 3-node cluster in the single test that uses it - just like all other tests in the test/topoplgy_experimental_raft framework.

**Comment by nyh** [comment]
I'll prepare a patch to drop the alternator3 fixture.
