### ISSUE TITLE
nodetool refresh error

### ISSUE THREAD

**Issue by infordb** [scylladb/scylladb#2160]
Scylla version (or git commit hash):

I tested nodetool refresh.
I accidentally set file ownership to root and performed a refresh
-rw-r--r--.  1 root   root     78 Mar 13 16:30 test-users2-ka-14-Data.db

As a result, all functions of the scylla have been stopped (gossip, transport)
I ran the following command, but gossip is still stalled 
  $nodetool enablebinary  ==> success
  $nodetool enablegossip  ==> fail

After a while the scylla was automatically restarted and The scylla is now ready for service.
The odd thing is that the file owner is still root

It seems to be a problem that minor mistakes turn into such big problems

<< stop log >>
Mar 13 16:13:48 test02 scylla[7216]:  [shard 5] storage_service - Loading new SSTables for test.users2...
Mar 13 16:13:48 test02 scylla[7216]:  [shard 5] storage_service - Shutting down communications due to I/O errors until operator intervention
**Mar 13 16:13:48 test02 scylla[7216]:  [shard 5] storage_service - Loading of new tables failed to test.users2 due to Storage I/O error: 1: Operation not permitted**
Mar 13 16:13:48 test02 scylla[7216]:  [shard 5] storage_service - CF test.users2 at shard 5 had SSTables writes disabled for 17793 usec
Mar 13 16:13:48 test02 scylla[7216]:  [shard 4] storage_service - CF test.users2 at shard 4 had SSTables writes disabled for 16788 usec
Mar 13 16:13:48 test02 scylla[7216]:  [shard 2] storage_service - CF test.users2 at shard 2 had SSTables writes disabled for 17766 usec
Mar 13 16:13:48 test02 scylla[7216]:  [shard 1] storage_service - CF test.users2 at shard 1 had SSTables writes disabled for 17808 usec
Mar 13 16:13:48 test02 scylla[7216]:  [shard 7] storage_service - CF test.users2 at shard 7 had SSTables writes disabled for 17791 usec
Mar 13 16:13:48 test02 scylla[7216]:  [shard 6] storage_service - CF test.users2 at shard 6 had SSTables writes disabled for 16821 usec
Mar 13 16:13:48 test02 scylla[7216]:  [shard 0] storage_service - Stop transport: starts
Mar 13 16:13:48 test02 scylla[7216]:  [shard 0] gossip - My status = NORMAL
Mar 13 16:13:48 test02 scylla[7216]:  [shard 0] gossip - Announcing shutdown
Mar 13 16:13:48 test02 scylla[7216]:  [shard 3] storage_service - CF test.users2 at shard 3 had SSTables writes disabled for 17717 usec
Mar 13 16:13:48 test02 scylla[7216]:  [shard 0] storage_service - Node 10.240.33.96 state jump to normal
Mar 13 16:13:48 test02 scylla[7216]:  [shard 0] storage_service - CF test.users2 at shard 0 had SSTables writes disabled for 18999 usec
Mar 13 16:13:51 test02 scylla[7216]:  [shard 0] storage_service - Stop transport: stop_gossiping done
Mar 13 16:13:51 test02 scylla[7216]:  [shard 0] storage_service - Thrift server stopped
Mar 13 16:13:51 test02 scylla[7216]:  [shard 0] storage_service - CQL server stopped
Mar 13 16:13:51 test02 scylla[7216]:  [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
Mar 13 16:13:51 test02 scylla[7216]:  [shard 0] storage_service - messaging_service stopped
Mar 13 16:13:51 test02 scylla[7216]:  [shard 0] storage_service - Stop transport: shutdown messaging_service done
Mar 13 16:13:51 test02 scylla[7216]:  [shard 0] storage_service - stream_manager stopped
Mar 13 16:13:51 test02 scylla[7216]:  [shard 0] storage_service - Stop transport: shutdown stream_manager done
Mar 13 16:13:51 test02 scylla[7216]:  [shard 0] storage_service - Stop transport: auth shutdown
Mar 13 16:13:51 test02 scylla[7216]:  [shard 0] storage_service - Stop transport: done

<< restart log >>
Mar 13 16:25:59 test02 scylla[10584]: Scylla version 1.6.0-20170202.7e1b245 starting ...
Mar 13 16:25:59 test02 scylla[10584]:  [shard 0] init - Scylla API server listening on 10.240.33.96:10000 ...

<< CQL log > >
cqlsh:test> select * from users2;
NoHostAvailable: ('Unable to complete the operation against any hosts', {})

**Comment by slivne** [comment]
The only method to recover from this is to restart a node.

Once scylla hits an IO error the node will "disconnect" from the cluster
and close the client interface ports.

It will stay "up" and report metrics and allow rest/jmx probing.

**Comment by nyh** [comment]
Three comments:

1. The message "Mar 13 16:13:48 fomstap02 scylla[7216]: [shard 5] storage_service - Shutting down communications due to I/O errors until operator intervention" is the key for the user understanding what happened, and yet it is only marked at "warn" level so the user didn't notice its importance. Should it be "Error"?  Also, it's confusing that this message comes *before* the message which says which I/O error has happened.

2. The sstable files he showed were readable, even if owned by root (it had the world read permission). We shouldn't have failed reading them! Are we opening files for both reading and writing even if we only intend to read from them?

3. As usual, it's bad we report an I/O error without reporting on which file or operation on it it actually happened.

**Comment by tgrabiec** [comment]
Should sstable import be excluded from shutdown-on-io-error logic? User will be notified that import failed, database would be left in a consistent (pre-import) state.

**Comment by slivne** [comment]
We should fail if we only have read permission - compaction may need to
remove the file later - so there is no point in allowing to boot/work on
files that we only have read access to them and failing later when
compaction can not remove them.

We can't exclude single files we are not able to import,  since the user
may be importing files that have a relation between them (e.g. one file has
data and the one we could not import has a tombstone). So a single rotten
apple (sstable) means we should not import any.

So, if we want to improve import, we can have an enhancement do a
"pre-scan" before adding the files and check that all the files are "legit"
(have permission, not missing a component, etc.)

Better logging is something that we should do.

**Comment by nyh** [comment]
I inspected the code, and couldn't find any place where we open sstables with read-write, so I still wonder where the actual failure is coming from. It can't be compaction, because the error message is coming from the sstable reading, not the compaction... By the way, since compaction is optional, I don't think that failing it or removing a file at its end has to be fatal.

**Comment by tgrabiec** [comment]
2017-03-13 12:27 GMT+01:00 Shlomi Livne <notifications@github.com>:

> We should fail if we only have read permission - compaction may need to
> remove the file later - so there is no point in allowing to boot/work on
> files that we only have read access to them and failing later when
> compaction can not remove them.
>
> We can't exclude single files we are not able to import, since the user
> may be importing files that have a relation between them (e.g. one file has
> data and the one we could not import has a tombstone). So a single rotten
> apple (sstable) means we should not import any.
>
> So, if we want to improve import, we can have an enhancement do a
> "pre-scan" before adding the files and check that all the files are "legit"
> (have permission, not missing a component, etc.)
>

We should be already attaching all imported sstables atomically, so that
partial data is not visible. If error is encountered, we simply not attach
anything and return failure to the user (import is atomic).

**Comment by tzach** [comment]
To summarize:
Scylla failed to read file with the wrong permission, and as a result executed the generic disk error policy of stopping the node.  This is the correct policy - as long as it provides clear logging to the users about what happened.
@slivne @nyh @tgrabiec do you agree?

**Comment by tgrabiec** [comment]
@tzach It seems better to only fail the refresh command rather than stopping the whole node.

**Comment by tzach** [comment]
@tgrabiec make sense
Scylla should propagate the error back to the `nodetool refresh` operation and print the error to the terminal (in addition to the log)

**Comment by glommer** [comment]
On Mon, Mar 13, 2017 at 6:17 AM, Tomasz Grabiec <notifications@github.com>
wrote:

> Should sstable import be excluded from shutdown-on-io-error logic? User
> will be notified that import failed, database would be left in a consistent
> (pre-import) state.
>

Yes, that would be the sane way in my view.

**Comment by glommer** [comment]
On Mon, Mar 13, 2017 at 7:27 AM, Shlomi Livne <notifications@github.com>
wrote:

> We should fail if we only have read permission - compaction may need to
> remove the file later - so there is no point in allowing to boot/work on
> files that we only have read access to them and failing later when
> compaction can not remove them.
>
> We can't exclude single files we are not able to import, since the user
> may be importing files that have a relation between them (e.g. one file has
> data and the one we could not import has a tombstone). So a single rotten
> apple (sstable) means we should not import any.
>

Isn't that equivalent to a lost mutation ?


>
> So, if we want to improve import, we can have an enhancement do a
> "pre-scan" before adding the files and check that all the files are "legit"
> (have permission, not missing a component, etc.)
>
>
That makes sense.

**Comment by raphaelsc** [comment]
On Mon, Mar 13, 2017 at 7:17 AM, Tomasz Grabiec <notifications@github.com>
wrote:

> Should sstable import be excluded from shutdown-on-io-error logic? User
> will be notified that import failed, database would be left in a consistent
> (pre-import) state.
>

We do that if user does refresh for files in cf's upload dir. We probably
need to do it too when reshuffling sstables in cf's root dir.

**Comment by raphaelsc** [comment]
On Mon, Mar 13, 2017 at 8:48 AM, nyh <notifications@github.com> wrote:

> I inspected the code, and couldn't find any place where we open sstables
> with read-write, so I still wonder where the actual failure is coming from.
> It can't be compaction, because the error message is coming from the
> sstable reading, not the compaction... By the way, since compaction is
> optional, I don't think that failing it or removing a file at its end has
> to be fatal.
>
I think the problem happens when reshuffling column family directory, which
does linking and unlinking (lack of permission here results in shutdown) of
files. We also need to make the operation is transactional to make sure
files aren't left in an inconsistent state, when reshuffling. As with
upload dir, we need to make sure an error (permission, lack of component)
won't result in shutdown either.

**Comment by slivne** [comment]
scylladb/scylla-tools-java#26

**Comment by tzach** [comment]
Can be fixed after rebasing of java-tools on 3.11 https://github.com/scylladb/scylla/issues/3686

**Comment by slivne** [comment]
Java tools were moved in 4.1 - pushing this out 

@elcallio can you please look at this now that the tools have been updated

**Comment by kostja** [comment]
The permission problem is addressed.
