### ISSUE TITLE
Add API to change local compaction strategy

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#2219]
*Installation details*
Scylla version (or git commit hash): 1.7

Update compaction strategy via REST (and JMX) API

reference:
https://issues.apache.org/jira/browse/CASSANDRA-9965

**Comment by slivne** [comment]
@amnonh - can you try and look at what this api is connected to

**Comment by tzach** [comment]
@amnonh ping

**Comment by amnonh** [comment]
I'm not sure what the issue is about,
under the column_family API there is an endpoint to set a compaction class strategy, for example, 
to set the compaction strategy of ``keyspace1:standard1`` to Size Tiered, you can run:
``curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' 'http://172.17.0.8:10000/column_family/compaction_strategy/keyspace1%3Astandard1?class_name=SizeTieredCompactionStrategy'``

From the imlementation perspective it calls the ``set_compaction_strategy`` method of each table

**Comment by tzach** [comment]
No clear why REST API is required, when CQL ALTER TABLE can be used.
