### ISSUE TITLE
table directory opened each time an sstable is sealed

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylladb#2399]
Right now, each time we seal an sstable, we open, flush, and close it.  But we could keep it open indefinitely (perhaps shared among shards).

**Comment by nyh** [comment]
By the way,  sstable::write_toc() also does this open-and-close thing.

**Comment by bhalevy** [comment]
We currently call `sync_directory` (that opens, flushes, and closes the dir) several times in the sstables lifetime:

From `filesystem_storage::open`:
https://github.com/scylladb/scylladb/blob/f1819419cc087edefaf14626ff3f8ad48192fa3d/sstables/storage.cc#L161-L163

Many times in `filesystem_storage::create_links_common`

From `filesystem_storage::wipe`:
https://github.com/scylladb/scylladb/blob/f1819419cc087edefaf14626ff3f8ad48192fa3d/sstables/storage.cc#L447

**Comment by lersek** [comment]
or just keep referring to `.get()` for the sake of each flush -- then the first flush may wait (or may not, dependent on whether the opening has completed by then), and the rest of the flushes will launch immediately?

**Comment by lersek** [comment]
related seastar commits (background for splitting up `sync_directory()`):

1. 50e2f24dfab1 ("core: add recursive_touch directory", 2015-07-12)
2. d162922e03d1 ("core: simplify do_flush_directory", 2015-07-12)
3. 495822f52d9b ("core: fix close-after-free in recursive mkdir", 2015-07-28)

**Comment by lersek** [comment]
More key commits:
1. a7b6c1110f42 ("sstables: do not require seal_sstable() to be run in thread", 2016-07-07)
2. 8f417b802193 ("sstable: coroutinize seal_sstable", 2022-02-14)
3. 1efddc228d32 ("sstable: Do not nest io-check wrappers into each other", 2023-11-27)

**Comment by lersek** [comment]
It's one thing if a particular member function calls `sync_directory` multiple times on the same directory; we can then at least reuse the open directory object similarly to what can be seen today (as of commit a230ecc4ebfa) in `filesystem_storage::seal()`. But if we want to pre-open the `_dir` directory so that it can be reused across multiple member function calls (just for flushing), what is the best place & time to do that? For example, I couldn't locate where the directory is *created* in the first place. (Because opening `_dir` right after it is created could be an idea.) Thanks.

**Comment by bhalevy** [comment]
@lersek we create the `data` directory, if needed, when scylla starts, but most of the traffic of creating and deleting files is in the table directory and below it.
We potentially create it in `init_table_storage`:
```
            co_await io_check([&dir] { return recursive_touch_directory(dir); });
```

But it seems to me that a better place to keep the open directory would be from `populate_keyspace` and `table_populator` that opens the table directory and its sub-directories.
We pass a `global_table_ptr` to the `table_populator` and I think that the `table` object could be a good place to keep the open directories.

This should be integrated somehow with the sstables' `storage` and be used by `filesystem_storage::open` / `touch_temp_dir` (called when the sstable is created), and maybe also in `create_pending_deletion_log` when multiple sstables are deleted atomically.
We may want to create a pending_delete directory in advance in `init_table_storage` and keep it open as well, since it's used pretty often by compaction.

`filesystem_storage::move` can also benefit from open directory caching, but it's used more rarely, after repair when the table has materialized views.  There, the sstables are first created in the `staging` sub-directory, and later moved to the table base directory after view update generation finishes processing them.

All that said, let's consider also a more generic solution of caching open directory objects where we can lookup a directory by path, and if it's missing in the cache, create it, and keep it opened for later.
Then we could consult this cache in the common paths mentioned above.

**Comment by xemul** [comment]
Whenever an sstable is opened (e.g. its Data file), its kernel file object holds dentry (and inode) and the dentry itself holds parent dentry in cache. So opening a directory for sync always happens from dcache and doesn't do any IO (we're only interested in XFS case). Why is this a problem at all? @avikivity
