### ISSUE TITLE
Updates to system tables should be batched

### ISSUE THREAD

**Issue by glommer** [scylladb/scylladb#4075]
Every operation that changes system tables need to be flushed to disk before they can be acknowledged.
However, some of those operations could be batched and flushed just once.

One example is updating system.local when tables are dropped: if we are dropping an entire keyspace, every table being dropped will generate an update, in its own memtable which will then need to be compacted. This generates a lot of extra load.

We could do automatic batching - batching every operation that happens within, say, 200ms (I am here assuming that updates to system tables are not super latency critcal), or we could do explicit batching with some operations clearly marking the beginning or end of the batch procedure.

**Comment by elcallio** [comment]
The "problem" (if I'm reading this and adjoining issues correctly) is not really "batching" but that you end up doing parallel flushes on all shards to ensure data is on disk. Note that at least a little bit of at least contention is removed by now storing truncation records in a separate, clustered table. Because this is really the only "big" concurrent junk happening in drop tables. 
Technically, you could potentially have a guard object for some tables, saying flushes are deferred, and create it in the calling schema update (in the master shard), and then when the drops are done in all shards, release the guard -> do actual flush. 
This does technically create a risk of breaking the drop/truncation though, since we cannot rely on CL for this. Though I guess in some way the problem already exists, in that we could crash half-way through the shards.
More to the point though, I feel strongly that optimizing for what should be a rare operation (drop) feels wrong. Making sure flushes stall instead of OOM, yes, please, but me thinks if user drops keyspace, user should have the satisfaction of watching some chugging...

**Comment by eliransin** [comment]
I am aware that it is not really a `commitlog` issue, but if there is a solution for this it will probably heavily rely on commitlog.

**Comment by elcallio** [comment]
Given that schema updates have changed almost 100% since this was created (hello raft), I am gonna close this for now.
