### ISSUE TITLE
Commitlog: why not save the cf-mapping once per segment

### ISSUE THREAD

**Issue by slivne** [scylladb/scylladb#4334]
Vlads question from https://github.com/scylladb/scylla/issues/4122

> 
> I would like to ask you something: I noticed that commitlog resets column family mappings every "cycle". This means that if a segment has undergo a few "cycles" it would save information of the same CF a few times. In the use case I described above (default c-s schema) this is the case and I saw that some segments have the same cf mapping is saved ~250 times!!!
> I wonder what's the reason to save it more than once per-segment?

**Comment by elcallio** [comment]
You need to ask @pdziepak exactly why the "forget_schema_versions" call is made on every segment chunk. 
My guess however would be that we at some point skipped parts of the file for replay and wanted to ensure we have required schema info in every possible begin position (i.e. chunk start). 
However, we now at least always go through all the mutations, even if we skip them, so it should be perfectly ok to not reset the schemas on every chunk...

**Comment by pdziepak** [comment]
Well, we would have to ask me-3-years-ago since me-today isn't totally sure either. Calle's guess seems very reasonable and it looks like we do skip entries in some cases ([1], [2]), so repeating the schema information would increases the chances that we are able to read as much as possible. I don't think there is much value in that, though. It is most likely perfectly fine to write schema info only once per segment.

[1] https://github.com/scylladb/scylla/blob/a66a5d423abd0fc3687fefc4a069c2f0827fcf1a/db/commitlog/commitlog.cc#L1937-L1945
[2] https://github.com/scylladb/scylla/blob/a66a5d423abd0fc3687fefc4a069c2f0827fcf1a/db/commitlog/commitlog.cc#L1958-L1965

**Comment by elcallio** [comment]
Thanks for the reminder there. So the final answer is: because a segment can have (tolerates) partial corruption - i.e. broken chunks. If a schema is located in a broken chunk and this is corrupted, we'd loose all data related to this table for the rest of the table. 

We could consider accepting this (partial file corruption is rare). But it should not be done lightly and we should get some stats on data vs. schema weight proper (is it really a problem). 

It might btw be more of an issue in a batch-log mode world, if chunks become smaller.
