### ISSUE TITLE
Extend Replication Factor flexibility

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#4412]
*Installation details*
Scylla version (or git commit hash): 3.1

In some cases, the out of the box RF semantic is not good enough. 
For example, a user might want to use RF=X (where X > 3), or RF=ALL-Y

See 
https://www.slideshare.net/DataStax/maintaining-consistency-across-data-centers-randy-fradin-blackrock-cassandra-summit-2016

**Comment by tzach** [comment]
https://github.com/scylladb/scylla/issues/4210

**Comment by haaawk** [comment]
Can this be closed because #4210 is merged, @tzach ?

**Comment by tzach** [comment]
AFAIU, this feature requests give more flexibility than #4210 
For example, RF=ALL-Y. More examples in the slides.

**Comment by nyh** [comment]
Do we still want this issue open?

It's a nice idea, but sadly in the CQL protocol the consistency levels aren't strings like "ONE", etc., the protocol actually specifies all the consistency levels that exist:

```
   [consistency]  A consistency level specification. This is a [short]
                   representing a consistency level with the following
                   correspondance:
                     0x0000    ANY
                     0x0001    ONE
                     0x0002    TWO
                     0x0003    THREE
                     0x0004    QUORUM
                     0x0005    ALL
                     0x0006    LOCAL_QUORUM
                     0x0007    EACH_QUORUM
                     0x0008    SERIAL
                     0x0009    LOCAL_SERIAL
                     0x000A    LOCAL_ONE
```

So we can't easily support "FOUR". Theoretically we could decide that 0x000B means "FOUR", but then we'll need to support this mapping in all drivers, and risk the possibility that some newer Cassandra will start to use B as well, but for something different and not FOUR.

**Comment by nyh** [comment]
It's not clear to me what this issue is asking for, @tzach can you please explain (or close if you think it's no longer relevant)? You are talking about **replication factor**, but the slides you point to complain not about the replication factor, but about the **consistency level** options (e.g., the fact that they don't have ALL_BUT_ONE or SIX consistency levels.

If adding more consistency level options is what you want (?), this is a problem, because the CQL protocol ends the consistency levels as a short list of known codes:
```
   [consistency]  A consistency level specification. This is a [short]
                   representing a consistency level with the following
                   correspondance:
                     0x0000    ANY
                     0x0001    ONE
                     0x0002    TWO
                     0x0003    THREE
                     0x0004    QUORUM
                     0x0005    ALL
                     0x0006    LOCAL_QUORUM
                     0x0007    EACH_QUORUM
                     0x0008    SERIAL
                     0x0009    LOCAL_SERIAL
                     0x000A    LOCAL_ONE
```

Although in theory we could add 0x000B to mean something new (like SIX), we would need to modify all the drivers to support the new features, and we will risk a future Cassandra introducing the same 0x000B to mean something else and we would not be able to support it.
