### ISSUE TITLE
CQL version should conform to capabilities

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylladb#4599]
Currently we report cql version 3.3.1 [defined here](https://github.com/scylladb/scylla/blob/master/cql3/query_processor.cc#L65)
We should make sure that we conform to: [Cassandras changes](https://github.com/apache/cassandra/blob/trunk/doc/source/cql/changes.rst) at least as far as client expectations goes.
For example materialized views syntax was added in 3.4.0 and CAST was added in 3.4.1.

**Comment by slivne** [comment]
The issues is that we are not always aligned

**Comment by eliransin** [comment]
I believe that #4550 will present us with a problem. ALTER column is deprecated only on 3.4.4 so clients are going to expect that this is still present on Scylla (3.3.1).
It was not of an issue as long as we supported more than the cql spec such as supporting MV syntax in 3.3.1, but removing support is a problem.
Any thoughts? Should we align? 
According to my tests we should bump it at least to 3.4.1 since we support all of the features that went in
between 3.3.1 to 3.4.1.

**Comment by kostja** [comment]
We will never fully align. We support a non-strict superset. We also have no defined compatibility policy, rather, provide best-effort, case-by-case support. Closing as won't fix.

**Comment by nyh** [comment]
> We will never fully align. We support a non-strict superset. We also have no defined compatibility policy, rather, provide best-effort, case-by-case support. Closing as won't fix.

Sadly I agree with the decision to close this issue. If Cassandra's drivers were a vibrant project, we would very much need to handle this issue because the drivers may use this version to make decision on what to send. But the current situation is that Scylla's drivers projects are much more active than Cassandra's, and we already added a bunch of features that don't use the "CQL version" to test whether they can be used or not, so this "CQL version" thing became irrelevant, and probably we can never fix this issue and will never want to fix this issue.
