### ISSUE TITLE
WHERE IN secondary_index requires ALLOW FILTERING unlike in Cassandra

### ISSUE THREAD

**Issue by kokizzu** [scylladb/scylladb#5545]
```
CREATE TABLE IF NOT EXISTS users (
	id    BIGINT,
	created_at BIGINT,
	updated_at BIGINT,
	deleted_at BIGINT,
	email TEXT,
	password TEXT,
	PRIMARY KEY(email)
);

CREATE INDEX IF NOT EXISTS ON users(id);

SELECT * FROM users WHERE id IN (1,2,3);

Error from server: code=2200 [Invalid query] message="Cannot execute this query as it might involve data filtering and thus may have unpredictable performa
nce. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING" 
```

In Cassandra: https://stackoverflow.com/questions/52868299/cassandra-predicates-on-non-primary-key-columns-eventtype-are-not-yet-supporte

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

Scylla version (or git commit hash): 3.1.2
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ubuntu 18.04

**Comment by psarna** [comment]
It's a compatibility issue - right now we only support `EQ` relation for indexing. Support for `IN`, and potentially other operators, would need to be implemented.

**Comment by slivne** [comment]
@kokizzu - I think you can workaround this with changing the query like @psarna hinted. 

Its clear its not compatible and we need to fix it - yet if its urgent you can try this out.

**Comment by kokizzu** [comment]
@slivne not really urgent tho
the more pressing matters is i can't query something like `WHERE id > 30 LIMIT 10`  for offset paging, which is quite annoying, even when id is indexed.

**Comment by nyh** [comment]
Guys, and @dekimir, I tried to write a test for this and recent Cassandra seems to return the following error for "WHERE a IN (1,2)" when "a" is an indexed column:
> IN predicates on non-primary-key columns (a) is not yet supported
Scylla prints a different error message:
> Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING.
With "ALLOW FILTERING", the query does work in Scylla.

Scylla is arguably better here - it implemented a feature that Cassandra didn't, so it isn't a Scylla bug. What *is*, arguably, a bug, is the need to specify "ALLOW FILTERING". It shouldn't have been needed... "a IN (1,2)" doesn't require filtering just like "a = 1" doesn't require filtering.

So I think maybe this issue should be closed an instead a more accurate issue should be opened.

**Comment by nyh** [comment]
I wrote a test for this issue in cql-pytest, `test_allow_filtering.py`::`test_allow_filtering_index_in`. 

The test code is trivial:
```python
def test_allow_filtering_index_in(cql, table2):
    check_af_optional(cql, table2, 'a IN (1,2)', lambda row: row.a in {1,2})
```
This test fails on both current Scylla and current Cassandra: As I mentioned above, in Cassandra the query fails both with and without ALLOW FILTERING. In Scylla the query fails only without ALLOW FILTERING, and and works with it.

**Comment by mkawalec** [comment]
Found a workaround to split the query into two. The first queries the `MATERIALIZED VIEW` for the index for the primary key columns using the `IN` operator, the second queries the actual table. Use `DESC TABLE yourTableName` to find out the `MATERIALIZED VIEW` name for the index you need to query.

**Comment by nyh** [comment]
This difference is also noted by the translated Cassandra unit test `cassandra_tests/validation/operations/select_test.py`::`testFilteringWithoutIndices`. The test code has:
```python
            assert_invalid_message(cql, table, "IN predicates on non-primary-key columns (c) is not yet supported",
                                 "SELECT * FROM %s WHERE a IN (1, 2) AND c IN (6, 7)")
            assert_invalid_message(cql, table, "IN predicates on non-primary-key columns (c) is not yet supported",
                                 "SELECT * FROM %s WHERE a IN (1, 2) AND c IN (6, 7) ALLOW FILTERING")
```
While this is what happens in Cassandra, in Scylla the first request is rejected with a different message (saying that ALLOW FILTERING is missing) but the second request is actually not rejected.

Because we don't consider this difference a bug (see discussion above), I had to comment out that part of the test.

**Comment by nyh** [comment]
I'm closing this issue, as the actual behavior of this request changed from what is reported here.

The use case described here still behaves wrongly, and another issue was just opened about it - #13533 - explaining the new wrong (but different) behavior: Instead of reporting that ALLOW FILTERING is required (as complained here), the code today actually does this filtering with only a **warning** that ALLOW FILTERING is required (see commit 2f28f68e84b76e7d3eb3ce78b6200ec3f0c65ca9 for #7608), which returns the correct results but very slowly, and worse - usually times out without even an opportunity to return the warning.
