### ISSUE TITLE
Improve error message where fs.aio-max-nr is too low

### ISSUE THREAD

**Issue by tzach** [scylladb/scylladb#5981]
*Installation details*
Scylla version (or git commit hash): 3.3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

When running Scylla Docker on a server with high number of core, scylla fail to start and generate the following error:
```
scylla: ../../src/core/reactor.cc:1297: seastar::reactor::reactor(unsigned int, seastar::reactor_backend_selector, seastar::reactor_config): Assertion `r >= 0' failed.
```

The root cause is low value of kernel parameter `fs.aio-max-nr`
It would be good to check for this value and generate a more informative error message.

**Comment by tzach** [comment]
https://github.com/scylladb/scylla/issues/5173
https://github.com/scylladb/scylla/issues/3842

**Comment by sitano** [comment]
https://github.com/scylladb/scylla/pull/7252/

**Comment by bhalevy** [comment]
@lersek please look into this

**Comment by lersek** [comment]
This problem has been addressed by seastar commits
1. `cc4115b9134e` ("reactor: fallback to epoll backend when fs.aio-max-nr is too small", 2020-02-09)
2. `2a3b4ac62865` ("reactor: adjust max_networking_aio_io_control_blocks to lower size when fs.aio-max-nr is small", 2021-09-13)
3. `f1667c93b80d` ("reactor, linux-aio: print value of aio-max-nr on error", 2023-08-07)
4.` d4468c1c1fb5` ("linux-aio: print more specific error when setup_aio fails", 2023-09-13)

(Not an exhaustive list.)

Accordingly, if I start scylla @ `607abe96e864` with `--smp=8` (after setting `aio-max-nr` to 32K, and while having 0 in `aio-nr`), I get the following log:

~~~
WARN  2024-08-15 19:25:30,390 seastar - Requested AIO slots too large, please increase request capacity in /proc/sys/fs/aio-max-nr.
                                        configured:32768 available:32768 requested:408208
WARN  2024-08-15 19:25:30,390 seastar - max-networking-io-control-blocks adjusted from 50000 to 3070, since AIO slots are unavailable
~~~

If I further reduce `aio-max-nr` to 1K, then the networking IOCB count cannot be sufficiently decreased (it would fall under 1 per shard), and therefore we hit the hard failure path:

~~~
WARN  2024-08-15 19:58:09,472 seastar - Requested AIO slots too large, please increase request capacity in /proc/sys/fs/aio-max-nr.
                                        configured:1024 available:1024 requested:408208
Could not initialize seastar: std::runtime_error (Could not setup Async I/O: Not enough request capacity in /proc/sys/fs/aio-max-nr.
Try increasing that number or reducing the amount of logical CPUs available for your application)
~~~

Thus I think we're good, code-wise.

However, I suggest updating the documentation. What we have today in `docs/dev/docker-hub.md` on `aio-max-nr` is not great. (It dates back to scylla commit `f4412029f414`, "docs/docker-hub.md: add quickstart section with --smp 1", 2020-09-22.) Problems with the current language:
- Although I haven't verified it, the "65K" claim as default value on non-production systems looks suspicious; I'd rather think it's "64K".
- The section
    ~~~
    Available AIO on the system - (request AIO per-cpu * ncpus) =
    aio_max_nr - aio_nr < (reactor::max_aio + detect_aio_poll + reactor_backend_aio::max_polls) * cpu_cores =
    aio_max_nr - aio_nr < (1024 + 2 + 10000) * cpu_cores =
    aio_max_nr - aio_nr < 11026 * cpu_cores
    ~~~
    uses equal signs (`=`) incorrectly. The intent was probably to say "which means the same as", but that's not what equality means.
- In the same section, the relop `<` is bogus. The available AIO count must be *at least as high* (`>=`) as the requested AIO count.
- Clearer names should be used; `adjust_max_networking_aio_io_control_blocks()` in `src/core/reactor.cc` sets a great example:
    - `reactor::max_aio` should be called `storage_iocbs`.
    - `detect_aio_poll` is inexplicable to me; it should be called `preempt_iocbs`.
    - `reactor_backend_aio::max_polls` is again inexplicable to me; it should be called `network_iocbs`.
    - The specific value `10000` for the last one is not correct in scylla's context. It is correct as the Seastar default, but scylla has used `50000` since commit `2cfc517874e9` ("main, test: adjust number of networking iocbs", 2021-07-18).


TBH I think we should just remove the `aio-max-nr` treatise from `docs/dev/docker-hub.md`; the runtime warning and error message are good enough nowadays. What do you guys think about removing that part?

**Comment by sitano** [comment]
> What do you guys think about removing that part?

it was correct back in the days. users need some info to estimate the required amounts based on cores count. thus if you want to delete those estimations, I did suggest adding a msg to the output - "Set aio_max_nr to at least X".

**Comment by sitano** [comment]
If the requested value is the value to set - then no. It’s not clear though if there needed some free space for reserve.

**Comment by lersek** [comment]
OK, I'll refine the warning message a bit further... It currently says `configured:32768 available:32768 requested:408208`, where `configured` is the current contents of `aio-max-nr`, `available` is the *difference* `aio-max-nr - aio-nr` (that is, the *remaining* free AIO slots that scylla finds when it starts up), and then `requested` is what should fit into that *difference* (i.e., not into `aio-max-nr`). The current warning is not actionable enough. The user is supposed to set `aio-max-nr` to `requested + aio-nr`, not just `requested`. (`aio-nr` is what other workloads on the system are using at the time of initializing scylla.)
