### ISSUE TITLE
View building wrongly counted as "Non-paged CQL reads"

### ISSUE THREAD

**Issue by nyh** [scylladb/scylladb#5983]
A user reported that during view building (i.e., adding a materialized-view to an existing table), the "Non-paged CQL reads" counter is increased. The user considers this confusing. Definitely, view building does do reads and they should be counted somewhere, but there is nothing "CQL" about these reads.

**Comment by slivne** [comment]
We have system and user generated queries - we should be able to split this apart, still it would be good to understand that we have a non paged range scan running in the system.

**Comment by piodul** [comment]
@mlitvk investigated the issue. It turns out that Scylla doesn't use non-paged CQL reads during view building, each node only reads its own base table data via a flat_mutation_reader_v2 and completely skips the CQL layer.

The reads come from the driver. Creating a MV is a schema change, so an event is sent to the driver. After that, drivers usually query system tables to get recent information about the schema. @mlitvk was using cqlsh for testing and he did observed that the metric increased - after checking in wireshark he observed that the number of queries sent by the driver is exactly the same as the increment in the metric.

It's a driver issue and not an issue in Scylla, so closing.

**Comment by piodul** [comment]
Opened an issue in the python driver: https://github.com/scylladb/python-driver/issues/331
