### ISSUE TITLE
alternator: an index identical to the base table will fail with KA/LA sstable format

### ISSUE THREAD

**Issue by psarna** [scylladb/scylladb#6157]
While it's not an interesting case at all from the user's point of view, it should still be handled (with low priority).

Alternator allows creating a somewhat useless index: for a table with one partition key `X` and no clustering key, it allows creating an index on column `X` as partition key. The absurdity of this index is that it provides no value, since one can just read directly from the base table.

Still, this weird construct is subject to a problem from #6035 - it is capable of producing a row tombstone for a partition instead of using a partition tombstone. The problem is that such a tombstone looks like an open-ended range tombstone, which KA/LA formats are incapable of writing.

Given that in order to hit this error the user would have to:
1. Create a useless index
2. Use ka/la sstable format, while mc is expected to be used

... gives that issue a very low priority. But, we do have an alternator test that doesn't work with KA/LA sstables, so I'm marking this test as `to be skipped`, and use this issue as a reference. 

/cc @nyh

**Comment by psarna** [comment]
In order to reproduce, simply disallow `mc` format in `scylla.yaml` config file when booting Scylla - it will result in using LA format, which is enough to reproduce this problem:
```yaml
-- scylla.yaml
enable_sstables_mc_format: false

**Comment by nyh** [comment]
@psarna forgot to mention the name of the test failing when MC format is disabled: it is `test_gsi.py::test_gsi_identical`.

Since commit 55240e9db2a0157cfccb0c55a8433248e13e36c4 this test is skipped - since it can either succeed (in MC format) or hang (with MC format disabled).

**Comment by nyh** [comment]
On the mailing list @psarna and @tgrabiec explained that the problem is that we (in this case, the view upgate code) generates - for a table without clustering keys - row tombstones with and empty clustering key instead of a partition key. 

They suggested that this situation should simply be handled by the ka/la writers themselves (and actually mc writers as well) - they're aware of the schema, so if they see a row tombstone in a table which does not have a clustering key, they should write a partition deletion.

If we do this, this bug gets fixed for free without any changes to the MV code (and the fix to #6035 also becomes unnecessary, but it doesn't hurt so doesn't need to be reverted).

**Comment by slivne** [comment]
we moved to mc - pushing this out

**Comment by nyh** [comment]
If I understand correctly, current Scylla can no longer write KA/LA (@tgrabiec, am I right?). If this is correct, this issue is no longer interesting and can be closed.

**Comment by tgrabiec** [comment]
> If I understand correctly, current Scylla can no longer write KA/LA (@tgrabiec, am I right?). If this is correct, this issue is no longer interesting and can be closed.

Correct.
