### ISSUE TITLE
Created an issue on Kong to support Scylla

### ISSUE THREAD

**Issue by sonicaghi** [scylladb/scylladb#621]
https://github.com/Mashape/kong/issues/754

Maybe you guys can help down the road? Kong support Cassandra atm. But we have many requests to support more DBs.

**Comment by tzach** [comment]
@sinzone since Kong is using C* 2.1.x this should be straight forward, without updating from the application side. Take a look at http://www.scylladb.com/technology/status/#road-map and let us know if you see anything you need for Kong.

Since Kong is [tested on EC2](https://getkong.org/about/benchmark/), using [Scylla AMI](http://www.scylladb.com/download/#run-scylla-on-ec2) with Kong should be easy.

**Comment by thefosk** [comment]
Currently ScyllaDB wouldn't work with Kong because Kong uses counters and `ALTER TABLE` statements (related to #577).

**Comment by duarten** [comment]
We should now be able to support Kong. A good way to find out is to run their integration tests with Scylla as a backend.

**Comment by dorlaor** [comment]
+1

**Comment by tomer-sandler** [comment]
Kong is now supported with Scylla 2.2. Read here: https://github.com/Kong/kong/issues/754#issuecomment-408696135

**Comment by nyh** [comment]
> @sonicaghi @thefosk Kong is now supported with Scylla 2.2. Read here: [Kong/kong#754 (comment)](https://github.com/Kong/kong/issues/754#issuecomment-408696135)

So closing the issue as completed.
