### ISSUE TITLE
TTL unexpected behavior when setting to 0 on a table with default_time_to_live

### ISSUE THREAD

**Issue by guy9** [scylladb/scylladb#6447]
*Installation details*
Scylla version (or git commit hash): 4.0.0
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker on local Fedora

When trying to remove a column TTL, by setting it to 0, on a Table with a default_time_to_live defined, instead of being set to 0 the TTL of the column is reset to the default_time_to_live value. 
To recreate:

1.  Create a 3 node cluster
2. CQLSH
3. CREATE KEYSPACE pet_catalog WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy','DC1' : 3};
4. use pet_catalog;
5. CREATE TABLE heartrate_ttl (     pet_chip_id  uuid,     name text,     heart_rate int,     PRIMARY KEY (pet_chip_id)) WITH default_time_to_live = 500;
6. INSERT INTO heartrate_ttl(pet_chip_id, name, heart_rate) VALUES (c63e71f0-936e-11ea-bb37-0242ac130002, 'Rocky', 92);
7. cqlsh:pet_catalog> SELECT name, heart_rate, TTL(name) as name_ttl, TTL(heart_rate) as heart_rate_ttl FROM heartrate_ttl WHERE pet_chip_id = c63e71f0-936e-11ea-bb37-0242ac130002;

 name  | heart_rate | name_ttl | heart_rate_ttl
-------+------------+----------+----------------
 Rocky |         92 |      494 |            494

(1 rows)

8. cqlsh:pet_catalog> UPDATE heartrate_ttl USING TTL 0 SET heart_rate =  150 WHERE pet_chip_id = c63e71f0-936e-11ea-bb37-0242ac130002;
9. cqlsh:pet_catalog> SELECT name, heart_rate, TTL(name) as name_ttl, TTL(heart_rate) as heart_rate_ttl FROM heartrate_ttl WHERE pet_chip_id = c63e71f0-936e-11ea-bb37-0242ac130002;

 name  | heart_rate | name_ttl | heart_rate_ttl
-------+------------+----------+----------------
 Rocky |        150 |      434 |            482

(1 rows)

heart_rate_ttl above should be null, instead, it is 482 (it was reset to 500 instead of removed)

For reference, in Cassandra 3.4.4 this doesn't happen.

**Comment by bhalevy** [comment]
Thanks for reporting @guy9. 
@eliransin @dekimir can you please look into this from the cql layer perspective?
@tgrabiec can you please look into how the TTL is being applied on the updated cell with 'USING TTL 0' and non-zero default ttl in the table schema?

**Comment by eliransin** [comment]
@bhalevy at least at first glance this looks like the cql layers fault:
https://github.com/scylladb/scylla/blob/517f2c049058a2231853515b43732fadba77017a/cql3/update_parameters.hh#L192-L194

Which is then used when building the update mutation.

**Comment by eliransin** [comment]
@bhalevy according the the cassandra cql docs TTL of 0 should delete the ttl as @guy9 expected.
(here) [https://docs.datastax.com/en/cql-oss/3.3/cql/cql_reference/cqlUpdate.html#cqlUpdate__time-value] is the reference.
@dekimir assigning me and you since it is in our domain :slightly_smiling_face:

**Comment by nyh** [comment]
We had a duplicate issue https://github.com/scylladb/scylladb/issues/9842, and I wrote xfailing tests for it demonstrating Scylla's wrong behavior compared to Cassandra:

https://github.com/scylladb/scylladb/commit/5fbeae90161de783104c4ecd65216849ed920ed1

**Comment by fee-mendes** [comment]
Yea, this seems like a hidden incompatibility bug. I personally couldn't find this limitation documented anywhere. In particular, even in https://github.com/scylladb/scylladb/blob/f1f117696323f7d63b9c8da2d8950bc3c302aaea/docs/cql/time-to-live.rst we mention that one can simply update the TTL to 0 in order to get rid of it without addressing this corner case, so we have an issue and a documentation bug :-)

**Comment by guy9** [comment]
@annastuchlik FYI

**Comment by nyh** [comment]
@fee-mendes @guy9 do you want to document this incompatibility and live with it, or document it as currently a bug and eventually when the issue is fixed change the documentation? Maybe it makes sense just to fix this bug and not document anything? :-)

**Comment by fee-mendes** [comment]
@nyh - 2 years after we have this issue opened I am not sure, you tell us. 

What we DEFINITELY want to avoid is a situation where one expects to set `TTL 0` for a row and find their data was evicted silently. And - if this happens - we better save our arses should this "minor detail" take another 2y, don't you think? ;-)

**Comment by nyh** [comment]
After two years, two duplicates, two reproducing tests - maybe it's time to fix it :-)
I'll take a stab at it myself now. If I don't come back here with a patch soon, feel free to submit a documentation patch excusing it.

**Comment by nyh** [comment]
The fix is not trivial:

The "original sin" is that in `class attributes` (attributes.hh), `_time_to_live` is an optional, but the `attributes::get_time_to_live()` function returns an integer,  and not having any value is returns 0 instead of some other signal (e.g., unset optional).

From there, the caller `modification_statement::get_time_to_live()` returns a duration with duration 0 (instead of unset optional) used for unset option (and also for the actual value 0).

Finally, `update_parameters` gets such a duration (instead of optional duration), and its methods `ttl()` and two copies of `make_cell()` check if `ttl.count()` is 0 as a sign it wasn't set (so should be set to default). Only after we fix the functions above can we modify these three functions to check whether the ttl was explicitly set instead of if it's 0.

**Comment by nyh** [comment]
By the way, interestingly but not surprisingly, setting an UNSET_VALUE ttl doesn't behave like 0 - it doesn't override the default. It's not surprising but it contradicts Cassandra's unofficial statement (in its NEWS.txt) that UNSET_VALUE always means "unlimited". It doesn't. I created a new test for this case as well.

**Comment by avikivity** [comment]
Backported to 5.2. But 5.1 is more involved due to unset changes, @nyh please take over.

**Comment by nyh** [comment]
@avikivity I assume you decided that we **should** backport this change because it wasn't completely obvious to me since this fixes dubious behavior we had from the start (the problem was known in Scylla for 3 years) so it's not a regression, and also it's not a very serious bug.

But anyway, I'll look into what it takes to backport this to 5.1.
Also 5.0?

**Comment by nyh** [comment]
Backported to next-5.1 (2ea3d5ebf0cfd3b8ba78fb2a78375d8af9906723). There was one thing I needed to fix in the backport - the unset() case was a few lines down in the code and needed to be modified there. I verified that the regression tests - both 0 and unset case - work on the backported version.

Let's backport from 5.1 to 5.0 as soon as next-5.1 passes all the tests and promotes. I'm hoping that second backport will be trivial.

**Comment by nyh** [comment]
Promotion of next-5.1 with this patch is failing dtest because of an outdated test that needed to be removed and done in dtest master (https://github.com/scylladb/scylla-dtest/pull/3076 ). This PR was already backported by @fruch to the 5.2 branch of dtest, but now needs to be backported also to the 5.1 and 5.0 branches of dtest before we can promote the Scylla code in those versions.

**Comment by denesb** [comment]
Looks like all backports were done, removing Backport labels.
