### ISSUE TITLE
offline install: can't fine log by `journalctl --user -xe`

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylladb#7578]
*Installation details*
Scylla version (or git commit hash): scylla-unified-package-4.4.dev.0.20201110.78c598e08e.tar.gz
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS8 instance on GCE
GCE Machine type:  e2-medium (2 vCPUs, 4 GB memory)

### Description

After nonroot offline installation, try to start scylla-server, but it failed.

```
[scylla-test@amos-offlineinstall-centos7 ~]$ systemctl --user start scylla-server
Job for scylla-server.service failed because the control process exited with error code.
See "systemctl --user status scylla-server.service" and "journalctl --user -xe" for details.
```

I didn't find any log by `journalctl --user -xe`

```
[scylla-test@amos-offlineinstall-centos7 ~]$ journalctl --user -xe
No journal files were found.
-- No entries --
```

### Workaround

But I can see the scylla log by:`journalctl -xe`

/CC @penberg @roydahan

**Comment by penberg** [comment]
@syuu1228 Looks like logging on CentOS 8 goes directly to the global journal, not to the per-user one...

**Comment by syuu1228** [comment]
I thought `journalctl --user -xe` on CentOS8 does not work because of #7131, no?
We introduced logging to file instead of journal because of it: https://github.com/scylladb/scylla/commit/0f786f05fed41be94b09e33aa34a767074a14ec1

Or, is this environment changed journal.conf to make usermode journal work?
see: https://github.com/scylladb/scylla/issues/7131#issuecomment-693179919

**Comment by syuu1228** [comment]
Offline install on CentOS8 does not support journal log, due to systemd bug.
Since it doe not fix on distribution side, we provide a workaround: https://github.com/scylladb/scylladb/commit/0f786f05fed41be94b09e33aa34a767074a14ec1
So there is a solution, closing.
