### ISSUE TITLE
Repair - error handling + logging

### ISSUE THREAD

**Issue by slivne** [scylladb/scylladb#81]
Error hangling, logging, etc., needs to be improved.

**Comment by tzach** [comment]
@slivne we now have test for repair correctness, speed.
Do you have comment on repair logging? should we open a new issue for it?

**Comment by slivne** [comment]
@tzach - the originator of this is acutally @nyh .. @nyh are we missing anything ?

**Comment by nyh** [comment]
Well, our repair still doesn't have identical log messages to those of Cassandra's repair. In particular, our repair doesn't summarize how much difference was found between the nodes. I doubt this is urgent to fix, I don't know if it's even important to fix (in other areas of the code, are our log messages identical to those of Cassandra?) but it wasn't fixed yet.

**Comment by tzach** [comment]
@nyh I argue it is an urgent fix.
We need insight to what repair do. The goal is not have the same logs, but insight into what the system do.

**Comment by slivne** [comment]
@tzach  so change the prio

**Comment by slivne** [comment]
@nyh - please list what you think we can provide - it does not need to be identical.

**Comment by nyh** [comment]
@slivne , @tzach - we can provide whatever statistics you'll want. It is trivial to count the number of streamed ranges, slightly harder but also should be fairly striaghtforward to count the actual number of streamed partitions (the streaming code will need to count this for us) - note there will be a separate count of incoming and outgoing partitions. We can multiply - or not multiply - the number of partitions by the number of nodes we sent them to. We can count the amount of time repair took, the number of nodes involved, and so on. Or whatever other kinds of statistics you were thinking of. Just please say what it is you are looking for. Since you marked this issue as "high", I assume you know exactly what you want :-)

**Comment by tzach** [comment]
>  I assume you know exactly what you want

As a repair expert, what info would **you** need to debug a problem?
All the counters you mention make sense. 
What I'm missing is how many values did the repair fix.
This can give an insight in to how "distance" was each node pair before the repair.
Or can I extract is from the partition count?

**Comment by nyh** [comment]
On Wed, Apr 6, 2016 at 9:11 AM, Tzach Livyatan <notifications@github.com>
wrote:

> I assume you know exactly what you want
>
> As a repair expert, what info would *you* need to debug a problem?
>
Debug which problem? Debug a repair bug? For this we already have a bunch
of low-level logs which I used when debugging repair.

If it's some higher-level database problem that the user is trying to
understand, well, I'm definitely not the expert here on what users want or
expect, and could use some advice.


> All the counters you mention make sense.
> What I'm missing is how many values did the repair fix.
>
This we cannot really provide:

1. Remember that in Cassandra (and Scylla), writes are not preceeded by
reads, so when we stream a partition from a remote host and write it into
our own sstable, we don't know if we just wrote different data than we had
before, or if it's actually the same data (or even older data which will be
ignored).
2. So when we decide to stream a range and get 100 (for example)
partitions, we can add "100" to the counter of streamed partitions - but
don't know how many of these partitions actually changed. We know that at
least one did change (because we stream when the checksum is different) -
but even then it's possible that the data we get is actually *older*
(timestamp-wise) than the data we already have, and we will ignore it.
3. Note that repair also sends data to the remote nodes. We definitely
don't know how much that fixed on the remote node - but we can count the
number of partitions we sent.


> This can give an insight in to how "distance" was each node pair before
> the repair.
>
The most trivial counter is the number of streamed ranges. But what I don't
like about it is that the user will not really know what "42" means here
(is it a lot? little? how big are those ranges). This is why I think it
will be more useful to use the units of partitions - even if it doesn't
mean that all these partitions different, it's a count of how many
partitions were streamed. Does this sound useful?

Do you know what does Cassandra provide?

**Comment by tzach** [comment]
@nyh yes, unit partitions make sense

Maybe the difference measurement can not come from streaming, rather in the logic which use the streamed partitions and merged it into the node data.

**Comment by glommer** [comment]
Generic bug from 2016 saying logs need to be improve. Which improvements exactly ? The repairs logs seem ok to me as they are today. @slivne can we close ?

**Comment by glommer** [comment]
@slivne asking again, can we close this ?

**Comment by nyh** [comment]
This is a 7 year old issue about the repair we had then not generating enough log messages. Since then, the repair code was rewritten twice, and the log messages are completely different. So closing this issue. If we want to improve logging of the current repair, we should open a new issue saying what we want to improve.
