### ISSUE TITLE
cql-pytest: allow changing configuration dynamically

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylladb#9905]
It would be a nice feature for testing config options that are live-updateable.

It would have to write a new configuration file to the path used by Scylla and send SIGUP to the Scylla process.

This would probably only work when running tests against a Scylla process that is created by the test runner, as then the config file is also managed by the test runner.

On the other hand, cql-pytests can also by executed against an existing Scylla process, without managing its directory. In this case I guess the feature would have to be disabled, and the tests which use the feature would have to be disabled. Perhaps it would work in some cases if the user passes a `--conf path/to/config` parameter, in which case it would try rewriting the file pointed to.

**Comment by kbr-** [comment]
cc @nyh

**Comment by nyh** [comment]
We could have a configuration-file-changing fixture that detects whether it actually can change the configuration, and if it can't, it will skip the test. So such test would be skipped when testing against Cassandra (which I assume doesn't have the same configuration loading rules as Scylla?) - or a Scylla instance that you ran yourself.

Another approach would be to change the configuration using the REST API, not the configuration file (you can see an example of using the REST API in test/cql-pytest/nodetool.py).

In any case, there is one problem that this idea causes that we need to be aware of: It breaks the ability to run multiple tests in parallel on the same Scylla, because one test's configuration changes will also affect other tests. We don't actually run cql-pytests tests in parallel today, but maybe we'll want to do this in the future, and these configuration tests will need to be serialized somehow. I guess we can address this later when we start to run tests in parallel - I'm pretty sure we have a lot of other problems in this area anyway.

**Comment by nyh** [comment]
In commit e27127bb7f00f35293f2b25c6fe2cb9082abe42e, @denesb added to cql-pytest a feature very similar to what you asked for, just using the REST API (as I proposed) instead of configuration file. He added to cql-pytest/util.py a context manager `config_value_context` which changes the given configuration while held - and then restores it. He used it to write a test which needs a different setting for the `query_tombstone_page_limit` configuration.

So I think this issue can be closed. @kbr-scylla ?

**Comment by denesb** [comment]
My context actually uses the `system.config` virtual table to manipulate the configuration value. It is even more convenient than the REST API.

**Comment by kbr-scylla** [comment]
Yes, let's close the issue. Thanks.
